#!/bin/sh

#BSUB -J gfs_wafs_grib2
#BSUB -oo /ptmpp1/Yali.Mao/gfs_wafs_grib2.o%J
#BSUB -eo /ptmpp1/Yali.Mao/gfs_wafs_grib2.o%J
#BSUB -L /bin/sh
#BSUB -q debug
#BSUB -W 00:30
#BSUB -P GFS-T2O
#BSUB -R affinity[core]

set -xa

export OMP_NUM_THREADS=1
export MP_MPILIB=mpich2
export MP_EUILIB=us
export MP_LABELIO=yes
export MP_COMPILER=intel


############################################
# Loading module
############################################
. /usrx/local/Modules/default/init/ksh
module load prod_util/v1.0.2
module load grib_util/v1.0.1

############################################
# required exports!
############################################
### envir: prod/dev/para/bkup/ges/test bkup2/ges2/para2/prod2/prd_p6
export envir=prod

export cyc=${cyc:-00}

# gfs_wafs_grib2 for generating global WAFS on grid 45
export job=gfs_wafs_grib2_${cyc}

############################################
# set NET RUN
############################################
### NET: gfs/para/parallel-test/nam/rap/ dump/ens/nawips/nesdis/
export NET=gfs
export RUN=gfs


############################################
# Specify versions
############################################
export gfs_ver=v13.0.0


############################################
# user defined
############################################
export pid=${pid:-$$}
export jobid=${job}.${pid}

#needs to be the current date to make sure comparison is good at $PCOM
export PDY=`cut -c 7-14 /com2/date/t00z`

USER=`whoami`

############################################
# SENDCOM=YES--Copy output file to /com
# SENDECF=YES--Allow to talk back to ECF
# SENDDBN=YES--Alert output file to TOC
# KEEPDATA=NO--Remove temporary working
############################################
export SENDCOM=YES
export SENDDBN=NO
export SENDDBN_NTC=NO
export SENDDBN_GB2=NO
export KEEPDATA=YES
 
############################################
# Define ROOT directories
############################################
export COMROOT=/com
#export NWROOTp1=/nwprod
export PCOMROOT=/ptmpp1/${USER}/pcom
export NWROOT=/global/save/Yali.Mao/project
export DATAROOT=/ptmpp1/${USER}
#export DCOMROOT=/dcom

############################################
# Define DATA PCOM, COMOUT and COMIN
############################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
export PCOM=${PCOM:-$PCOMROOT/wafs}
export COMOUT=/ptmpp1/${USER}/gfs_wafs_grib2.$PDY
#export COMIN=${COMIN:-$COMROOT/${NET}/prod/$RUN.$PDY}

export jlogfile=/$DATA/jlogfile.${jobid}

################################
# Set up the HOME directory
################################
export HOMEgfs=${HOMEgfs:-${NWROOT}/gfs.${gfs_ver}}


############################################
# run the job
#############################################
export SHOUR=06
export EHOUR=36
export FHINC=03

sh $HOMEgfs/jobs/JGFS_WAFS_GRIB2

#############################################
# compare the output (optional)
#############################################
if [ $USER = 'Yali.Mao' ] ; then

  # the standard data to be compared to
  stdout=/com/${NET}/$envir/${RUN}.${PDY}
  if [ $envir = prod ]; then
    stdpcom=/pcom/wafs
  else
    stdpcom=/pcom/${envir}/wafs
  fi

  ffhr=$SHOUR

  cd $COMOUT
  # Filter 775mb and 750mb since the operational 775mb is going to be replaced by 750mb
  while test $ffhr -le $EHOUR ; do
    # cmp $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr}.grib2 $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr}.grib2
    wgrib2 $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr}.grib2 | grep -v "750 mb" | wgrib2 -i $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr}.grib2 -grib my.grb2
    wgrib2 $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr}.grib2 | grep -v "775 mb" | wgrib2 -i $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr}.grib2 -grib com.grb2
    cmp my.grb2 com.grb2

    # cmp $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr} $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr}
    #wgrib $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr} | grep -v ":kpds7=750:" | wgrib -i -grib $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr} -o my.grb
    #wgrib $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr} | grep -v ":kpds7=775:" | wgrib -i -grib $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr} -o com.grb
    cmp my.grb com.grb

    # cmp $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr}.nouswafs.grib2 $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr}.nouswafs.grib2
    wgrib2 $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr}.nouswafs.grib2 | grep -v "750 mb" | wgrib2 -i $COMOUT/gfs.t${cyc}z.wafs_grb45f${ffhr}.nouswafs.grib2 -grib my45.grb2
    wgrib2 $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr}.nouswafs.grib2 | grep -v "775 mb" | wgrib2 -i $stdout/gfs.t${cyc}z.wafs_grb45f${ffhr}.nouswafs.grib2 -grib com45.grb2
    cmp my45.grb2 com45.grb2

    # $PCOM data on develop machine may be out of date, so skip the comparison
    continue


    # cmp $PCOM/grib2.t${cyc}z.wafs_grbf${ffhr}.45 $stdpcom/grib2.t${cyc}z.wafs_grbf${ffhr}.45
    wgrib2 $PCOM/grib2.t${cyc}z.wafs_grbf${ffhr}.45 | grep -v "750 mb" | wgrib2 -i $PCOM/grib2.t${cyc}z.wafs_grbf${ffhr}.45 -grib mypcom.grb2
    wgrib2 $stdpcom/grib2.t${cyc}z.wafs_grbf${ffhr}.45 | grep -v "775 mb" | wgrib2 -i $stdpcom/grib2.t${cyc}z.wafs_grbf${ffhr}.45 -grib pcom.grb2
    cmp mypcom.grb2 pcom.grb2

    # cmp $PCOM/grib2.t${cyc}z.wafs_grb_wifsf${ffhr}.45 $stdpcom/grib2.t${cyc}z.wafs_grb_wifsf${ffhr}.45
    wgrib2 $PCOM/grib2.t${cyc}z.wafs_grb_wifsf${ffhr}.45 | grep -v "750 mb" | wgrib2 -i $PCOM/grib2.t${cyc}z.wafs_grb_wifsf${ffhr}.45 -grib mypcomwifs.grb2
    wgrib2 $stdpcom/grib2.t${cyc}z.wafs_grb_wifsf${ffhr}.45 | grep -v "775 mb" | wgrib2 -i $stdpcom/grib2.t${cyc}z.wafs_grb_wifsf${ffhr}.45 -grib pcomwifs.grb2
    cmp mypcomwifs.grb2 pcomwifs.grb2
  

    ffhr=`expr $ffhr + $FHINC`
    if test $ffhr -lt 10
    then
      ffhr=0${ffhr}
    fi

  done

fi
exit

