#!/bin/sh

#BSUB -J gfs_wafs
#BSUB -oo /ptmpp1/Yali.Mao/gfs_wafs.o%J
#BSUB -eo /ptmpp1/Yali.Mao/gfs_wafs.o%J
#BSUB -L /bin/sh
#BSUB -q debug
#BSUB -W 00:30
#BSUB -P GFS-T2O
#BSUB -R rusage[mem=500]
#BSUB -R affinity[core]

set -xa

export OMP_NUM_THREADS=1
export MP_MPILIB=mpich2
export MP_EUILIB=us
export MP_LABELIO=yes
export MP_COMPILER=intel


############################################
# Loading module
############################################
. /usrx/local/Modules/default/init/ksh
module load prod_util/v1.0.2
module load grib_util/v1.0.1

############################################
# required exports!
############################################
### envir: prod/dev/para/bkup/ges/test bkup2/ges2/para2/prod2/prd_p6
export envir=prod

export cyc=${cyc:-00}
export fcsthrs=30

# gfs_wafs for octants (8 WAFS files)
export job=gfs_wafs_f${fcsthrs}_${cyc}

############################################
# set NET RUN
############################################
### NET: gfs/para/parallel-test/nam/rap/ dump/ens/nawips/nesdis/
export NET=gfs
export RUN=gfs


############################################
# Specify versions
############################################
export gfs_ver=v13.0.0


############################################
# user defined
############################################
export pid=${pid:-$$}
export jobid=${job}.${pid}

#needs to be the current date to make sure comparison is good at $PCOM
export PDY=`cut -c 7-14 /com2/date/t00z`

USER=`whoami`

############################################
# SENDCOM=YES--Copy output file to /com
# SENDECF=YES--Allow to talk back to ECF
# SENDDBN=YES--Alert output file to TOC
# KEEPDATA=NO--Remove temporary working
############################################
export SENDCOM=YES
export SENDDBN=NO
export SENDDBN_NTC=NO
export KEEPDATA=YES
 
############################################
# Define ROOT directories
############################################
export COMROOT=/com
#export NWROOTp1=/nwprod
export PCOMROOT=/ptmpp1/${USER}/pcom
export NWROOT=/global/save/Yali.Mao/project
export DATAROOT=/ptmpp1/${USER}

############################################
# Define DATA PCOM, COMOUT and COMIN
############################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
export PCOM=${PCOM:-$PCOMROOT/${NET}}
export COMOUT=/ptmpp1/${USER}/gfs_wafs.$PDY
#export COMIN=/com/${NET}/${envir}/${RUN}.${PDY}

export jlogfile=/$DATA/jlogfile.${jobid}

################################
# Set up the HOME directory
################################
export HOMEgfs=${HOMEgfs:-${NWROOT}/gfs.${gfs_ver}}

#############################################
# run the job
#############################################
sh $HOMEgfs/jobs/JGFS_WAFS

#############################################
# compare the output (optional)
#############################################
if [ $USER = 'Yali.Mao' ] ; then
  # the standard data to be compared to
  stdout=/com/${NET}/$envir/${RUN}.${PDY}
  if [ $envir = prod ]; then
    stdpcom=/pcom/gfs
  else
    stdpcom=/pcom/${envir}/gfs
  fi

  for gid in 37 38 39 40 41 42 43 44 ; do

    # comparing $COMOUT products
    cmp $COMOUT/wafs${NET}${gid}.t${cyc}z.gribf${fcsthrs} $stdout/wafs${NET}${gid}.t${cyc}z.gribf${fcsthrs}
    cmp $COMOUT/wafs${NET}${gid}.t${cyc}z.gribf${fcsthrs}.grib2 $stdout/wafs${NET}${gid}.t${cyc}z.gribf${fcsthrs}.grib2

    # $PCOM data on develop machine may be out of date, so skip the comparison
    continue
    #stdpcom=/ptmpp2/Jiayi.Peng/data

    # comparing $PCOM products
    if [ $fcsthrs -eq 30 ] ; then
      sets=b
      for fhr in 12 18 24 30 ; do
	  cmp $PCOM/com.wafs${cyc}${fhr}${sets}.$job $stdpcom/com.wafs${cyc}${fhr}${sets}.$job
	  cmp $PCOM/xtrn.wfs${NET}${cyc}${fhr}${sets}.$job $stdpcom/xtrn.wfs${NET}${cyc}${fhr}${sets}.$job
      done
      sets=
      for fhr in 00 06 ; do
	  cmp $PCOM/com.wafs${cyc}${fhr}${sets}.$job $stdpcom/com.wafs${cyc}${fhr}${sets}.$job
	  cmp $PCOM/xtrn.wfs${NET}${cyc}${fhr}${sets}.$job $stdpcom/xtrn.wfs${NET}${cyc}${fhr}${sets}.$job
      done
    fi
    if [ $fcsthrs -ge 12 -a $fcsthrs -le 30 ] ; then
      sets=a
      cmp $PCOM/com.wafs${cyc}${fcsthrs}${sets}.$job $stdpcom/com.wafs${cyc}${fcsthrs}${sets}.$job
      cmp $PCOM/xtrn.wfs${NET}${cyc}${fcsthrs}${sets}.$job $stdpcom/xtrn.wfs${NET}${cyc}${fcsthrs}${sets}.$job
    elif  [ $fcsthrs -ge 36 ] ; then
      sets=
      cmp $PCOM/com.wafs${cyc}${fcsthrs}${sets}.$job $stdpcom/com.wafs${cyc}${fcsthrs}${sets}.$job
      cmp $PCOM/xtrn.wfs${NET}${cyc}${fcsthrs}${sets}.$job $stdpcom/xtrn.wfs${NET}${cyc}${fcsthrs}${sets}.$job
    # elif [ $fcsthrs -le 36 ] ; then 
    #   no comparison
    fi

  done

fi

exit

