V=>this%V
VALL=>this%VALL
HALL=>this%HALL

a_diff_f=>this%a_diff_f
a_diff_h=>this%a_diff_h
b_diff_f=>this%b_diff_f
b_diff_h=>this%b_diff_h

p_eps=>this%p_eps
p_del=>this%p_del
p_sig=>this%p_sig
p_rho=>this%p_rho
paspx=>this%paspx
paspy=>this%paspy
pasp1=>this%pasp1
pasp2=>this%pasp2
pasp3=>this%pasp3

vpasp2=>this%vpasp2
hss2=>this%hss2
vpasp3=>this%vpasp3
hss3=>this%hss3

ssx=>this%ssx
ssy=>this%ssy
ss1=>this%ss1
ss2=>this%ss2
ss3=>this%ss3

dixs=>this%dixs
diys=>this%diys
dizs=>this%dizs

dixs3=>this%dixs3
diys3=>this%diys3
dizs3=>this%dizs3

qcols=>this%qcols

iref=>this%iref
jref=>this%jref
Lref=>this%Lref
Lref_h=>this%Lref_h
cvf1=>this%cvf1
cvf2=>this%cvf2
cvf3=>this%cvf3
cvf4=>this%cvf4
cvh1=>this%cvh1
cvh2=>this%cvh2
cvh3=>this%cvh3
cvh4=>this%cvh4

cx0=>this%cx0
cx1=>this%cx1
cx2=>this%cx2
cx3=>this%cx3
cy0=>this%cy0
cy1=>this%cy1
cy2=>this%cy2
cy3=>this%cy3

p_coef=>this%p_coef
q_coef=>this%q_coef
a_coef=>this%a_coef
b_coef=>this%b_coef

cf00=>this%cf00
cf01=>this%cf01
cf02=>this%cf02
cf03=>this%cf03
cf10=>this%cf10
cf11=>this%cf11
cf12=>this%cf12
cf13=>this%cf13
cf20=>this%cf20
cf21=>this%cf21
cf22=>this%cf22
cf23=>this%cf23
cf30=>this%cf30
cf31=>this%cf31
cf32=>this%cf32
cf33=>this%cf33
