#!/usr/bin/env python3
"""
Script to generate GitLab CI pipeline configurations based on supported cases for each machine.
This uses the functionality of get_host_case_list.py to determine which cases are supported
on each machine and generates the appropriate pipeline configuration.
"""

import os
import sys
import argparse
from pathlib import Path
import yaml

# Get the path to the top directory of the repository
_here = os.path.dirname(os.path.abspath(__file__))
_top = os.path.abspath(os.path.join(_here, '../../..'))

# Import the get_host_cases function from get_host_case_list
from get_host_case_list import get_host_cases

# Template for the top portion of the GitLab CI configuration
GITLAB_CI_TEMPLATE = """# THIS FILE IS AUTOMATICALLY GENERATED
# DO NOT EDIT MANUALLY - ALL CHANGES WILL BE LOST
# Edit the template in ci/platforms/machine_configs.j2 instead

stages:
  - build
  - create_experiments
  - run_tests

variables:
  BUILD: 'TODAY'
  GIT_CLONE_PATH: '$CI_BUILDS_DIR/${BUILD}/global-workflow'
  HOMEGFS: $GIT_CLONE_PATH
  RUNTESTS_DIR: $CI_BUILDS_DIR/${BUILD}/RUNTESTS
  GIT_DEPTH: 1
  RUNNER_SCRIPT_TIMEOUT: 6h
  RUNNER_AFTER_SCRIPT_TIMEOUT: 6h

.base_config:
  variables:
    GIT_STRATEGY: none

.build_template:
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  allow_failure: true
  script:
    - echo "Using build directory $HOMEGFS (dated $BUILD_DATE)"
    - ci/scripts/utils/ci_utils_wrapper.sh build_compute
    - sorc/link_workflow.sh
    - mkdir -p $RUNTESTS_DIR

.setup_template:
  extends: .base_config
  stage: create_experiments
  allow_failure: true
  script:
    - export RUNTESTS=$RUNTESTS_DIR
    - $HOMEGFS/ci/scripts/utils/ci_utils_wrapper.sh create_experiment $HOMEGFS/ci/cases/pr/${caseName}.yaml
  dependencies:
    - build-$MACHINE

.run_tests_template:
  extends: .base_config
  stage: run_tests
  allow_failure: true
  script:
    - echo "Using build directory $HOMEGFS (dated $BUILD_DATE)"
    - pslot=$($HOMEGFS/ci/scripts/utils/ci_utils_wrapper.sh get_pslot $RUNTESTS_DIR ${caseName})
    - $HOMEGFS/ci/scripts/run-check_ci.sh $CI_BUILDS_DIR/$BUILD $pslot global-workflow
  dependencies:
    - setup_experiments-$MACHINE

# Machine-specific jobs generated from template:
"""

# Template for each machine's configuration
MACHINE_TEMPLATE = """
build-{machine}:
  extends: .build_template
  variables:
    MACHINE: {machine}
  tags: ["{machine}"]

setup_experiments-{machine}:
  extends: .setup_template
  variables:
    MACHINE: {machine}
  tags: ["{machine}"]
  parallel:
    matrix:
      - caseName: {case_list}
  dependencies:
    - build-{machine}

run_tests-{machine}:
  extends: .run_tests_template
  variables:
    MACHINE: {machine}
  tags: ["{machine}"]
  parallel:
    matrix:
      - caseName: {case_list}
  dependencies:
    - setup_experiments-{machine}
"""

def get_case_list_for_machine(machine):
    """Get the list of supported cases for the given machine using get_host_cases function"""
    # Directly call the imported function instead of using subprocess
    cases = get_host_cases(machine, homegfs=_top)
    return cases

def generate_pipeline_config(machines):
    """Generate the GitLab CI pipeline configuration for the given machines"""
    config = GITLAB_CI_TEMPLATE

    for machine in machines:
        # Get the list of cases for this machine
        cases = get_case_list_for_machine(machine)
        
        # Format the list of cases as a YAML-compatible string
        case_list_str = str(cases).replace("'", '"')
        
        # Add this machine's configuration to the output
        config += MACHINE_TEMPLATE.format(
            machine=machine,
            case_list=case_list_str
        )

    return config

def main():
    parser = argparse.ArgumentParser(description='Generate GitLab CI pipeline configuration')
    parser.add_argument('--machines', type=str, required=True, 
                        help='Comma-separated list of machines to include in the pipeline')
    parser.add_argument('--output', type=str, required=False, default=None,
                        help='Output file path (default: ci/.gitlab-ci.yml)')
    args = parser.parse_args()

    # Parse the list of machines
    machines = [m.strip() for m in args.machines.split(',')]
    
    # Generate the pipeline configuration
    config = generate_pipeline_config(machines)
    
    # Determine the output path
    output_path = args.output
    if output_path is None:
        output_path = os.path.join(_top, 'ci', '.gitlab-ci.yml')
    
    # Write the configuration to the output file
    with open(output_path, 'w') as f:
        f.write(config)
    
    print(f"Generated GitLab CI pipeline configuration for machines: {', '.join(machines)}")
    print(f"Configuration written to: {output_path}")

    return 0

if __name__ == '__main__':
    sys.exit(main())
