name: Pull Request
description: Submit an update the global-workflow

body:
  - type: markdown
    attributes:
      value: |
        Please use a short (<54 char), descriptive title. It should complete the sentence "If merged, this PR will _____". Capitalize the first word and do not end with a period.

        PRs should meet these guidelines:
        - Each PR should address ONE topic and have an associated issue.
        - No hard-coded paths or personal directories.
        - No temporary or backup files should be committed (including logs).
        - Any code that you disabled by being commented out should be removed or reenabled.

  - type: textarea
    attributes:
      label: Description
      description: The description will become the commit message for the PR.
      placeholder: |
        Please use this format for your description.

        Describe your changes. Focus on the *what* and *why*. The *how* will be evident from the changes. Also note any interface changes such as command line syntax, that will need to be communicated to users.

        At the end of your description, please be sure to add the issue this PR solves using the word "Resolves". If there are any issues that are related but not resolved, you can use "Refs".

        Resolves #1234
        Refs #5678
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Type of change
      options:
        - label: Bug fix
        - label: New feature
        - label: Breaking change (changes functionality)
        - label: Documentation update

  - type: textarea
    attributes:
      label: How has this been tested?
      description: Please list any tests you conducted, including the machine.
      placeholder: |
        - Clone and build on WCOSS
        - Cycled test on Orion
        - Forecast-only on Hera

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: Any dependent changes have been merged and published
        - label: I have performed a self-review of my own code
        - label: My code follows the style guidelines of this project
        - label: I have commented my code, particularly in hard-to-understand areas
        - label: My changes generate no new warnings
        - label: New and existing tests pass with my changes
        - label: I have made corresponding changes to the documentation, if necessary









