C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    BIN2CHAR    CONVERTS BINARY NUMBER TO EBCDIC
C   PRGMMR: BOSTELMAN        ORG: W/NMC421   DATE: 96-05-23
C
C ABSTRACT: CONVERTS A INTEGER QUANTITY TO EBCDIC CHARACTERS
C
C PROGRAM HISTORY LOG:
C   96-05-23  W.J. BOSTELMAN
C
C USAGE:    CALL  BIN2CHAR (NUMBIN, KDATA, N2)
C
C   INPUT ARGUMENT LIST:
C    NUMBIN  = INTEGER QUANTITY (RANGE: 0 - 99999999)
C    N2      = DESIRED LENGTH OF FINAL CHARACTER STRING, LEFT
C              JUSTIFIED. EXAMPLES: 'I2', 'I4', 'I10', WHERE 'I' IS
C        THE FORMAT TYPE SPECIFIER AND 'W' IS THE WIDTH (# OF DIGITS)
C
C   OUTPUT ARGUMENT LIST:
C    KDATA   = CONVERTED NUMERIC TO EBCDIC CHARACTER STRING.
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      SUBROUTINE  BIN2CHAR (NUMBIN, KDATA, N2)
C
      CHARACTER*3   IW(8)
      CHARACTER*7   FORMT
      CHARACTER*(*) KDATA
C
      INTEGER       NUMBIN
C
      DATA  IW /'1.1', '2.2', '3.3', '4.4', '5.5','6.6','7.7','8.8'/
C
      NERR     = 0
      IF (N2 .LT. 9) THEN  ! >>> START PROCESSING
        FORMT    = '(I'//IW(N2)//')'
        KDATA = ' '
        WRITE (KDATA, FORMT) NUMBIN
C
      ELSE    ! >>>> DON'T PROCESS
        NERR = 12
        PRINT *, ' EXCEEDED NUMBER SIZE IN SUB BIN2CHAR, NERR = '
     &           , NERR
      ENDIF
C
      RETURN
      END
