C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    WINDY        COMPUTES WIND SPEED AND DIRECTION
C   PRGMMR: BOSTELMAN        ORG: W/NMC42    DATE: 92-03-09
C
C ABSTRACT:  THIS SUBROUTINE COMPUTES THE WIND DIRECTION AND WIND
C     SPEED AT EACH POINT IN A SET OF GRID POINTS FROM THE EARTH
C     ORIENTED U AND V COMPONENTS FOR THE GIVEN SET OF POINTS.
C
C PROGRAM HISTORY LOG:
C   81-12-20  R. ALLARD ORGINATOR
C   92-03-09  W. BOSTELMAN - UPGRADED DOCBLOCK
C
C USAGE:    CALL WINDY (U,V,NDIR,NSPD,N)
C   INPUT ARGUMENT LIST:
C     U    - ARRAY OF WESTERLY WIND COMPONENTS (INPUT)
C     V    - ARRAY OF SOUTHERLY WIND COMPONENTS (INPUT)
C     N    - NUMBER OF ELEMENTS IN EACH OF THE ABOVE ARRAYS
C
C   OUTPUT ARGUMENT LIST:
C     NDIR - ARRAY OF WIND DIRECTIONS IN DEGREES (OUTPUT)
C     NSPD - ARRAY OF WIND SPEEDS IN SAME UNIT AS U AND V (OUTPUT)
C
C   INPUT FILES:
C     NONE
C
C   OUTPUT FILES:
C     NONE
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      SUBROUTINE WINDY(U,V,NDIR,NSPD,N)
C
      DIMENSION  U(N), V(N), NDIR(N), NSPD(N)
      DO 50 I=1,N
      NSPD(I)=SQRT(U(I)*U(I)+V(I)*V(I))+0.5
      IF(NSPD(I)) 15,10,15
 10   NDIR(I)=0
      GO TO 50
 15   IF(U(I)) 20,29,20
 20   DIR=(ATAN(V(I)/U(I)))*57.29578
      IF(DIR) 21,22,22
 21   NDIR(I)=DIR-0.5
      GO TO 29
 22   NDIR(I)=DIR+0.5
 29   IF(V(I)) 40,30,30
 30   IF(U(I)) 36,31,35
 31   NDIR(I)=180
      GO TO 50
 35   NDIR(I)=270-NDIR(I)
      GO TO 50
 36   NDIR(I)=90-NDIR(I)
      GO TO 50
 40   IF(U(I)) 36,45,35
 45   NDIR(I)=360
 50   CONTINUE
      RETURN
      END
