set -x
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f000.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f001.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f002.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f003.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f004.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f005.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f006.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f007.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f008.ecf
cp jgdas_atmos_post_anl.ecf jgdas_atmos_post_f009.ecf
