#!/bin/ksh
set -xa
#
# Specify whether the run is production or development
#
export RUN_ENVIR=${RUN_ENVIR:-prod}

####################################
# set up job name and  environment
####################################
export job=${job:-$RUN}
export envir=${envir:-prod}
export host=${host:-`hostname | cut -c1`}

#####################################################################################
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to $DATAROOT
# DEV_ECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to NO
# COM_IN:  Directory for input files, default to $COMROOT/$NET/${envir}
# COM_OUT: Directory for output file, default to $COMROOT/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != prod ]      ### For Developers, "group_name" is passed from the ECF script
then
  . ${PARA_CONFIG:-/global/save/${LOGNAME}/2jif/q3fy12_hybrid/tests/para_config}
  export userid=$LOGNAME
  export DATA_IN=${DATA_IN:-/ptmp/$userid}
fi

###############################################################
# This block can be modified for different test environment
###############################################################
if [[ $RUN_ENVIR = prod && $envir != prod ]]; then
  export DBNROOT=/nwprod/spa_util/fakedbn
  export jlogfile=${jlogfile:-$COMROOT/logs/${envir}/jlogfile}
fi

#
####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-enkf}


####################################
# Specify version numbers
####################################
export crtm_ver=${crtm_ver:-v2.2.3}
export gdas_ver=${gdas_ver:-v6.0.0}
export global_shared_ver=${global_shared_ver:-v6.0.0}
export gsm_ver=${gsm_ver:-v12.0.0}


###############################################

export PS4='$SECONDS + '

# ##############################################
# SETUP EnKF DATA SELECTION PROCESSING VARIABLES
# ##############################################

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=${pid:-$$}
export DATA_IN=${DATA_IN:-$DATAROOT}

export DATA=$DATA_IN/${job}.${pid}
mkdir -p $DATA
cd $DATA

echo "PROCESS EnKF ensemble group $ENSGRP from member $ENSBEG to $ENSEND"

#

####################################
# Determine Job Output Name on System
####################################
export cyc=${cyc:-00}
export outid="LL$job"
[ $envir != prod ]  && export outid="LL${job}_${envir}"
export jobid="${outid}.o${pid}"
export pgmout="$DATA/OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z

####################################
# SENDECF - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
# VERBOSE  - Specify Verbose Output in exglobal_fcst.sh.ecf
####################################
export SENDCOM=${SENDCOM:-NO}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SAVEGES=${SAVEGES:-YES}
export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}

#################################
# Define the Log File directory
#################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Specify Execution Areas
####################################
export HOMEgsm=${HOMEgsm:-$NWROOT/gsm.$gsm_ver}
export EXECgsm=${EXECgsm:-$HOMEgsm/exec}
export FIXgsm=${FIXgsm:-$HOMEgsm/fix/fix_am}
export USHgsm=${USHgsm:-$HOMEgsm/ush}
export SCRgsm=${SCRgsm:-$HOMEgsm/scripts}
export UTILgsm=${UTILgsm:-$HOMEgsm/util}

export HOMEgsi=${HOMEgsi:-/nw${envir}/global_shared.$global_shared_ver}
export EXECgsi=${EXECgsi:-$HOMEgsi/exec}
export FIXgsi=${FIXgsi:-$HOMEgsi/fix}
export SCRgsi=${SCRgsi:-$HOMEgsi/scripts}

export HOMEgdas=${HOMEgdas:-/nw${envir}/gdas.$gdas_ver}
export SCRgdas=${SCRgdas:-$HOMEgdas/scripts}

export HOMEutil=${HOMEutil:-$UTILROOT}
export EXECutil=${EXECutil:-$HOMEutil/exec}
export USHutil=${USHutil:-$HOMEutil/ush}

##############################
# Set up the UTILITIES
##############################
export utilscript=${utilscript:-$USHutil}
export utilexec=${utilexec:-$EXECutil}
export NDATE=${NDATE:-$utilexec/ndate}

# Run setup to initialize working directory and utility scripts
##############################
$utilscript/setup.sh

ERRSCRIPT=${ERRSCRIPT:-$err_chk}
LOGSCRIPT=${LOGSCRIPT:-$startmsg}
export FILESTYLE=${FILESTYLE:-'L'}

##############################
# Run setpdy and initialize PDY variables
##############################
$utilscript/setpdy.sh
. ./PDY

export CDATE=${CDATE:-${PDY}${cyc}}
export GDATE=`$NDATE -06 $CDATE`
export PDYges=`echo $GDATE | cut -c1-8`
export CYCges=`echo $GDATE | cut -c9-10`

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-$COMROOT/${NET}/${envir}}
export COM_OUT=${COM_OUT:-$COMROOT/${NET}/${envir}}

export COMIN=$COM_IN/${RUN}.${PDY}/$cyc
export COMOUT=$COM_OUT/${RUN}.${PDY}/$cyc
export COMINGDAS=${COMINGDAS:-$COM_IN/gdas.${PDY}}
export COMINGES=$COM_IN/${RUN}.${PDYges}/$CYCges

mkdir -m 775 -p $COMOUT

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-/nwges/${envir}}
export GESdir=$gespath/gdas.$PDY
mkdir -m 775 -p $GESdir
####################################
# Specify Special Fcst Vars
####################################
#
# Set executable and script
export GSIEXEC=${GSIEXEC:-$EXECgsi/global_gsi}
export ENKFOMGSH=${ENKFOMGSH:-$SCRgdas/exglobal_enkf_innovate_obs.sh.ecf}
export ANALYSISSH=${ANALYSISSH:-$SCRgsi/exglobal_analysis.sh.ecf}


#Set hybrid and ensemble resolution parameters
export DOHYBVAR=${DOHYBVAR:-YES}
export DIAG_SUFFIX=${DIAG_SUFFIX:-"_ensmean"}
export DIAG_COMPRESS=${DIAG_COMPRESS:-NO}
export DIAG_TARBALL=${DIAG_TARBALL:-YES}
export RUN_SELECT=${RUN_SELECT:-YES}
export USE_SELECT=${USE_SELECT:-NO}

export JCAP_ENKF=${JCAP_ENKF:-574}
export LEVS_ENKF=${LEVS_ENKF:-64}
export LONB_ENKF=${LONB_ENKF:-1152}
export LATB_ENKF=${LATB_ENKF:-576}
export LONA_ENKF=${LONA_ENKF:-1152}
export LATA_ENKF=${LATA_ENKF:-576}
export DELTIM_ENKF=${DELTIM_ENKF:-900}

#
# Forecast Model Horizontal Resolution
#
export JCAP=${JCAP_ENKF:-574}
export JCAP_A=${JCAP_ENKF:-574}
export JCAP_ges=${JCAP_ENKF:-574}
export JCAP_HIRES=${JCAP_HIRES:-1534}

#
# Forecast MOdel Vertical Resolution
#
export LEVS=${LEVS_ENKF:-64}
export LEVS_ges=${LEVS:-64}


#
# These defaults are for the T254L64
#
export LONA=${LONA_ENKF:-512}
export LATA=${LATA_ENKF:-256}
export LONB=${LONB_ENKF:-768}
export LATB=${LATB_ENKF:-384}

export NLAT=$(($LATA+2))
export NLON=$LONA
export NLON_A=$LONA
export NLAT_A=$(($LATA+2))

export LSOIL=${LSOIL:-4}

#
# Time Step
#
export DELTIM=${DELTIM_ENKF:-900}

#
# Surface cycle
#
export use_ufo=${use_ufo:-.true.}
export SNOW_NUDGE_COEFF=${SNOW_NUDGE_COEFF:-'-2.'}

#
# Analysis Fix Fields
#
export FNGLAC=${FNGLAC:-${FIXgsm}/global_glacier.2x2.grb}
export FNMXIC=${FNMXIC:-${FIXgsm}/global_maxice.2x2.grb}
export FNTSFC=${FNTSFC:-$FIXgsm/RTGSST.1982.2012.monthly.clim.grb}
export FNSNOC=${FNSNOC:-${FIXgsm}/global_snoclim.1.875.grb}
export FNZORC=${FNZORC:-'sib'}
export FNALBC=${FNALBC:-${FIXgsm}/global_albedo4.1x1.grb}
export FNAISC=${FNAISC:-${FIXgsm}/CFSR.SEAICE.1982.2012.monthly.clim.grb}
export FNTG3C=${FNTG3C:-${FIXgsm}/global_tg3clim.2.6x1.5.grb}
export FNVEGC=${FNVEGC:-${FIXgsm}/global_vegfrac.0.144.decpercent.grb}
export FNVETC=${FNVETC:-${FIXgsm}/global_vegtype.1x1.grb}
export FNSOTC=${FNSOTC:-${FIXgsm}/global_soiltype.1x1.grb}
export FNSMCC=${FNSMCC:-${FIXgsm}/global_soilmgldas.t${JCAP}.$LONB.$LATB.grb}
export FNOROG=${FNOROG:-${FIXgsm}/global_orography.t${JCAP}.$LONB.$LATB.grb}
export FNMASK=${FNMASK:-${FIXgsm}/global_slmask.t${JCAP}.$LONB.$LATB.grb}
export OROGRAPHY=${OROGRAPHY:-${FIXgsm}/global_orography.t${JCAP}.$LONB.$LATB.grb}
export OROGRAPHY_UF=${OROGRAPHY_UF:-${FIXgsm}/global_orography_uf.t${JCAP}.$LONB.$LATB.grb}
export SLMASK=${SLMASK:-${FIXgsm}/global_slmask.t${JCAP}.$LONB.$LATB.grb}

export BERROR_ENKF=${BERROR_ENKF:-${FIXgsi}/Big_Endian/global_berror.l${LEVS}y${NLAT}.f77}
export BERROR=${BERROR_ENKF:-${FIXgsi}/global_berror.l${LEVS}y${NLAT}.f77}
export SATANGL=${SATANGL:-${FIXgsi}/global_satangbias.txt}
export SATINFO=${SATINFO:-${FIXgsi}/global_satinfo.txt}
export ATMSFILTER=${ATMSFILTER:-${FIXgsi}/atms_beamwidth.txt}
export ANAVINFO=${ANAVINFO:-${FIXgsi}/global_anavinfo.l${LEVS}.txt}
export CONVINFO=${CONVINFO:-${FIXgsi}/global_convinfo.txt}
export OZINFO=${OZINFO:-${FIXgsi}/global_ozinfo.txt}
export PCPINFO=${PCPINFO:-${FIXgsi}/global_pcpinfo.txt}
export AEROINFO=${AEROINFO:-${FIXgsi}/global_aeroinfo.txt}
export SCANINFO=${SCANINFO:-${FIXgsi}/global_scaninfo.txt}
export HYBENSINFO=${HYBENSINFO:-${FIXgsi}/global_hybens_locinfo.l${LEVS}.txt}
export OBERROR=${OBERROR:-${FIXgsi}/prepobs_errtable.global}

export RTMFIX=${RTMFIX:-$NWROOT/lib/crtm/${crtm_ver}/fix}


#
# Common Analysis Input Fields
#
export SELECT_OBS=${SELECT_OBS:-${COMIN}/obsinput_${CDATE}_ensmean}
export SIGGESMEAN=${SIGGESMEAN:-${COMINGES}/sfg_${GDATE}_fhr06s_ensmean}
export SFCGESMEAN=${SFCGESMEAN:-${COMINGES}/bfg_${GDATE}_fhr06_ensmean}
export NSTGESMEAN=${NSTGESMEAN:-${COMINGES}/nfg_${GDATE}_fhr06_ensmean}

# Specify smoothed EnKF forecasts
export SMOOTH_ENKF=${SMOOTH_ENKF:-"YES"}

# Specify dump files for global_cycle
export PREINPGDAS=${PREINPGDAS:-gdas1.${cycle}.}
export FNTSFA=${FNTSFA:-${COMINGDAS}/${PREINPGDAS}rtgssthr.grb}
export FNACNA=${FNACNA:-${COMINGDAS}/${PREINPGDAS}seaice.5min.blend.grb}
export FNSNOA=${FNSNOA:-${COMINGDAS}/${PREINPGDAS}snogrb_t${JCAP}.${LONB}.${LATB}}


# Set non-assimilated obs fles as /dev/null to prevent reading
# added 11/2008 by wx11sc to decrease run time, since SSMI and AMSRE are
# not assimilated
export AMSREBF=${AMSREBF:-/dev/null}
export SSMITBF=${SSMITBF:-/dev/null}

############################################################################ 
#
# Check grib date of current snogrb vs that of prev cycle 
#
# if cdate_of_snogrb -le cdate_of_snoprv, i.e. file has not been updated 
#   then set namelist input to CYCLEXEC to use the snow from the guess
#   FNSNOA=" ";CYCLVARS="FSNOL=99999.,FSNOS=99999.,"
#   FNSNOA is the name of the snow depth  analysis file 
#     when not supplied, signals to CYCLEXEC to blend guess and climatology
#     (Note: file must be " ", not "" or the shell syntax for default
#      values X=${X:-default} will reset to default if X="")
#     FSNOL=99999.,FSNOS=99999., sets the blending of guess and climo to
#		use 100% guess
#
####################################
prev_cdate=$($NDATE -6 ${PDY}$cyc)
wgrib=$utilexec/wgrib
RUN_GETGES=${RUN_GETGES:-YES}        # Set to NO if not running getges.sh
if [ $RUN_GETGES = YES ]; then
 GETGESSH=${GETGESSH:-$utilscript/getges.sh}
 export gesenvir=${gesenvir:-$envir}
 snoprv=$($GETGESSH -q -t snogrb_$JCAP_ENKF -e $gesenvir -n gdas -v $prev_cdate)
else
 snoprv=${snoprv:-$FNSNOG}
fi
if [ `$wgrib -4yr ${FNSNOA} 2>/dev/null|grep -i snowc |\
	  awk -F: '{print $3}'|awk -F= '{print $2}'` -le \
     `$wgrib -4yr $snoprv 2>/dev/null |grep -i snowc  |\
			awk -F: '{print $3}'|awk -F= '{print $2}'` ] ; then
	export FNSNOA=" "
	export CYCLVARS="FSNOL=99999.,FSNOS=99999.,"
else
     export SNOW_NUDGE_COEFF=${SNOW_NUDGE_COEFF:-0.}
     export CYCLVARS="FSNOL=${SNOW_NUDGE_COEFF},$CYCLVARS"
fi

############################################################################ 
#
# Output File Names

export SIGANL=/dev/null
export ABIAS=/dev/null
export ABIASPC=/dev/null


#
# PDS Grid Designator
# What IGEN to use for GDAS EnKF?
export IGEN=${IGEN:-82}

msg="HAS BEGUN on `hostname`"
./postmsg "$jlogfile" "$msg"

####################################
# Check if this is a restart
#
# Define Previous Guess File Names (dev users must provide from outside)
####################################
err1=0
if [ $RUN_GETGES = YES ]; then
  export gesenvir=${gesenvir:-$envir}
  $GETGESSH -t biascr -r ${JCAP_ges}$LEVS_ges -v ${PDY}$cyc -e $gesenvir -n gdas gbias
err1=$?
  $GETGESSH -t biascr_pc -r ${JCAP_ges}$LEVS_ges -v ${PDY}$cyc -e $gesenvir -n gdas gbias_pc
  $GETGESSH -t biascr_air -r ${JCAP_ges}${LEVS_ges} -v $PDY$cyc -e $gesenvir -n gdas gbias_air
  $GETGESSH -t radstat -r ${JCAP_ges}$LEVS_ges -v ${PDY}$cyc -e $gesenvir -n gdas gradstat
fi

export GBIAS=${GBIAS:-$DATA/gbias}
export GRADSTAT=${GRADSTAT:-$DATA/gradstat}
export GBIASPC=${GBIASPC:-$DATA/gbias_pc}
export GBIASAIR=${GBIASAIR:-$DATA/gbias_air}

if [ $err1 -eq 0 ] ; then
   msg="Analysis Starting/Guess Fields Found"
   ./postmsg "$jlogfile" "$msg"
else
   msg="Analysis Cannot Start/Guess Fields Not Available"
   ./postmsg "$jlogfile" "$msg"
   export pgm=$job
   export err=911
   ./err_chk
fi


# Set namelist jobs for ensemble data selection
export USE_NEWRADBC=${USE_NEWRADBC:-YES}
export SETUP="miter=0,niter=1,lread_obs_save=.false.,lread_obs_skip=.true.,lwrite_predterms=.true.,lwrite_peakwt=.true.,reduce_diag=.true.,passive_bc=.false.,"
export BKGVERR="bkgv_flowdep=.false.,"
export STRONGOPTS="tlnmc_option=0,nstrong=0,nvmodes_keep=0,baldiag_full=.false.,baldiag_inc=.false.,"
export OBSQC="tcp_width=60.0,tcp_ermin=2.0,tcp_ermax=12.0,qc_noirjaco3_pole=.true.,"
export OBSINPUT="dmesh(1)=225.0,dmesh(2)=225.0,"


############################
# WCOSS environment settings
##export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usrx/local/netcdf-3.6.3/lib

export MP_EAGER_LIMIT=65536
export MP_COREFILE_FORMAT=lite
export MP_EUIDEVELOP=min
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_MPILIB=mpich2

export MP_LABELIO=yes
export MP_USE_BULK_XFER=yes
export MP_SHARED_MEMORY=yes
export MPICH_ALLTOALL_THROTTLE=0
export MP_USE_TOKEN_FLOW_CONTROL=yes
export KMP_STACKSIZE=1024m

export NTHREADS_GSI=${NTHREADS_GSI:-1}
export NTHSTACK=1024000000                # stacks for fcst step; default 128000000
export NTHSTACK_GSI=1024000000            # stack size for anal, default=128000000

export OMP_NUM_THREADS_CY=24

export machine=WCOSS
##export APRUNCY=
export APRUN='mpirun.lsf'


env

#############################################################
# Execute the script
${ENKFOMGSH:-$SCRgdas/exglobal_enkf_innovate_obs.sh.ecf}
#############################################################

##########
# NOTES: 1) script exglobal_analysis.sh.ecf compresses the contents of
#           RADSTAT, PCPSTAT, OZNSTAT, and CNVSTAT.  These stat files
#           files are tarballs of compressed files.
##########

if [ $SENDDBN = YES ] ; then
   $DBNROOT/bin/dbn_alert MODEL ENKF1_MSC_gsistat $job $COMOUT/gsistat_${CDATE}_ensmean
fi

cat $pgmout

##grep memory $DATA/mpi*

msg="ENDED NORMALLY."
./postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${KEEPDATA:-NO} != YES ] ; then rm -rf $DATA ; fi

date
