#!/bin/ksh
set -xa
#
# Specify whether the run is production or development
#
export RUN_ENVIR=${RUN_ENVIR:-prod}

#####################################################################################
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd
# DEV_ECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to NO
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != prod ]      ### For Developers, "group_name" is passed from the ECF script
then
  . ${PARA_CONFIG:-/global/save/${LOGNAME}/2jif/q3fy12_hybrid/tests/para_config}
  export userid=$LOGNAME
  export DATA_IN=${DATA_IN:-/ptmp/$userid}
fi

###############################################################
# This block can be modified for different test environment
###############################################################
if [[ $RUN_ENVIR = prod && $envir != prod ]]; then
  export SENDDBN=${SENDDBN:-NO}
  export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
fi

#
####################################
# Specify NET and RUN Name and model
####################################
export NET=gfs
export RUN=enkf

####################################
# set up job name and  environment
####################################
export job=${job:-$RUN}
export envir=${envir:-prod}
export host=${host:-`hostname | cut -c1`}

###############################################

date
export PS4='$SECONDS + '

# ##############################################
# SETUP EnKF DATA SELECTION PROCESSING VARIABLES
# ##############################################

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=${pid:-$$}
export DATA_IN=${DATA_IN:-/tmpnwprd}

export DATA=$DATA_IN/${job}.${pid}
mkdir -p $DATA
cd $DATA

echo "PROCESS EnKF ensemble group $ENSGRP from member $ENSBEG to $ENSEND"

#

####################################
# Determine Job Output Name on System
####################################
export cyc=${cyc:-00}
export outid="LL$job"
[ $envir != prod ]  && export outid="LL${job}_${envir}"
export jobid="${outid}.o${pid}"
##export pgmout="OUTPUT.${pid}"
export pgmout="$DATA/OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
# VERBOSE  - Specify Verbose Output in exglobal_fcst.sh.ecf
####################################
export SAVEGES=${SAVEGES:-NO}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-NO}
export SENDDBN=${SENDDBN:-NO}
export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}

#################################
# Define the Log File directory
#################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}


####################################
# Specify Execution Areas
####################################
export HOMEGLOBAL=${HOMEGLOBAL:-/nw${envir}}
export EXECGLOBAL=${EXECGLOBAL:-$HOMEGLOBAL/exec}
export FIXGLOBAL=${FIXGLOBAL:-$HOMEGLOBAL/fix}
export USHGLOBAL=${USHGLOBAL:-$HOMEGLOBAL/ush}
export SCRGLOBAL=${SCRGLOBAL:-$HOMEGLOBAL/scripts}
export UTILGLOBAL=${UTILGLOBAL:-$HOMEGLOBAL/util}
export PARMGLOBAL=${PARMGLOBAL:-$HOMEGLOBAL/parm}

##############################
# Set up the UTILITIES
##############################
export utilscript=${utilscript:-$UTILGLOBAL/ush}
export utilexec=${utilexec:-$UTILGLOBAL/exec}
export NDATE=${NDATE:-$utilexec/ndate}

# Run setup to initialize working directory and utility scripts
##############################
$utilscript/setup.sh

err_chk=${err_chk:-$utilscript/err_chk.sh}
startmsg=${startmsg:-$utilscript/startmsg.sh}
ERRSCRIPT=${ERRSCRIPT:-$err_chk}
LOGSCRIPT=${LOGSCRIPT:-$startmsg}
export FILESTYLE=${FILESTYLE:-'L'}

##############################
# Run setpdy and initialize PDY variables
##############################
##export PDY=2012011006
$utilscript/setpdy.sh
. ./PDY

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-/com/${NET}/${envir}}
export COM_OUT=${COM_OUT:-/com/${NET}/${envir}}

export COMIN=$COM_IN/enkf.${PDY}/$cyc
export COMOUT=$COM_OUT/enkf.${PDY}/$cyc
export COMINGDAS=${COMINGDAS:-$COM_IN/gdas.${PDY}}

mkdir -m 775 -p $COMOUT

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-/nwges/${envir}}
export GESdir=$gespath/gdas.$PDY
mkdir -m 775 -p $GESdir
####################################
# Specify Special Fcst Vars
####################################

#Set hybrid and ensemble resolution parameters
export DOHYBVAR=${DOHYBVAR:-YES}

export JCAP_ENKF=${JCAP_ENKF:-254}
export LEVS_ENKF=${LEVS_ENKF:-64}
export LONB_ENKF=${LONB_ENKF:-768}
export LATB_ENKF=${LATB_ENKF:-384}
export LONA_ENKF=${LONA_ENKF:-512}
export LATA_ENKF=${LATA_ENKF:-256}
export DELTIM_ENKF=${DELTIM_ENKF:-300}

export CO2DIR=$FIXGLOBAL/fix_co2_proj
export CO2_seasonal_cycle=$FIXGLOBAL/global_co2monthlycyc1976_2006.txt

#
# Forecast Model Horizontal Resolution
#
export JCAP=${JCAP_ENKF:-254}
export JCAP_A=${JCAP_ENKF:-254}
export JCAP_ges=${JCAP_ENKF:-254}

export JCAP_HIRES=${JCAP_HIRES:-574}

#
# Forecast MOdel Vertical Resolution
#
export LEVS=${LEVS_ENKF:-64}
export LEVS_ges=${LEVS:-64}

export CDATE=${CDATE:-${PDY}${cyc}}
export GDATE=`$NDATE -06 $CDATE`

export PDYges=`echo $GDATE | cut -c1-8`
export CYCges=`echo $GDATE | cut -c9-10`
export COMINGES=$COM_IN/enkf.${PDYges}/$CYCges

#
# These defaults are for the T254L64
#
export LONA=${LONA_ENKF:-512}
export LATA=${LATA_ENKF:-256}
export LONB=${LONB_ENKF:-768}
export LATB=${LATB_ENKF:-384}

export NLAT=$(($LATA+2))
export NLON=$LONA
export NLON_A=$LONA
export NLAT_A=$(($LATA+2))

export LSOIL=${LSOIL:-4}

#
# Time Step
#
export DELTIM=${DELTIM_ENKF:-300}

############################################################
# Input parameters to the Model
############################################################
export FHROT_ENFK=${FHROT_ENKF:-0}  # Forecast hour to Read One Time level
export FHOUT_ENKF=${FHOUT_ENKF:-3}  # Forecast Hour Output Frequency
export FHMAX_ENKF=${FHMAX_ENKF:-9}  # Forecast Length (Hours)
export FHRES_ENKF=${FHRES_ENKF:-24} # Forecast Hour Restart Frequency
export FHZER_ENKF=${FHZER_ENKF:-6}  # Interval to Zero out precip field,etc. Should not be less that FHOUT
export FHDFI_ENKF=${FHDFI_ENKF:-3}  # Half number of hours of digital filter initialization
export FHCYC_ENKF=${FHCYC_ENKF:-24} # Surface cycling boundary condition update frequency in hours
export FHLWR_ENKF=${FHLWR_ENKF:-1}  # LW radiation calling interval (hrs)
export FHSWR_ENKF=${FHSWR_ENKF:-1}  # SW radiation calling interval (hrs)
export IEMS_ENKF=${IEMS_ENKF:-0}    # 0-blackbody ground emission; 1-climatology on one-deg map
export ISOL_ENKF=${ISOL_ENKF:-0}    # 0--fixed solar constant; 1--changing solar constant
export IAER_ENKF=${IAER_ENKF:-111}  # 111--with stratospheric aerosol, tropospheric aerosol LW, troposphere aerosol SW.
export ICO2_ENKF=${ICO2_ENKF:-1}    # 0--fixed CO2 constant; 1--time varying global mean CO2; 2--changing CO2
export ICTM_ENKF=${ICTM_ENKF:-1}    # ictm=0 => use data at initial cond time, if not available, use latest, no extrapolation.
                                    # ictm=1 => use data at the forecast time, if not available, use latest and extrapolation.
                                    # ictm=yyyy0 => use yyyy data for the forecast time, no further data extrapolation.
                                    # ictm=yyyy1 = > use yyyy data for the fcst. if needed, do extrapolation to match the fcst time.
                                    # ictm=-1 => use user provided external data for the fcst time, no extrapolation.
                                    # ictm=-2 => same as ictm=0, but add seasonal cycle from climatology. no extrapolation.


# Variables for High Frequency Output
export FHOUTHF_ENKF=${FHOUTHF_ENKF:-3}  # High Frequency Forecast Output Interval
export FHMAXHF_ENKF=${FHMAXHF_ENKF:-9}  # High Frequency Forecast Length (Hours)

# Variables for GOCART Output
export FHGOC3D_ENKF=${FHGOC3D_ENKF:-0}      # Forecast Output Length for G3D files for GOCART
export LGOC3D_ENKF=${LGOC3D_ENKF:-.false.}  # Control Variable to output the G3D files for GOCART

# Variables for input to the Namelist
export IALB_ENKF=${IALB_ENKF:-0}        # 0: climatology sw albedo based on surface veg types;
                                        # 1: MODIS based land surface albedo
export IOVR_SW_ENKF=${IOVR_SW_ENKF:-1}  # 0--random cloud overlap for SW; 1--maximum-random cloud overlap for SW

#  Other parameters input to the model
export FCSTVARS_ENKF=${FCSTVARS_ENKF:-"ras=.false.,nsout=0,lsm=1,tfiltc=0.85,liope=.true.,zhao_mic=.true.,ncw=50,150,crtrh=0.85,0.85,0.85,flgmin=0.220 ,IALB=$IALB_ENKF,ccnorm=.false.,OUT_VIRTTEMP=.true.,LDIAG3D=.false.,mstrat=.false.,ctei_rm=0.50,MOM4ICE=.false.,cnvgwd=.false.,RUN_ENTHALPY=.false.,IOVR_SW=$IOVR_SW_ENKF,zflxtvd=.true.,sashal=.true.,old_monin=.false.,newsas=.true.,ICTM=$ICTM_ENKF"}

if [ $LGOC3D_ENKF = .true. ] ; then
  export FCSTVARS_ENKF="LGOC3D=$LGOC3D_ENKF,FHGOC3D=$FHGOC3D_ENKF,$FCSTVARS_ENKF"
fi

# Forecast executable
export FCSTEXEC=${FCSTEXEC:-${EXECGLOBAL}/global_fcst}

# EnKF scripts
export ENKFFCSSH=${ENKFFCSSH:-$SCRGLOBAL/exglobal_enkf_fcst.sh.ecf}
export FORECASTSH=${FORECASTSH:-$SCRGLOBAL/exglobal_fcst.sh.ecf}

# Input variables

#
# Input fix files
export FNOROG=${FNOROG:-$FIXGLOBAL/global_orography.t$JCAP.grb}
export FNMASK=${FNMASK:-$FIXGLOBAL/global_slmask.t$JCAP.grb}
export OROGRAPHY=${OROGRAPHY:-$FIXGLOBAL/global_orography.t$JCAP.grb}
export SLMASK=${SLMASK:-$FIXGLOBAL/global_slmask.t$JCAP.grb}

#
# Input Fields
#


############################################################################ 
#
# Output File Names
#  SIGANL, ABIAS, ABIASPC not needed by EnKF.  Therefore keep in $DATA


#
# PDS Grid Designator
# What IGEN to use for GDAS EnKF?
export IGEN=${IGEN:-82}

msg="HAS BEGUN on `hostname`"
./postmsg "$jlogfile" "$msg"


############################
# WCOSS environment variables
##export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usrx/local/netcdf-3.6.3/lib

export MP_EAGER_LIMIT=165536
export MP_COREFILE_FORMAT=lite
export MP_EUIDEVELOP=min
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_MPILIB=mpich2

export MP_LABELIO=yes
export MP_SINGLE_THREAD=yes
export MP_USE_BULK_XFER=yes
export MP_SHARED_MEMORY=yes
export MP_COLLECTIVE_OFFLOAD=no
export KMP_STACKSIZE=1024m

export MP_TASK_AFFINITY=${MP_TASK_AFFINITY:-cpu:1}
export NTHREADS_EFCS=${NTHREADS_EFCS:-1}

export machine=WCOSS
export APRUN='mpirun.lsf'


env

#############################################################
# Execute the script
${ENKFFCSSH:-$SCRGLOBAL/exglobal_enkf_fcst.sh.ecf}
#############################################################

##########
# NOTES: 1) script exglobal_analysis.sh.ecf compresses the contents of
#           RADSTAT, PCPSTAT, OZNSTAT, and CNVSTAT.  These stat files
#           files are tarballs of compressed files.
##########

if [ $SENDDBN = YES ] ; then
   $DBNROOT/bin/dbn_alert MODEL ENKF1_MSC_fcsstat $job $COMOUT/fcsstat_${CDATE}_grp${ENSGRP}
fi

cat $pgmout

msg="ENDED NORMALLY."
./postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date
