#!/bin/ksh
set -xa
#
# Specify whether the run is production or development
#
export RUN_ENVIR=${RUN_ENVIR:-prod}

####################################
# set up job name and  environment
####################################
export job=${job:-$RUN}
export envir=${envir:-prod}
export host=${host:-`hostname | cut -c1`}

#####################################################################################
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to $DATAROOT
# DEV_ECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to NO
# COM_IN:  Directory for input files, default to $COMROOT/$NET/${envir}
# COM_OUT: Directory for output file, default to $COMROOT/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != prod ]      ### For Developers, "group_name" is passed from the ECF script
then
  . ${PARA_CONFIG:-/global/save/${LOGNAME}/2jif/q3fy12_hybrid/tests/para_config}
  export userid=$LOGNAME
  export DATA_IN=${DATA_IN:-/ptmp/$userid}
fi

###############################################################
# This block can be modified for different test environment
###############################################################
if [[ $RUN_ENVIR = prod && $envir != prod ]]; then
  export DBNROOT=/nwprod/spa_util/fakedbn
  export jlogfile=${jlogfile:-$COMROOT/logs/${envir}/jlogfile}
fi

#
####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-enkf}


####################################
# Specify version numbers
####################################
export gdas_ver=${gdas_ver:-v6.0.0}
export global_shared_ver=${global_shared_ver:-v6.0.0}
export gsm_ver=${gsm_ver:-v12.0.0}


###############################################

export PS4='$SECONDS + '

# ##############################################
# SETUP EnKF DATA SELECTION PROCESSING VARIABLES
# ##############################################

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=${pid:-$$}
export DATA_IN=${DATA_IN:-$DATAROOT}

export DATA=$DATA_IN/${job}.${pid}
mkdir -p $DATA
cd $DATA
#

####################################
# Determine Job Output Name on System
####################################
export cyc=${cyc:-00}
export outid="LL$job"
[ $envir != prod ]  && export outid="LL${job}_${envir}"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun fcst from beginning (default no)
# VERBOSE  - Specify Verbose Output in exglobal_fcst.sh.ecf
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SAVEGES=${SAVEGES:-NO}
export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}

#################################
# Define the Log File directory
#################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Specify Execution Areas
####################################
export HOMEgsm=${HOMEgsm:-$NWROOT/gsm.$gsm_ver}
export EXECgsm=${EXECgsm:-$HOMEgsm/exec}
export FIXgsm=${FIXgsm:-$HOMEgsm/fix/fix_am}
export USHgsm=${USHgsm:-$HOMEgsm/ush}
export SCRgsm=${SCRgsm:-$HOMEgsm/scripts}
export UTILgsm=${UTILgsm:-$HOMEgsm/util}

export HOMEgsi=${HOMEgsi:-/nw${envir}/global_shared.$global_shared_ver}
export EXECgsi=${EXECgsi:-$HOMEgsi/exec}
export FIXgsi=${FIXgsi:-$HOMEgsi/fix}
export SCRgsi=${SCRgsi:-$HOMEgsi/scripts}

export HOMEgdas=${HOMEgdas:-/nw${envir}/gdas.$gdas_ver}
export EXECgdas=${EXECgdas:-$HOMEgdas/exec}
export FIXgdas=${FIXgdas:-$HOMEgdas/fix}
export SCRgdas=${SCRgdas:-$HOMEgdas/scripts}

export HOMEutil=${HOMEutil:-$UTILROOT}
export EXECutil=${EXECutil:-$HOMEutil/exec}
export USHutil=${USHutil:-$HOMEutil/ush}

##############################
# Set up the UTILITIES
##############################
export utilscript=${utilscript:-$USHutil}
export utilexec=${utilexec:-$EXECutil}
export NDATE=${NDATE:-$utilexec/ndate}

# Run setup to initialize working directory and utility scripts
##############################
$utilscript/setup.sh

ERRSCRIPT=${ERRSCRIPT:-$err_chk}
LOGSCRIPT=${LOGSCRIPT:-$startmsg}
export FILESTYLE=${FILESTYLE:-'L'}

##############################
# Run setpdy and initialize PDY variables
##############################
$utilscript/setpdy.sh
. ./PDY

# Set CDATE and GDATE
export CDATE=${CDATE:-${PDY}${cyc}}
export GDATE=`$NDATE -06 $CDATE`
export PDYges=`echo $GDATE | cut -c1-8`
export CYCges=`echo $GDATE | cut -c9-10`

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-$COMROOT/${NET}/${envir}}
export COM_OUT=${COM_OUT:-$COMROOT/${NET}/${envir}}

export COMIN=$COM_IN/enkf.${PDY}/$cyc
export COMOUT=$COM_OUT/enkf.${PDY}/$cyc
export COMINGDAS=${COMINGDAS:-$COM_IN/gdas.${PDY}}
export COMINGES=$COM_IN/enkf.${PDYges}/$CYCges
export GETGES_COM=${GETGES_COM:-$COMROOT}
export GETGES_NWG=${GETGES_NWG:-/nwges}


mkdir -m 775 -p $COMOUT

##############################################
# Define GES directories
##############################################
export gespath=${gespath:-/nwges/${envir}}
export GESdir=$gespath/gdas.$PDY
mkdir -m 775 -p $GESdir
####################################
# Specify Special Fcst Vars
####################################
#
#Set hybrid and ensemble resolution parameters
export NTHREADS_ENKF=${NTHREADS_ENKF:-2}
export JCAP_ENKF=${JCAP_ENKF:-574}
export LEVS_ENKF=${LEVS_ENKF:-64}
export LONB_ENKF=${LONB_ENKF:-1152}
export LATB_ENKF=${LATB_ENKF:-576}
export LONA_ENKF=${LONA_ENKF:-1152}
export LATA_ENKF=${LATA_ENKF:-576}
export NMEM_ENKF=${NMEM_ENKF:-80}
export NVARS=${NVARS:-5}

#
# These defaults are for the T254L64
#
export LONA=${LONA_ENKF:-1152}
export LATA=${LATA_ENKF:-576}
export LONB=${LONB_ENKF:-1152}
export LATB=${LATB_ENKF:-576}
export LEVS=${LEVS_ENKF:-64}

# Forecast Vertical Resolution
#
export JCAP_ges=${JCAP_ges:-574}
export LEVS_ges=${LEVS_ges:-64}
#


# EnKF executable
export ENKFUPDEXEC=${ENKFUPDEXEC:-${EXECgdas}/global_enkf}

# EnKF script
export ENKFUPDSH=${ENKFUPDSH:-$SCRgdas/exglobal_enkf_update.sh.ecf}

# Enkf fix files
export SATANGL=${SATANGL:-${FIXgsi}/global_satangbias.txt}
export SATINFO=${SATINFO:-${FIXgsi}/global_satinfo.txt}
export SCANINFO=${SCANINFO:-${FIXgsi}/global_scaninfo.txt}
export CONVINFO=${CONVINFO:-${FIXgsi}/global_convinfo.txt}
export OZINFO=${OZINFO:-${FIXgsi}/global_ozinfo.txt}
export HYBENSINFO=${HYBENSINFO:-${FIXgsi}/global_hybens_locinfo.l${LEVS}.txt}

# EnKF ensemble files
export GBIASE=${GBIASE:-$COMIN/biascr_int_${CDATE}_ensmean}
export CNVSTAT=${CNVSTAT:-$COMIN/cnvstat_$CDATE}
export OZNSTAT=${OZNSTAT:-$COMIN/oznstat_$CDATE}
export RADSTAT=${RADSTAT:-$COMIN/radstat_$CDATE}
export SIGGESENS=${SIGGESENS:-${COMINGES}/sfg_${GDATE}_fhr06s}

export SIGGES=${SIGGES:-${COMINGES}/sfg_${GDATE}_fhr06_ensmean}
export SFCGES=${SFCGES:-${COMINGES}/bfg_${GDATE}_fhr06_ensmean}

# Specify smoothed EnKF forecasts
export SMOOTH_ENKF=${SMOOTH_ENKF:-"YES"}


############################################################################ 
#
# Output File Names

export ENKFSTAT=${ENKFSTAT:-$COMOUT/enkfstat_$CDATE}
export SIGANLENS=${SIGANLENS:-${COMOUT}/sanl_${CDATE}}


msg="HAS BEGUN on `hostname`"
./postmsg "$jlogfile" "$msg"

####################################
# Check if this is a restart
#
# Define Previous Guess File Names (dev users must provide from outside)
####################################
RUN_GETGES=${RUN_GETGES:-YES}        # Set to NO if not running getges.sh
err1=0
if [ $RUN_GETGES = YES ]; then
  GETGESSH=${GETGESSH:-$utilscript/getges.sh}
  export gesenvir=${gesenvir:-$envir}
  $GETGESSH -t biascr -r ${JCAP_ges}$LEVS_ges -v ${PDY}$cyc -e $gesenvir -n gdas gbias
err1=$?
fi

export GBIAS=${GBIAS:-$DATA/gbias}


if [ $err1 -eq 0 ] ; then
   msg="Analysis Starting/Guess Fields Found"
   ./postmsg "$jlogfile" "$msg"
else
   msg="Analysis Cannot Start/Guess Fields Not Available"
   ./postmsg "$jlogfile" "$msg"
   export pgm=$job
   export err=911
   ./err_chk
fi


# Set namelist variables for enhanced radiance bias correction scheme
export USE_NEWRADBC=${USE_NEWRADBC:-YES}


############################
# WCOSS environment settings
export MP_EAGER_LIMIT=65536
export MP_COREFILE_FORMAT=lite
export MP_EUIDEVELOP=min
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_MPILIB=mpich2

export MP_LABELIO=yes
export MP_USE_BULK_XFER=yes
export MP_SHARED_MEMORY=yes
export MP_SINGLE_THREAD=yes

export MPICH_ALLTOALL_THROTTLE=0
export KMP_STACKSIZE=2048m

export machine=WCOSS
export APRUN='mpirun.lsf'

env

#############################################################
# Execute the script
${ENKFUPDSH:-$SCRgdas/exglobal_enkf_update.sh.ecf}
#############################################################


if [ $SENDDBN = YES ] ; then
   $DBNROOT/bin/dbn_alert MODEL ENKF1_MSC_enkfstat $job $COMOUT/enkfstat_${CDATE}
fi

cat $pgmout

grep memory $DATA/mpi*

msg="ENDED NORMALLY."
./postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${KEEPDATA:-NO} != YES ] ; then rm -rf $DATA ; fi

date
