#!/usr/bin/sh

# run model
setenv DATOUT ${datapath}${analdatep1}

set nanal=1

while ($nanal <= $nanals)
 setenv charnanal "mem`printf %03i $nanal`"
 setenv SFCI ${datapath}/${analdate}/sfcanl_${analdate}_${charnanal}
 setenv SIGI ${datapath}/${analdate}/sanl_${analdate}_${charnanal}

# check to see if output files already created.
 set fhr=$FHMIN
 set outfiles=""
 while ($fhr <= $FHMAX)
    set charhr="fhr`printf %02i $fhr`"
    set outfiles = "${outfiles} ${datapath}${analdatep1}/sfg_${analdatep1}_${charhr}_${charnanal} ${datapath}${analdatep1}/bfg_${analdatep1}_${charhr}_${charnanal}"
    @ fhr = $fhr + $FHOUT
 end
 echo "run_fg_fgs outfiles = " $outfiles

 set filemissing='no'
 foreach outfile ($outfiles) 
   if (-e "${outfile}" ) then
     echo "${outfile} is OK"
   else
     echo "${outfile} is missing"
     set filemissing='yes'
   endif
 end

 if ($filemissing == 'yes') then
   echo "nanal = ${nanal}"
   time sh ${enkfscripts}/drive_gfs >&! ${current_logdir}/run_fg_${charnanal}.out 
 else
   echo "skipping nanal = ${nanal}, output files already created"
 endif

@ nanal = $nanal + 1
end

echo "all done `date`"

# check to see all files created
echo "checking output files .."`date`

set nanal=1
set anyfilemissing='no'
while ($nanal <= $nanals)
    setenv charnanal  "mem`printf %03i $nanal`"
    set fhr=$FHMIN
    set outfiles=""
    while ($fhr <= $FHMAX)
       set charhr="fhr`printf %02i $fhr`"
       set outfiles = "${outfiles} ${datapath}${analdatep1}/sfg_${analdatep1}_${charhr}_${charnanal} ${datapath}${analdatep1}/bfg_${analdatep1}_${charhr}_${charnanal}"
       @ fhr = $fhr + $FHOUT
    end
    set filemissing='no'
    foreach outfile ($outfiles) 
      ls -l $outfile
      if (-e $outfile) then 
        echo "${outfile} is OK"
      else
        echo "${outfile} is missing"
        set filemissing='yes'
        set anyfilemissing='yes'
      endif
    end
    @ nanal = $nanal + 1
end

if ($anyfilemissing == 'yes') then
    echo "there are output files missing!"
    exit 1
else
    echo "all output files seem OK"
    exit 0
endif
