Interoperable Physics Driver for NGGPS: gfs_typedefs Module Reference
gfs_typedefs Module Reference
Data Types
type gfs_cldprop_type
type gfs_control_type
type gfs_coupling_type
type gfs_diag_type
type gfs_grid_type
type gfs_init_type
type gfs_radtend_type
type gfs_sfcprop_type
type gfs_statein_type
type gfs_stateout_type
type gfs_tbd_type
Functions/Subroutines
subroutine statein_create (Statein, IM, Model)
subroutine stateout_create (Stateout, IM, Model)
subroutine sfcprop_create (Sfcprop, IM, Model)
subroutine coupling_create (Coupling, IM, Model)
subroutine control_initialize (Model, nlunit, fn_nml, me, master, logunit, isc, jsc, nx, ny, levs, cnx, cny, gnx, gny, dt_dycore, dt_phys, idat, jdat, tracer_names, input_nml_file)
subroutine control_print (Model)
subroutine grid_create (Grid, IM, Model)
subroutine tbd_create (Tbd, IM, Model)
subroutine cldprop_create (Cldprop, IM, Model)
subroutine radtend_create (Radtend, IM, Model)
subroutine diag_create (Diag, IM, Model)
subroutine diag_rad_zero (Diag, Model)
subroutine diag_phys_zero (Diag, Model, linit)
Variables
character(len=64) phys_version = 'v2018 FV3GFS BETA VERSION PHYSICS'
real(kind=kind_phys), parameter zero = 0.0_kind_phys
real(kind=kind_phys), parameter huge = 9.9999D15
real(kind=kind_phys), parameter clear_val = zero
real(kind=kind_phys), parameter rann_init = 0.6_kind_phys
real(kind=kind_phys), parameter cn_one = 1._kind_phys
real(kind=kind_phys), parameter cn_100 = 100._kind_phys
real(kind=kind_phys), parameter cn_th = 1000._kind_phys
real(kind=kind_phys), parameter cn_hr = 3600._kind_phys
Function/Subroutine Documentation
statein_create()
subroutine gfs_typedefs::statein_create (class(gfs_statein_type) Statein, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 901 of file GFS_typedefs.F90.
References clear_val.
stateout_create()
subroutine gfs_typedefs::stateout_create (class(gfs_stateout_type) Stateout, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 952 of file GFS_typedefs.F90.
References clear_val.
sfcprop_create()
subroutine gfs_typedefs::sfcprop_create (class(gfs_sfcprop_type) Sfcprop, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 976 of file GFS_typedefs.F90.
References clear_val, and zero.
coupling_create()
subroutine gfs_typedefs::coupling_create (class(gfs_coupling_type) Coupling, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 1128 of file GFS_typedefs.F90.
References clear_val.
control_initialize()
subroutine gfs_typedefs::control_initialize (class(gfs_control_type) Model, integer, intent(in) nlunit, character(len=64), intent(in) fn_nml, integer, intent(in) me, integer, intent(in) master, integer, intent(in) logunit, integer, intent(in) isc, integer, intent(in) jsc, integer, intent(in) nx, integer, intent(in) ny, integer, intent(in) levs, integer, intent(in) cnx, integer, intent(in) cny, integer, intent(in) gnx, integer, intent(in) gny, real(kind=kind_phys), intent(in) dt_dycore, real(kind=kind_phys), intent(in) dt_phys, integer, dimension(8), intent(in) idat, integer, dimension(8), intent(in) jdat, character(len=32), dimension(:), intent(in) tracer_names, character(len=*), dimension(:), intent(in), pointer input_nml_file)
Definition at line 1330 of file GFS_typedefs.F90.
References phys_version.
control_print()
subroutine gfs_typedefs::control_print (class(gfs_control_type) Model)
Definition at line 2188 of file GFS_typedefs.F90.
grid_create()
subroutine gfs_typedefs::grid_create (class(gfs_grid_type) Grid, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 2448 of file GFS_typedefs.F90.
References clear_val.
tbd_create()
subroutine gfs_typedefs::tbd_create (class(gfs_tbd_type) Tbd, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 2491 of file GFS_typedefs.F90.
References clear_val, and rann_init.
cldprop_create()
subroutine gfs_typedefs::cldprop_create (class(gfs_cldprop_type) Cldprop, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 2554 of file GFS_typedefs.F90.
References clear_val.
radtend_create()
subroutine gfs_typedefs::radtend_create (class(gfs_radtend_type) Radtend, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 2576 of file GFS_typedefs.F90.
References clear_val.
diag_create()
subroutine gfs_typedefs::diag_create (class(gfs_diag_type) Diag, integer, intent(in) IM, type(gfs_control_type), intent(in) Model)
Definition at line 2631 of file GFS_typedefs.F90.
diag_rad_zero()
subroutine gfs_typedefs::diag_rad_zero (class(gfs_diag_type) Diag, type(gfs_control_type), intent(in) Model)
Definition at line 2748 of file GFS_typedefs.F90.
References zero.
diag_phys_zero()
subroutine gfs_typedefs::diag_phys_zero (class(gfs_diag_type) Diag, type(gfs_control_type), intent(in) Model, logical, intent(in), optional linit)
Definition at line 2768 of file GFS_typedefs.F90.
References huge, and zero.
Variable Documentation
phys_version
character(len=64) gfs_typedefs::phys_version = 'v2018 FV3GFS BETA VERSION PHYSICS'
Definition at line 12 of file GFS_typedefs.F90.
Referenced by control_initialize().
zero
real(kind=kind_phys), parameter gfs_typedefs::zero = 0.0_kind_phys
Definition at line 15 of file GFS_typedefs.F90.
Referenced by diag_phys_zero(), diag_rad_zero(), and sfcprop_create().
huge
real(kind=kind_phys), parameter gfs_typedefs::huge = 9.9999D15
Definition at line 16 of file GFS_typedefs.F90.
Referenced by diag_phys_zero().
clear_val
real(kind=kind_phys), parameter gfs_typedefs::clear_val = zero
Definition at line 17 of file GFS_typedefs.F90.
Referenced by cldprop_create(), coupling_create(), grid_create(), radtend_create(), sfcprop_create(), statein_create(), stateout_create(), and tbd_create().
rann_init
real(kind=kind_phys), parameter gfs_typedefs::rann_init = 0.6_kind_phys
Definition at line 19 of file GFS_typedefs.F90.
Referenced by tbd_create().
cn_one
real(kind=kind_phys), parameter gfs_typedefs::cn_one = 1._kind_phys
Definition at line 20 of file GFS_typedefs.F90.
cn_100
real(kind=kind_phys), parameter gfs_typedefs::cn_100 = 100._kind_phys
Definition at line 21 of file GFS_typedefs.F90.
cn_th
real(kind=kind_phys), parameter gfs_typedefs::cn_th = 1000._kind_phys
Definition at line 22 of file GFS_typedefs.F90.
cn_hr
real(kind=kind_phys), parameter gfs_typedefs::cn_hr = 3600._kind_phys
Definition at line 23 of file GFS_typedefs.F90.