Interoperable Physics Driver for NGGPS: gfs_driver Module Reference
gfs_driver Module Reference
Functions/Subroutines
subroutine, public gfs_initialize (Model, Statein, Stateout, Sfcprop, Coupling, Grid, Tbd, Cldprop, Radtend, Diag, Init_parm)
subroutine, public gfs_time_vary_step (Model, Statein, Stateout, Sfcprop, Coupling, Grid, Tbd, Cldprop, Radtend, Diag)
subroutine, public gfs_stochastic_driver (Model, Statein, Stateout, Sfcprop, Coupling, Grid, Tbd, Cldprop, Radtend, Diag)
subroutine gfs_rad_time_vary (Model, Statein, Tbd, sec)
subroutine gfs_phys_time_vary (Model, Grid, Tbd)
subroutine gfs_grid_populate (Grid, xlon, xlat, area)
Variables
real(kind=kind_phys), parameter con_24 = 24.0_kind_phys
real(kind=kind_phys), parameter con_hr = 3600.0_kind_phys
real(kind=kind_phys), parameter con_99 = 99.0_kind_phys
real(kind=kind_phys), parameter con_100 = 100.0_kind_phys
real(kind=kind_phys), parameter qmin = 1.0e-10
integer, dimension(:), allocatable blksz
Function/Subroutine Documentation
gfs_initialize()
subroutine, public gfs_driver::gfs_initialize (type(gfs_control_type), intent(inout) Model, type(gfs_statein_type), dimension(:), intent(inout) Statein, type(gfs_stateout_type), dimension(:), intent(inout) Stateout, type(gfs_sfcprop_type), dimension(:), intent(inout) Sfcprop, type(gfs_coupling_type), dimension(:), intent(inout) Coupling, type(gfs_grid_type), dimension(:), intent(inout) Grid, type(gfs_tbd_type), dimension(:), intent(inout) Tbd, type(gfs_cldprop_type), dimension(:), intent(inout) Cldprop, type(gfs_radtend_type), dimension(:), intent(inout) Radtend, type(gfs_diag_type), dimension(:), intent(inout) Diag, type(gfs_init_type), intent(in) Init_parm)
Definition at line 108 of file GFS_driver.F90.
References blksz, and gfs_grid_populate().
gfs_time_vary_step()
subroutine, public gfs_driver::gfs_time_vary_step (type(gfs_control_type), intent(inout) Model, type(gfs_statein_type), dimension(:), intent(inout) Statein, type(gfs_stateout_type), dimension(:), intent(inout) Stateout, type(gfs_sfcprop_type), dimension(:), intent(inout) Sfcprop, type(gfs_coupling_type), dimension(:), intent(inout) Coupling, type(gfs_grid_type), dimension(:), intent(inout) Grid, type(gfs_tbd_type), dimension(:), intent(inout) Tbd, type(gfs_cldprop_type), dimension(:), intent(inout) Cldprop, type(gfs_radtend_type), dimension(:), intent(inout) Radtend, type(gfs_diag_type), dimension(:), intent(inout) Diag)
Definition at line 300 of file GFS_driver.F90.
References blksz, con_24, con_hr, gfs_phys_time_vary(), and gfs_rad_time_vary().
gfs_stochastic_driver()
subroutine, public gfs_driver::gfs_stochastic_driver (type(gfs_control_type), intent(in) Model, type(gfs_statein_type), intent(in) Statein, type(gfs_stateout_type), intent(in) Stateout, type(gfs_sfcprop_type), intent(in) Sfcprop, type(gfs_coupling_type), intent(inout) Coupling, type(gfs_grid_type), intent(in) Grid, type(gfs_tbd_type), intent(in) Tbd, type(gfs_cldprop_type), intent(in) Cldprop, type(gfs_radtend_type), intent(in) Radtend, type(gfs_diag_type), intent(inout) Diag)
Definition at line 418 of file GFS_driver.F90.
gfs_rad_time_vary()
subroutine gfs_driver::gfs_rad_time_vary (type(gfs_control_type), intent(inout) Model, type(gfs_statein_type), dimension(:), intent(in) Statein, type(gfs_tbd_type), dimension(:), intent(inout) Tbd, real(kind=kind_phys), intent(in) sec) private
Definition at line 518 of file GFS_driver.F90.
References blksz, con_100, qmin, and module_radiation_driver::radupdate().
Referenced by gfs_time_vary_step().
gfs_phys_time_vary()
subroutine gfs_driver::gfs_phys_time_vary (type(gfs_control_type), intent(inout) Model, type(gfs_grid_type), dimension(:), intent(inout) Grid, type(gfs_tbd_type), dimension(:), intent(inout) Tbd)
Definition at line 585 of file GFS_driver.F90.
References blksz, con_100, con_99, and con_hr.
Referenced by gfs_time_vary_step().
gfs_grid_populate()
subroutine gfs_driver::gfs_grid_populate (type(gfs_grid_type), dimension(:) Grid, real(kind=kind_phys), dimension(:,:), intent(in) xlon, real(kind=kind_phys), dimension(:,:), intent(in) xlat, real(kind=kind_phys), dimension(:,:), intent(in) area)
Definition at line 669 of file GFS_driver.F90.
Referenced by gfs_initialize().
Variable Documentation
con_24
real(kind=kind_phys), parameter gfs_driver::con_24 = 24.0_kind_phys private
Definition at line 80 of file GFS_driver.F90.
Referenced by gfs_time_vary_step().
con_hr
real(kind=kind_phys), parameter gfs_driver::con_hr = 3600.0_kind_phys private
Definition at line 81 of file GFS_driver.F90.
Referenced by gfs_phys_time_vary(), and gfs_time_vary_step().
con_99
real(kind=kind_phys), parameter gfs_driver::con_99 = 99.0_kind_phys private
Definition at line 82 of file GFS_driver.F90.
Referenced by gfs_phys_time_vary().
con_100
real(kind=kind_phys), parameter gfs_driver::con_100 = 100.0_kind_phys private
Definition at line 83 of file GFS_driver.F90.
Referenced by gfs_phys_time_vary(), and gfs_rad_time_vary().
qmin
real(kind=kind_phys), parameter gfs_driver::qmin = 1.0e-10 private
Definition at line 84 of file GFS_driver.F90.
Referenced by gfs_rad_time_vary().
blksz
integer, dimension(:), allocatable gfs_driver::blksz private
Definition at line 86 of file GFS_driver.F90.
Referenced by gfs_initialize(), gfs_phys_time_vary(), gfs_rad_time_vary(), and gfs_time_vary_step().