Interoperable Physics Driver for NGGPS: module_physics_driver Module Reference
module_physics_driver Module Reference
Functions/Subroutines
subroutine, public gfs_physics_driver (Model, Statein, Stateout, Sfcprop, Coupling, Grid, Tbd, Cldprop, Radtend, Diag)
GFS Physics Implementation Layer.
subroutine moist_bud (im, ix, ix2, levs, me, kdt, grav, dtp, delp, rain, qv0, ql0, qi0, qv1, ql1, qi1, comp)
Variables
real(kind=kind_phys), parameter hocp = con_hvap/con_cp
real(kind=kind_phys), parameter qmin = 1.0e-10
real(kind=kind_phys), parameter p850 = 85000.0
real(kind=kind_phys), parameter epsq = 1.e-20
real(kind=kind_phys), parameter hsub = con_hvap+con_hfus
real(kind=kind_phys), parameter czmin = 0.0001
real(kind=kind_phys), parameter one = 1.0d0
real(kind=kind_phys), parameter onebg = one/con_g
real(kind=kind_phys), parameter albdf = 0.06
real(kind=kind_phys), parameter tf =258.16
real(kind=kind_phys), parameter tcr =273.16
real(kind=kind_phys), parameter tcrf =1.0/(tcr-tf)
real(kind=kind_phys), parameter con_p001 = 0.001d0
real(kind=kind_phys), parameter con_day = 86400.d0
Function/Subroutine Documentation
gfs_physics_driver()
subroutine, public module_physics_driver::gfs_physics_driver (type(gfs_control_type), intent(in) Model, type(gfs_statein_type), intent(inout) Statein, type(gfs_stateout_type), intent(inout) Stateout, type(gfs_sfcprop_type), intent(inout) Sfcprop, type(gfs_coupling_type), intent(inout) Coupling, type(gfs_grid_type), intent(in) Grid, type(gfs_tbd_type), intent(inout) Tbd, type(gfs_cldprop_type), intent(inout) Cldprop, type(gfs_radtend_type), intent(inout) Radtend, type(gfs_diag_type), intent(inout) Diag)
GFS Physics Implementation Layer.
Layer that invokes individual GFS physics routines
This subroutine is the suite driver for the GFS atmospheric physics and surface. It is responsible for calculating and applying tendencies of the atmospheric state variables due to the atmospheric physics and due to the surface layer scheme. In addition, this routine applies radiative heating rates that were calculated during the antecedent call to the radiation scheme. Code within this subroutine is executed on the physics sub-timestep. The sub-timestep loop is executed in the subroutine gloopb.
General Algorithm
Prepare input variables for calling individual parameterizations.
Using a two-iteration loop, calculate the state variable tendencies for the surface layer.
Calculate the state variable tendencies due to the PBL (vertical diffusion) scheme.
Calculate the state variable tendencies due to orographic gravity wave drag and Rayleigh damping.
Apply tendencies to the state variables calculated so far:
for temperature: radiation, surface, PBL, oro. GWD, Rayleigh damping
for momentum: surface, PBL, oro. GWD, Rayleigh damping
for water vapor: surface, PBL
Calculate and apply the tendency of ozone.
Prepare input variables for physics routines that update the state variables within their subroutines.
If SHOC is active and is supposed to be called before convection, call it and update the state variables within.
Calculate and apply the state variable tendencies (within the subroutine) due to deep convection.
Calculate the state variable tendencies due to convective gravity wave drag and apply them afterwards.
Calculate and apply the state variable tendencies (within the subroutine) due to shallow convection.
If SHOC is active and is supposed to be called after convection, call it and update the state variables within.
Prepare for microphysics call by calculating preliminary variables.
If necessary, call the moist convective adjustment subroutine and update the state temperature and moisture variable within.
Calculate and apply the state variable tendencies (within the subroutine) due to microphysics.
Determine the precipitation type and update land surface properties if necessary.
Fill the output variables from the local variables as necessary and deallocate allocatable arrays.
Detailed Algorithm
Prepare input variables for calling individual parameterizations.
Before calling any parameterizations, there is a section at the beginning of the subroutine for preparing input arguments to the various schemes based on general input to the driver and initializing variables used throughout the driver.
General initialization:
set a flag for running in debug mode and the horizontal index of the column to print
calculate the pressure at layer centers, the exner function at layer centers and interfaces, geopotential at layer centers and interfaces, and the layer-centered pressure difference
calculate the ratio of dynamics time step to physics time step for applying tendencies
initialize local tendency arrays to zero
Radiation:
adjust radiative fluxes and heating rates to the shorter physics time step (from the longer radiation time step), unless idealized physics is true (lsidea) where radiative heating rates are set to 0
compute diagnostics from the radiation scheme needed for other schemes (e.g., downward longwave flux absorbed by the surface)
accumulate the upward and downward longwave fluxes at the surface
Surface:
set NOAH and OSU scheme variables from gbphys input arguments and initialize local soil moisture variables
set local sea ice variables from gbphys arguments
set up A/O/I coupling variables from gbphys arguments
PBL:
set the number of tracers that are diffused vertically
SHOC:
determine the index of TKE (ntk) in the convectively transported tracer array (clw)
allocate precipitation mixing ratio cloud droplet number concentration arrays
Deep Convection:
determine which tracers in the tracer input array undergo convective transport (valid only for the RAS and Chikira-Sugiyama schemes) and allocate a local convective transported tracer array (clw)
apply an adjustment to the tracers from the dynamics
calculate horizontal grid-related parameters needed for some parameterizations
calculate the maxiumum cloud base updraft speed for the Chikira-Sugiyama scheme
allocate array for cloud water and cloud cover (for non-RAS and non-Chikira-Sugiyama deep convective schemes)
Shallow Convection:
when using the Tiedtke shallow convection scheme with the stratus modifications, find the lowest model level where a temperature inversion exists in the absence of CTEI
Microphysics:
for the Morrison (MGB) scheme, calculate 'FRLAND' if the grid point is over land
allocate arrays associated with the Morrison scheme
assign the local critical relative humidity variables from the gbphys arguments
Gravity Wave Drag:
calculate the deep convective cloud fraction at cloud top for the convective GWD scheme
Using a two-iteration loop, calculate the state variable tendencies for the surface layer.
Each iteration of the loop calls the following:
'sfc_diff' to calculate surface exchange coefficients and near-surface wind
surface energy balances routines are called regardless of surface type; the surface type is checked within each to determine whether the routine is "active"
for the surface energy balance over the ocean, call 'sfc_nst' if NSST is on, otherwise, call 'sfc_ocean'
for the surface energy balance over the land, call 'sfc_drv' for the NOAH model and 'sfc_land' for the OSU model
for the surface energy balance over sea ice, call sfc_sice; if A/O/I coupling, call sfc_cice
The initial iteration has flag_guess = F unless wind < 2 m/s; flag_iter = T
After the initial iteration, flag_guess = F and flag_iter = F (unless wind < 2 m/s and over a land surface or an ocean surface with NSST on)
The following actions are performed after the iteration to calculate surface energy balance:
set surface output variables from their local values
call 'sfc_diag' to calculate state variable values at 2 and 10 m as appropriate from near-surface model levels and the surface exchange coefficients
if A/O/I coupling, set coupling variables from local variables and calculate the open water albedo
finally, accumulate surface-related diagnostics and calculate the max/min values of T and q at 2 m height.
Calculate the state variable tendencies due to the PBL (vertical diffusion) scheme.
Call the vertical diffusion scheme (PBL) based on the following logical flags: do_shoc, hybedmf, old_monin, mstrat
the PBL scheme is expected to return tendencies of the state variables
If A/O/I coupling and the surface is sea ice, overwrite some surface-related variables to their states before PBL was called
For diagnostics, do the following:
accumulate surface state variable tendencies and set the instantaneous values for output
accumulate the temperature tendency due to the PBL scheme in dt3dt(:,:,3), subtracting out the radiative heating rate if necessary
accumulate the u, v tendencies due to the PBL in du3dt(:,:,1:2) and dv3dt(:,:,1:2)
accumulate the water vapor tendency due to the PBL in dq3dt(:,:,1)
accumulate the ozone tendency in dq3dt(:,:,5)
Calculate the state variable tendencies due to orographic gravity wave drag and Rayleigh damping.
Based on the variable nmtvr, unpack orographic gravity wave varibles from the hprime array
Call 'gwdps' to calculate tendencies of u, v, T, and surface stress
Accumulate gravity wave drag surface stresses.
Accumulate change in u, v, and T due to oro. gravity wave drag in du3dt(:,:,2), dv3dt(:,:,2), and dt3dt(:,:,2)
Call 'rayleigh_damp' to calculate tendencies to u, v, and T due to Rayleigh friction
Apply tendencies to the state variables calculated so far.
Calculate and apply the tendency of ozone.
Call the convective adjustment scheme for IDEA
Call 'ozphys_2015' or 'ozphys' depending on the value of pl_coeff, updating the ozone tracer within and outputing the tendency of ozone in dq3dt(:,:,6)
Call 'h20phys' if necessary ("adaptation of NRL H20 phys for stratosphere and mesophere")
Prepare input variables for physics routines that update the state variables within their subroutines.
If diagnostics is active, save the updated values of the state variables in 'dudt', 'dvdt', 'dTdt', and 'dqdt(:,:,1)'
Call 'get_phi' to calculate geopotential from p, q, T
Initialize the cloud water and ice portions of the convectively transported tracer array (clw) and (if the deep convective scheme is not RAS or Chikira-Sugiyama) the convective cloud water and cloud cover.
If the dep convective scheme is RAS or Chikira-Sugiyama, fill the 'clw' array with tracers to be transported by convection
Initialize 'ktop' and 'kbot' (to be modified by all convective schemes except Chikira-Sugiyama)
Prepare for microphysics call (if cloud condensate is in the input tracer array):
all schemes: calculate critical relative humidity
Morrison et al. scheme (occasionally denoted MGB) (when ncld==2): set clw(:,:,1) to cloud ice and clw(:,:,2) to cloud liquid water
Ferrier scheme (num_p3d==3): set the cloud water variable and separate hydrometeors into cloud ice, cloud water, and rain; set clw(:,:,1) to cloud ice and clw(:,:,2) to cloud liquid water
Zhao-Carr scheme (num_p3d==4): calculate autoconversion coefficients from input constants and grid info; set set clw(:,:,1) to cloud liquid water
otherwise: set autoconversion parameters like in Zhao-Carr and set critical relative humidity to 1
If SHOC is active and is supposed to be called before convection, call it and update the state variables within.
Prior to calling SHOC, prepare some microphysics variables:
if Morrison et al. scheme: set 'skip_macro', fill clw(:,:,1,2) with cloud ice, liquid from the tracer array, and fill cloud droplet number concentration arrays from the input tracer array
if Zhao-Carr scheme: initialize precip. mixing ratios to 0, fill clw(:,:,1,2) with cloud ice, liquid from the tracer array (as a function of temperature)
Call 'shoc' (modifies state variables within the subroutine)
Afterward, set updated cloud number concentrations in the tracer array from the updated 'ncpl' and 'ncpi'
Calculate and apply the state variable tendencies (within the subroutine) due to deep convection.
Call deep convective scheme according to the parameter 'imfdeepcnv', 'ras', and 'cscnv'.
if imfdeepcnv == 0, 1, or 2, no special processing is needed
if the Chikira-Sugiyama scheme (cscnv), convert rain rate to accumulated rain (rain1)
if RAS, initialize 'ccwfac', 'dlqfac', 'lmh', and revap before the call to 'rascnv'
Zero out 'cld1d' (cloud work function calculated in non-RAS, non-Chikira-Sugiyama schemes)
If 'lgocart', accumulate convective mass fluxes and convective cloud water
Update tracers in the tracer array (gq0) due to convective transport (RAS, CS only) from the 'clw' array
Calculate accumulated surface convective precip. for this physics time step (rainc)
If necessary, accumulate cloud work function, convective precipitation, and convective mass fluxes; accumulate dt3dt(:,:,4), dq3dt(:,:,2), du3dt(:,:,3), dv3dt(:,:,3) as change in state variables due to deep convection
If 'lgocart', repeat the accumulation of convective mass fluxes and convective cloud water; save convective tendency for water vapor in 'dqdt_v'
If PDF-based clouds are active and Zhao-Carr microphysics, save convective cloud cover and water in 'phy_f3d' array
otherwise, if non-PDF-based clouds and the "convective cloudiness enhancement" is active, save convective cloud water in 'phy_f3d' array
Calculate the state variable tendencies due to convective gravity wave drag and apply them afterwards.
Calculate the average deep convective heating rate in the column to pass into 'gwdc'
Call 'gwdc' to calculate tendencies of u, v due to convective GWD
For diagnostics, accumulate the vertically-integrated change in u, v due to conv. GWD; accumulate change in u, v, due to conv. GWD in du3dt(:,:,4) and dv3dt(:,:,4)
Calculate updated values of u, v, T using conv. GWD tendencies
Calculate and apply the state variable tendencies (within the subroutine) due to shallow convection.
If diagnostics are active, set 'dtdt' and 'dqdt' to updated values of T and q before shallow convection
If SHOC is not active, do the following:
for the mass-flux shallow convection scheme (imfshalcnv == 1), call 'shalcnv'
for the scale- and aerosol-aware scheme (imfshalcnv == 2), call 'samfshalcnv'
for either of the first two schemes, perform the following after the call:
if Zhao-Carr microphysics with PDF-based clouds, save convective cloud water an cover in 'phy_f3d'
if non-PDF-based clouds and convective cloudiness enhancement is active, save convective cloud water in 'phy_f3d'
calculate shallow convective precip. and add it to convective precip; accumulate convective precip.
for the Tiedtke scheme (imfshalcnv == 0), find the top level where shallow convection must stratosphere
if using Moorthi's approach to stratus, call 'shalcv'
otherwise, call 'shalcvt3'
for diagnostics, accumulate the change in water vapor due to shallow convection and save in dqdt_v if 'lgocart';
save the change in T and q due to shallow convection in dt3dt(:,:,5) and dq3dt(:,:,3); reset dtdt and dqdt to the updated values of T, q after shallow Convection
if 'clw' is not partitioned into ice/water, set 'clw(ice)' to zero
If SHOC is active (and shocaftcnv)
if Morrison et al. scheme: set 'skip_macro' and fill cloud droplet number concentration arrays from the input tracer array
initialize precip. mixing ratios to 0
call 'shoc' (modifies state variables within the subroutine)
afterward, set updated cloud number concentrations in the tracer array from the updated 'ncpl' and 'ncpi'
Prepare for microphysics call by calculating preliminary variables.
For Morrison et al. microphysics, set cloud water and ice arrays to the convecitvely transported values
For Ferrier microphysics, combine convectively transported cloud water and ice with column rain and save in cloud water array
calculate and save ice fraction and rain fraction in phy_f3d(1),(2)
For Zhao-Carr, combine convectively transported cloud water and ice into the cloud water array
Otherwise, combine convectively transported cloud water and ice into the convectively transported cloud water
Call 'cnvc90'; a "legacy routine which determines convective clouds"; outputs 'acv','acvb','acvt','cv','cvb','cvt'
If necessary, call the moist convective adjustment subroutine and update the state temperature and moisture variable within.
Updates T, q, 'rain1', cloud water array
Accumulate convective precip
For diagnostics, accumulate the change in T, q due to moist convective adjustment; reset 'dtdt' and 'dqdt' to updated T, q before call to microphysics
Calculate and apply the state variable tendencies (within the subroutine) due to microphysics.
If 'lgocart', calculate instantaneous moisture tendency in dqdt_v
If no cloud microphysics (ncld == 0), call 'lrgscl' to update T, q and output large scale precipitation and cloud water
Otherwise, a more advanced microphysics scheme is called (which scheme depends on values of 'num_p3d','do_shoc',and 'ncld')
Ferrier scheme (num_p3d == 3):
calculate droplet number concentration and minimum large ice fraction
call 'gsmdrive' (modifies T, q, cloud water, 'f_ice', 'f_rain', 'f_rimef', 'rain1')
Zhao-Carr-Sundqvist scheme (num_p3d == 4):
if non-PDF-based clouds:
if 'do_shoc', call 'precpd_shoc' (precpd modified for SHOC)
else, call 'gscond' (grid-scale condensation/evaporation); updates water vapor, cloud water, temperature
call 'precpd'; updates water vapor, cloud water, temperature and outputs precip., snow ratio, and rain water path
for PDF-based clouds:
call 'gscondp' followed by 'precpdp' (similar arguments to gscond, precpd above)
Morrison et al. scheme (ncld = 2):
if 'do_shoc', set clw(1),(2) from updated values; set phy_f3d(:,:,1) from phy_f3d(:,:,ntot3d-2)
else, set clw(1),(2) from updated values; set phy_f3d(:,:,1) to cloud cover from previous time step + convective cloud water from convective scheme
call 'm_micro_driver'; updates water vapor, temperature, droplet number concentrations, cloud cover
Combine large scale and convective precip.
For diagnostics, accumulate total surface precipitation and accumulate change in T and q due to microphysics in dt3dt(:,:,6) and dq3dt(:,:,4)
Determine the precipitation type and update land surface properties if necessary.
If 'cal_pre', diagnose the surface precipitation type
call 'calpreciptype'; set snow flag to 1 if snow or sleet, 0 otherwise
For rain/snow decision, calculate temperature at 850 hPa (\(T_{850}\))
If not 'cal_pre', set snow flag to 1 if \(T_{850}\) is below freezing
For coupling, accumulate rain if \(T_{850}\) is above freezing, otherwise accumulate snow
If using the OSU land model, accumulate surface snow depth if \(T_{850}\) is below freezing and not over an ocean surface
call 'progt2' (canopy and soil moisture?) and set the soil liquid water equal to soil total water
if 'lgocart', call 'sfc_diag' to update near-surface state variables (this "allows gocart to use filtered wind fields")
If necessary (lssav), update the 2m max/min values of T and q
If necessary (lssav), accumulate total runoff and surface runoff.
Fill the output variables from the local variables as necessary and deallocate allocatable arrays.
Set global sea ice thickness and concentration as well as the temperature of the sea ice
Set global soil moisture variables
Calculate precipitable water and water vapor mass change due to all physics for the column
Deallocate arrays for SHOC scheme, deep convective scheme, and Morrison et al. microphysics
Definition at line 402 of file GFS_physics_driver.F90.
References albdf, con_day, con_p001, czmin, epsq, hocp, one, onebg, p850, qmin, tcr, and tcrf.
moist_bud()
subroutine module_physics_driver::moist_bud (integer im, integer ix, integer ix2, integer levs, integer me, integer kdt, real (kind=kind_phys) grav, real (kind=kind_phys) dtp, real (kind=kind_phys), dimension(ix,levs) delp, real (kind=kind_phys), dimension(im) rain, real (kind=kind_phys), dimension(ix,levs) qv0, real (kind=kind_phys), dimension(ix,levs) ql0, real (kind=kind_phys), dimension(ix,levs) qi0, real (kind=kind_phys), dimension(ix2,levs) qv1, real (kind=kind_phys), dimension(ix2,levs) ql1, real (kind=kind_phys), dimension(ix2,levs) qi1, character*10 comp)
Definition at line 3741 of file GFS_physics_driver.F90.
Variable Documentation
hocp
real(kind=kind_phys), parameter module_physics_driver::hocp = con_hvap/con_cp
Definition at line 27 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
qmin
real(kind=kind_phys), parameter module_physics_driver::qmin = 1.0e-10
Definition at line 28 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
p850
real(kind=kind_phys), parameter module_physics_driver::p850 = 85000.0
Definition at line 29 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
epsq
real(kind=kind_phys), parameter module_physics_driver::epsq = 1.e-20
Definition at line 30 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
hsub
real(kind=kind_phys), parameter module_physics_driver::hsub = con_hvap+con_hfus
Definition at line 31 of file GFS_physics_driver.F90.
czmin
real(kind=kind_phys), parameter module_physics_driver::czmin = 0.0001
Definition at line 32 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
one
real(kind=kind_phys), parameter module_physics_driver::one = 1.0d0
Definition at line 33 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
onebg
real(kind=kind_phys), parameter module_physics_driver::onebg = one/con_g
Definition at line 33 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
albdf
real(kind=kind_phys), parameter module_physics_driver::albdf = 0.06
Definition at line 34 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
tf
real(kind=kind_phys), parameter module_physics_driver::tf =258.16
Definition at line 35 of file GFS_physics_driver.F90.
tcr
real(kind=kind_phys), parameter module_physics_driver::tcr =273.16
Definition at line 35 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
tcrf
real(kind=kind_phys), parameter module_physics_driver::tcrf =1.0/(tcr-tf)
Definition at line 35 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
con_p001
real(kind=kind_phys), parameter module_physics_driver::con_p001 = 0.001d0
Definition at line 36 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().
con_day
real(kind=kind_phys), parameter module_physics_driver::con_day = 86400.d0
Definition at line 37 of file GFS_physics_driver.F90.
Referenced by gfs_physics_driver().