      SUBROUTINE HEXCHAR(HEX,OUT,IERR)
C
C     CONVERT 2 CHARACTER HEX NUMBERS (Z2) INTO 1 CHARACTER
C     WITH VALUE OF 0 TO 255
C     CRAY CFT77 FORTRAN DOES NOT LET YOU READ CHARACTER
C     DATA, OR PRINT CHARACTER DATA WITH A Z2 FORMAT
C
      CHARACTER * 1  OUT
      CHARACTER * 2  HEX
C
      INTEGER        INT
      INTEGER        INT1
      INTEGER        INT2
C
      SAVE
C
      IERR = 0
      INT1 = MOVA2I(HEX(1:1))
      IF (INT1.GE.48.AND.INT1.LE.57) THEN
        INT1 = INT1 - 48
      ELSE IF (INT1.GE.65.AND.INT1.LE.70) THEN
        INT1 = INT1 - 55
      ELSE IF (INT1.GE.97.AND.INT1.LE.102) THEN
        INT1 = INT1 - 87
      ELSE
        IERR = 1
        RETURN
      END IF
C
      INT2 = MOVA2I(HEX(2:2))
      IF (INT2.GE.48.AND.INT2.LE.57) THEN
        INT2 = INT2 - 48
      ELSE IF (INT2.GE.65.AND.INT2.LE.70) THEN
        INT2 = INT2 - 55
      ELSE IF (INT2.GE.97.AND.INT2.LE.102) THEN
        INT2 = INT2 - 87
      ELSE
        IERR = 1
        RETURN
      END IF
      INT = INT1 * 16 + INT2
      OUT = CHAR(INT)
C
      RETURN
      END
