#!/bin/ksh 

set -xa

export RUN_ENVIR=${RUN_ENVIR:-nco}

if [ $RUN_ENVIR != nco ] ; then
  PBEG=${PBEG:-""}
  $PBEG
fi

export PS4='$SECONDS + '
date

# #### 01/26/2016 #############################
# SETUP GDAS FCST PROCESSING VARIABLES
# #############################################

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=${pid:-$$}
export DATAROOT=${DATAROOT:-/tmpnwprd2}
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
cd $DATA

export cyc=${cyc:-00}
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gdas1}
export RUNdir=${RUNdir:-gdas}

####################################
# Specify version numbers
####################################
export gdas_ver=${gdas_ver:-v13.0.0}
export gfs_ver=${gfs_ver:-v13.0.0}
export global_shared_ver=${global_shared_ver:-v13.0.0}
export NWROOT=${NWROOT:-/nwprod}
export COMROOT=${COMROOT:-/com2}
export GESROOT=${GESROOT:-/nwges2}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

####################################
# RERUN    - Rerun fcst from beginning (default no)
# VERBOSE  - Specify Verbose Output in exglobal_fcst.sh.ecf
####################################
export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEgfs=${HOMEgfs:-$NWROOT/gfs.${gfs_ver}}
export PARMgfs=${PARMgfs:-$HOMEgfs/parm}
export HOMEglobal=${HOMEglobal:-$NWROOT/global_shared.${global_shared_ver}}
export EXECgsm=${EXECgsm:-$HOMEglobal/exec}
export FIXgsm=${FIXgsm:-$HOMEglobal/fix/fix_am}
export USHgsm=${USHgsm:-$HOMEglobal/ush}
export PARMgsm=${PARMgsm:-$HOMEglobal/parm}
export HOMEgdas=${HOMEgdas:-$NWROOT/gdas.${gdas_ver}}
export PARMgdas=${PARMgdas:-$HOMEgdas/parm}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUNdir}.${PDY}}
export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUNdir}.${PDY}}

mkdir -m 775 -p $COMOUT

####################################
# Specify Special Fcst Vars
####################################
. ${PARM_GDASFCST_HIGH:-$PARMgdas/gdas_forecast_high.parm}


##############################################
# Define GES directories
##############################################
gespath=${gespath:-$GESROOT/${envir}}
export GESdir=${GESdir:-$gespath/${RUNdir}.${PDY}}
mkdir -m 775 -p $GESdir

#
# Output File Names
#
export SIGO=${SIGO:-$COMOUT/$RUN.$cycle.sf'${FH}'}
export SFCO=${SFCO:-$COMOUT/$RUN.$cycle.bf'${FH}'}
export FLXO=${FLXO:-$COMOUT/$RUN.$cycle.sfluxgrbf'${FH}'}
export G3DO=${G3DO:-$COMOUT/$RUN.$cycle.g3df'${FH}'}
export LOGO=${LOGO:-$COMOUT/$RUN.$cycle.logf'${FH}'}
#
# Restart File Names
#
export SIGR1=${SIGR1:-$GESdir/$RUN.$cycle.sigr1}
export SIGR2=${SIGR2:-$GESdir/$RUN.$cycle.sigr2}
export SFCR=${SFCR:-$GESdir/$RUN.$cycle.sfcr}

#
# PDS Grid Designator
#
export IGEN=82

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

####################################
# Check if this is a restart
# Define Initialization File Names
####################################

if [ -f $SIGR1 -a -f $SIGR2 -a -f $SFCR -a $RERUN = NO ] ; then
  cp $SIGR1 $DATA/sigr1
  cp $SIGR2 $DATA/sigr2
  cp $SFCR $DATA/sfcr

  export SIGI=$DATA/sigr1
  export SIGI2=$DATA/sigr2
  export SFCI=$DATA/sfcr

  msg="Forecast Starting with Restart files in $GESdir"
  postmsg "$jlogfile" "$msg"
else
  export SIGI=${SIGI:-$GESdir/$RUN.t${cyc}z.sanl}
  export SFCI=${SFCI:-$GESdir/$RUN.t${cyc}z.sfcanl}

  if [ -f $SIGI -a -f $SFCI ] ; then
     msg="Forecast Starting with Initial Guess Fields"
     postmsg "$jlogfile" "$msg"
  else
     msg="FATAL ERROR initial Guess Fields Not Available/Rerun $job"
     postmsg "$jlogfile" "$msg"
     export pgm=$job
     export err=911
     $ERRSCRIPT
  fi
fi

############################################################
## The following is set in ecflow script
# ulimit -s unlimited
#export NTHREADS=${NTHREADS:-${OMP_NUM_THREADS:-4}}
#export OMP_NUM_THREADS=${OMP_NUM_THREADS:-$NTHREADS}
#export MP_EUIDEVICE=${MP_EUIDEVICE:-min}
#export MP_EUILIB=${MP_EUILIB:-us}
#export MP_TASK_AFFINITY=${MP_TASK_AFFINITY:-cpu:$OMP_NUM_THREADS}
#export MP_EUIDEVELOP=${MP_EUIDEVELOP:-min}
#export KMP_STACKSIZE=${KMP_STACKSIZE:-2048m}
#export F_UFMTENDIAN=${F_UFMTENDIAN:-big}
#export MPICH_ALLTOALL_THROTTLE=${MPICH_ALLTOALL_THROTTLE:-0}
#export MP_SINGLE_THREAD=${MP_SINGLE_THREAD:-yes}
#export MP_EAGER_LIMIT=${MP_EAGER_LIMIT:-65536}
#export MP_USE_BULK_XFER=${MP_USE_BULK_XFER:-no}
#export MP_SHARED_MEMORY=${MP_SHARED_MEMORY:-yes}
#export MP_MPILIB=${MP_MPILIB:-mpich2}
#export MP_LABELIO=${MP_LABELIO:-yes}
#export MP_STDOUTMODE=${MP_STDOUTMODE:-unordered}
#export MP_COLLECTIVE_OFFLOAD=${MP_COLLECTIVE_OFFLOAD:-no}
#export APRUN=${APRUN:-mpirun.lsf}
############################################################

env

#############################################################
# Execute the script

FORECASTSH=${FORECASTSH:-$HOMEglobal/scripts/exglobal_fcst.sh.ecf}
export FCSTEXEC=${FCSTEXEC:-${EXECgsm}/global_fcst}
$FORECASTSH


cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT

if [ ${KEEPDATA:-NO} != YES ] ; then rm -rf $DATA ; fi

if [ $RUN_ENVIR != nco ] ; then
     PEND=${PEND:-""}
     export CSTEP=fcst1
    $PEND
fi
date
