#!/bin/ksh 

set -xa

export RUN_ENVIR=${RUN_ENVIR:-nco}

if [ $RUN_ENVIR != nco ] ; then
  PBEG=${PBEG:-""}
  $PBEG
  . ${PARA_CONFIG:-/global/save/${LOGNAME}/para_gfs/pr4devb/para_config}
  export userid=$LOGNAME
fi

export PS4='$SECONDS + '
date

# #### 01/26/2016 #############################
# SETUP GDAS FCST PROCESSING VARIABLES
# #############################################

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=${pid:-$$}
export DATAROOT=${DATAROOT:-/tmpnwprd2}
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
cd $DATA

export cyc=${cyc:-00}
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gdas}
export RUNdir=${RUNdir:-gdas}


####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


####################################
# RERUN    - Rerun fcst from beginning (default no)
# VERBOSE  - Specify Verbose Output in exglobal_fcst_nems.sh.ecf
####################################
export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}

####################################
# Specify Execution Areas
####################################
export HOMEgfs=${HOMEgfs:-$NWROOT/gfs.${gfs_ver}}
export PARMgfs=${PARMgfs:-$HOMEgfs/parm}
export HOMEglobal=${HOMEglobal:-$NWROOT/global_shared.${global_shared_ver}}
export EXECgsm=${EXECgsm:-$HOMEglobal/exec}
export SCRgsm=${SCRgsm:-$HOMEglobal/scripts}
export FIXgsm=${FIXgsm:-$HOMEglobal/fix/fix_am}
export USHgsm=${USHgsm:-$HOMEglobal/ush}
export PARMgsm=${PARMgsm:-$HOMEglobal/parm}
export HOMEgdas=${HOMEgdas:-$NWROOT/gdas.${gdas_ver}}
export PARMgdas=${PARMgdas:-$HOMEgdas/parm}

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COM_IN=${COM_IN:-$COMROOT/${NET}/${envir}}
export COM_OUT=${COM_OUT:-$COMROOT/${NET}/${envir}}
export COMIN=${COM_IN}/${RUNdir}.${PDY}
export COMOUT=${COM_OUT}/${RUNdir}.${PDY}

mkdir -m 775 -p $COMOUT

####################################
# Specify Special Fcst Vars
####################################
. ${PARM_GDASFCST_HIGH:-$PARMgdas/gdas_forecast_high.parm}


##############################################
# Define GES directories
##############################################
gespath=${gespath:-$GESROOT/${envir}}
export GESdir=${GESdir:-$gespath/${RUNdir}.${PDY}}
mkdir -m 775 -p $GESdir

#
# Output File Names
#
export SIGO=${SIGO:-$COMOUT/$RUN.$cycle.atmf'${FH3}'.nemsio}
export SFCO=${SFCO:-$COMOUT/$RUN.$cycle.sfcf'${FH3}'.nemsio}
export FLXO=${FLXO:-$COMOUT/$RUN.$cycle.flxf'${FH3}'.nemsio}
export NSTO=${NSTO:-$COMOUT/$RUN.$cycle.nstf'${FH3}'.nemsio}
export D3DO=${D3DO:-$COMOUT/$RUN.$cycle.d3df'${FH3}'.nemsio}
export LOGO=${LOGO:-$COMOUT/$RUN.$cycle.logf'${FH3}'.nemsio}
#
# Restart File Names
#
export GRDR1=${GRDR1:-$GESdir/$RUN.$cycle.grdr1}
export GRDR2=${GRDR2:-$GESdir/$RUN.$cycle.grdr2}
export SIGR1=${SIGR1:-$GESdir/$RUN.$cycle.sigr1}
export SIGR2=${SIGR2:-$GESdir/$RUN.$cycle.sigr2}
export SFCR=${SFCR:-$GESdir/$RUN.$cycle.sfcr}
export NSTR=${NSTR:-$GESdir/$RUN.$cycle.nstr}

#
# PDS Grid Designator
#
export IGEN=82

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

####################################
# Check if this is a restart
# Define Initialization File Names
####################################

if [ -f $GRDR1 -a -f $GRDR2 -a -f $SIGR1 -a -f $SIGR2 -a -f $SFCR -a -f $NSTR -a $RERUN = NO ] ; then
  cp $GRDR1 $DATA/grdr1
  cp $GRDR2 $DATA/grdr2
  cp $SIGR1 $DATA/sigr1
  cp $SIGR2 $DATA/sigr2
  cp $SFCR $DATA/sfcr
  cp $NSTR $DATA/nstr

  export GRDI=$DATA/grdr1
  export GRDI2=$DATA/grdr2
  export SIGI=$DATA/sigr1
  export SIGI2=$DATA/sigr2
  export SFCI=$DATA/sfcr
  export NSTI=$DATA/nstr

  msg="Forecast Starting with Restart files in $GESdir"
  postmsg "$jlogfile" "$msg"
else
  export GRDI=${GRDI:-$GESdir/$RUN.t${cyc}z.atmanl.nemsio}
  export SIGI=${SIGI:-$GESdir/$RUN.t${cyc}z.atmanl.nemsio}
  export SFCI=${SFCI:-$GESdir/$RUN.t${cyc}z.sfcanl.nemsio}
  export NSTI=${NSTI:-$GESdir/$RUN.t${cyc}z.nstanl.nemsio}

  if [ -f $GRDI -a -f $SIGI -a -f $SFCI -a -f $NSTI ] ; then
     msg="Forecast Starting with Initial Guess Fields"
     postmsg "$jlogfile" "$msg"
  else
     msg="FATAL ERROR initial Guess Fields Not Available/Rerun $job"
     postmsg "$jlogfile" "$msg"
     export pgm=$job
     export err=911
     $ERRSCRIPT
  fi
fi

##############################################
# WCOSS_C environment settings
##############################################
export machine=${machine:-WCOSS_C}
export MKL_NUM_THREADS=1
export MKL_CBWR=AVX
export MP_MPILIB=mpich2
export USEBULKXFER=NO
export MPICH_GNI_COLL_OPT_OFF=MPI_Alltoallv
export IOBUF_PARAMS=${IOBUF_PARAMS:-'*:size=8M:verbose'}
export APRUN=${APRUN:-"aprun -j1 -n $ntasks -N $ptile -d $threads -cc depth"}

env

#############################################################
# Execute the script

FORECASTSH=${FORECASTSH:-$HOMEglobal/scripts/exglobal_fcst_nems.sh.ecf}
export FCSTEXEC=${FCSTEXEC:-${EXECgsm}/global_fcst}
$FORECASTSH


cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT

if [ ${KEEPDATA:-NO} != YES ] ; then rm -rf $DATA ; fi

if [ $RUN_ENVIR != nco ] ; then
     PEND=${PEND:-""}
     export CSTEP=fcst1
    $PEND
fi
date
