name: Bug report
description: Report something that is incorrect or broken
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Your bug may already be reported!
        Please search on the [Issue tracker](https://github.com/NOAA-EMC/global-workflow/issues) before creating one.

  - type: textarea
    id: current_behavior
    attributes:
      label: What is wrong?
      description: Give a brief description of what is incorrect or broken.
      placeholder: |
        Short log snippets that illustrate the problem can be included here.

        For any longer logs, please create a GitHub gist (https://gist.github.com/) and link it here.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: What should have happened?
      placeholder: Describe what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: hpc
    attributes:
      label: What machines are impacted?
      description: You may select multiple machines.
      multiple: true
      options:
        - All or N/A
        - WCOSS2
        - Hera
        - Orion
        - Jet
        - Cloud
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: Please give explicit instructions to reproduce the error
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Additional information
      description: Provide context or any additional information about the bug.
    validations:
      required: true

  - type: textarea
    id: propsed_implementation
    attributes:
      label: Do you have a proposed solution?
      description: If you already have an idea on how to fix this, please provide it here.
      placeholder: Optional
    validations:
      required: false
