name: Fix File Update
description: Request fix files be added or updated
labels: ["Fix Files", "triage"]
assignees:
  - KateFriedman-NOAA
  - WalterKolczynski-NOAA

body:
  - type: dropdown
    attributes:
      label: Target fix directory
      options:
        - NEW
        - aer
        - am
        - chem
        - cice
        - cpl
        - datm
        - gdas/crtm
        - gdas/fv3jedi
        - gdas/gsibec
        - gldas
        - glwu
        - gsi
        - lut
        - mom6
        - orog
        - raw
        - reg2grb2
        - sfc_climo
        - ugwd
        - verif
        - wave
      multiple: true
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Type of change
      options:
        - label: Update existing files
        - label: Remove files
        - label: Add new files to existing directory
        - label: Add new fix directory
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Any workflow changes needed?
      description: |
        Any change other than adding files to an existing directory will require at least a new fix version.
      options:
        - No change needed
        - Fix version only
        - Fix version + additional changes
    validations:
      required: true

  - type: textarea
    attributes:
      label: Related issues
      description: Please link any related issues in other repositories
      placeholder: NOAA-EMC/repo#1234
    validations:
      required: false

  - type: input
    attributes:
      label: Pickup location
      description: |
        Please provide a path to the data on either Hera or WCOSS.

        If this requires a version update, please provide the *entire* directory, including unchanged files from current fix.
      placeholder: /path/to/new/fix
    validations:
      required: true

  - type: input
    attributes:
      label: Size
      description: How much bigger/smaller is the new set from the existing set (in MB)?
      placeholder: 0
    validations:
      required: true

  - type: markdown
    value: |
      # Tasks
      - [ ] Discuss needs with global-workflow developer assigned to request.
      - [ ] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
      - [ ] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
      - [ ] Make related workflow/component updates.

