name: Production Update
description: Begin the process of an operational production update
labels: ["production update", "triage"]
assignees:
  - WalterKolczynski-NOAA
  - KateFriedman-NOAA

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a concise description of the production update.
      placeholder: Include related issues in component repositories.
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: Target version
      description: What is the target GFS version?
      placeholder: Use v#.#.# format
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Expected workflow changes
      description: What are the anticipated changes coming into the workflow?
      placeholder: Include version variables, checkout tags, config/parm, etc.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Tasks
      description: List of tasks to complete update. For use after issue is created.
      options:
        - label: Create release branch
        - label: Make workflow changes for upgrade in release branch (add additional checklist items as needed)
        - label: Create release notes
        - label: Cut hand-off tag for CDF
        - label: Submit CDF to NCO
        - label: Implementation into operations complete
        - label: Merge release branch into operational branch
        - label: Cut version tag from operational branch
        - label: Release new version tag
        - label: Announce to users
        - label: Update Read-The-Docs operations status version in develop
