# This file defines jobs to create and run specific to PR cases

# Template for experiment setup jobs
.setup_template:
  extends: .base_config
  stage: create_experiments
  script:
    - export RUNTESTS=${RUNTESTS_DIR}
    - ${HOMEGFS}/dev/ci/scripts/utils/ci_utils.sh create_experiment ${HOMEGFS}/dev/ci/cases/pr/${caseName}.yaml
  needs:
    - build-${machine}

# Template for test execution jobs
.run_tests_template:
  extends: .base_config
  stage: run_tests
  script:
    - echo "Using build directory $HOMEGFS (dated $BUILD_DATE)"
    - pslot=$(${HOMEGFS}/dev/ci/scripts/utils/ci_utils.sh get_pslot ${RUNTESTS_DIR} ${caseName})
    - ${HOMEGFS}/dev/ci/scripts/run_check_ci.sh ${CI_RUN_PATH} ${pslot} global-workflow
  needs:
    - setup_experiments-${machine}