program regrid_nemsio_main

  !=====================================================================

  !$$$ PROGRAM DOCUMENTATION BLOCK
  !
  ! ABSTRACT:
  !  
  !  This routine provides an interface between the National Oceanic
  !  and Atmospheric Administration (NOAA) National Centers for
  !  Environmental Prediction (NCEP) implemented NOAA Environmental
  !  Modeling System (NEMS) input/output file format and the native
  !  FV3 cubed sphere grid.
  !
  ! NOTES:
  !
  !    * Uses interpolation weights generated by 
  !      Earth-System Modeling Framework (ESMF) remapping utilities.
  !
  ! PRGMMR: Winterbottom        
  ! ORG:    ESRL/PSD1       
  ! DATE:   2016-02-02
  !
  ! PROGRAM HISTORY LOG:
  !
  !  2016-02-02 Initial version. Henry R. Winterbottom
  !  2016-11-01 Modifed by Jeff Whitaker.
  !
  !$$$

  !=====================================================================

  ! Define associated modules and subroutines

  !---------------------------------------------------------------------

  use kinds

  !---------------------------------------------------------------------

  use mpi_interface
  use fv3_interface
  use namelist_def
  use constants

  !---------------------------------------------------------------------

  implicit none

  !=====================================================================

  ! Define variables computed within routine

  real(r_kind)                                             :: exectime_start
  real(r_kind)                                             :: exectime_finish

  !=====================================================================

  ! Define local variables

  call mpi_interface_initialize()
  call init_constants(.false.)

  if(mpi_procid .eq. mpi_masternode) then

     call cpu_time(exectime_start)

  end if
  call mpi_barrier(mpi_comm_world,mpi_ierror)

  call namelistparams()
  call fv3_regrid_nemsio()


  if(mpi_procid .eq. mpi_masternode) then

     call cpu_time(exectime_finish)
     write(6,500) exectime_finish - exectime_start
     
  end if ! if(mpi_procid .eq. mpi_masternode)

  call mpi_barrier(mpi_comm_world,mpi_ierror)
  call mpi_interface_terminate()

  !=====================================================================
  ! Define format statements

500 format('MAIN: Execution time: ', f13.5, ' seconds.')

  !=====================================================================

end program regrid_nemsio_main
