C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    CHKFIL      MAKE SURE THE FILE IS PRESENT
C   PRGMMR: LARRY SAGER      ORG: W/NMC41    DATE: 97-03-05
C
C ABSTRACT: CHKFIL USES THE INQUIRE COMMAND TO SEE IF 
C           THE DATA FILE IS PRESENT
C
C PROGRAM HISTORY LOG:
C   97-03-05  LARRY SAGER
C
C USAGE:    CALL CHKFIL (ITYP,CDATE,IRTC)
C   INPUT ARGUMENT LIST:
C     ITYP     - TYPE FLAG (SYNOPTIC/METAR)
C     CDATE    - DATE OF FILE
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     IRTC     - IRTC = 0    FILE PRESENT
C                IRTC = 1    FILE ABSENT
C
C REMARKS: LIST CAVEATS, OTHER HELPFUL HINTS OR INFORMATION
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 90
C   MACHINE:  IBM SP
C
C$$$
      SUBROUTINE CHKFIL (ITYP,CDATE,IRTC)                    
C 
      CHARACTER*10   CDATE     
      CHARACTER*8   CSTAT(6)
      CHARACTER*50  CNAME
C
      LOGICAL       AROUND
C
      DATA CSTAT    /'synop   ','metar   ','ships   ','lcman   ',
     1       'mbuoy   ','dbuoy   '/ 
C
      IRTC = 0
C
C     BUILD THE NAME OF THE INQUIRE FILE    
C
      CNAME = CSTAT(ITYP)(1:5) // '.' // CDATE   
C
C     INVOKE INQUIRE TO SEE IF THIS FILE EXISTS
C
      INQUIRE(FILE=CNAME,EXIST=AROUND)
      IF(.NOT. AROUND) IRTC = 1

C     GEORGE VANDENBERGHE.   7/8/97  
C     STOP HERE IF THERE IS NO SYNOPTIC DATA, OTHERWISE CONTINUE
C
C     BOB HOLLERN.  9/16/99
C     WILL EXIT FROM THE SCRIPT gendata.sh IF NO SYNOPTIC DATA
C
CCC   IF( ITYP .EQ. 1 .AND. IRTC .EQ. 1) THEN
CCC      WRITE (102,*) 'NO SYNOP DATA.  STOPPING HERE '       
CCC      CALL ERREXIT(8)
CCC   ENDIF

      RETURN
      END
