C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    IJAFOS      CALCULATE THE I J OF THIS REP
C   PRGMMR: LARRY SAGER      ORG: W/NMC41    DATE: 97-01-10
C
C ABSTRACT: IJAFOS CALCULATES THE I J LOCATION OF THIS SURFACE
C   OBSERVATION                                       
C
C PROGRAM HISTORY LOG:
C   97-01-10  LARRY SAGER
C
C USAGE:    CALL IJAFOS  (HDR, ILOC, JLOC)                           
C   INPUT ARGUMENT LIST:
C     HDR      - STATION LOCATION INFORMATION       
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     ILOC     - I LOCATION OF REPORT                  
C     JLOC     - J LOCATION OF REPORT         
C
C REMARKS: LIST CAVEATS, OTHER HELPFUL HINTS OR INFORMATION
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 90
C   MACHINE:  IBM SP
C
C$$$
      SUBROUTINE IJAFOS (HDR, ILOC, JLOC)        
C 
C     THIS SUBROUTINE CALCULATES THE I J LOCATION   
C       FOR THIS SURFACE LOCATION           
C
      REAL     HDR(*)
C
C     THE I, J LOCATION FOR THIS
C       REPORT.
C
      ALAT = HDR(2)
      ALONG = HDR(3)
      KEIL = 7 
      CALL TRUIJ(ALAT,ALONG,XI,XJ,KEIL)
      XI = XI - 28.0
      XJ = XJ - 5.0
      ILOC = (XI - 1.)*37.5 + 0.5
      JLOC = (XJ - 1.)*37.5 + 0.5
C
      RETURN
      END
