#!/bin/sh

set -xa
#####################################
# SET PROCESSING VARIABLES
#####################################
export PS4='$SECONDS + '
date
 
# 
# obtain unique process id (pid) and make temp directory
#
export pid=$$
export DATA=/tmpnwprd1/${job}.${pid}
mkdir $DATA
cd $DATA 

export cycle=t${cyc}z 
 
####################################
# File To Log Msgs
####################################
if [ $envir = "prod" ]
  then
    export jlogfile=/com/logs/jlogfiles/jlogfile.${job}.${pid}
  else
    export jlogfile=/com/logs/$envir/jlogfile
fi

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export MP_PULSE=0

export SENDCOM=YES
if [ $envir = "prod" ]
  then
    export SENDDBN=YES
  else
    export SENDDBN=NO
fi
export SENDECF=YES

export NET=gfs
export RUN=gfs
export HOMEgfs=${HOMEgfs:-/nw${envir}/gfs.${gfs_ver}}
export HOMEcpc=/nwprod
export EXECcpc=$HOMEcpc/exec
export FIXcpc=$HOMEcpc/fix
export PARMcpc=$HOMEcpc/parm
export USHcpc=$HOMEcpc/ush

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
$utilscript/setup.sh

# Run setpdy and initialize PDY variables
$utilscript/setpdy.sh
. PDY

# export com=/com/${NET}/${envir}
export COMIN=/com/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=/com/${NET}/${envir}/${RUN}.${PDY}

mkdir -p $COMOUT
 
env

########################################################
# Execute the script.
$HOMEgfs/scripts/excpc_get_gfs_6hr.sh.ecf
########################################################

cd /tmpnwprd1
rm -rf $DATA
date
