#!/bin/sh
export PS4='$SECONDS + '
date
set -xa
########################################
# Runs GFS BUFR SOUNDINGS
########################################
#Specify whether the run is production or development
#
export envir=${envir:-prod}

#####################################
## The following is set in ecflow script
#export MP_EUIDEVELOP=min
#export KMP_STACKSIZE=2048m
#export MPICH_ALLTOALL_THROTTLE=0
#export MP_SINGLE_THREAD=yes
#export MP_EAGER_LIMIT=65536
#export MP_USE_BULK_XFER=no
#export MP_COLLECTIVE_OFFLOAD=no
#export MP_SHARED_MEMORY=yes
#export MP_MPILIB=mpich2
#export MP_LABELIO=yes
#####################################
# Specify version numbers
####################################
export gfs_bufrsnd_ver=${gfs_bufrsnd_ver:-v1.0.0}
export gfs_ver=${gfs_ver:-v13.0.0}
export util_ver=${util_ver:-v1.0.0}
export obsproc_shared_bufr_cword_ver=${obsproc_shared_bufr_cword_ver:-v1.0.0}

# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd1}
export DATA=$DATA_IN/${job}.${pid}
mkdir $DATA
cd $DATA 

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export NET=gfs
export RUN=gfs
export model=gfs

###################################
# Set up the UTILITIES
###################################
export HOMEutil=${HOMEutil:-/nw${envir}/util.${util_ver}}
export EXECutil=${EXECutil:-$HOMEutil/exec}
export FIXutil=${FIXutil:-$HOMEutil/fix}
export PARMutil=${PARMutil:-$HOMEutil/parm}
export USHutil=${USHutil:-$HOMEutil/ush}

export utilities=${utilities:-$HOMEutil/ush}
export utilscript=${utilscript:-$HOMEutil/ush}
export utilexec=${utilexec:-$HOMEutil/exec}

export HOMEbufrsnd=${HOMEbufrsnd:-${NWROOT}/gfs.${gfs_ver}}
export EXECbufrsnd=${EXECbufrsnd:-$HOMEbufrsnd/exec}
export FIXbufrsnd=${FIXbufrsnd:-$HOMEbufrsnd/fix}
export PARMbufrsnd=${PARMbufrsnd:-$HOMEbufrsnd/parm}
export USHbufrsnd=${USHbufrsnd:-$HOMEbufrsnd/ush}
export SCRbufrsnd=${SCRbufrsnd:-$HOMEbufrsnd/scripts}

export HOMEgfs=${HOMEgfs:-${NWROOT}/gfs.${gfs_ver}}
export FIXgfs=${FIXgfs:-$HOMEgfs/fix}

export HOMEglobal=${HOMEglobal:-$NWROOT/global_shared.${gfs_ver}}
export FIXglobal=${FIXglobal:-$HOMEglobal/fix}
export USHglobal=${USHglobal:-$HOMEglobal/ush}

export HOMEobsproc_shared_bufr_cword=${HOMEobsproc_shared_bufr_cword:-$NWROOTp1/obsproc_shared/bufr_cword.${obsproc_shared_bufr_cword_ver}}
export EXECobsproc_shared_bufr_cword=${EXECobsproc_shared_bufr_cword:-$HOMEobsproc_shared_bufr_cword/exec}
export cwordsh=${cwordsh:-${HOMEobsproc_shared_bufr_cword}/ush/bufr_cword.sh}

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

##############################
# Define COM Directories
##############################
export COMIN=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}
export COMOUT=${COMROOT}/${NET}/${envir}/${RUN}.${PDY}
export pcom=${pcom:-${PCOMROOT}/gfs}
mkdir -p $COMOUT $pcom

#  Set output directory:
export COMAWP=${COMAWP:-${COMROOT}/nawips/${envir}/${RUN}.${PDY}}

env

########################################################
# Execute the script.
$SCRbufrsnd/exgfs_postsnd.sh.ecf
########################################################

cat $pgmout

cd /tmpnwprd1
rm -rf $DATA
date
