      SUBROUTINE CUTSTR(ICARD,MXCH,ITH,NCHAR,ITABC,
     1            N,LIT,ISUBST,NXTCH,IEXIT)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    SEPCAR      SEPARATE CHARACTER STRING
C   PRGMMR: LIN              ORG: W/NMC412   DATE: 97-01-29
C
C ABSTRACT: CREATING SUBSTRINGS CHARACTERS FROM A 20-WORD ARRAY
C   WITH CARD IMAGE CHARACTER STRING.
C
C PROGRAM HISTORY LOG:
C   YY-MM-DD  ORIGINAL AUTHOR  UNKNOWN
C   88-07-25  GLORIA DENT  PUT IN DOCUMENTATION BLOCK
C   89-04-18  STEVE LILLY  UPDATE DOCUMENTATION BLOCK
C   93-05-08  LILLY CONVERT SUBROUTINE TO FORTRAN 77
C   97-01-28  LIN   CONVERT SUBROUTINE TO CFT-77
C
C USAGE:    CALL SEPCAR  (ICARD,ITC,MXITM,NITEMS,NLCH,IHSTRL,NRCH,
C          &            IHSTRR,IERR)
C
C   INPUT ARGUMENT LIST:
C     ICARD    - A 10-WORD (=80CHARS) ARRAY WITH CARD IMAGE
C              - CHARACTER STRING TO BE SEAPARATED INTO SUBSTRINGS
C     ITC      - CARD COLUMN TO BEGIN THE SEPARATING
C     MXITM    - MAX NO. OF ITEMS EXPECTED ON THE CARD IMAGE
C              - WHERE ITEMS ARE SEPARATED BY COMMAS OR BLANKS
C              - AND MAY BE AN EXPRESSION CONTAINING AN '=' SIGN
C              - AND THE STRING IS TERMINATED BY A SEMI-COLON.
C
C   OUTPUT ARGUMENT LIST:
C     NITEMS   - NO. OF ITEMS FOUND
C     NLCH     - IS CHAR COUNT OF FOLLOWING SUBSTRING
C     IHSTRL   - CHAR SUBSTRING W/ MAX OF 12 CHARS
C     NRCH     - IS CHAR COUNT OF SUBSTRING FROM RHS OF '=' SIGN IF ANY
C     IHSTRR   - CHAR STRING FROM RHS OF EQUAL SIGN IF ANY
C     IERR     - = 0 IS NORMAL RETURN
C              - = 1 IF SOME TROUBLE WAS ENCOUNTERED.
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      RETURN
      END
