      SUBROUTINE MOVEID(IO,JO,NAME,IPROB,ICNT,NOB,IDOTS,
     1                  JDOTS,KCNT,JCOUNT,IERR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    MOVEID      CHECKING FOR OVERWRITING STATIONS
C   PRGMMR: LIN              ORG: W/NMC412   DATE: 97-01-31
C
C ABSTRACT: EACH INDIVIUAL STATION IS COMPARED TO A LISTING
C   WHICH IDENTIFIES THE STATIONS THAT ARE OVERWRITING.
C
C PROGRAM HISTORY LOG:
C   89-05-26  ORIGINAL AUTHOR   STEVE LILLY
C   89-06-21  LILLY ADDED LOGIC TO PLACE TOP BAR
C   89-06-27  LILLY ADDED LOGIC TO WRITE MB LEVEL WITHIN
C              BOX
C   89-07-13  LILLY TAKE OUT LOGIC TO DRAW THE BOTTOM LINE
C             OF BOX.
C   89-07-14  LILLY LOGIC WAS ADDED TO INDENTIFY THE STATION
C              THAT WAS MOVED..IE; ID, LAT/LONG
C   89-11-03  LILLY ADDED LOGIC WHICH INDICATES THE I AND J
C              POSITIONS OF A STATION THAT WAS MOVED
C   89-12-26  DENT  INITIALIZE RETURN EXIT BEFORE THE FIRST
C              STATEMENT TO PREVENT FALSE PLOTTING OF NON-PIBAL
C              REPORTS.
C   93-05-08  LILLY CONVERT SUBROUTINE TO FORTRAN 77
C   97-01-31  LIN   CONVERT SUBROUTINE TO CFT 77
C
C USAGE:    CALL MOVEID(IO,JO,NAMSTN,IPROB,ICNT,NOB,IDOTS,
C                JDOTS,KCNT,JCOUNT,IERR)
C
C   INPUT ARGUMENT LIST:
C     IO       - VARIAN I POSITION OF THE STATION
C     JO       - VARIAN J POSITION OF THE STATION
C     NAME     - INTEGER   2 WORD ARRAY CONTAINING STATION NAME
C              - IN HOLLERTH. IE; '72308 ' CHARLESTON SC
C     IPROB    - STATIONS WHICH ARE OVERWRITING OTHER REPORTS
C     ICNT     - COUNTER OF OVERWRITING STATIONS FOUND IN LIST
C     NOB      - NUMBER OF OVERWRITING STATIONS
C
C   OUTPUT ARGUMENT LIST:
C     IDOTS    -  THE I POSITION IN DOTS UNITON THE VARIAN
C     JDOTS    -  THE J POSITION IN DOTS UNIT ON THE VARIAN
C     KCNT     -  INDICATES THE COUNT OF THE STATION MOVED
C     JCOUNT   -  THIS COUNT AIDS IN COMPUTING THE I AND J
C              -  POSITION OF A STATION THAT WAS MOVED
C     IERR     -  0 NO OVERLAPPING STATIONS WERE FOUND
C              -  1 A OVERLAPPING STATIONS WAS FOUND
C     COMMON /LKTLBS/TLIM,LOOKT
C     COMMON /ISTART/ISTART
C     COMMON  /KPLOT / LABEL(2,1024),LABIX,NOBUF,IDRA(50)
C
C REMARKS: FUTHER OVERWRITING STATIONS MAY BE ADDED TO IDTABLE
C   (FT26F001...PLOTMLTY).
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      COMMON /LKTLBS/TLIM,LOOKT
      INTEGER   LOOKT(9,63),TLIM
      COMMON /ISTART/ISTART
      COMMON  /KPLOT / LABEL(2,1024),LABIX,NOBUF,IDRA(50)
C
      CHARACTER*4 AAAAS(26)
      DATA        AAAAS        /26*'AAAA'/
C
      CHARACTER*8 DHMBS(29)
C
C???  INTEGER   ID1A         /1H7/
      CHARACTER*6 IPROB(NOB)
      CHARACTER*8   NAME   
      INTEGER   ICNT
      INTEGER   JCOUNT
      DATA      J     /0/
C
      LOGICAL   W3AI24
C
C  INITIALIZE RETURN HERE FOR NON PIBAL REPORTS
       IER1 = 0
C???  IF(.NOT.W3AI24(NAME,ID1A,1)) GOTO 5
      IF(.NOT.W3AI24(NAME,'7',1)) GOTO 5
C
C    TAKING THE NUMBER OF OVERLAPPING STATIONS AND THEN
C    COMPARING WITH THE OBSERVED.
C
      DO 711 K=1,NOB
C???    IF(W3AI24(NAME,IPROB(1,K),5)) GOTO 15
        IF(W3AI24(NAME,IPROB(K),5)) GOTO 15
  711 CONTINUE
C
C   THE ID OF THE OBSERVE STATION(NAME) DID NOT MATCH WITH
C   ANY OF THE TROUBLE STATIONS(IPROB).
C
       IER1 = 0
C
       GOTO 5
C
C   IF A OVERWRITING STATION IS NOTED, THE I AND J POSITIONS
C   ARE CHANGED TO AN I AND J POSITION AT THE LEFT SIDE OF THE
C   UPPER LEFT HAND CORNER.
C
C
   15 KCNT= K
      ICNT=ICNT + 2
      PRINT *,' MOVEID  ICNT IS ',ICNT,'  J IS ',J
      IF(ICNT.NE.1) GOTO 20
C
C   J IS A DUMMY VARIABLE USED AS A COUNTER FOR NUMBER OF OVERLAYING
C   STATIONS...BEGINNING WITH ZERO
      J = 0
C A BOUNDARY IS PLOTTED ABOVE THE 1-DOT/2-DOTS VARIANS CHARTS.
C
      ANGLE = 0.0
      IPRIOR = 1
C
C       LEFT SIDE:
      HGT   = 17.0
      NUMCH = 8
      CALL PUTLAB(10,1885,HGT,AAAAS,ANGLE,NUMCH,IPRIOR,0)
C
C       RIGHT SIDE:
C
      HGT   = 17.0
      NUMCH = 8
      CALL PUTLAB(1710,1885,HGT,AAAAS,ANGLE,NUMCH,IPRIOR,0)
C
C       BOTTOM LINE:
C
C     HGT   = 16.0
C     NUMCH = 100
C     CALL PUTLAB(10,1885,HGT,AAAAS,ANGLE,NUMCH,IPRIOR,0)
C
C       TOP LINE:
C
      HGT   = 16.0
      NUMCH = 100

      CALL PUTLAB(10,2025,HGT,AAAAS,ANGLE,NUMCH,IPRIOR,0)
C
C  IDENTIFYING THE LEVEL AT THE TOP OF THE MAP...HOPEFULLY
C  REPRODUCTION WILL NOT DESTORY OVERLAY STATION DATA
C  IDRA(9) AND IDRA(10) GIVE MB LEVEL.  IDRA'S FOUND IN
C  SUBROUTINE INIDRA WHICH IS CALL BY SUBROUTINE MAPLOP.
C  IDRA(9) AND IDRA(10) IS PASSED BY COMMON KPLOT
C
C
      HGT   = 11.0
      NUMCH = 6
      ANGLE = 90.
      CALL PUTLAB(25,2000,HGT,IDRA(9),ANGLE,NUMCH,IPRIOR,0)
C
C   ISTART IS DEFINED BY LCARD IN SUBROUTINE RDCAR1(THE
C   4 WORD)AND PASSED BY COMMON ISTART.  IF DOING A
C   ONE DOT FAX...ISTART = 460 (INDENTING THE OVERLAPPING
C   STATION 4 INCHES FROM THE EDGE OF THE MAP).  TWO DOT
C   REQUIRES ISTART = 460.
C
      IDOTS = ISTART
      JDOTS = 1965
C
C  THIS HELPS TO IDENTIFY THE STATION THAT MOVES..IE; ID, LAT/LONG
      CALL PUTLAB(300,1920,0.12,'ID',0.0,2,1,0)
      CALL PUTLAB(300,1905,0.12,'LAT/LONG',0.0,8,1,0)
C
      IER1  = 1
      GOTO 5
   20 CONTINUE
C
C  INCREMENT J COUNTER
      J = J + 1
      JCOUNT = J
      IDOTS = (60*ICNT) - (40*J) + (ISTART - 60)
      JDOTS = 1965
      IER1 = 1
    5 CONTINUE
C
      IERR = IER1
C
C   NOTE...IF A OVERWRITING STATION IS NOT NOTED, THE I AND J
C   POSITIONS DOES NOT CHANGE.
C
      RETURN
      END
