      SUBROUTINE MOVOBS(KIO,KJO,ICNT,KIDOTS,KJDOTS,JCOUNT)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    MOVOBS      CHECKING FOR OVERWRITING STATIONS
C   PRGMMR: LILLY            ORG: W/NMC412   DATE: 93-05-08
C
C ABSTRACT: FINDING THE I AND J VALUES FOR PLOTTING THE DATA
C   AT THE TOP OF THE VARIAN PRODUCT.
C
C PROGRAM HISTORY LOG:
C   89-11-03  ORIGINAL AUTHOR   STEVE LILLY
C   93-05-08  LILLY CONVERT SUBROUTINE TO FORTRAN 77
C
C USAGE:    CALL MOVOBS(KIO,KJO,ICNT,KIDOTS,KJDOTS,JCOUNT)
C
C   INPUT ARGUMENT LIST:
C     KIO      - VARIAN I POSITION OF THE STATION
C     KJO      - VARIAN J POSITION OF THE STATION
C     ICNT     - COUNTER OF PROBLEM STATION THAT REPORTED IN
C              - SUB MOVEID
C
C   OUTPUT ARGUMENT LIST:
C     KIDOTS   -  THE I POSITION IN DOTS UNITON THE VARIAN
C     KJDOTS   -  THE J POSITION IN DOTS UNIT ON THE VARIAN
C     JCOUNT   -  THIS COUNT AIDS IN COMPUTING THE I AND J
C              -  POSITION OF A STATION THAT WAS MOVED
C     COMMON /ISTART/ISTART
C     COMMON  /KPLOT / LABEL(2,1024),LABIX,NOBUF,IDRA(50)
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      COMMON /ISTART/ISTART
      COMMON  /KPLOT / LABEL(2,1024),LABIX,NOBUF,IDRA(50)
C
      CHARACTER*4  AAAAS(26)
      DATA         AAAAS          /26*'AAAA'/
      INTEGER    ICNT
      INTEGER    JCOUNT
C
      ICNT=ICNT + 2
C
      IF(ICNT.NE.1) GOTO 15
C
C A BOUNDARY IS PLOTTED ABOVE THE 1-DOT/2-DOTS VARIANS CHARTS.
C
      ANGLE = 0.0
      IPRIOR = 1
C
C       LEFT SIDE:
      HGT   = 17.0
      NUMCH = 8
      CALL PUTLAB(10,1885,HGT,AAAAS,ANGLE,NUMCH,IPRIOR,0)
C
C       RIGHT SIDE:
C
      HGT   = 17.0
      NUMCH = 8
      CALL PUTLAB(1710,1885,HGT,AAAAS,ANGLE,NUMCH,IPRIOR,0)
C
C       BOTTOM LINE:
C
C     HGT   = 16.0
C     NUMCH = 100
C     CALL PUTLAB(10,1885,HGT,AAAAS,ANGLE,NUMCH,IPRIOR,0)
C
C       TOP LINE:
C
      HGT   = 16.0
      NUMCH = 100
      CALL PUTLAB(10,2025,HGT,AAAAS,ANGLE,NUMCH,IPRIOR,0)
C
C  IDENTIFYING THE LEVEL AT THE TOP OF THE MAP...HOPEFULLY
C  REPRODUCTION WILL NOT DESTORY OVERLAY STATION DATA
C  IDRA(9) AND IDRA(10) GIVE MB LEVEL.  IDRA'S FOUND IN
C  SUB INIDRA WHICH IS CALL BY SUBROUTINE MAPLOP.
C  IDRA(9) AND IDRA(10) IS PASSED BY COMMON KPLOT
C
C
      HGT   = 11.0
      NUMCH = 6
      ANGLE = 90.
      CALL PUTLAB(25,2000,HGT,IDRA(9),ANGLE,NUMCH,IPRIOR,0)
C
C   ISTART IS DEFINED BY LCARD IN SUBROUTINE RDCAR1(THE
C   4 WORD)AND PASSED BY COMMON ISTART.  IF DOING A
C   ONE DOT FAX...ISTART = 460 (INDENTING THE OVERLAPPING
C   STATION 4 INCHES FROM THE EDGE OF THE MAP).  TWO DOT
C   REQUIRES ISTART = 460.
C
C  THIS HELPS TO IDENTIFY THE STATION THAT MOVES..IE; ID, LAT/LONG
      CALL PUTLAB(300,1920,0.12,'ID',0.0,2,1,0)
      CALL PUTLAB(300,1905,0.12,'LAT/LONG',0.0,8,1,0)
C
      ICNT=ICNT+2
C
   15 CONTINUE
C
C  INCREMENT J COUNTER
      J = JCOUNT + 1
      KIDOTS = (60*ICNT) - (40*J) + (ISTART - 60)
      KJDOTS = 1965
      JCOUNT = J
C
      RETURN
      END
