       SUBROUTINE PLTDAT(IDOTS,JDOTS,ihdewdep,IDDGD,IHFFF,NSSS,
     1             IHTT,JHT1,IHZZZ,C8NAMSTN,IOPTN,KEIL,NORWNDIR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PLTDAT      PLOT ONE STATION
C   PRGMMR: SHIMOMURA        ORG: W/NP12     DATE: 97-02-27
C
C ABSTRACT: GIVEN: DATA FOR ONE STATION READY TO BE PLOTTED;
C   TASK: TO PLOT THE DATA ACCORDING TO THE SPECIFED PLOTTING MODEL 
C   VIA PUTLAB.
C
C PROGRAM HISTORY LOG:
C   YY-MM-DD  ORIGINAL AUTHOR UNKNOWN
C   88-08-11  GLORIA DENT MOVE THE PLOTTING PARAMETERS DOWN OF STATION
C               72273 (FT. HUACHUA) SO THAT THEY WILL NOT OVERPLOT
C               STATION 72274 (TUCSON) ON THE VARIAN CHART.
C   89-05-01  STEVE LILLY UPDATED DOCUMENTATION BLOCK
C   89-06-09  LILLY MOVED THE PLOTTING PARAMETERS WEST OF STATION
C                        72435 (PADUCAH) AND EAST OF STATION 72327
C                        (NASHVILLE/BERRY) SO THAT THEY WILL NOT
C                        OVERPLOT ON THE VARIAN CHART.
C   89-06-12  LILLY MOVED THE PLOTTING PARAMETERS NORTH OF STATION
C                        72429 (DAYTON) AND SOUTH OF STATION 72425
C                        (HUNTINGTON) SO THAT THEY WILL NOT
C                        OVERPLOT ON THE VARIAN CHART.
C   89-06-21  LILLY MOVED THE PLOTTING PARAMETERS WEST AND NORTH
C                        OF STATION 72435 (PADUCAH) AND EAST AND
C                        SOUTH OF STATION 72327 (NASHVILLE/BERRY).
C   93-05-07  LILLY CONVERT SUBROUTINE TO FORTRAN 77
C   97-02-01  SHIMOMURA - CONVERT TO RUN ON CRAY;
C
C USAGE:    CALL PLTDAT(IDOTS,JDOTS,ihdewdep,NORWNDIR,IDDGD,IHFFF,NSSS,
C                       IHTT,JHT1,IHZZZ,C8NAMSTN,IOPTN,KEIL)
C
C   INPUT ARGUMENT LIST:
C     IDOTS    - VARIAN I POSITION OF THE STATION
C     JDOTS    - VARIAN J POSITION OF THE STATION
C     ihdewdep     - C*4 FOR LIGHT AND VRBL WIND INCLUDING CALM
C     NORWNDIR    - INT - THE TRUE NORTH-ORIENTED WIND DIRECTION
C                         as a left-justified 8-character txt string 
C                         in the integer word; of which the high-
C                         order 2-characters will be used 
C                         as Arg(3) in call to wndirdig();

C     IDDGD    - INT - THE GRID-ORIENTED WIND DIRECTION
C     IHFFF    - C*4 WIND SPEED OR 12HR HEIGHT CHANGE
C     NSSS     - INT - WIND SPEED
C     IHTT     - C*4 THE TEMPERATURE
C     JHT1     - C*4 TEMPERATURE OBS FOR THE CALC TEMP ABOVE OTHER TT
C     IHZZZ    - C*4 GEOPOTENIAL HEIGHT
C     C8NAMSTN   - C*8 C8NAMSTN STATION ID IN HOLLERITH FOR
C              - S/R PUTLAB ENTRY
C     IOPTN    - INT - BIT OPTIONS FOR THE DESIRED PLOTTING MODEL. SEE
C              -       THIS SOURCE FOR DETAILED BIT DECLARATION.
C     KEIL     - INT - GIVEN THE KRUN OPTION; KEIL SPECIFIED THE GRID
C
C   OUTPUT ARGUMENT LIST:
C     COMMON   - /CHKOUT/ NITEM
C     COMMON   - /MRGARG/YDIS,DUMMY(3),XO,YO
C     COMMON   - /XZPLAX/ XZPLOT,YZPLOT,IORITY
C
C REMARKS:
C   CALLS SUBR PUTLAB();
C              WNDBRK();
C              WNDIRT();
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  CRAY
C
C$$$
C
      EXTERNAL   LASTCH
      INTEGER    LASTCH


      COMMON   /CHKOUT/ NITEM
      COMMON   /MRGARG/YDIS,DUMMY(3),XO,YO
      COMMON   /XZPLAX/ XZPLOT,YZPLOT,IORITY
C
C     . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
C ... USAGE: CALL PLTDAT(IDOTS,JDOTS,ihdewdep,NORWNDIR,IDDGD,IHFFF,NSSS,
C                        IHTT,JHT1,IHZZZ,C8NAMSTN,IOPTN,KEIL)
      INTEGER      IDOTS,JDOTS
      CHARACTER*4  ihdewdep
      CHARACTER*8  NORWNDIR
      INTEGER      NDD
      CHARACTER*4  IHFFF
      INTEGER      NSSS
      CHARACTER*4  IHTT
      CHARACTER*4  JHT1
      CHARACTER*4  IHZZZ
      CHARACTER*8  C8NAMSTN
      INTEGER      IOPTN
      INTEGER      KEIL

C     . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
      INTEGER      IPRIOR(2)

      DIMENSION  IDEL(6),JDEL(6)
      DIMENSION  ISDEL(6),JSDEL(6)
      DIMENSION  IMDEL(6),JMDEL(6)
      DIMENSION  ISVDEL(6),JSVDEL(6)
      DIMENSION  IMVDEL(6),JMVDEL(6)
      DATA     IMDEL/-5,-35,-25,5,5,-15/
      DATA     JMDEL/-4,2,-13,-13,2,-28/
      DATA     ISDEL/-2,-23,-17,5,5,-11/
      DATA     JSDEL/-4,1,-8,-8,1,-17/
      DATA     ISVDEL/ -4, -9,  0,  0, -9,  9/
      DATA     JSVDEL/ -2,-23,-17,  5,  5,-11/
      DATA     IMVDEL/ -8,-14,  1,  1,-14, 16/
      DATA     JMVDEL/ -5,-35,-25,  5,  5,-15/
      DATA     IMEDLA /-26/
      DATA     JMEDLA /  1/
      DATA     IMEDLB /-11/
      DATA     JMEDLB /-26/
      DATA     ICTDEL,JCTDEL/1,-9/
C     ...POSITIONING TO BRACKET REL TO LL OF TEMP
      DATA     ICZDEL,JCZDEL/1,-9/
C     ...POSITIONING TO BRACKET REL TO LL OF ZZZ
      DATA     IDELTK/-19/
      DATA     JDELTK/5/
C     ...FOR RELOCATING TT TO ABOVE STN CIRCLE INSTEAD OF UPR LEFT...

      INTEGER      INTCIRCLES
      CHARACTER*1  C1CIRCLES(8)
      EQUIVALENCE (INTCIRCLES,C1CIRCLES(1))
      DATA         INTCIRCLES     / X'0000003E5C3C2928' /
C      DATA         INTCIRCLES     / X'28293C5C3E000000' /
C                                      1 2 3 4 5
      CHARACTER*1  C1OPENCIR
      EQUIVALENCE (C1CIRCLES(1),C1OPENCIR)
      CHARACTER*1  C1CLOSCIR
      EQUIVALENCE (C1CIRCLES(2),C1CLOSCIR)
      CHARACTER*1  C1SQRCIR
      EQUIVALENCE (C1CIRCLES(3),C1SQRCIR)
      CHARACTER*1  C1STARCIR
      EQUIVALENCE (C1CIRCLES(4),C1STARCIR)
      CHARACTER*1  C1RTBRACK
      EQUIVALENCE (C1CIRCLES(5),C1RTBRACK)

C ...      DATA     IOPCIR/Z'4D000000'/
C ...      DATA     ICLCIR/Z'5D000000'/
C ...      DATA     ISQCIR/Z'4C000000'/
C     ...WHICH IS SQUARE STN CIRCLE FOR A/C ...
C ...      DATA     ISRCIR/Z'E0000000'/
C ...      DATA     IBRACT/ '>$  ' /

C     ...FOR RIGHT BRACKET IN 10TH CHAR SET FOR CALCULATED TEMPS AND HGT
C
       CHARACTER*1  C1STNCIRCLE

C     *     *     *     *     *     *     *     *     *     *     *

C     ...NOW COMES BITS FOR VARIOUS OPTIONS IN IOPTN.....
C
      DATA     JSOUTH / X'0000000100000000' /
C     ...TO MOVE ALL PARAMETER SOUTH 4 DOTS EXCEPT STA CIRCLE/WIND BARB
      DATA     KDOWN /Z'80000000'/
C    ...TO MOVE ALL PARAMETERS DOWN 12 DOTS EXCEPT STA CIRCLE/WIND BARB
      DATA     IWEST /Z'40000000'/
C     ...TO MOVE ALL PARAMETER WEST 4 DOTS EXCEPT STA CIRCLE/WIND BARB
      DATA     IEAST /Z'20000000'/
C     ...TO MOVE ALL PARAMETER EAST 4 DOTS EXCEPT STA CIRCLE/WIND BARB
      DATA     JNORTH /Z'10000000'/
C     ...TO MOVE ALL PARAMETER NORTH 4 DOTS EXCEPT STA CIRCLE/WIND BARB
      DATA    KMVTR/Z'8000000'/
C     ...FOR MOVING TT TO UPPER RIGHT OF STN CIRCLE
      DATA    KMEDW/Z'4000000'/
C     ...FOR MED-SMALL CHAR FOR HGT ON WINDS ALOFT CHART
       DATA   KMTMP/Z'2000000'/
C     ...TO PLOT 850 MB CALC TMP ABOVE REPORTED TMP
C     ...TO MOVE BRACKET CLOSER TO DATA ON SIRS PLOTTED CHART.
      DATA    KCLOS/Z'1000000'/
C     ...TO MOVE BOGUS 'B' CLOSER TO STN CIRCLE
      DATA     KANGB/Z'800000'/
C     ...            TO SET ANGLE TO 90 DEGREES FOR SIDEWAYS PLOTTING
      DATA     KSMNB/Z'400000'/
C     ...FOR SMALL CHARS IN STN NAME ...
      DATA     KCLZB/Z'200000'/
C     ...            FOR CALCULATED GEOPOTENTIAL HGT ...
      DATA     KCLTB/Z'100000'/
C     ...            FOR CALCULATED TEMPERATURES ...
      DATA     KMEDB/Z'80000'/
C     ...            FOR MEDIUM-SMALL CHAR FOR TEMP ON IQSY CHART
C     DATA     KMVWB/Z'40000'/
C     ...            FOR MOVING WIND BARBS FARTHER OUT STAFF
      DATA     KSMLB/Z'20000'/
C     ...            FOR TINY CHAR SET  PRINTING AS ON IQSY CHART
      DATA     KMVNB/Z'10000'/
C     ...            FOR MOVING NAME CLOSER TO STN CIRCLE...
      DATA     KTALB/Z'8000'/
C     ...            FOR ITALICS ON 12HR HGT CHG PRINT IN FFF LOT
      DATA     KSTRB/Z'4000'/
C     ...            FOR STAR IN PLACE OF STN CIRCLE...
      DATA     KSQRB/Z'2000'/
C     ...            FOR SQUARE IN PLACE OF STN CIRCLE...
      DATA     KMVDB/Z'1000'/
C     ...            FOR MOVING DD PRINT RIGHT AND LOWER...
      DATA     KMVZB/Z'800'/
C     ...            FOR MOVING ZZZ UPWARD...
      DATA     KDOVB/Z'400'/
C     ...            FOR WIND DIR DIGIT PLOTTED NEAR END OF WIND STAFF
      DATA     KMVTB/Z'200'/
C     ...            FOR MOVING TT TO ABOVE THE STN CIRCLE...
      DATA     KSMCB/Z'100'/
C     ...            FOR SMALL STN CIRCLE...
      DATA     KVECB/Z'80'/
C     ...            FOR WIND VECTOR...
      DATA     KNAMB/Z'40'/
C     ...            FOR STATION NAME...
      DATA     KZZZB/Z'20'/
C     ...            FOR GEOPOTENTIAL HEIGHT ...
      DATA     KFFFB/Z'10'/
C     ...            FOR WIND SPEED PRINT IN LOWER RIGHT...
      DATA     KDDB/Z'8'/
C     ...            FOR WIND DIRECTION PRINT IN LOWER LEFT...
      DATA     KTTB/Z'4'/
C     ...            FOR TEMPERATURE PRINT IN UPPER LEFT...
      DATA     KOCB/Z'2'/
C     ...            FOR OPEN OR CLOSED STN CIRCLE...
      DATA     KCIQB/1/
C     ...            FOR A STATION CIRCLE...
C     *     *     *     *     *     *     *     *     *     *     *
C
      DATA     HGTIT/18.0/
      DATA     HGTMEA /19.0/
      DATA     HGTMEB /24.0/
C
      integer    magddgd

      INTEGER   IQUAD		!... FOR WNDIRDIG()
      LOGICAL   LSRNHEMI

      integer      i8acc
      character*8  c8acc
      equivalence (i8acc,c8acc)

      character*2  c2dir

      SAVE

C     *     *     *     *     *     *     *     *     *     *     *
      IQUAD = 0			!... FOR WNDIRDIGIT UPRIGHT ON NHEMI
      LSRNHEMI = .FALSE.	!... NOT A SRN HEMI
C     ...STEP(1) ... INITIALIZE ...
C ...      NITEM = NITEM + 1
C ...      IF(MOD(NITEM,10) .NE. 0) GO TO 130
      write(6,122)IDOTS,JDOTS,IDDGD,IHFFF(1:3),NSSS,
     1            IHTT(1:3),IHZZZ(1:4),IOPTN,C8NAMSTN(1:6),KEIL
  122 FORMAT(1H ,'pltdat:'2I6, 2X, 2X,Z16, 2X, A3, 2X, I4,
     1            2X, A3, 2X, A4,2X,Z10,2X,A6,I6)
      
  130 CONTINUE
      HGT = 1.0
      HGTSML = 4.0 
      ANGLE = 0.0
      IPRIOR(1) = 0
      IPRIOR(2) = 1
      IF((IAND(IOPTN,KANGB)) .EQ. 0) GO TO 140
C     ...OTHERWISE, INITIALIZE FOR SIDEWAYS PLOTTING MODEL
      hgt = 3.0			!... 97-02-20 for Merc sideways regular
      hgtsml = 5.0		!... 97-02-20 for Merc sideways small
      ANGLE = 90.0
      JUPNAM = 0
      ISCDEL = ISVDEL(1)
      JSCDEL = JSVDEL(1)
      IMCDEL = IMVDEL(1)
      JMCDEL = JMVDEL(1)
      HGTMED = HGTMEB

      IMEDEL = IMEDLB
      JMEDEL = JMEDLB
      IF((IAND(IOPTN,KSMLB)) .EQ. 0) GO TO 134
C     ...OTHERWISE, INITIALIZE FOR SMALL SIDEWAYS PLOTTING MODEL
      ZHGT = HGTSML
      IUPNAM = -3
      DO  132  I = 1,6
      IDEL(I) = ISVDEL(I)
      JDEL(I) = JSVDEL(I)
  132 CONTINUE
      IUPNM1 = -4
      JUPNM1 = 2
      GO TO 149

  134 CONTINUE
C     ...INITIALIZE FOR REGULAR SIDEWAYS PLOTTING MODEL
      ZHGT = HGT
      IUPNAM = -9
      DO  136  I = 1,6
      IDEL(I) = IMVDEL(I)
      JDEL(I) = JMVDEL(I)
  136 CONTINUE
      GO TO 149

  140 CONTINUE
      IUPNAM = 0
      ISCDEL = ISDEL(1)
      JSCDEL = JSDEL(1)
      IMCDEL = IMDEL(1)
      JMCDEL = JMDEL(1)
      HGTMED = HGTMEA
      IMEDEL = IMEDLA
      JMEDEL = JMEDLA
      IF(IAND(IOPTN,KSMLB) .EQ. 0) GO TO 145
C     ...COMES HERE TO INITIALIZE FOR SMALL CHAR SET...
      ZHGT = HGTSML
      JUPNAM = 3
      IUPNM1 = 2
      JUPNM1 = 4
      DO  143  I = 1,6
      IDEL(I) = ISDEL(I)
      JDEL(I) = JSDEL(I)
  143 CONTINUE
      GO TO 149

  145 CONTINUE
C     ...COMES HERE TO INITIALIZE FOR MIDDLE-SIZED (REGULAR) CHAR SET..
      ZHGT = HGT
      JUPNAM=15
      IUPNM1 = 2
      JUPNM1=11
      DO  147  I = 1,6
      IDEL(I) = IMDEL(I)
      JDEL(I) = JMDEL(I)
  147 CONTINUE
  149 CONTINUE
      IF(IAND(IOPTN,KCIQB) .EQ. 0) GO TO 200
C     ...TO PLOT THE STN CIRCLE...
      IF(IAND(IOPTN,KSQRB) .EQ. 0) GO TO 153
      C1STNCIRCLE = C1SQRCIR
      GO TO 158
  153 CONTINUE
      IF(IAND(IOPTN,KSTRB) .EQ. 0) GO TO 1532
C     ...TO TEST IF STAR IS DESIRED FOR STN CIRCLE...
      C1STNCIRCLE = C1STARCIR
      GO TO 158
 1532 CONTINUE
      IF(IAND(IOPTN,KOCB) .EQ. 0) GO TO 156
      C1STNCIRCLE = C1CLOSCIR
      GO TO 158
  156 C1STNCIRCLE = C1OPENCIR
  158 CONTINUE
      IF(IAND(IOPTN,KSMCB) .EQ. 0) GO TO 162
      ICIR = IDOTS + ISCDEL
      JCIR = JDOTS + JSCDEL
      XHGT = HGTSML
      GO TO 164
  162 CONTINUE
      ICIR = IDOTS + IMCDEL
      JCIR = JDOTS + JMCDEL
      XHGT = HGT
  164 CONTINUE
c
c     Start by checking for the out of bounds error:
c
      IF(IAND(IOPTN,KVECB) .EQ. 0) GO TO 175
      IF(NSSS) 173,175,173
  173 CONTINUE
      CALL TSTBND(IDOTS,JDOTS,IDDGD,NSSS,NWOK,IOPTN,IRET_WNB)
      IF(IRET_WNB .GT. 0) THEN
         print *,'TSTBND error # ',iret_wnb
         print *,'Drop out-of-bounds station ',C8NAMSTN(1:5)
         goto 800
      ENDIF
  175 CONTINUE    

      CALL PUTLAB(ICIR,JCIR,XHGT,C1STNCIRCLE,ANGLE,1,IPRIOR,0)
C
C     *     *     *     *     *     *     *     *     *     *     *
C     ...STEP(2) ... PREPARE TEMPERATURE FOR PLOT IN UPR LEFT...
  200 CONTINUE
      IF(IAND(IOPTN,KTTB) .EQ. 0) GO TO 300
      IF(IAND(IOPTN,KMVTB) .EQ. 0) GO TO 244
      IUL = IDOTS + IDELTK
      JUL = JDOTS + JDELTK
      IF(IAND(IOPTN,KSMCB) .EQ. 0) GO TO 246
      JUL = JUL - 2
      GO TO 246
  244 CONTINUE
      IF(IAND(IOPTN,KMVTR).EQ.0) GO TO 245
C     ...TO MOVE TMP TO UPR RT FOR FAX WINDS ALOFT CHART
      IUL=IDOTS-10
      JUL=JDOTS+8
      GO TO 246
  245 CONTINUE
      IUL = IDOTS + IDEL(2)
      JUL = JDOTS + JDEL(2)
  246 CONTINUE
      THGT = ZHGT
      IF(IAND(IOPTN,KMEDB) .EQ. 0) GO TO 255
C     ...COMES HERE TO CHG TO MEDIUM-SMALL CHAR SIZE...
      THGT = HGTMED
      IUL = IDOTS + IMEDEL
      JUL = JDOTS + JMEDEL
  255 CONTINUE
      IF(IAND(IOPTN,KDOWN) .NE. 0) JUL = JUL - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) IUL = IUL - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JUL = JUL + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) IUL = IUL + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JUL = JUL - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JUL = JUL + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JUL = JUL - 4
C ...      write(6,2554)thgt,IHTT(1:3),ANGLE
C ... 2554 format(1H ,'pltdat: thgt=',F6.2,' ihtt=',A3,' angle=',F6.0)
      CALL PUTLAB(IUL,JUL,THGT,IHTT,ANGLE,3,IPRIOR,0)
      IF(IAND(IOPTN,KCLTB) .EQ. 0) GO TO 266
C     ...WHICH TESTS FOR CALCULATED TEMPERATURE...
      IULC = IUL + ICTDEL
      JULC = JUL + JCTDEL
C     ...MOVE OVERSIZED BRACKET ON SIRS PLOTTED CHART
      IF(IAND(IOPTN,KSMLB).EQ.0) GO TO 263
      IULC = IULC - 13
      JULC = JULC - 4
  263 CONTINUE
      TCHGT = 10.0
      IF(IAND(IOPTN,KDOWN) .NE. 0) JULC = JULC - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) IULC = IULC - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JULC = JULC + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) IULC = IULC + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JULC = JULC - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JULC = JULC + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JULC = JULC - 4
      CALL PUTLAB(IULC,JULC,TCHGT,C1RTBRACK,ANGLE,1,IPRIOR,0)
  266 CONTINUE
C
C     *     *     *     *     *     *     *     *     *     *     *
C     ...STEP(3) ... TO PREPARE WIND DD FFF FOR PLOTTING...
  300 CONTINUE
      KB = IAND(IOPTN,KDDB)
C     PRINT *,' PLTDAT  KB FLAG IS ',KB
      IF(IAND(IOPTN,KDDB) .EQ. 0) GO TO 330
      ILL = IDOTS + IDEL(3)
      JLL = JDOTS + JDEL(3)
      IF(KEIL .NE. 14) GO TO 323
      ILL = IDOTS - 21
      JLL = JDOTS - 11
      ZHGTMP = ZHGT
      ZHGT = HGTMED
  323 CONTINUE
      IF(IAND(IOPTN,KMVDB) .EQ. 0) GO TO 325
C     ...MOVE DD PRINT TO AVOID OVERPLOTTING ANOTHER STN...
      ILL = ILL + 10
      JLL = JLL - 6
  325 CONTINUE
      IF(IAND(IOPTN,KDOWN) .NE. 0) JLL = JLL - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) ILL = ILL - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JLL = JLL + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) ILL = ILL + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JLL = JLL - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JLL = JLL + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JLL = JLL - 4
      CALL PUTLAB(ILL,JLL,ZHGT,ihdewdep,ANGLE,2,IPRIOR,0)
      IF(KEIL .EQ. 14) ZHGT = ZHGTMP
  330 CONTINUE
      IF(IAND(IOPTN,KFFFB) .EQ. 0) GO TO 400
      IF(KEIL .EQ. 14) GO TO 400
      IF(IAND(IOPTN,KTALB) .EQ. 0) GO TO 3305
      ILR = IDOTS + IDEL(4)
      JLR = JDOTS + JDEL(4) - 1
      IF(IAND(IOPTN,KDOWN) .NE. 0) JLR = JLR - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) ILR = ILR - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JLR = JLR + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) ILR = ILR + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JLR = JLR - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JLR = JLR + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JLR = JLR - 4
      CALL PUTLAB(ILR,JLR,HGTIT,IHFFF,ANGLE,3,IPRIOR,0)
      GO TO 333
 3305 CONTINUE
      IF(NSSS) 331,333,331
  331 CONTINUE
      ILR = IDOTS + IDEL(4)
      JLR = JDOTS + JDEL(4)
      IF(IAND(IOPTN,KDOWN) .NE. 0) JLR = JLR - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) ILR = ILR - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JLR = JLR + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) ILR = ILR + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JLR = JLR - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JLR = JLR + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JLR = JLR - 4
      CALL PUTLAB(ILR,JLR,ZHGT,IHFFF,ANGLE,3,IPRIOR,0)
  333 CONTINUE
C
C     *     *     *     *     *     *     *     *     *     *     *
C     ...STEP(4) ... TO PREPARE HEIGHT FOR PRINTING IN UPR RIGHT
C     ...   GIVEN IHZZZ IN (A4) FORMAT...
  400 CONTINUE
      IF(IAND(IOPTN,KZZZB) .EQ. 0) GO TO 500
      IUR = IDOTS + IDEL(5)
      JUR = JDOTS + JDEL(5)
      IF(IAND(IOPTN,KMVZB) .EQ. 0) GO TO 408
C     ... MOVE ZZZ PLOT UP 6 DOTS TO AVOID ANOTHER STN...
      JUR = JUR + 6
  408 CONTINUE
      IF(IAND(IOPTN,KMEDW).EQ.0) GO TO 409
C     ...COMES HERE TO CHANGE TO MEDIUM-SMALL CHAR SIZE
      ZHGT=HGTMED
  409 CONTINUE
      IF(IAND(IOPTN,KDOWN) .NE. 0) JUR = JUR - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) IUR = IUR - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JUR = JUR + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) IUR = IUR + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JUR = JUR - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JUR = JUR + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JUR = JUR - 4
      CALL PUTLAB(IUR,JUR,ZHGT,IHZZZ,ANGLE,4,IPRIOR,0)
      IF(IAND(IOPTN,KCLZB) .EQ. 0) GO TO 426
C     ...WHICH TESTS FOR CALCULATED HEIGHTS
      IURC=IUR+ICZDEL
      JURC=JUR+JCZDEL
      IF(IAND(IOPTN,KMEDW).EQ.0) GO TO 422
C     ...MOVE OVERSIZE BRACKET ON WINDS ALOFT CHART
      IURC=IURC-8
      JURC=JURC-2
      GO TO 423
  422 CONTINUE
      IF(IAND(IOPTN,KSMLB).EQ.0) GO TO 423
C     ...MOVE OVERSIZE BRACKET ON SIRS PLOTTED CHART
      IURC = IURC - 13
      JURC = JURC - 4
  423 CONTINUE
      TCHGT = 10.0
      JPRIOR=2
      IF(IAND(IOPTN,KDOWN) .NE. 0) JURC = JURC - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) IURC = IURC - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JURC = JURC + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) IURC = IURC + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JURC = JURC - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JURC = JURC + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JURC = JURC - 4
      CALL PUTLAB(IURC,JURC,TCHGT,C1RTBRACK,ANGLE,1,JPRIOR,0)
  426 CONTINUE
      GO TO 500
C
C     *     *     *     *     *     *     *     *     *     *     *
C     ...STEP(5) ... TO PLOT STATION NAME...
  500 CONTINUE
      IF(IAND(IOPTN,KNAMB) .EQ. 0) GO TO 600
      ILLL = IDOTS + IDEL(6)
      JLLL = JDOTS + JDEL(6)
      IF(IAND(IOPTN,KMVNB) .EQ. 0) GO TO 506
      JLLL = JLLL + JUPNAM
      ILLL = ILLL + IUPNAM
C     ...TO MOVE NAME UP TO JUST BELOW STN CIRCLE, ASSUMING NO DD NOR FF
      GO TO 508
  506 CONTINUE
      IF(IAND(IOPTN,KCLOS).EQ.0) GO TO 508
      ILLL = ILLL + IUPNM1
      JLLL=JLLL+JUPNM1
C     ...TO MOVE UP BOGUS 'B' TO JUST BELOW STN CIRCLE
  508 CONTINUE
      AMHGT = ZHGT
      IF(IAND(IOPTN,KSMNB) .EQ. 0) GO TO 514
C     ...TO USE SMALL CHAR SET FOR NAME NO MATTER WHAT ZHGT WAS...
      AMHGT = HGTSML
  514 CONTINUE
      NCHAR = LASTCH(C8NAMSTN(1:6))
      CALL PUTLAB(ILLL,JLLL,AMHGT,C8NAMSTN,ANGLE,NCHAR,IPRIOR,0)
C
C     *     *     *     *     *     *     *     *     *     *     *
C     ...STEP(6) ... PLOT WIND VECTOR IN PROPER DIRECTION ON MAP...
  600 CONTINUE
      IF(IAND(IOPTN,KVECB) .EQ. 0) GO TO 700
      IF(NSSS) 611,700,611
  611 CONTINUE
      CALL WNDBRK(IDOTS,JDOTS,IDDGD,NSSS,NWOK,IOPTN,IRET_WNB)
      IF(IRET_WNB .EQ. 0) THEN
        IF(NWOK .GT. 0) THEN
          GO TO 622
        ELSE
      PRINT  620
  620 FORMAT(1H , 10X, '***ERROR FROM WNDBRK.  UNABLE TO PLOT A WIND VEC
     1TOR * * * * *' )
          GO TO 700
        ENDIF
      ELSE
C       ... ERROR RETURN FROM WNDBRK ...
        IF(IRET_WNB .LT. 0) THEN
          WRITE(6,621)IRET_WNB,C8NAMSTN(1:6)
  621     FORMAT(1H ,'pltdat::wndbrk:FATAL ERROR ... RETURN CODE=',I4,
     1               ' FOR STN=',A6)
          GO TO 800
        ELSE
          WRITE(6,6214)IRET_WNB,C8NAMSTN(1:6)
 6214     FORMAT(1H ,'pltdat::wndbrk:WARNING ... RETURN CODE=',I4,
     1               ' FOR STN=',A6)
          GO TO 700
        ENDIF
      ENDIF
 
  622 CONTINUE
      IF(IAND(IOPTN,KDOVB) .EQ. 0) GO TO 700
      if(iddgd .LT. 0) then
        lsrnhemi = .true.
      else
        lsrnhemi = .false.
      endif
      magddgd = iabs(iddgd)
C     i8acc = norwndir
      c2dir(1:2) = norwndir(1:2)
C     PRINT *,' PLTDAT   ENTERING WNDIRDIG  c2dir is ',c2dir
      CALL WNDIRDIG(IDOTS,JDOTS,c2dir,magddgd,NSSS,IQUAD,LSRNHEMI)
C
C     *     *     *     *     *     *     *     *     *     *     *
  700 CONTINUE
C     ...STEP(7)...PLOT CALCULATED TMP ABOVE OBSERVED TMP
      IF(IAND(IOPTN,KMTMP).EQ.0) GO TO 800
      IUPL=IDOTS-35
      JUPL=JDOTS+17
      IF(IAND(IOPTN,KDOWN) .NE. 0) JUPL = JUPL - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) IUPL = IUPL - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JUPL = JUPL + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) IUPL = IUPL + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JUPL = JUPL - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JUPL = JUPL + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JUPL = JUPL - 4
      CALL PUTLAB(IUPL,JUPL,HGT,JHT1,ANGLE,3,IPRIOR,0)
      IUPL=IUPL+1
      JUPL=JUPL-9
      IF(IAND(IOPTN,KDOWN) .NE. 0) JUPL = JUPL - 12
      IF(IAND(IOPTN,IWEST) .NE. 0) IUPL = IUPL - 4
      IF(IAND(IOPTN,IWEST) .NE. 0) JUPL = JUPL + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) IUPL = IUPL + 4
      IF(IAND(IOPTN,IEAST) .NE. 0) JUPL = JUPL - 4
      IF(IAND(ioptn,jnorth) .NE. 0) JUPL = JUPL + 4
      IF(IAND(ioptn,jsouth) .NE. 0) JUPL = JUPL - 4
      CALL PUTLAB(IUPL,JUPL,10.0,C1RTBRACK,ANGLE,1,IPRIOR,0)
  800 CONTINUE
      RETURN
      END
