      SUBROUTINE PNANJI(INFILE,IDWORD,IDATE,IYR,IMO,IDAY,ITIME,IYMDH)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PNANJI      PACK NANJI ARRAY
C   PRGMMR: LILLY            ORG: W/NMC412   DATE: 93-05-05
C
C ABSTRACT: THIS PROGRAM PACKS THE COMMON ARRAY NANJI, WHICH IS
C   USED FOR A NUMBER OF PURPOSES DOWNSTREAM.  IT HOLDS DATE/TIME
C   INFORMATION, THE CURRENT FILE NAME, AND THE DUMP TIME, ALL
C   CAREFULLY FORMATTED.
C
C PROGRAM HISTORY LOG:
C   YY-MM-DD  ORIGINAL AUTHOR  UNKNOWN
C   89-04-25  STEVE LILLY  UPDATE DOCUMENTATION BLOCK
C   89-04-27  HENRICHSEN  CLEAN UP CODE AND SIMPLIFY.
C   93-05-05  LILLY CONVERT SUB. TO FORTRAN 77
C
C USAGE:    CALL PNANJI(INFILE,IDWORD,IDATE,IYR,IMO,IDAY,ITIME,IYMDH)
C
C   INPUT ARGUMENT LIST:
C     INFILE   - INPUT FILE NUMBER SUCH AS 19 FOR ADPUPA
C     IDWORD   - USE FOR FINDING THE DUMP TIME OF THIS FILE IN
C              - HUNDREDTHS OF HOURS
C     IDATE    - INTEGER   8 WORD ARRAY THAT CONTAINS FILE NAME
C              - AND DATE TIME INFORMATION OF INFILE.
C
C
C   OUTPUT ARGUMENT LIST:
C     IYR      - YEAR
C     IMO      - MONTH
C     IDAY     - DAY
C     ITIME    - SYNOPTIC TIME
C     IYMDH    - DATE/TIME PACKED, 8 BITS EACH PART
C     COMMON   - /TIMES / NANJI(12)
C     COMMON   - /TIMET / NANJK(2)
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      COMMON /TIMES / NANJI(12)
      COMMON /TIMET / NANJK(2)
C
      CHARACTER*12 IBCD
      CHARACTER*4  BLANKS(12)  /12*'    '/
C
      CHARACTER*1  PLUS        /'+'/
      CHARACTER*1  LGAC(4)
C
      INTEGER    JBCD(4)
      INTEGER    IDATE(8)
      INTEGER    ITEXT(2)
      INTEGER    MSKL2       /ZFFFF0000/
      INTEGER    MSKR2       /Z0000FFFF/
C
C
      EQUIVALENCE(LGAC(1),IACC)
      EQUIVALENCE(JBCD(1),IBCD)
C
C    FILL NANJI WITH BLANKS.
      CALL MOVCH(48,BLANKS,1,NANJI,1)
C
C     UNPACK AND CONVERT DATE TO INTEGER STARTING WITH WORD 3 OF
C     IDATE ARRAY. WHERE IDATE(3-4) CONTAIN YYMM DDHH IN HOLLERITH.
C
      CALL FFA2I(IDATE,9,2,4,JBCD,IERR)
      IYR = JBCD(1)
      IMO = JBCD(2)
      IDAY= JBCD(3)
      IHR = JBCD(4)
C
      ITIME = IHR * 100
      WRITE(6,20) ITIME,IYR,IMO,IDAY
  20  FORMAT(5X,'SYNOPTIC TIME IS ',I4,1HZ,'  YEAR ',I2,
     Z    '  MONTH ',I2,'  DAY ',I2)
      LGAC(1) = CHAR(IYR)
      LGAC(2) = CHAR(IMO)
      LGAC(3) = CHAR(IDAY)
      LGAC(4) = CHAR(IHR)
      IYMDH = IACC
C
C     WHICH PACKS DATE/TIME AS INTEGERS,  8-BITS FOR EACH PART.
C
      CALL MOVCH(8,IDATE,9,NANJI,1)
C
C     WHERE NANJI(1),(2) NOW CONTAIN DATE/TIME OF THIS FILE IN
C     EBCDIC, YYMM DDZZ, 2A4.
C
      CALL MOVCH(6,IDATE,1,NANJI,9)
C
C     NOW NANJI(3),(4) HOLDS FILE NAME SUCH AS 'ADPU', 'PA  '.
C
      CALL FFA2I(IDATE,17,4,1,IDMPTM,IERR)
C
C     IDMPTM HAS DUMP TIME OF THIS FILE IN HUNDREDTHS OF HOURS.
C
C
C      FILL ITEXT WITH BLANKS.
C
      CALL MOVCH(8,BLANKS,1,ITEXT,1)
C
      IACC = IAND(IDWORD,MSKL2)
      MQ = IAND(IDMPTM,MSKR2)
      IDWORD = IOR(IACC,MQ)
      IRELTM = IDMPTM - ITIME
      IF(IRELTM .GE. 0) GO TO 500
C
C     FALL THROUGH IF SYNOPTIC TIME WAS GREATER THAN DUMP TIME.
C
      IRELTM = 2400 + IRELTM
      IF(IRELTM .GE. 0) GO TO 500
      WRITE(6,40) IDATE(1),IDATE(2),INFILE
   40 FORMAT(1H0, 5X, 'ERROR IN DUMP TIME OF FILE = ', A4, A2, 3X,
     X 'ON FT', I2, /1H , 15X,'PROCEEDING WITH BLANKS IN DUMP TIME')
      GO TO 600
C
  500 CONTINUE
      IRELHR = IRELTM / 100
      MINUTE = MOD(IRELTM,100)
      MINUTE = (FLOAT(MINUTE) * 0.60) + 0.50
      NCHAR = 2
      CALL INT2CH(IRELHR,IBCD,NCHAR,'A999')
      CALL MOVCH(2,IBCD,1,ITEXT,1)
      CALL MOVCH(1,PLUS,1,ITEXT,3)
      CALL INT2CH(MINUTE,IBCD,NCHAR,'A999')
      CALL MOVCH(2,IBCD,1,ITEXT,4)
  600 CONTINUE
      CALL MOVCH(8,ITEXT,1,NANJI,17)
C
C     GIVING NANJI(5),(6) THE RELATIVE DUMP TIME IN 5 CHARACTERS,
C     SUCH AS  '10+2', '5   '    (A4,A1)
C
      IF(INFILE.NE.19) GO TO 700
      NANJK(1)=NANJI(5)
      NANJK(2)=NANJI(6)
  700 CONTINUE
C
      NANJI(7) = IYMDH
      NANJI(8) = 0
C
C     SO NANJI(7) HAS DATE/TIME PACKED, 8 BITS EACH PART.
C
      RETURN
      END
