      SUBROUTINE RDAFIL(INFILE,NOLVSR,LVLSAL,KRUN,IOPCLO,
     X                  LCKOUT,IOPENQ,IERROR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    RDAFIL           READING THE DATA FIELD
C   PRGMMR: LILLY            ORG: W/NMC412   DATE: 93-05-11
C
C ABSTRACT: PLACES DATA FIELD INTO TEMPORARY STORAGE, AND
C   WRITES STRIP TITLE (IE; MAP BACKGROUND, DATE/TIME ETC).
C
C PROGRAM HISTORY LOG:
C   YY-MM-DD  ORIGINAL AUTHOR  UNKNOWN
C   89-04-25  STEVE LILLY  DOCUMENT
C   93-05-11  LILLY CONVERT SUB. TO FORTRAN 77
C
C USAGE:    CALL RDAFIL(INFILE,NOLVSR,LVLSAL,KRUN,IOPCLO,LCKOUT,
C           &           IOPENQ,IERROR)
C
C   INPUT ARGUMENT LIST:
C     INFILE   - INPUT FILE NUMBER SUCH AS 19 FOR ADPUPA
C     NOLVSR   - NO. OF MANDATORY LEVELS REQUESTED
C     LVLSAL   - ARRAY OF ALL LEVELS REQUESTED (BY INDEX NO.)
C     KRUN     - FOR SETTING OPTIONS BY RUN TYPE, SUCH AS =11 TROPIC
C     LCKOUT   - TRUE. IF CHECKOUT RUN FOR MORE PRINT. LOGICAL  
C     IOPENQ   - INDICATES WHETHER GRANPA FILE IS OPEN
C
C   OUTPUT ARGUMENT LIST:
C     IOPCLO   - TO OPEN/CLOSE GRANPA FILE
C              - =1, CLOSE GRANPA AFTER PROCESSING THIS INP FILE
C              - =2, OPEN GRANPA FILE THEN PROCESS THIS INP FILE
C              - =4, CLOSE GRANPA IMMEDIATELY
C     IERROR   - =0, NORMAL EXIT
C              - =1, RETURN FROM REDADP WITH ERROR
C     COMMON /BOBIN / LOCT(256),IDTBL(1539)
C     COMMON /TIMES / NANJI(12)
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      COMMON /BOBIN / LOCT(256),IDTBL(1539)
      COMMON /TIMES / NANJI(12)
C
      CHARACTER*8 GRANPA
      DATA        GRANPA            /'GRANPA  '/
C
      INTEGER    LVLSAL(11)
      INTEGER    MESSG(10)
C
      LOGICAL    LCKOUT
C
      RETURN
      END
