      SUBROUTINE RDCAR3(IERR1)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    RDCAR3      SPECIALIZED CARD READER '3'
C   PRGMMR: LIN              ORG: W/NMC412   DATE: 97-02-07
C
C ABSTRACT: THIS SPECIALIZED CARD READER IS FOR READING CARD '3'
C   FORMAT WHICH MUST HAVE A '3' IN CARD COLUMN 1, FOLLOWED BY
C   LOCATION ADJUSTMENTS DELTAX AND DELTAY.
C
C PROGRAM HISTORY LOG:
C   97-02-07  ORIGINAL AUTHOR   LUKE LIN
C
C USAGE:    CALL RDCAR3(IERR1)
C
C   INPUT ARGUMENT LIST:
C
C   OUTPUT ARGUMENT LIST:
C     IERR1    - = 0 IF NORMAL RETURN
C              - = -1  IF IT ENCOUNTERED A '9' IN COLUMN 1
C              - = +1  IF ERROR EXIT
C                    NVRBLS.  SEE DIMENSION STATEMENT.
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      COMMON /ADJUST/  IXADJ, IYADJ
C
      CHARACTER*1 LCARD(80)
      CHARACTER*80 JCARD
      EQUIVALENCE (LCARD(1),JCARD)
      CHARACTER*1 LIT3
      DATA        LIT3    /'3'/
      CHARACTER*1 LIT9
      DATA        LIT9    /'9'/
C
C     INTEGER    ICARD(10)
C
C     ...START...
      PRINT *,' *** IN THE RECAR3'
      IERR1 = 0
      IXADJ = 0
      IYADJ = 0
C
      READ (15,122)LCARD
  122 FORMAT(80A1)
      PRINT  124,LCARD
  124 FORMAT(1H , 80A1)
      IF(LCARD(1) .EQ. LIT3) GO TO 135
      IF(LCARD(1) .NE. LIT9) GO TO 128
C     ...OTHERWISE, IT WAS A '9' CARD, SO NO MORE CARDS TO READ
      PRINT  126
  126 FORMAT(1H , 10X, 'SUBR RDCAR3 READ A 9 CARD AND RETURNED WITHOUT D
     1OING ANYTHING')
      IERR1 = -1
      GO TO 999
C
  128 CONTINUE
      PRINT  130
  130 FORMAT(1H , 10X, 'CARD3 DOES NOT BEGIN WITH A 3 IN COLUMN1 ')
      GO TO 900
C
  135 CONTINUE
      PRINT *,' READ CARD #3'
      READ(JCARD,140)IXADJ,IYADJ
  140 FORMAT(11X,I6, 7X,I6)
      PRINT *,' IXADJ=',IXADJ,' IYADJ=',IYADJ
      GO TO 999
  900 CONTINUE
      PRINT  905
  905 FORMAT(1H , ' * * * * ERROR RETURN FROM SUB RDCAR3 WHILE ',
     1'READING CONTROLLING DATA CARD2 * * * * ')
      IERR1 = 1
      GO TO 999
  999 CONTINUE
      RETURN
      END
