      SUBROUTINE RDCAR2(NVRBLS,DHMBS,MXMBS,IVALRA,IERR1,
     1                  KNAM,NAME,KNUMB,NUMBS)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    RDCAR2      SPECIALIZED CARD READER '2'
C   PRGMMR: LILLY            ORG: W/NMC412   DATE: 93-05-06
C
C ABSTRACT: THIS SPECIALIZED CARD READER IS FOR READING CARD '2'
C   FORMAT WHICH MUST HAVE A '2' IN CARD COLUMN 1, FOLLOWED BY MB
C   LEVEL ...NAMES, FOR EXAMPLE 850MB, 700MB, 500MB;
C
C PROGRAM HISTORY LOG:
C   YY-MM-DD  ORIGINAL AUTHOR   UNKNOWN
C   88-07-25  GLORIA DENT  PUT IN DOCUMENTATION BLOCK
C   89-04-18  STEVE LILLY  UPDATE DOCUMENTATION BLOCK
C   93-05-06  LILLY CONVERT SUB. TO FORTRAN 77
C
C USAGE:    CALL RDCAR2(NVRBLS,DHMBS,MXMBS,IVALRA,IERR1,
C          &            KNAM,NAME,KNUMB,NUMBS)
C
C   INPUT ARGUMENT LIST:
C     NVRBLS   - NO. OF LEVEL NAMES ON THE CARD
C     DHMBS    - LOOKUP TABLE FOR MATCHING THE FOUND NAME AGAINST.
C              - CONTAINS MB NAMES IN REAL*8 ARRAY
C     MXMBS    - DIMENSION OF DHMBS TABLE
C
C   OUTPUT ARGUMENT LIST:
C     IVALRA   - THE SUBSCRIPTS OF THE MATCHING ITEM IN DHMBS TABLE
C              - IS RETURNED IN IVALRA,DIMENSIONED NVRBL
C     KNAM     - DEFINES AS SCRATCH ARRAY AS A FUNCTION OF NVRBLS
C     NAME     - DEFINES AS SCRATCH ARRAY AS A FUNCTION OF NVRBLS
C     KNUMB    - DEFINES AS SCRATCH ARRAY AS A FUNCTION OF NVRBLS
C     NUMBS    - DEFINES AS SCRATCH ARRAY AS A FUNCTION OF NVRBLS
C     IERR1    - = 0 IF NORMAL RETURN
C              - = -1  IF IT ENCOUNTERED A '9' IN COLUMN 1
C              - = +1  IF ERROR EXIT
C                    NVRBLS.  SEE DIMENSION STATEMENT.
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      CHARACTER*1 LCARD(80)
      CHARACTER*80 JCARD
      EQUIVALENCE (LCARD(1),JCARD)
      CHARACTER*1 LIT2
      DATA        LIT2  /'2'/
      CHARACTER*1 LIT9
      DATA        LIT9    /'9'/
C
      CHARACTER*8  DBLWRD
      CHARACTER*8  DHMBS(MXMBS)
C
C     INTEGER    ICARD(10)
      INTEGER    INGLES(2)
      INTEGER    IVALRA(NVRBLS)
      INTEGER    KNAM(NVRBLS)
      CHARACTER*12  NAME(NVRBLS)
      INTEGER    KNUMB(NVRBLS)
      CHARACTER*12  NUMBS(NVRBLS)
C
C     EQUIVALENCE(ICARD(1),LCARD(1))
C     EQUIVALENCE(DBLWRD,INGLES(1))
C
C     ...START...
      IERR1 = 0
      IF(NVRBLS .GT. 0) GO TO 105
      PRINT  102,NVRBLS
  102 FORMAT(1H , 10X, 'GIVEN ARGUMENT FOR NO. OF VRBLS EXPECTED IS OUT
     1OF RANGE.  NVRBLS = HEX', Z8)
      GO TO 900
  105 CONTINUE
      DO  110  I = 1,NVRBLS
      IVALRA(I) = 0
  110 CONTINUE
      MXITM = NVRBLS
      READ (15,122)LCARD
  122 FORMAT(80A1)
      PRINT  124,LCARD
  124 FORMAT(1H , 80A1)
      IF(LCARD(1) .EQ. LIT2) GO TO 135
      IF(LCARD(1) .NE. LIT9) GO TO 128
C     ...OTHERWISE, IT WAS A '9' CARD, SO NO MORE CARDS TO READ
      PRINT  126
  126 FORMAT(1H , 10X, 'SUBR RDCAR2 READ A 9 CARD AND RETURNED WITHOUT D
     1OING ANYTHING')
      IERR1 = -1
      GO TO 999
C
  128 CONTINUE
      PRINT  130
  130 FORMAT(1H , 10X, 'CARD2 DOES NOT BEGIN WITH A 2 IN COLUMN1 ')
      GO TO 900
C
  135 CONTINUE
      ITH = 2
      CALL SEPCAR(JCARD,ITH,MXITM,ITEM,KNAM,NAME,KNUMB,NUMBS,IERR)
      IF(IERR .EQ. 0) GO TO 200
  137 CONTINUE
      PRINT  138
  138 FORMAT(1H , 10X, 'SUB SEPCAR COMPLAINED ABOUT FORMAT OF CAR
     1D 2  WHEN CALLED BY RDCAR2' )
      GO TO 900
  200 CONTINUE
      IF(ITEM .LE. 0) GO TO 137
C     ...THE FOUND VRBL NAMES ARE IN NAME(1,X),(2,X),(3,X)
C     ...   AND ITEM HAS NO. OF ITEMS FOUND
C     ...   AND NVRBLS HAS NO. OF ITEMS EXPECTED.
      IF(ITEM .GE. NVRBLS) GO TO 266
      PRINT  262, ITEM,NVRBLS
  262 FORMAT(1H , 10X, 'ITEM COUNT OF FOUND VRBLS = ', I5, 2X,
     1       'WHICH IS LESS THAN THE EXPECTED ', I5)
      GO TO 900
  266 CONTINUE
C     ...WHAT I HAVE NOW IS '100MB', '70MB',  ETC.
C     ...   WHAT I WANT IS A TABLE OF ILVLT
      DO  377 IA = 1,NVRBLS
          DBLWRD(1:8) = NAME(IA)(1:8)
C???      INGLES(1) = NAME(1,IA)
C???      INGLES(2) = NAME(2,IA)
          CALL GBYTES(DBLWRD,INGLES,0,32,0,2)
          DO  333  IB = 1,MXMBS
              ILVLT = IB
              IF(DBLWRD .EQ. DHMBS(IB)) GO TO 350
  333     CONTINUE
C          ...SINCE IT FELL THRU HERE WITHOUT FINDING A MATCH, ERROR
C     ...   BECAUSE EACH LEVEL NAME FOUND ON CARD SHOULD HAVE A MATCH
C     ...   IN THE DHMBS TABLE.
          PRINT  342, INGLES(1), INGLES(2)
  342 FORMAT(1H , 10X, 'CANNOT FIND A MATCH IN THE DHMBS TABLE FOR A LEV
     1EL NAME FOUND ON CARD2 .   LOOK FOR MISSPELLING IN ...',2A4)
          GO TO 900
  350     CONTINUE
          IVALRA(IA) = ILVLT
  377 CONTINUE
C     ...WHEN IT FALLS THRU HERE  ILVLT HAS BEEN FOUND FOR EVERY MB LEV
C     ...   NAMED ON CARD2.
C     ...MAYBE A SORT AND LOOK FOR DUPLICATES CAN BE INSERTED IN HERE
      GO TO 999
  900 CONTINUE
      PRINT  905
  905 FORMAT(1H , ' * * * * ERROR RETURN FROM SUB RDCAR2 WHILE ',
     1'READING CONTROLLING DATA CARD2 * * * * ')
      IERR1 = 1
      GO TO 999
  999 CONTINUE
      RETURN
      END
