      SUBROUTINE TITLEN(IPT,JPT,IERR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    TITLEN      OUTPUTS LABEL FOR 1000-250MB THICKNESS.
C   PRGMMR: LIN              ORG: W/NMC412   DATE: 970-2-10
C
C ABSTRACT: PLACES A DESCRIPTIVE TITLE ON THE 1000-250MB THICKNESS.
C   UNPACKS THE TIMES OUT OF WORDS (1-2) OF NANJI AND BUILDS A TITLE
C   FOR CALL TO PUTLAB.
C
C PROGRAM HISTORY LOG:
C   YY-MM-DD  ORIGINAL AUTHOR UNKNOWN
C   89-04-06  HENRICHSEN REPLACED ENCODE AND DECODE WITH FFA2I,
C                        FFI2A AND MOVCH. DOCUMENT CODE.
C   93-05-08  LILLY CONVERT SUBROUTINE TO FORTRAN 77
C   97-02-10  LIN   CONVERT SUBROUTINE TO CFT     77
C
C USAGE:    CALL TITLEN(IPT,JPT,IERR)
C
C   INPUT ARGUMENT LIST:
C     IPT      - I POSITION IN DOTS OF TITLE.
C     JPT      - J POSITION IN DOTS OF TITLE.
C     COMMON   - /TIMES/ NANJI(12)
C              - CONTAINS YYMMDDHH IN WORDS (1-2) IN HOLLERTH.
C              - CONTAINS DUMP TIME IN WORDS (5-6) IN HOLLERTH.
C
C   OUTPUT ARGUMENT LIST:
C     IERR     - ERROR RETURN
C              - =0 NORMAL RETURN
C              - =1 ERROR FROM SUB DAYOWK, NO TITLE MADE.
C
C
C REMARKS: FUTHER DOCUMENTATION IS NEEDED.
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
      COMMON /ADJUST/  IXADJ, IYADJ
C
      COMMON /TIMES/ NANJI(12)
      COMMON / DATE / NYR,NMO,NDA,NHR,CDUMP
      CHARACTER*8  CDUMP

C
C     ...COMMON TIMES IS COMMON TO MAIN(PLOTOB) AND REDADP.
C
      CHARACTER*8  CWORK
      CHARACTER*4  LAB(7) 
      DATA         LAB         /'    ','    ','HHZ ','THU ','06 A',
     1                        'PR 1','989 '/
      CHARACTER*4  MONAM(12)
      DATA         MONAM       /'JAN ','FEB ','MAR ','APR ','MAY ',
     1                        'JUN ','JUL ','AUG ','SEP ','OCT ',
     2                        'NOV ','DEC '/
      CHARACTER*4 IOPCIR
C???  DATA      IOPCIR       /Z'4D000000'/
C     DATA      IOPCIR       /Z'28000000'/
C     CHARACTER*4 ISRCIR
C???  DATA      ISRCIR       /Z'E0000000'/
C     DATA      ISRCIR       /Z'5C000000'/
      INTEGER   IWORK(4)
      CHARACTER*1 TEXT(8)
      INTEGER     ITEXT
      EQUIVALENCE (TEXT(1),ITEXT)
      INTEGER   IPRIOR(2)
      CHARACTER*4   IHDAYW
C
C     *     *     *     *     *     *     *     *     *     *     *
C
      IERR = 0
      IPRIOR(1) = 0
      IPRIOR(2) = 1
C
C     CONVERT TIMES TO INTEGER
C
C     PRINT *,' ...IN TITLEN'
C     PRINT 214, NANJI(1),NANJI(2)
C 214 FORMAT (1X, Z16,4X,Z16)
C     PRINT 215, NANJI(1),NANJI(2)
C 215 FORMAT (1X, A8,12X,A8 )
C     ITEXT = NANJI(1)
C     CALL ASC2INT(2,TEXT(5),IWORK(1),IERR)
C     CALL ASC2INT(2,TEXT(7),IWORK(2),IERR)
C     ITEXT = NANJI(2)
C     CALL ASC2INT(2,TEXT(5),IWORK(3),IERR)
C     CALL ASC2INT(2,TEXT(7),IWORK(4),IERR)
C     CALL FFA2I(NANJI,1,2,4,IWORK,IERR)
C     IYR = IWORK(1) + 1900
C     IF(IYR .LT. 1950)  IYR = IYR + 100
C     IMO = IWORK(2)
C     IDA = IWORK(3)
C     IHR = IWORK(4)
      IYR =  NYR     + 1900
      IF(IYR .LT. 1950)  IYR = IYR + 100
      IMO =  NMO
      IDA =  NDA
      IHR =  NHR
      PRINT *, ' IYR=',IYR,' IMO=',IMO,' IDA=',IDA,' IHR=',IHR

      PRINT *, ' IYR=',IYR,' IMO=',IMO,' IDA=',IDA,' IHR=',IHR
      CALL DAYOWK(IDA,IMO,IYR,IDAYWK,IHDAYW)
      IF (IDAYWK.NE.0) GO TO 40
      IERR = 1
      GO TO 100
   40 CONTINUE
C
C       MOVE HOUR INTO BYTES 9-10 OF TITLE ARRAY
C
      CALL INT2CH(IHR,CWORK,2,'L999')
       LAB(3)(1:2) = CWORK(1:2)
C      CALL MOVCH(2,CWORK,1,TITLE,9)
C
C       MOVE DAY OF WEEK INTO BYTES 13-16 OF TITLE ARRAY
C
       CALL MOVCH(4,IHDAYW,1,LAB,13)
C
C       MOVE DAY OF MONTH INTO BYTES 17-18 OF TITLE ARRAY
C
      CALL INT2CH(NDA,CWORK,4,'L999')
       LAB(5)(1:2)=CWORK(3:4)
C      CALL MOVCH(2,CWORK,1,TITLE,17)
C
C       MOVE MONTH INTO BYTES 20-23 OF TITLE ARRAY
C
       CALL MOVCH(4,MONAM(IMO),1,TITLE,20)
C
C     CONVERT YEAR TO HOLLERTH
C
C??   CALL FFI2A(IWORK,1,4,1,IYR)
      CALL INT2CH(IYR,TEXT,4,'L999')
      CALL MOVCH(4,TEXT,1,LAB,24)
C
C
C       MOVE YEAR INTO BYTES 24-27 OF TITLE ARRAY
C
C??    CALL MOVCH(4,IWORK,1,TITLE,24)
C      CALL MOVCH(4,TEXT,1,TITLE,24)
C
C
C       MOVE DUMP TIME INTO FIRST 8 BYTES OF LAB ARRAY
C
C      CALL MOVCH(8,NANJ1,17,LAB,1)
C
C       MOVE HOUR INTO BYTES 9-10 OF LAB ARRAY
C
C      CALL MOVCH(2,NANJ1,7,LAB,9)
C
C       MOVE DAY OF WEEK INTO BYTES 13-16 OF LAB ARRAY
C
CC     CALL MOVCH(4,IHDAYW,1,LAB,13)
C
C       MOVE DAY OF MONTH INTO BYTES 17-18 OF LAB ARRAY
C
C      CALL MOVCH(2,NANJ1,5,LAB,17)
C
C       MOVE MONTH INTO BYTES 20-23 OF LAB ARRAY
C
C      CALL MOVCH(4,MONAM(IMO),1,LAB,20)
C
C     CONVERT YEAR TO HOLLERTH
C
C??   CALL FFI2A(IWORK,1,4,1,IYR)
C     CALL INT2CH(IYR,TEXT,4,'L999')
C
C       MOVE YEAR INTO BYTES 24-27 OF LAB ARRAY
C
C????  CALL MOVCH(4,IWORK,1,LAB,24)
C      CALL MOVCH(4,TEXT,1,LAB,24)
      IPT0 = IPT + IXADJ
      JPT0 = JPT + IYADJ
      I = IPT + IXADJ
      HEIGHT = 1.0
      CALL PUTLAB(IPT0,JPT0,HEIGHT,'   SATELLITE   RADIOSONDE',
     1            0.0,25,IPRIOR,1)
      IPT1 = IPT0 + 12
      TEXT(1) = CHAR(92)
      IPRIOR(1) = 0
      IPRIOR(2) = 2
C     .....char(92)= hex5c which is the 'star'
      CALL PUTLAB(IPT1,JPT0,HEIGHT,TEXT,0.0,1,IPRIOR,1)
      IPT2 = IPT1 + 120
      TEXT(1) = CHAR(40)
C     .....char(40)= hex28 which is the 'open circle'
      CALL PUTLAB(IPT2,JPT0,HEIGHT,IOPCIR,0.0,1,2,1)
      IPT3 = I
      IPT3 = IPT3 + 30
      JPT3 = JPT0 + 15
      IPRIOR(2) = 1
      CALL PUTLAB(IPT3,JPT3,HEIGHT,LAB(3),0.0,19,IPRIOR,1)
      IPT4 = I
      JPT4 = JPT0 + 15
      CALL PUTLAB(IPT4,JPT4,HEIGHT,'1000-250MB THICKNESS ',0.0,21,
     1            IPRIOR,1)
      IPT5 = IPT4 + 210
      CALL PUTLAB(IPT5,JPT4,HEIGHT,LAB(1),0.0,8,IPRIOR,1)
      IPT6 = I
      JPT6 = JPT0 + 15
      CALL PUTLAB(IPT6,JPT6,HEIGHT,' NATIONAL WEATHER SERVICE',0.0,25,
     1            IPRIOR,1)
100   RETURN
      END
