      SUBROUTINE TITLHC(IPT,JPT,ILVLT)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    TITLHC      PUT HGT CHANGE LEGEND    
C   PRGMMR: LIN              ORG: W/NMC412   DATE: 97-02-11
C
C ABSTRACT: PLOTS HGT CHANGE LEGEND ON ALL THE MAPS
C
C PROGRAM HISTORY LOG:
C   97-02-10  ORIGINAL AUTHOR  LUKE LIN
C
C USAGE:    CALL TITLHC(IPT,JPT)
C
C   INPUT ARGUMENT LIST:
C     IPT      - THE I POSITION IN DOTS ON THE VARIAN
C     JPT      - THE J POSITION IN DOTS ON THE VARIAN
C
C   OUTPUT ARGUMENT LIST:
C     COMMON   - /TIMET/NANJK(2)
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  CRAY
C
C$$$
C
      COMMON /ADJUST/  IXADJ, IYADJ
C
      COMMON/TIMET/NANJK(2)
C     ...COMMON TIMET IS COMMON TO MAIN(PLOTOB) AND REDADP
      INTEGER   IPRIOR(2)
      INTEGER   ILVLT
C
      XHT=1.0
      YHT=11.0
      IPRIOR(1)=0
      IPRIOR(2)=2
      IPT0 = IPT + IXADJ
      JPT0 = JPT + IYADJ
      IF (ILVLT.LT.5) THEN
      CALL PUTLAB(IPT0,JPT0,XHT,'HGT CHANGE IN METERS',0.0,20,IPRIOR,0)
      ELSE 
      CALL PUTLAB(IPT0,JPT0,XHT,'HGT CHANGE IN DECAMETERS',0.0,
     1            24,IPRIOR,0)
      ENDIF
      RETURN
      END
