      SUBROUTINE RDOBVT(JLVT,IERROR)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM: RDOBVT         READ OBSERVATION STATION FILE
C   AUTHOR: LUKE LIN         ORG: WD41        DATE: 97-01-22
C
C ABSTRACT: READ OBSERVATION STATION FILE
C
C HISTORY LOG:
C   97-01-22  LUKE LIN
C
C INPUT ARGUMENTS:
C     LABEL    -  INTEGER*12 6-WORD OFFICE 84 ID
C     LUGRBIX  -  ONE DEGREE GRIB INDEX FILE UNIT
C
C OUTPUT ARGEMENTS:
C    IERROR   -- RETURN STATUS
C              - =0, NORMAL;
C
C USAGE:
C
C   OUTPUT FILES:
C     FT06F001 -   PRINT OUTPUT (STANDARD FORTRAN OUTPUT FILE)
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: CFT-77
C   MACHINE:  CRAY
C
C$$$
C
C     OPEN FILES AND OBTAIN LOCATER TABLES FOR VARIOUS RUNS
C
C     KRUN1=1  RADAT FILES= ANL1
C     KRUN1=2  OPNL FILES=  ANL,F00,F12,F24,F36,F48
C     KRUN1=3  OPNL OVER 48HR FILES=  F60,F72,F84,F96
C     KRUN1=4  FINAL FILES=ANL ANL5 GF12 GF24
C     KRUN1=5  LFM FILES=  FMANL,FM00,FM12,FM24
C     KRUN1=6  PFAX FILES  F24
C     KRUN1=7  BACKUP PFAX FILES  F36
C     KRUN1=8  PLOTFAX (1 DOT) FILES  ANL1
C     KRUN1=9  PLOTFAX (2 DOT) FILES  FMANL
C     KRUN1=10 SIRSPLOT FILES= GF12
C
C     (7)  IOPN=             0  OPNL RUN
C                            1  CHECK OUT RUN
C                            2  EXTRA PRINT RUN
C
C
      COMMON /CPOB/ CPOBFG,ITAPOB,ILVLT,KRUN,IOPTRA(2)
      LOGICAL        CPOBFG
C
      DIMENSION XTRA(2,1024)
C
C     INTEGER LOBTAP
C     DIMENSION IOPTRA(2)
C
C     DIMENSION  LVL(2,18)
C
      INTEGER      DATIM(8)
      INTEGER      IDATG(4)
      INTEGER      JLVT
C
C     DATA LOBTAP/54/
C     DATA IOPTRA/0,0/
      DATA NOPTNS/2/
C
C     DATA LVL/4HSFC ,0,        4H1000,Z00271081,4H850 ,Z014C0882,
C    1         4H700 ,Z01117082,4H500 ,Z00C35082,4H400 ,Z009C4082,
C    2         4H300 ,Z00753082,4H250 ,Z0061A882,4H200 ,Z004E2082,
C    3         4H150 ,Z003A9882,4H100 ,Z00271082,4H070 ,Z01117083,
C    4         4H050 ,Z00C35083,4H030 ,Z00753083,4H020 ,Z004E2083,
C    5         4H010 ,Z00271083,4HTROP,0,        4HSIGL,0/
C
C      . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
      IERROR = 0
C     .... FOLLOWING IS A SAMPLE
      IF (JLVT.EQ.1000) THEN
          ILVLT=2
      ELSE IF (JLVT.EQ. 850) THEN
          ILVLT=3
      ELSE IF (JLVT.EQ. 700) THEN
          ILVLT=4
      ELSE IF (JLVT.EQ. 500) THEN
          ILVLT=5
      ELSE IF (JLVT.EQ. 400) THEN
          ILVLT=6
      ELSE IF (JLVT.EQ. 300) THEN
          ILVLT=7
      ELSE IF (JLVT.EQ. 250) THEN
          ILVLT=8
      ELSE IF (JLVT.EQ. 200) THEN
          ILVLT=9
      ELSE IF (JLVT.EQ. 150) THEN
          ILVLT=10
      ELSE IF (JLVT.EQ. 100) THEN
          ILVLT=11
      ENDIF
C
      ITAPOB = 54
      KRUN = 11
C     .... FOR TROPIC 1 
      IOPTRA(1) = 1
C     .... by passing the time check
      IOPTRA(2) = 1
C     .... by passing the background check
C
C     GET PLOTTED DATA FROM TAPE54
C
CADDED BY KUMAR BEGIN
C
           CALL W3LOCDAT(DATIM)
C
             IYEAR = DATIM(1)
C             KDAYR = DATIM(3)
             MONTH = DATIM(2)
             IDAY  = DATIM(3)
             IHOUR = DATIM(5)
C
CADDED BY KUMAR END
C 
             IF (IHOUR .LE. 11) THEN
                 IHOUR = 0
             ELSE
                 IHOUR = 12
             ENDIF
C
C
           IDATG(1) = IYEAR
           IDATG(2) = MONTH
           IDATG(3) = IDAY 
           IDATG(4) = IHOUR
C
CADDED BY KUMAR BEGIN
C
      PRINT*, 'IYEAR,MONTH,IDAY,IHOUR   ', IYEAR,MONTH,IDAY,IHOUR
C
CADDED BY KUMAR END
C
      PRINT *, ' ILVLT=',ILVLT
      PRINT *, ' KRUN=',KRUN
      CALL COPYOB(ITAPOB,XTRA,ILVLT,KRUN,IDATG,IOPTRA,NOPTNS,
     XKOUNT,IERROR)
      PRINT 901,KOUNT,IERROR
 901  FORMAT(1H0,'LABEL ARRAY ITEMS-KOUNT=  ',I5,
     X'  COPYOB RETURN-IERROR=  ',I5,'  GO ON ANYWAY')
 902  CONTINUE
C
      RETURN
      END
