set -x
cp jgfs_post_anl.ecf jgfs_post_f000.ecf
cp jgfs_post_anl.ecf jgfs_post_f001.ecf
cp jgfs_post_anl.ecf jgfs_post_f002.ecf
cp jgfs_post_anl.ecf jgfs_post_f003.ecf
cp jgfs_post_anl.ecf jgfs_post_f004.ecf
cp jgfs_post_anl.ecf jgfs_post_f005.ecf
cp jgfs_post_anl.ecf jgfs_post_f006.ecf
cp jgfs_post_anl.ecf jgfs_post_f007.ecf
cp jgfs_post_anl.ecf jgfs_post_f008.ecf
cp jgfs_post_anl.ecf jgfs_post_f009.ecf
cp jgfs_post_anl.ecf jgfs_post_f010.ecf
cp jgfs_post_anl.ecf jgfs_post_f011.ecf
cp jgfs_post_anl.ecf jgfs_post_f012.ecf
cp jgfs_post_anl.ecf jgfs_post_f013.ecf
cp jgfs_post_anl.ecf jgfs_post_f014.ecf
cp jgfs_post_anl.ecf jgfs_post_f015.ecf
cp jgfs_post_anl.ecf jgfs_post_f016.ecf
cp jgfs_post_anl.ecf jgfs_post_f017.ecf
cp jgfs_post_anl.ecf jgfs_post_f018.ecf
cp jgfs_post_anl.ecf jgfs_post_f019.ecf
cp jgfs_post_anl.ecf jgfs_post_f020.ecf
cp jgfs_post_anl.ecf jgfs_post_f021.ecf
cp jgfs_post_anl.ecf jgfs_post_f022.ecf
cp jgfs_post_anl.ecf jgfs_post_f023.ecf
cp jgfs_post_anl.ecf jgfs_post_f024.ecf
cp jgfs_post_anl.ecf jgfs_post_f025.ecf
cp jgfs_post_anl.ecf jgfs_post_f026.ecf
cp jgfs_post_anl.ecf jgfs_post_f027.ecf
cp jgfs_post_anl.ecf jgfs_post_f028.ecf
cp jgfs_post_anl.ecf jgfs_post_f029.ecf
cp jgfs_post_anl.ecf jgfs_post_f030.ecf
cp jgfs_post_anl.ecf jgfs_post_f031.ecf
cp jgfs_post_anl.ecf jgfs_post_f032.ecf
cp jgfs_post_anl.ecf jgfs_post_f033.ecf
cp jgfs_post_anl.ecf jgfs_post_f034.ecf
cp jgfs_post_anl.ecf jgfs_post_f035.ecf
cp jgfs_post_anl.ecf jgfs_post_f036.ecf
cp jgfs_post_anl.ecf jgfs_post_f037.ecf
cp jgfs_post_anl.ecf jgfs_post_f038.ecf
cp jgfs_post_anl.ecf jgfs_post_f039.ecf
cp jgfs_post_anl.ecf jgfs_post_f040.ecf
cp jgfs_post_anl.ecf jgfs_post_f041.ecf
cp jgfs_post_anl.ecf jgfs_post_f042.ecf
cp jgfs_post_anl.ecf jgfs_post_f043.ecf
cp jgfs_post_anl.ecf jgfs_post_f044.ecf
cp jgfs_post_anl.ecf jgfs_post_f045.ecf
cp jgfs_post_anl.ecf jgfs_post_f046.ecf
cp jgfs_post_anl.ecf jgfs_post_f047.ecf
cp jgfs_post_anl.ecf jgfs_post_f048.ecf
cp jgfs_post_anl.ecf jgfs_post_f049.ecf
cp jgfs_post_anl.ecf jgfs_post_f050.ecf
cp jgfs_post_anl.ecf jgfs_post_f051.ecf
cp jgfs_post_anl.ecf jgfs_post_f052.ecf
cp jgfs_post_anl.ecf jgfs_post_f053.ecf
cp jgfs_post_anl.ecf jgfs_post_f054.ecf
cp jgfs_post_anl.ecf jgfs_post_f055.ecf
cp jgfs_post_anl.ecf jgfs_post_f056.ecf
cp jgfs_post_anl.ecf jgfs_post_f057.ecf
cp jgfs_post_anl.ecf jgfs_post_f058.ecf
cp jgfs_post_anl.ecf jgfs_post_f059.ecf
cp jgfs_post_anl.ecf jgfs_post_f060.ecf
cp jgfs_post_anl.ecf jgfs_post_f061.ecf
cp jgfs_post_anl.ecf jgfs_post_f062.ecf
cp jgfs_post_anl.ecf jgfs_post_f063.ecf
cp jgfs_post_anl.ecf jgfs_post_f064.ecf
cp jgfs_post_anl.ecf jgfs_post_f065.ecf
cp jgfs_post_anl.ecf jgfs_post_f066.ecf
cp jgfs_post_anl.ecf jgfs_post_f067.ecf
cp jgfs_post_anl.ecf jgfs_post_f068.ecf
cp jgfs_post_anl.ecf jgfs_post_f069.ecf
cp jgfs_post_anl.ecf jgfs_post_f070.ecf
cp jgfs_post_anl.ecf jgfs_post_f071.ecf
cp jgfs_post_anl.ecf jgfs_post_f072.ecf
cp jgfs_post_anl.ecf jgfs_post_f073.ecf
cp jgfs_post_anl.ecf jgfs_post_f074.ecf
cp jgfs_post_anl.ecf jgfs_post_f075.ecf
cp jgfs_post_anl.ecf jgfs_post_f076.ecf
cp jgfs_post_anl.ecf jgfs_post_f077.ecf
cp jgfs_post_anl.ecf jgfs_post_f078.ecf
cp jgfs_post_anl.ecf jgfs_post_f079.ecf
cp jgfs_post_anl.ecf jgfs_post_f080.ecf
cp jgfs_post_anl.ecf jgfs_post_f081.ecf
cp jgfs_post_anl.ecf jgfs_post_f082.ecf
cp jgfs_post_anl.ecf jgfs_post_f083.ecf
cp jgfs_post_anl.ecf jgfs_post_f084.ecf
cp jgfs_post_anl.ecf jgfs_post_f085.ecf
cp jgfs_post_anl.ecf jgfs_post_f086.ecf
cp jgfs_post_anl.ecf jgfs_post_f087.ecf
cp jgfs_post_anl.ecf jgfs_post_f088.ecf
cp jgfs_post_anl.ecf jgfs_post_f089.ecf
cp jgfs_post_anl.ecf jgfs_post_f090.ecf
cp jgfs_post_anl.ecf jgfs_post_f091.ecf
cp jgfs_post_anl.ecf jgfs_post_f092.ecf
cp jgfs_post_anl.ecf jgfs_post_f093.ecf
cp jgfs_post_anl.ecf jgfs_post_f094.ecf
cp jgfs_post_anl.ecf jgfs_post_f095.ecf
cp jgfs_post_anl.ecf jgfs_post_f096.ecf
cp jgfs_post_anl.ecf jgfs_post_f097.ecf
cp jgfs_post_anl.ecf jgfs_post_f098.ecf
cp jgfs_post_anl.ecf jgfs_post_f099.ecf
cp jgfs_post_anl.ecf jgfs_post_f100.ecf
cp jgfs_post_anl.ecf jgfs_post_f101.ecf
cp jgfs_post_anl.ecf jgfs_post_f102.ecf
cp jgfs_post_anl.ecf jgfs_post_f103.ecf
cp jgfs_post_anl.ecf jgfs_post_f104.ecf
cp jgfs_post_anl.ecf jgfs_post_f105.ecf
cp jgfs_post_anl.ecf jgfs_post_f106.ecf
cp jgfs_post_anl.ecf jgfs_post_f107.ecf
cp jgfs_post_anl.ecf jgfs_post_f108.ecf
cp jgfs_post_anl.ecf jgfs_post_f109.ecf
cp jgfs_post_anl.ecf jgfs_post_f110.ecf
cp jgfs_post_anl.ecf jgfs_post_f111.ecf
cp jgfs_post_anl.ecf jgfs_post_f112.ecf
cp jgfs_post_anl.ecf jgfs_post_f113.ecf
cp jgfs_post_anl.ecf jgfs_post_f114.ecf
cp jgfs_post_anl.ecf jgfs_post_f115.ecf
cp jgfs_post_anl.ecf jgfs_post_f116.ecf
cp jgfs_post_anl.ecf jgfs_post_f117.ecf
cp jgfs_post_anl.ecf jgfs_post_f118.ecf
cp jgfs_post_anl.ecf jgfs_post_f119.ecf
cp jgfs_post_anl.ecf jgfs_post_f120.ecf
cp jgfs_post_anl.ecf jgfs_post_f123.ecf
cp jgfs_post_anl.ecf jgfs_post_f126.ecf
cp jgfs_post_anl.ecf jgfs_post_f129.ecf
cp jgfs_post_anl.ecf jgfs_post_f132.ecf
cp jgfs_post_anl.ecf jgfs_post_f135.ecf
cp jgfs_post_anl.ecf jgfs_post_f138.ecf
cp jgfs_post_anl.ecf jgfs_post_f141.ecf
cp jgfs_post_anl.ecf jgfs_post_f144.ecf
cp jgfs_post_anl.ecf jgfs_post_f147.ecf
cp jgfs_post_anl.ecf jgfs_post_f150.ecf
cp jgfs_post_anl.ecf jgfs_post_f153.ecf
cp jgfs_post_anl.ecf jgfs_post_f156.ecf
cp jgfs_post_anl.ecf jgfs_post_f159.ecf
cp jgfs_post_anl.ecf jgfs_post_f162.ecf
cp jgfs_post_anl.ecf jgfs_post_f165.ecf
cp jgfs_post_anl.ecf jgfs_post_f168.ecf
cp jgfs_post_anl.ecf jgfs_post_f171.ecf
cp jgfs_post_anl.ecf jgfs_post_f174.ecf
cp jgfs_post_anl.ecf jgfs_post_f177.ecf
cp jgfs_post_anl.ecf jgfs_post_f180.ecf
cp jgfs_post_anl.ecf jgfs_post_f183.ecf
cp jgfs_post_anl.ecf jgfs_post_f186.ecf
cp jgfs_post_anl.ecf jgfs_post_f189.ecf
cp jgfs_post_anl.ecf jgfs_post_f192.ecf
cp jgfs_post_anl.ecf jgfs_post_f195.ecf
cp jgfs_post_anl.ecf jgfs_post_f198.ecf
cp jgfs_post_anl.ecf jgfs_post_f201.ecf
cp jgfs_post_anl.ecf jgfs_post_f204.ecf
cp jgfs_post_anl.ecf jgfs_post_f207.ecf
cp jgfs_post_anl.ecf jgfs_post_f210.ecf
cp jgfs_post_anl.ecf jgfs_post_f213.ecf
cp jgfs_post_anl.ecf jgfs_post_f216.ecf
cp jgfs_post_anl.ecf jgfs_post_f219.ecf
cp jgfs_post_anl.ecf jgfs_post_f222.ecf
cp jgfs_post_anl.ecf jgfs_post_f225.ecf
cp jgfs_post_anl.ecf jgfs_post_f228.ecf
cp jgfs_post_anl.ecf jgfs_post_f231.ecf
cp jgfs_post_anl.ecf jgfs_post_f234.ecf
cp jgfs_post_anl.ecf jgfs_post_f237.ecf
cp jgfs_post_anl.ecf jgfs_post_f240.ecf
cp jgfs_post_anl.ecf jgfs_post_f243.ecf
cp jgfs_post_anl.ecf jgfs_post_f246.ecf
cp jgfs_post_anl.ecf jgfs_post_f249.ecf
cp jgfs_post_anl.ecf jgfs_post_f252.ecf
cp jgfs_post_anl.ecf jgfs_post_f255.ecf
cp jgfs_post_anl.ecf jgfs_post_f258.ecf
cp jgfs_post_anl.ecf jgfs_post_f261.ecf
cp jgfs_post_anl.ecf jgfs_post_f264.ecf
cp jgfs_post_anl.ecf jgfs_post_f267.ecf
cp jgfs_post_anl.ecf jgfs_post_f270.ecf
cp jgfs_post_anl.ecf jgfs_post_f273.ecf
cp jgfs_post_anl.ecf jgfs_post_f276.ecf
cp jgfs_post_anl.ecf jgfs_post_f279.ecf
cp jgfs_post_anl.ecf jgfs_post_f282.ecf
cp jgfs_post_anl.ecf jgfs_post_f285.ecf
cp jgfs_post_anl.ecf jgfs_post_f288.ecf
cp jgfs_post_anl.ecf jgfs_post_f291.ecf
cp jgfs_post_anl.ecf jgfs_post_f294.ecf
cp jgfs_post_anl.ecf jgfs_post_f297.ecf
cp jgfs_post_anl.ecf jgfs_post_f300.ecf
cp jgfs_post_anl.ecf jgfs_post_f303.ecf
cp jgfs_post_anl.ecf jgfs_post_f306.ecf
cp jgfs_post_anl.ecf jgfs_post_f309.ecf
cp jgfs_post_anl.ecf jgfs_post_f312.ecf
cp jgfs_post_anl.ecf jgfs_post_f315.ecf
cp jgfs_post_anl.ecf jgfs_post_f318.ecf
cp jgfs_post_anl.ecf jgfs_post_f321.ecf
cp jgfs_post_anl.ecf jgfs_post_f324.ecf
cp jgfs_post_anl.ecf jgfs_post_f327.ecf
cp jgfs_post_anl.ecf jgfs_post_f330.ecf
cp jgfs_post_anl.ecf jgfs_post_f333.ecf
cp jgfs_post_anl.ecf jgfs_post_f336.ecf
cp jgfs_post_anl.ecf jgfs_post_f339.ecf
cp jgfs_post_anl.ecf jgfs_post_f342.ecf
cp jgfs_post_anl.ecf jgfs_post_f345.ecf
cp jgfs_post_anl.ecf jgfs_post_f348.ecf
cp jgfs_post_anl.ecf jgfs_post_f351.ecf
cp jgfs_post_anl.ecf jgfs_post_f354.ecf
cp jgfs_post_anl.ecf jgfs_post_f357.ecf
cp jgfs_post_anl.ecf jgfs_post_f360.ecf
cp jgfs_post_anl.ecf jgfs_post_f363.ecf
cp jgfs_post_anl.ecf jgfs_post_f366.ecf
cp jgfs_post_anl.ecf jgfs_post_f369.ecf
cp jgfs_post_anl.ecf jgfs_post_f372.ecf
cp jgfs_post_anl.ecf jgfs_post_f375.ecf
cp jgfs_post_anl.ecf jgfs_post_f378.ecf
cp jgfs_post_anl.ecf jgfs_post_f381.ecf
cp jgfs_post_anl.ecf jgfs_post_f384.ecf
