#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"

#############################
# Source relevant config files
#############################
export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
configs="base earc"
config_path=${EXPDIR:-${PACKAGEROOT}/gfs.${gfs_ver}/parm/config}
for config in ${configs}; do
    . "${config_path}"/config."${config}"
    status=$?
    [[ ${status} -ne 0 ]] && exit "${status}"
done

##########################################
# Source machine runtime environment
##########################################
. "${HOMEgfs}"/env/"${machine}".env earc
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export pid=${pid:-$$}
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p "${DATA}"
cd "${DATA}"


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY


##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


##############################################
# Set variables used in the script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gdas"}}
export COMPONENT=${COMPONENT:-atmos}

###############################################################
# Run archive script
###############################################################

"${SCRgfs}"/exgdas_enkf_earc.sh
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

###############################################################

echo "ENDED NORMALLY."

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}"
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"

exit 0
