#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "eupd" -c "base anal eupd"


##############################################
# Set variables used in the script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"enkfgdas"}}
export COMPONENT="atmos"


##############################################
# Begin JOB SPECIFIC work
##############################################

GDATE=$(${NDATE} -${assim_freq} ${CDATE})
gPDY=$(echo ${GDATE} | cut -c1-8)
gcyc=$(echo ${GDATE} | cut -c9-10)

export APREFIX="${CDUMP}.t${cyc}z."
export GPREFIX="enkfgdas.t${gcyc}z."

# COMIN_GES_ENS and COMOUT_ANL_ENS are used in script
export COMIN_GES_ENS="${ROTDIR}/enkfgdas.${gPDY}/${gcyc}"
export COMOUT_ANL_ENS="${ROTDIR}/${CDUMP}.${PDY}/${cyc}"


###############################################################
# Run relevant script

${ENKFUPDSH:-${SCRgfs}/exgdas_enkf_update.sh}
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


##############################################
# Send Alerts
##############################################
if [ ${SENDDBN} = YES  ] ; then
   ${DBNROOT}/bin/dbn_alert MODEL ENKF1_MSC_enkfstat ${job} ${COMOUT_ANL_ENS}/${APREFIX}enkfstat
fi


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
