#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "gempak" -c "base gempak"

############################################
# Set up model and cycle specific variables
############################################
export model=${model:-gdas}
export GRIB=${GRIB:-pgrb2f}
export EXT=""
export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-GDAS_GEMPAK}

export SENDDBN=${SENDDBN:-NO}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

##############################################
# Define COM directories
##############################################
for grid in 0p25 1p00; do
  GRID=${grid} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "COM_ATMOS_GRIB_${grid}:COM_ATMOS_GRIB_GRID_TMPL"
done

for grid in 0p25 1p00; do
  prod_dir="COM_ATMOS_GEMPAK_${grid}"
  GRID=${grid} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "COM_ATMOS_GEMPAK_${grid}:COM_ATMOS_GEMPAK_TMPL"

  if [[ ! -d "${!prod_dir}" ]] ; then
    mkdir -m 775 -p "${!prod_dir}"
  fi
done

########################################################
# Execute the script for one degree grib
########################################################

"${SCRgfs}/exgdas_atmos_nawips.sh" "1p00" "${FHR3}" "GDAS_GEMPAK" "${COM_ATMOS_GEMPAK_1p00}"

########################################################
# Execute the script for quater-degree grib
########################################################

"${SCRgfs}/exgdas_atmos_nawips.sh" "0p25" "${FHR3}" "GDAS_GEMPAK" "${COM_ATMOS_GEMPAK_0p25}"

export err=$?; err_chk

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]] ; then
  rm -rf "${DATA}"
fi
