#!/bin/sh
#############################################################
# Set up environment for GDAS Ozone Monitor job
#############################################################
set -xa
echo `date` $0 `date -u` begin
export PS4='$SECONDS + '

export RUN_ENVIR=${RUN_ENVIR:-nco}
export envir=${envir:-prod}

###############################
# Specify NET and RUN name
##############################
export NET=${NET:-gfs}
export RUN=${RUN:-gdas}

########################################################### 
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export outid=${outid:-"LL$job"}
export jobid=${jobid:-"${outid}.o${pid}"}

export DATAROOT=${DATAROOT:-/tmpnwprod2}
export DATA=${DATA:-${DATAROOT}/${jobid}}

export OZNMON_SUFFIX=${OZNMON_SUFFIX:-${NET}}

mkdir -p $DATA
cd $DATA


####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile
export cycle=t${cyc}z

##############################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# VERBOSE  - Specify Verbose Output in exglobal
##############################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}
export VERBOSE=${VERBOSE:-YES}


##############################################
# Specify Execution Areas
##############################################
export HOMEgfs_ozn=${HOMEgfs_ozn:-${NWROOT}/gfs.${gfs_ver}}
export PARMmon_ozn=${PARMmon_ozn:-$HOMEgfs_ozn/parm/mon}
export SCRgfs_ozn=${SCRgfs_ozn:-$HOMEgfs_ozn/scripts}
export FIXgdas_ozn=${FIXgdas_ozn:-$HOMEgfs_ozn/fix/gdas}

export HOMEoznmon=${HOMEoznmon:-${HOMEgfs_ozn}}
export EXECoznmon=${EXECoznmon:-$HOMEoznmon/exec}
export FIXoznmon=${FIXoznmon:-${HOMEoznmon}/fix}
export USHoznmon=${USHoznmon:-$HOMEoznmon/ush}


###################################
# source the parm file
###################################
.  ${PARMmon_ozn}/da_mon.parm


#############################################
# Run setpdy and initialize PDY variables
#############################################
if [[ $MY_MACHINE != "theia" ]]; then
   setpdy.sh
   . ./PDY
fi   

#############################################
# COMOUT - WHERE GSI OUTPUT RESIDES
# TANKverf - WHERE OUTPUT DATA WILL RESIDE
#############################################
OZN_TANKDIR=${OZN_TANKDIR:-${COMROOT}/${NET}/${envir}}
export TANKverf_ozn=${TANKverf_ozn:-${OZN_TANKDIR}/${RUN}.${PDY}/oznmon}
export TANKverf_oznM1=${TANKverf_oznM1:-${OZN_TANKDIR}/${RUN}.${PDYm1}/oznmon}
export COM_IN=${COM_IN:-${COMROOT}/${NET}/${envir}}
export COMIN=${COMIN:-${COM_IN}/${RUN}.${PDY}}

mkdir -p -m 775 $TANKverf_ozn
 
env

########################################
# Set necessary environment variables
########################################
export OZO_AREA=${OZO_AREA:-glb}

export biascr=${biascr:-$COMIN/gdas.t${cyc}z.abias}
export oznstat=${oznstat:-$COMIN/gdas.t${cyc}z.oznstat}

msg="JOB HAS STARTED"
postmsg "$jlogfile" "$msg"

err=0
########################################################
# Execute the script.
${OZOMONSH:-${SCRgfs_ozn}/exgdas_vrfyozn.sh.ecf} ${PDY} ${cyc}

err=$?
########################################################

if [[ ${err} -ne 0 ]]; then
   msg="WARNING:  JOB DID NOT COMPLETE NORMALLY, error code $err"
else
   msg="JOB COMPLETED NORMALLY"
fi

postmsg "$jlogfile" "$msg"

################################
# Remove the Working Directory
################################
KEEPDATA=${KEEPDATA:-YES}
cd $DATAROOT
if [ ${KEEPDATA} = NO ] ; then 
  rm -rf $DATA 
fi

date

