#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "eobs" -c "base anal eobs analdiag ediag"


##############################################
# Set variables used in the script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gdas"}}
export COMPONENT="atmos"
export MAKE_NSSTBUFR=${MAKE_NSSTBUFR:-"NO"}
export MAKE_ACFTBUFR=${MAKE_ACFTBUFR:-"NO"}


##############################################
# Begin JOB SPECIFIC work
##############################################

GDATE=$(${NDATE} -${assim_freq} ${CDATE})
gPDY=$(echo ${GDATE} | cut -c1-8)
gcyc=$(echo ${GDATE} | cut -c9-10)
GDUMP=${GDUMP:-"gdas"}
GDUMP_ENS=${GDUMP_ENS:-"enkf${GDUMP}"}

export CASE=${CASE_ENKF}
export CDUMP_OBS=${CDUMP_OBS:-${CDUMP/enkf}}
export CDUMP_CTL=${CDUMP_CTL:-${CDUMP/enkf}}


export OPREFIX="${CDUMP_OBS}.t${cyc}z."
export APREFIX="${CDUMP_CTL}.t${cyc}z."
export APREFIX_ENS="${CDUMP}.t${cyc}z."
export GPREFIX="${GDUMP}.t${gcyc}z."
export GPREFIX_ENS="${GDUMP_ENS}.t${gcyc}z."

if [ ${RUN_ENVIR} = "nco" -o ${ROTDIR_DUMP:-NO} = "YES" ]; then
    export COMIN_OBS=${COMIN_OBS:-$(compath.py ${envir}/obsproc/${obsproc_ver})/${CDUMP_OBS}.${PDY}/${cyc}/${COMPONENT}}
else
    export COMIN_OBS="${COMIN_OBS:-${ROTDIR}/${CDUMP_OBS}.${PDY}/${cyc}/obs}"
fi

# COMIN_GES, COMIN_ANL COMIN_GES_ENS, and COMOUT  are used in script
COMIN_GES_CTL="${ROTDIR}/gdas.${gPDY}/${gcyc}/${COMPONENT}"
export COMIN_ANL="${ROTDIR}/${CDUMP/enkf}.${PDY}/${cyc}/${COMPONENT}"
export COMIN_GES_ENS="${ROTDIR}/enkfgdas.${gPDY}/${gcyc}"
export COMOUT="${ROTDIR}/${CDUMP}.${PDY}/${cyc}"


export ATMGES_ENSMEAN="${COMIN_GES_ENS}/${GPREFIX_ENS}atmf006.ensmean.nc"
if [ ! -f ${ATMGES_ENSMEAN} ]; then
    echo "FATAL ERROR: FILE MISSING: ATMGES_ENSMEAN = ${ATMGES_ENSMEAN}"
    exit 1
fi


# Link observational data
export PREPQC="${COMIN_OBS}/${OPREFIX}prepbufr"
if [[ ! -f ${PREPQC} ]]; then
    echo "WARNING: Global PREPBUFR FILE ${PREPQC} MISSING"
fi
export TCVITL="${COMIN_ANL}/${OPREFIX}syndata.tcvitals.tm00"
if [[ ${DONST} = "YES" ]]; then
   export NSSTBF="${COMIN_OBS}/${OPREFIX}nsstbufr"
fi
export PREPQCPF="${COMIN_OBS}/${OPREFIX}prepbufr.acft_profiles"

# Guess Bias correction coefficients related to control
export GBIAS=${COMIN_GES_CTL}/${GPREFIX}abias
export GBIASPC=${COMIN_GES_CTL}/${GPREFIX}abias_pc
export GBIASAIR=${COMIN_GES_CTL}/${GPREFIX}abias_air
export GRADSTAT=${COMIN_GES_CTL}/${GPREFIX}radstat

# Bias correction coefficients related to ensemble mean
export ABIAS="${COMOUT}/${APREFIX_ENS}abias.ensmean"
export ABIASPC="${COMOUT}/${APREFIX_ENS}abias_pc.ensmean"
export ABIASAIR="${COMOUT}/${APREFIX_ENS}abias_air.ensmean"
export ABIASe="${COMOUT}/${APREFIX_ENS}abias_int.ensmean"

# Diagnostics related to ensemble mean
export GSISTAT="${COMOUT}/${APREFIX_ENS}gsistat.ensmean"
export CNVSTAT="${COMOUT}/${APREFIX_ENS}cnvstat.ensmean"
export OZNSTAT="${COMOUT}/${APREFIX_ENS}oznstat.ensmean"
export RADSTAT="${COMOUT}/${APREFIX_ENS}radstat.ensmean"

# Select observations based on ensemble mean
export RUN_SELECT="YES"
export USE_SELECT="NO"
export SELECT_OBS="${COMOUT}/${APREFIX_ENS}obsinput.ensmean"

export DIAG_SUFFIX="_ensmean"
export DIAG_COMPRESS="NO"

# GSI namelist options specific to eobs
export SETUP_INVOBS="passive_bc=.false.,${SETUP_INVOBS}"

# Ensure clean stat tarballs for ensemble mean
for fstat in ${CNVSTAT} ${OZNSTAT} ${RADSTAT}; do
    [[ -f ${fstat} ]] && rm -f ${fstat}
done


###############################################################
# Run relevant script

${ANALDIAGSH:-${SCRgfs}/exglobal_diag.sh}
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
