#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "esfc" -c "base esfc"


##############################################
# Set variables used in the script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gdas"}}
export COMPONENT="atmos"


##############################################
# Begin JOB SPECIFIC work
##############################################

GDATE=$(${NDATE} -${assim_freq} ${CDATE})
gPDY=$(echo ${GDATE} | cut -c1-8)
gcyc=$(echo ${GDATE} | cut -c9-10)
GDUMP=${GDUMP:-"gdas"}
GDUMP_ENS=${GDUMP_ENS:-"enkf${GDUMP}"}

export CASE=${CASE_ENKF}

export CDUMP_OBS=${CDUMP_OBS:-${CDUMP/enkf}}

export OPREFIX="${CDUMP_OBS}.t${cyc}z."
export APREFIX="${CDUMP/enkf}.t${cyc}z."
export APREFIX_ENS="${CDUMP}.t${cyc}z."
export GPREFIX="${GDUMP}.t${gcyc}z."
export GPREFIX_ENS="${GDUMP_ENS}.t${gcyc}z."

# COMIN, COMIN_ENS and COMIN_GES_ENS are used in script
export COMIN="${ROTDIR}/${RUN/enkf}.${PDY}/${cyc}/atmos"
export COMIN_GES="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/atmos"
export COMIN_ENS="${ROTDIR}/${CDUMP}.${PDY}/${cyc}"
export COMOUT_ENS="${ROTDIR}/${CDUMP}.${PDY}/${cyc}"
export COMIN_GES_ENS="${ROTDIR}/${GDUMP_ENS}.${gPDY}/${gcyc}"


###############################################################
# Run relevant script

${ENKFRESFCSH:-${SCRgfs}/exgdas_enkf_sfc.sh}
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
