#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "fit2obs" -c "base fit2obs"


##############################################
# Set variables used in the script
##############################################

CDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${VBACKUP_FITS} hours")
export CDATE
vday=${CDATE:0:8}
vcyc=${CDATE:8:2}

# These are used by fit2obs, so we can't change them to the standard COM variable names
# shellcheck disable=SC2153
YMD=${vday} HH=${vcyc} declare_from_tmpl -rx COMIN_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL
RUN=${RUN/enkf} YMD=${vday} HH=${vcyc} declare_from_tmpl -rx COMIN_OBS:COM_OBS_TMPL

# We want to defer variable expansion, so ignore warning about single quotes
# shellcheck disable=SC2016
export COMIN_HISTORY='$ROTDIR/vrfyarch/gfs.$fdy/$fzz'

export PRPI=${COMIN_OBS}/${RUN}.t${vcyc}z.prepbufr
# shellcheck disable=SC2153
export sig1=${COMIN_ANALYSIS}/${RUN}.t${vcyc}z.atmanl.nc
export sfc1=${COMIN_ANALYSIS}/${RUN}.t${vcyc}z.atmanl.nc
export CNVS=${COMIN_ANALYSIS}/${RUN}.t${vcyc}z.cnvstat

export OUTPUT_FILETYPE=${OUTPUT_FILETYPE:-netcdf}

export FIT_DIR=${ARCDIR}/fits
if [[ ! -d "${FIT_DIR}" ]]; then
    mkdir -p "${FIT_DIR}"
fi
export HORZ_DIR=${ARCDIR}/horiz
if [[ ! -d "${HORZ_DIR}" ]]; then
    mkdir -p "${HORZ_DIR}"
fi
export COMOUT_FITX=${DATA}/fitx
if [[ ! -d "${COMOUT_FITX}" ]]; then
    mkdir -p "${COMOUT_FITX}"
fi

echo "echo err_chk">"${DATA}/err_chk"; chmod 755 "${DATA}/err_chk"
echo "echo postmsg">"${DATA}/postmsg"; chmod 755 "${DATA}/postmsg"

##############################################
# Check spinup and available inputs
##############################################

# Ignore spelling warning; nothing is misspelled
# shellcheck disable=SC2153
if [[ ${CDATE} -gt ${SDATE} ]]; then
  for file in ${PRPI} ${sig1} ${sfc1} ${CNVS}; do
    if [[ ! -f "${file}" ]]; then
      echo "FATAL ERROR: FILE MISSING: ${file}"
      exit 1
    fi
  done

  ##############################################
  # RUN FIT2OBS VERIFICATION
  ##############################################

  # Un-export SHELLOPTS before going into the Fit2Obs package (let that package handle logging/errors)
  export -n SHELLOPTS
  "${SCRIPTSfit2obs}/excfs_gdas_vrfyfits.sh"
  err=$?
  if [[ ${err} -ne 0 ]]; then
      exit "${err}"
  fi

  ##############################################
  # End JOB SPECIFIC work
  ##############################################

  ##############################################
  # Final processing
  ##############################################
  if [[ -e "${pgmout}" ]] ; then
    cat "${pgmout}"
  fi

else

  echo "Too early for FIT2OBS to run. Exiting."

fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (echo "FATAL ERROR: ${DATAROOT} does not exist. ABORT!"; exit 1)
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
