#!/bin/ksh
set -x

export RUN_ENVIR=${RUN_ENVIR:-"nco"}
export PS4='$SECONDS + '
date


#############################
# Source relevant config files
#############################
configs="base vrfy"
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done


##########################################
# Source machine runtime environment
##########################################
. $HOMEgfs/env/${machine}.env vrfy
status=$?
[[ $status -ne 0 ]] && exit $status


##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
if [ $RUN_ENVIR = "nco" ]; then
    export DATA=${DATA:-${DATAROOT}/${jobid:?}}
else
    export job="gfs_cyclone_tracker"
    export DATA="$DATAROOT/${job}$$"
    [[ -d $DATA ]] && rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY


####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}
export COMPONENT=${COMPONENT:-atmos}


##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}


####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=YES
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${NWROOT:?}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}

##############################################
# Define COM and Data directories
##############################################
export COMINgfs=${ROTDIR}/gfs.${PDY}/${cyc}/$COMPONENT
export gfsdir=${COMINgfs}
export COMINgdas=${ROTDIR}/gdas.${PDY}/${cyc}/$COMPONENT
export gdasdir=${COMINgdas}
export COMOUT=${ROTDIR}/${RUN}.${PDY}/${cyc}/$COMPONENT
export COMINsyn=${COMINsyn:-$(compath.py ${envir}/com/gfs/${gfs_ver})/syndat}

if [ $RUN_ENVIR = "nco" ]; then
    export COMOUThur=${COMROOTp1:?}/hur/${envir}/global
    export COMOUTatcf=${COMROOTp1:?}/nhc/${envir}/atcf
    mkdir -m 775 -p $COMOUThur $COMOUTatcf
else
#    export COMOUThur=$COMOUT         
#    export COMOUTatcf=$COMOUT
    export COMOUThur=$DATA
    export COMOUTatcf=$DATA
fi

##############################################
# Run relevant script
##############################################
env
echo "HAS BEGUN on `hostname`"
$LOGSCRIPT

#############################################################
# Execute the script
export pert="p01"
export cmodel=$CDUMP
export loopnum=1

#-----------input data checking -----------------
#${USHens_tracker}/data_check_gfs.sh
# exit code 6 = missing data of opportunity
#if [ $? -eq 6 ]; then exit; fi
#------------------------------------------------

${USHens_tracker}/extrkr_gfs.sh ${loopnum} ${cmodel} ${CDATE} ${pert} ${DATA}
export err=$?; err_chk


#if [ "$SENDCOM" = 'YES' ]; then
#  cat ${DATA}/trak.avnx.atcfunix.${PDY}${cyc} | \
#      sed s:AVNX:GFSO:g \
#    > ${COMOUT}/gfso.t${cyc}z.cyclone.trackatcfunix
#
#  cat ${DATA}/trak.avnx.atcfunix.${PDY}${cyc} | \
#      sed s:AVNX:AVNO:g \
#    > ${COMOUT}/avn.t${cyc}z.cyclone.trackatcfunix
#fi

##############################################
# Final processing
##############################################
if [ -e "$pgmout" ] ; then
  cat $pgmout
fi


echo "ENDED NORMALLY."

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0
