#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "ecen" -c "base ecen"


##############################################
# Set variables used in the script
##############################################
export CDUMP="${RUN/enkf}"

##############################################
# Begin JOB SPECIFIC work
##############################################
DATE_PREV=$(${NDATE} -"${assim_freq}" "${PDY}${cyc}")
export PDY_PREV=${DATE_PREV:0:8}
export cyc_PREV=${DATE_PREV:8:2}
export GDUMP="gdas"
export GDUMP_ENS="enkf${GDUMP}"

export CASE=${CASE_ENKF}

export OPREFIX="${CDUMP}.t${cyc}z."
export APREFIX="${CDUMP}.t${cyc}z."
export APREFIX_ENS="${RUN}.t${cyc}z."
export GPREFIX="${GDUMP}.t${cyc_PREV}z."
export GPREFIX_ENS="${GDUMP_ENS}.t${cyc_PREV}z."

RUN=${CDUMP} YMD=${PDY} HH=${cyc} generate_com -rx \
  COM_ATMOS_ANALYSIS_DET:COM_ATMOS_ANALYSIS_TMPL

MEMDIR="ensstat" YMD=${PDY} HH=${cyc} generate_com -rx \
  COM_ATMOS_ANALYSIS_STAT:COM_ATMOS_ANALYSIS_TMPL

MEMDIR="ensstat" RUN=${GDUMP} YMD=${PDY_PREV} HH=${cyc_PREV} generate_com -rx \
  COM_ATMOS_HISTORY_STAT_PREV:COM_ATMOS_HISTORY_TMPL


###############################################################
# Run relevant script

${ENKFRECENSH:-${SCRgfs}/exgdas_enkf_ecen.sh}
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
