#! /usr/bin/env bash

############################################
# GDAS GEMPAK META NCDC PRODUCT GENERATION
############################################

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "gempak_meta" -c "base gempak"

# Now set up GEMPAK/NTRANS environment

# datatype.tbl specifies the paths and filenames of files
cp "${HOMEgfs}/gempak/fix/datatype.tbl" datatype.tbl

###################################
# Specify NET and RUN Name and model
####################################
export COMPONENT="atmos"
export MODEL=GDAS
export GRID_NAME=gdas
export fend=09

######################################################
# set increment to 6 hours  --  3 hours is available.
######################################################
export finc=6
export fstart=00

export DBN_ALERT_TYPE=GDAS_METAFILE

export SENDDBN=${SENDDBN:-NO}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

##############################################
# Define COM directories
##############################################
GRID=1p00 YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "COMIN_ATMOS_GEMPAK_1p00:COM_ATMOS_GEMPAK_TMPL"

GRID="meta" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "COMOUT_ATMOS_GEMPAK_META:COM_ATMOS_GEMPAK_TMPL"
if [[ ! -d "${COMOUT_ATMOS_GEMPAK_META}" ]]; then
  mkdir -m 775 -p "${COMOUT_ATMOS_GEMPAK_META}"
fi

if (( cyc%12 == 0 )); then
  GRID="gif" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "COMOUT_ATMOS_GEMPAK_GIF:COM_ATMOS_GEMPAK_TMPL"
  if [[ ! -d "${COMOUT_ATMOS_GEMPAK_GIF}" ]]; then
    mkdir -m 775 -p "${COMOUT_ATMOS_GEMPAK_GIF}"
  fi
fi

export COMINukmet="${COMINukmet:-$(compath.py "${envir}/ukmet/${ukmet_ver}")/ukmet}"
export COMINecmwf="${COMINecmwf:-$(compath.py "${envir}/ecmwf/${ecmwf_ver}")/ecmwf}"

export pgmout=OUTPUT.$$

########################################################
# Execute the script.
"${HOMEgfs}/gempak/ush/gdas_meta_na.sh"
export err=$?; err_chk
"${HOMEgfs}/gempak/ush/gdas_meta_loop.sh"
export err=$?; err_chk
if [[ "${cyc}" == '06' ]]; then
  "${HOMEgfs}/gempak/ush/gdas_ecmwf_meta_ver.sh"
  export err=$?; err_chk
  "${HOMEgfs}/gempak/ush/gdas_ukmet_meta_ver.sh"
  export err=$?; err_chk
fi
########################################################

############################################
# GDAS GEMPAK NCDC PRODUCT GENERATION
############################################

########################################################
# Execute the script.
if (( cyc%12 == 0 )); then
  "${SCRgfs}/exgdas_atmos_gempak_gif_ncdc.sh"
fi
export err=$?; err_chk
########################################################

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]] ; then
  rm -rf "${DATA}"
fi

