#! /usr/bin/env bash

#############################################################
# Set up environment for GDAS Radiance Monitor job
#############################################################
source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "verfrad" -c "base verfrad"

#############################################
#  determine PDY and cyc for previous cycle
#############################################
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}

#############################################
# COMOUT - WHERE GSI OUTPUT RESIDES
# TANKverf - WHERE OUTPUT DATA WILL RESIDE
#############################################
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_ATMOS_RADMON:COM_ATMOS_RADMON_TMPL
YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
    COMIN_ATMOS_RADMON_PREV:COM_ATMOS_RADMON_TMPL

export biascr="${COMIN_ATMOS_ANALYSIS}/gdas.t${cyc}z.abias"
export radstat="${COMIN_ATMOS_ANALYSIS}/gdas.t${cyc}z.radstat"
export TANKverf_rad=${TANKverf_rad:-${COMOUT_ATMOS_RADMON}}
export TANKverf_radM1=${TANKverf_radM1:-${COMIN_ATMOS_RADMON_PREV}}

if [[ ! -d ${TANKverf_rad} ]]; then mkdir -p ${TANKverf_rad} ; fi

########################################################
# Execute the script.
"${SCRgfs}/exgdas_atmos_verfrad.sh"
err=$?
if (( err != 0 )); then
    exit "${err}"
fi

################################
# Remove the Working Directory
################################
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
