#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "fit2obs" -c "base fit2obs"


##############################################
# Set variables used in the script
##############################################

# Ignore spelling warning; nothing is misspelled
# shellcheck disable=SC2153
CDATE=$(${NDATE} -"${VBACKUP_FITS}" "${PDY}${cyc}") # set CDATE to lookback cycle for use in fit2obs package
export CDATE
vday=${CDATE:0:8}
vcyc=${CDATE:8:2}

# These are used by fit2obs, so we can't change them to the standard COM variable names
# shellcheck disable=SC2153
YMD=${vday} HH=${vcyc} declare_from_tmpl -rx COM_INA:COM_ATMOS_ANALYSIS_TMPL
RUN=${RUN/enkf} YMD=${vday} HH=${vcyc} declare_from_tmpl -rx COM_PRP:COM_OBS_TMPL

# We want to defer variable expansion, so ignore warning about single quotes
# shellcheck disable=SC2016
export COM_INF='$ROTDIR/vrfyarch/gfs.$fdy/$fzz'

export PRPI=${COM_PRP}/${RUN}.t${vcyc}z.prepbufr
# shellcheck disable=SC2153
export sig1=${COM_INA}/${RUN}.t${vcyc}z.atmanl.nc
export sfc1=${COM_INA}/${RUN}.t${vcyc}z.atmanl.nc
export CNVS=${COM_INA}/${RUN}.t${vcyc}z.cnvstat

export OUTPUT_FILETYPE=${OUTPUT_FILETYPE:-netcdf}

export FIT_DIR=${ARCDIR}/fits
if [[ ! -d "${FIT_DIR}" ]]; then
    mkdir -p "${FIT_DIR}"
fi
export HORZ_DIR=${ARCDIR}/horiz
if [[ ! -d "${HORZ_DIR}" ]]; then
    mkdir -p "${HORZ_DIR}"
fi
export COMLOX=${DATA}/fitx
if [[ ! -d "${COMLOX}" ]]; then
    mkdir -p "${COMLOX}"
fi

echo "echo err_chk">"${DATA}/err_chk"; chmod 755 "${DATA}/err_chk"
echo "echo postmsg">"${DATA}/postmsg"; chmod 755 "${DATA}/postmsg"

##############################################
# Check spinup and available inputs
##############################################

# Ignore spelling warning; nothing is misspelled
# shellcheck disable=SC2153
if [[ ${CDATE} -gt ${SDATE} ]]; then
  for file in ${PRPI} ${sig1} ${sfc1} ${CNVS}; do
    if [[ ! -f "${file}" ]]; then
      echo "FATAL ERROR: FILE MISSING: ${file}"
      exit 1
    fi
  done

  ##############################################
  # RUN FIT2OBS VERIFICATION
  ##############################################

  "${SCRIPTSfit2obs}/excfs_gdas_vrfyfits.sh"
  status=$?
  if [[ ${status} -ne 0 ]]; then
      exit "${status}"
  fi

  ##############################################
  # End JOB SPECIFIC work
  ##############################################

  ##############################################
  # Final processing
  ##############################################
  if [[ -e "${pgmout}" ]] ; then
    cat "${pgmout}"
  fi

else

  echo "Too early for FIT2OBS to run. Exiting."

fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (echo "FATAL ERROR: ${DATAROOT} does not exist. ABORT!"; exit 1)
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
