#! /usr/bin/env bash

source "${HOMEgfs:?}/ush/preamble.sh"

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p "${DATA}"
cd "${DATA}" || exit 1


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY


##############################################
# Determine Job Output Name on System
##############################################
export pid=${pid:-$$}
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


#############################
# Source relevant config files
#############################
export EXPDIR=${EXPDIR:-${HOMEgfs}/parm/config}
configs="base gldas"
for config in ${configs}; do
    . ${EXPDIR}/config.${config}
    status=$?
    [[ ${status} -ne 0 ]] && exit "${status}"
done


if [[ "${cyc:?}" -ne "${gldas_cyc:?}" ]]; then
    echo "GLDAS only runs for ${gldas_cyc} cycle; Skip GLDAS step for cycle ${cyc}"
    exit 0
fi

gldas_spinup_hours=${gldas_spinup_hours-:72}
xtime=$((gldas_spinup_hours+12))
if [[ "${CDATE}" -le "$(${NDATE:?} +"${xtime}" "${SDATE:?}")" ]]; then
    echo "GLDAS needs fluxes as forcing from cycles in previous ${xtime} hours"
    echo "starting from ${SDATE}. This gldas cycle is skipped"
    exit 0
fi

##########################################
# Source machine runtime environment
##########################################
# shellcheck disable=SC1090-SC1091
. "${HOMEgfs}/env/${machine:?}.env" gldas
# shellcheck disable=
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"


##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gdas"}}
export COMPONENT="atmos"


##############################################
# Begin JOB SPECIFIC work
##############################################
export gldas_ver=${gldas_ver:-v2.3.0}
export HOMEgldas=${HOMEgldas:-${HOMEgfs}}
export FIXgldas=${FIXgldas:-${HOMEgldas}/fix/gldas}
export PARMgldas=${PARMgldas:-${HOMEgldas}/parm/gldas}
export EXECgldas=${EXECgldas:-${HOMEgldas}/exec}
export USHgldas=${USHgldas:-${HOMEgldas}/ush}
export PARA_CONFIG=${HOMEgfs}/parm/config/config.gldas

if [[ "${RUN_ENVIR}" = "nco" ]]; then
    export COMIN=${COMIN:-${ROTDIR}/${RUN}.${PDY}/${cyc}/atmos}
    export COMOUT=${COMOUT:-${ROTDIR}/${RUN}.${PDY}/${cyc}/atmos}
else
    export COMIN="${ROTDIR}/${CDUMP}.${PDY}/${cyc}/atmos"
    export COMOUT="${ROTDIR}/${CDUMP}.${PDY}/${cyc}/atmos"
fi
if [[ ! -d ${COMOUT} ]]; then
    mkdir -p "${COMOUT}"
    chmod 775 "${COMOUT}"
fi

export COMINgdas=${COMINgdas:-${ROTDIR}}
export DCOMIN=${DCOMIN:-${DCOMROOT:-"/lfs/h1/ops/prod/dcom"}}

export model=${model:-noah}
export MODEL=${MODEL:-"${model} |tr 'a-z' 'A-Z'"}


###############################################################
# Run relevant exglobal script

${GLDASSH:-${HOMEgldas}/scripts/exgdas_atmos_gldas.sh}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit 1
[[ ${KEEPDATA:?} = "NO" ]] && rm -rf "${DATA}"

exit 0

