#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "wave_stat" -c "base wave wave_stat"
source  "${USHgfs}/wave_domain_grid.sh"

# Set COM Paths and GETGES environment
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_WAVE_HISTORY:COM_WAVE_HISTORY_TMPL \
    COMOUT_WAVE_GRID:COM_WAVE_GRID_TMPL

for out_dir in "${COMOUT_WAVE_GRID}"; do
    if [[ ! -d "${out_dir}" ]]; then mkdir -p "${out_dir}"; fi
done

for grid in ${wavepostGRD}; do
  process_grdID "${grid}"
  prod_dir_grid="COMOUT_WAVE_GRID_${grid}"
  prod_dir_station="COMOUT_WAVE_STATION_ENS"
  MEMDIR="ensstat" GRID=${grid} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "${prod_dir_grid}:COM_WAVE_GRID_TMPL"
  MEMDIR="ensstat"  YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "${prod_dir_station}:COM_WAVE_STATION_TMPL"
  if [[ ! -d "${!prod_dir_grid}" ]]; then mkdir -m 775 -p "${!prod_dir_grid}"; fi
  if [[ ! -d "${!prod_dir_station}" ]]; then mkdir -m 775 -p "${!prod_dir_station}"; fi
done

# Execute the Script
"${SCRgfs}/exgefs_wave_stat.sh"

##########################################
## Remove the Temporary working directory
###########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi
 
exit 0
