#! /usr/bin/env bash
#
#
#####################################################################
source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "repair_replay" -c "base repair_replay"

####################################
# Specify Execution Areas
####################################
#
# Construct COM variables from templates
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL \
    COMOUT_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL \
    COMIN_TOP:COM_TOP_TMPL

export COMIN_03=${COMIN_TOP}/mem000/model/atmos/input

########################################################
# Execute the acc script.
"${SCRgfs}/exgefs_atmos_repair_replay.sh"
export err=$?; err_chk
##############################
# Remove the Temporary working directory
##############################
if [[ "${KEEPDATA}" != "YES" ]] ; then
  rm -fr "${DATA}"
fi
