#! /usr/bin/env bash
#
#
#####################################################################
# 8/14/2024, Hong Guan Scripts to repair F0306 for GEFSv13 reforecasts
#################################################################### 
source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "repair_replay" -c "base repair_replay"

####################################
# Specify Execution Areas
####################################
export EXECacc=${EXECacc:-${HOMEgfs}/exec}

# Construct COM variables from templates
 YMD=${PDY} HH=${cyc} declare_from_tmpl -rx COMIN_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL

export COMIN_03=${HOMEgfs}/anl

########################################################
# Execute the acc script.
"${SCRgfs}/exgefs_atmos_repair_replay.sh"

exit

##############################
# Remove the Temporary working directory
##############################
if [[ "${KEEPDATA}" !="YES" ]] ; then
  rm -fr "${DATA}"
fi
