#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "tracker" -c "base tracker"

# Hack to temporary skip this as the tracker has not been build
#   on Hercules Rocky 9 yet
# TODO: Remove this after tracker has been built for Rocky 9 #2639
if [[ "${machine}" == 'HERCULES' ]]; then exit 0; fi

export COMPONENT="atmos"


##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}


####################################
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-${HOMEens_tracker}/exec}
export FIXens_tracker=${FIXens_tracker:-${HOMEens_tracker}/fix}
export USHens_tracker=${USHens_tracker:-${HOMEens_tracker}/ush}


##############################################
# Define COM and Data directories
##############################################
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx COM_ATMOS_TRACK COM_ATMOS_GENESIS
YMD=${PDY} HH=${cyc} GRID="0p25" declare_from_tmpl -rx COM_ATMOS_GRIB_0p25:COM_ATMOS_GRIB_GRID_TMPL

if [[ ! -d "${COM_ATMOS_TRACK}" ]]; then mkdir -p "${COM_ATMOS_TRACK}"; fi

# The following variables are used by the tracker scripts which are outside
#   of global-workflow and therefore can't be standardized at this time
export COMINgfs=${COM_ATMOS_GRIB_0p25}
export gfsdir=${COM_ATMOS_GRIB_0p25}
export COMINgdas=${COM_ATMOS_GRIB_0p25}
export gdasdir=${COM_ATMOS_GRIB_0p25}
export COMOUT=${COM_ATMOS_TRACK}
export COMINsyn=${COMINsyn:-$(compath.py ${envir}/com/gfs/${gfs_ver})/syndat}

export COMINgenvit=${COM_ATMOS_GENESIS}

if [ ${RUN_ENVIR} = "nco" ]; then
    export COMOUThur=${COMROOTp1}/hur/${envir}/global
    export COMOUTatcf=${COMROOTp1}/nhc/${envir}/atcf
    mkdir -m 775 -p ${COMOUThur} ${COMOUTatcf}
else
#    export COMOUThur=$COMOUT
#    export COMOUTatcf=$COMOUT
    export COMOUThur=${DATA}
    export COMOUTatcf=${DATA}
fi

##############################################
# Run relevant script
##############################################

#############################################################
# Execute the script
export pert="p01"
export cmodel=${RUN/enkf}
export loopnum=1

#-----------input data checking -----------------
${USHens_tracker}/data_check_gfs.sh
export err=$?; err_chk
#------------------------------------------------

machine=${machine:-$(echo ${SITE})}
${USHens_tracker}/extrkr_gfs.sh ${loopnum} ${cmodel} ${CDATE} ${pert} ${DATA}
export err=$?; err_chk


#  cat ${DATA}/trak.avnx.atcfunix.${PDY}${cyc} | \
#      sed s:AVNX:GFSO:g \
#    > ${COMOUT}/gfso.t${cyc}z.cyclone.trackatcfunix
#
#  cat ${DATA}/trak.avnx.atcfunix.${PDY}${cyc} | \
#      sed s:AVNX:AVNO:g \
#    > ${COMOUT}/avn.t${cyc}z.cyclone.trackatcfunix

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
