#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "genesis" -c "base genesis"

##############################################
# Set variables used in the exglobal script
##############################################
export cmodel=${RUN}

####################################
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-${HOMEens_tracker}/exec}
export FIXens_tracker=${FIXens_tracker:-${HOMEens_tracker}/fix}
export USHens_tracker=${USHens_tracker:-${HOMEens_tracker}/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-${HOMEens_tracker}/scripts}

##############################################
# Define COM directories
##############################################
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx COMOUT_ATMOS_GENESIS:COM_ATMOS_GENESIS_TMPL
YMD=${PDY} HH=${cyc} GRID="0p25" declare_from_tmpl -rx COMIN_ATMOS_GRIB_0p25:COM_ATMOS_GRIB_GRID_TMPL

# The following variables are used by the tracker scripts which are outside
#   of global-workflow and therefore can't be standardized at this time
export COMIN=${COMIN_ATMOS_GRIB_0p25}
export gfsdir=${COMIN_ATMOS_GRIB_0p25}
export COMINgfs=${COMIN_ATMOS_GRIB_0p25}

export COMINgenvit=${COMOUT_ATMOS_GENESIS}
export COMOUTgenvit=${COMOUT_ATMOS_GENESIS}
export COMOUT=${COMOUT_ATMOS_GENESIS}

export COMINsyn=${COMINsyn:-$(compath.py "${envir}/com/gfs/${gfs_ver}")/syndat}

mkdir -m 775 -p "${COMOUTgenvit}"

export JYYYY=${PDY:0:4}

##############################################
# Run relevant script
##############################################

# Do not fail on errors or unassigned variables in external code
set +eu
${SCRIPTens_tracker}/exgfs_tc_genesis.sh && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

set_strict

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi


exit 0
