#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "genesis_fsu" -c "base genesis_fsu"

export COMPONENT="atmos"


##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}


####################################
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-${HOMEens_tracker}/exec}
export FIXens_tracker=${FIXens_tracker:-${HOMEens_tracker}/fix}
export USHens_tracker=${USHens_tracker:-${HOMEens_tracker}/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-${HOMEens_tracker}/scripts}
export BINens_tracker=${BINens_tracker:-${HOMEens_tracker}/ush/FSUgenesisPY/bin}
export PYTHONPATH=${USHens_tracker}/FSUgenesisPY:${PYTHONPATH}

##############################################
# Define COM and Data directories
##############################################
YMD=${PDY} HH=${cyc} generate_com -rx COM_ATMOS_GENESIS
YMD=${PDY} HH=${cyc} GRID="0p25" generate_com -rx COM_ATMOS_GRIB_0p25:COM_ATMOS_GRIB_GRID_TMPL

# The following variables are used by the tracker scripts which are outside
#   of global-workflow and therefore can't be standardized at this time
export COMIN=${COM_ATMOS_GRIB_0p25}
export gfsdir=${COM_ATMOS_GRIB_0p25}
export COMINgfs=${COM_ATMOS_GRIB_0p25}

export COMOUT=${COM_ATMOS_GENESIS}

export COMINsyn=${COMINsyn:-$(compath.py "${envir}/com/gfs/${gfs_ver}")/syndat}

##############################################
# Run relevant script
##############################################

#############################################################
# Execute the script
${SCRIPTens_tracker}/exgfs_fsu_genesis.sh
export err=$?; err_chk

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
