#!/bin/ksh
set -x

export RUN_ENVIR=${RUN_ENVIR:-"nco"}
export PS4='$SECONDS + '
date


#############################
# Source relevant config files
#############################
configs="base vrfy"
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done


##########################################
# Source machine runtime environment
##########################################
. $HOMEgfs/env/${machine}.env vrfy
status=$?
[[ $status -ne 0 ]] && exit $status


##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export job=${job:-"gfs_cyclone_tracker"}
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export jobid=${jobid:-"${outid}.o${pid}"}
if [ $RUN_ENVIR = "nco" ]; then
    export DATA="$DATAROOT/${job}.${pid}"
else
    export DATAROOT="$RUNDIR/$CDATE/$CDUMP"
    export DATA="$DATAROOT/$job"
fi
[[ -d $DATA ]] && rm -rf $DATA
mkdir -p $DATA
cd $DATA


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY


##############################################
# Define the Log File directory
##############################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}


##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}
if [ $RUN_ENVIR = "nco" ]; then
    export ROTDIR=${COMROOT:?}/$NET/$envir
fi


##############################################
# Define COM directories
##############################################
export ATCFdir=${COMROOTp1}/nhc/${envir}/atcf
export COMIN=${ROTDIR}/${RUN}.${PDY}/${cyc}
export COMOUT=${ROTDIR}/${RUN}.${PDY}/${cyc}
if [ ! -d ${COMOUT} ]; then mkdir -p $COMOUT; fi


##############################################
# Run relevant script
##############################################
env
msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"
$LOGSCRIPT

export cmodel=gfs
export FHMAX2=252
gfstrackhour1=180; gfstrackhour2=252
if [ $gfstrackhour1 -gt $FHMAX2 ]; then gfstrackhour1=$FHMAX2 ; fi
if [ $gfstrackhour2 -gt $FHMAX2 ]; then gfstrackhour2=$FHMAX2 ; fi

${PARATRKR:-$USHRELO/global_extrkr.sh}
status=$?
[[ $status -ne 0 ]] && exit $status

#    ${APRUNTRACK} ${PARATRKR:-$USHRELO/global_extrkr.sh} --gfs-last-hour $gfstrackhour1 --wait-for-data 900
#    cp $DATA/trak.gfso.atcfunix.$CDATE $COMOUT/gfso.$cycle.cyclone.trackatcfunix
# Run a second tracker for 252 hours for experimental ten day forecasts:
#    if [ $gfstrackhour2 -gt $gfstrackhour1 ]; then
#     export SENDNHC=NO
#     ${APRUNTRACK} ${PARATRKR:-$USHRELO/global_extrkr.sh} --gfs-last-hour $gfstrackhour2 --wait-for-data 900
#     cp $DATA/trak.gfso.atcfunix.$CDATE $COMOUT/gfso.$cycle.252hr.trackatcfunix
#    fi


##############################################
# Final processing
##############################################
cat $pgmout


msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"


##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0
