#!/bin/sh

########################################
# GFS AWIPS PRODUCT GENERATION
########################################

date
export PS4='$SECONDS + ' 
set -x

############################################
# Override some ecFlow environment variables
############################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${jobid}}

export DATAROOT=${DATAROOT:-/tmpnwprd1}

# keep the working directory or not
export KEEPDATA=${KEEPDATA:-NO}

############################################
# Working Directory
############################################
export DATA=${DATA:-${DATAROOT:?}/$jobid}
[ -d $DATA ] && rm -rf $DATA
mkdir -p $DATA
cd $DATA

############################################
# Output for executables
############################################
export pgmout=OUTPUT.$$

############################################
# Load the UTILITIES module
############################################
#### module load prod_util
#### module load grib_util

###########################################
# Run setpdy and initialize PDY variables
###########################################
export cycle=t${cyc}z 
setpdy.sh
. ./PDY

############################################
# SENDCOM=YES--Copy output file to /com
# SENDECF=YES--Allow to talk back to ECF
# SENDDBN=YES--Alert output file to TOC, set to NO for testing
############################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}  # need to set to NO for testing
#export SENDDBN_GB2=${SENDDBN_GB2:-YES}  # need to set to NO for testing
export SENDDBN_NTC=${SENDDBN_NTC:-YES}  # need to set to NO for testing

############################################
# Set up the NET and RUN
############################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}

############################################
# Specify HOME Directory 
############################################
export gfs_ver=${gfs_ver:-v15.0.0}
export HOMEgfs=${HOMEgfs:-${NWROOT}/gfs.${gfs_ver}}
export EXECgfs=$HOMEgfs/exec
export FIXgfs=$HOMEgfs/fix/wafs
export PARMgfs=$HOMEgfs/parm
export USHgfs=$HOMEgfs/ush
export SCRIPTSgfs=$HOMEgfs/scripts

################################################
# Set up the input/output directory
################################################
#### if [ $envir = "prod" ] || [ $envir = "para" ] ; then
####  export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/$RUN.$PDY}
#### else
####   export COMIN=${COMIN:-$COMROOT/${NET}/prod/$RUN.$PDY}
#### fi

export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/$RUN.$PDY/$cyc}
export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}/$cyc}
export PCOM=${PCOM:-$COMOUT/wmo}

if [ $SENDCOM = YES ] ; then
  mkdir -p $COMOUT $PCOM
fi

############################################
# print current environment
############################################
env

############################################
# Execute the script.
############################################
export MPIRUN=${MPIRUN:-mpirun}
${SCRIPTSgfs}/exgfs_wafs_grib2.sh.ecf
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY!"
postmsg $jlogfile "$msg"

############################################
# print exec output
############################################
if [ -e "$pgmout" ] ; then
  cat $pgmout
fi

############################################
# remove temporary working directory
############################################
if [ $KEEPDATA != YES ] ; then
    rm -rf $DATA
fi

date

