#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "vrfy" -c "base vrfy"

export RUN_ENVIR=${RUN_ENVIR:-"nco"}

export COMPONENT="atmos"


##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}


####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=YES
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-${HOMEens_tracker}/exec}
export FIXens_tracker=${FIXens_tracker:-${HOMEens_tracker}/fix}
export USHens_tracker=${USHens_tracker:-${HOMEens_tracker}/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-${HOMEens_tracker}/scripts}
export BINens_tracker=${BINens_tracker:-${HOMEens_tracker}/ush/FSUgenesisPY/bin}
export PYTHONPATH=${USHens_tracker}/FSUgenesisPY:${PYTHONPATH}

##############################################
# Define COM and Data directories
##############################################
export COMIN=${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}
export COMINgfs=${COMIN}
#export gfsdir=${COMINgfs}
export gfsdir=${ROTDIR}
export COMINgdas=${COMIN}
export gdasdir=${COMINgdas}
export COMOUT=${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}
export COMINsyn=${COMINsyn:-$(compath.py ${envir}/com/gfs/${gfs_ver})/syndat}

if [ ${RUN_ENVIR} = "nco" ]; then
    export COMOUThur=${COMROOTp1}/hur/${envir}/global
    export COMOUTatcf=${COMROOTp1}/nhc/${envir}/atcf
    mkdir -m 775 -p ${COMOUThur} ${COMOUTatcf}
else
#    export COMOUThur=$COMOUT
#    export COMOUTatcf=$COMOUT
    export COMOUThur=${DATA}
    export COMOUTatcf=${DATA}
fi

##############################################
# Run relevant script
##############################################

#############################################################
# Execute the script
${SCRIPTens_tracker}/exgfs_fsu_genesis.sh
export err=$?; err_chk

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
