#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" base awips


export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}


################################
# Set up the HOME directory
################################
export HOMEgfs=${HOMEgfs:-${PACKAGEROOT}/gfs.${gfs_ver}}
export USHgfs=${USHgfs:-${HOMEgfs}/ush}
export EXECgfs=${EXECgfs:-${HOMEgfs}/exec}
export PARMgfs=${PARMgfs:-${HOMEgfs}/parm}
export PARMwmo=${PARMwmo:-${HOMEgfs}/parm/wmo}
export PARMproduct=${PARMproduct:-${HOMEgfs}/parm/product}
export FIXgfs=${FIXgfs:-${HOMEgfs}/fix}

###################################
# Specify NET and RUN Name and model
####################################
export model=${model:-gfs}
export COMPONENT="atmos"

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-$(compath.py ${envir}/${NET}/${gfs_ver})/${RUN}.${PDY}/${cyc}/${COMPONENT}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${gfs_ver}/${RUN}.${PDY})/${cyc}/${COMPONENT}}
export COMOUTwmo=${COMOUTwmo:-${COMOUT}/wmo}

export SENDDBN=${SENDDBN:-NO}
export SENDAWIP=${SENDAWIP:-NO}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

if [ ${SENDCOM} = YES ] ; then
  mkdir -m 775 -p ${COMOUT} ${COMOUTwmo}
fi

export pgmout=OUTPUT.$$


########################################################
# Execute the script.
#   Forecast hours from F00 - F84  at 3-hour interval
#   Forecast hours from F90 - F240 at 6-hour interval
#########################################################

########################################################
# Execute the script.
${HOMEgfs}/scripts/exgfs_atmos_awips_20km_1p0deg.sh ${fcsthrs}
export err=$?; err_chk
########################################################

############################################
# print exec I/O output
############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

###################################
# Remove temp directories
###################################
if [ "${KEEPDATA}" != "YES" ] ; then
  rm -rf ${DATA}
fi

