#!/bin/sh
export PS4='$SECONDS + '
date
set -xa
########################################
# Runs GFS BUFR SOUNDINGS
########################################

#Specify whether the run is production or development
export envir=${envir:-prod}

############################
export MP_EUIDEVELOP=min
export KMP_STACKSIZE=2048m
export MPICH_ALLTOALL_THROTTLE=0
export MP_SINGLE_THREAD=yes
export MP_EAGER_LIMIT=65536
export MP_USE_BULK_XFER=no
export MP_COLLECTIVE_OFFLOAD=no
export MP_SHARED_MEMORY=yes
export MP_MPILIB=mpich2
export MP_LABELIO=yes

####################################
# obtain unique process id (pid) and make temp directories
export DATA=${DATA:-$DATAROOT/${jobid}}
mkdir $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export NET=${NET:-gfs}
export RUN=${RUN:-gfs}
export model=${model:-gfs}

###################################
# Set up the UTILITIES
###################################

export HOMEbufrsnd=${HOMEbufrsnd:-$NWROOT/gfs.${gfs_ver}}
export EXECbufrsnd=${EXECbufrsnd:-$HOMEbufrsnd/exec}
export FIXbufrsnd=${FIXbufrsnd:-$HOMEbufrsnd/fix/product}
export PARMbufrsnd=${PARMbufrsnd:-$HOMEbufrsnd/parm/product}
export USHbufrsnd=${USHbufrsnd:-$HOMEbufrsnd/ush}
export SCRbufrsnd=${SCRbufrsnd:-$HOMEbufrsnd/scripts}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

##############################
# Define COM Directories
##############################
export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}
export pcom=${pcom:-${COMOUT}/${cyc}/wmo}
mkdir -p $COMOUT $pcom
export COMAWP=${COMAWP:-${COMOUT}/${cyc}/nawips}
env

########################################################
# Execute the script.
$SCRbufrsnd/exgfs_postsnd.sh.ecf
########################################################

if [ -e "$pgmout" ] ; then
  cat $pgmout
fi

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0
