#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "postsnd" -c "base postsnd"


##############################################
# Set variables used in the exglobal script
##############################################

########################################
# Runs GFS BUFR SOUNDINGS
########################################

export model=${model:-gfs}
export SENDDBN=${SENDDBN:-YES}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

##############################
# Define COM Directories
##############################
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

YMD=${PDY} HH=${cyc} declare_from_tmpl -rx COM_ATMOS_HISTORY COM_ATMOS_BUFR \
  COM_ATMOS_WMO COM_ATMOS_GEMPAK

[[ ! -d ${COM_ATMOS_BUFR} ]] && mkdir -p "${COM_ATMOS_BUFR}"
[[ ! -d ${COM_ATMOS_GEMPAK} ]] && mkdir -p "${COM_ATMOS_GEMPAK}"
[[ ! -d ${COM_ATMOS_WMO} ]] && mkdir -p "${COM_ATMOS_WMO}"


########################################################
# Execute the script.
${SCRgfs}/exgfs_atmos_postsnd.sh
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0

