#! /usr/bin/env bash

############################################
# GFS_PGRB2_SPEC_GEMPAK PRODUCT GENERATION
############################################
source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "gempak_spec" -c "base"

###################################
# Specify NET and RUN Name and model
####################################
export COMPONENT="atmos"
export finc=3
export model=gfs
export EXT=""

# For half-degree P Grib files
#export DO_HD_PGRB=YES

##############################################
# Define COM directories
##############################################
YMD=${PDY} HH=${cyc} generate_com -rx COM_ATMOS_GOES
GRID=0p25 YMD=${PDY} HH=${cyc} generate_com -rx "COM_ATMOS_GEMPAK_0p25:COM_ATMOS_GEMPAK_TMPL"
if [[ ! -d "${COM_ATMOS_GEMPAK_0p25}" ]]; then mkdir -m 775 -p "${COM_ATMOS_GEMPAK_0p25}"; fi

export SENDDBN="${SENDDBN:-NO}"
export DBNROOT="${DBNROOT:-${UTILROOT}/fakedbn}"

#################################################################
# Execute the script for the regular grib
#################################################################
export DATA_SPECIAL="${DATA}/SPECIAL"
mkdir -p "${DATA_SPECIAL}"
cd "${DATA_SPECIAL}" || exit 1

export DBN_ALERT_TYPE=GFS_GOESSIM_GEMPAK
export RUN2=gfs_goessim
export GRIB=goessimpgrb2.0p25.f
export EXT=""
export fend=180
if (( fend > FHMAX_GFS )); then
  fend=${FHMAX_GFS}
fi
export finc=3
export fstart=0

echo "RUNS the Program"

########################################################
# Execute the script.
"${SCRgfs}/exgfs_atmos_goes_nawips.sh"

#################################################################
# Execute the script for the 221 grib

export DATA_SPECIAL221="${DATA}/SPECIAL221"
mkdir -p "${DATA_SPECIAL221}"
cd "${DATA_SPECIAL221}" || exit 1

export DBN_ALERT_TYPE=GFS_GOESSIM221_GEMPAK
export RUN2=gfs_goessim221
export GRIB=goessimpgrb2f
export EXT=".grd221"
export fend=180
if (( fend > FHMAX_GFS )); then
  fend=${FHMAX_GFS}
fi
export finc=3
export fstart=0

echo "RUNS the Program"

########################################################
# Execute the script.
"${SCRgfs}/exgfs_atmos_goes_nawips.sh"
export err=$?; err_chk
########################################################

echo "end of program"
cd "${DATA}" || exit 1
echo "######################################"
echo "  SPECIAL.OUT "
echo "######################################"

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]] ; then
  rm -rf "${DATA}"
fi

