#!/bin/sh

set -xa
export PS4='$SECONDS + '
date

############################################
# GFS GEMPAK META PRODUCT GENERATION
############################################

export LAUNCH_MODE=MPI
NWROOT=${NWROOT:?}
DATAROOT=${DATAROOT:?}
COMROOT=${COMROOT:?}

###############################################
# Set MP variables
###############################################
export OMP_NUM_THREADS=1
export MP_LABELIO=yes
export MP_PULSE=0
export MP_DEBUG_NOTIMEOUT=yes

#############################
# Source relevant config files
#############################
configs="base gempak_meta"
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done

##########################################
# Source machine runtime environment
##########################################
. $HOMEgfs/env/${machine}.env gempak
status=$?
[[ $status -ne 0 ]] && exit $status

###########################################################
# obtain unique process id (pid) and make temp directory
###########################################################
export job=${job:-"gempak_meta"}
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export jobid=${jobid:-"${outid}.o${pid}"}
if [ $RUN_ENVIR = "nco" ]; then
    export DATA="$DATAROOT/$jobid"
else
    export DATAROOT="$RUNDIR/$CDATE/$CDUMP"
    export DATA="$DATAROOT/$job"
fi
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

######################################
# Set up the cycle variable
######################################
export cycle=${cycle:-t${cyc}z}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY

############################################
# SENDCOM=YES--Copy output file to /com
# SENDECF=YES--Allow to talk back to ECF
# SENDDBN=YES--Alert output file to TOC
# KEEPDATA=NO--Remove temporary working
############################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

################################
# Set up the HOME directory
################################
export HOMEgfs=${HOMEgfs:-${NWROOT}/gfs.${gfs_ver}}
export EXECgfs=${EXECgfs:-$HOMEgfs/exec}
export PARMgfs=${PARMgfs:-$HOMEgfs/parm}
export FIXgfs=${FIXgfs:-$HOMEgfs/gempak/fix}
export USHgfs=${USHgfs:-$HOMEgfs/gempak/ush}
export SRCgfs=${SRCgfs:-$HOMEgfs/scripts}

######################################
# Set up the GEMPAK directory
#######################################
export HOMEgempak=${HOMEgempak:-${NWROOTp1}/gempak}
export FIXgempak=${FIXgempak:-$HOMEgempak/fix}
export USHgempak=${USHgempak:-$HOMEgempak/ush}

cp  $FIXgfs/datatype.tbl datatype.tbl

#############################################
#set the fcst hrs for all the cycles
#############################################
export fhbeg=00
export fhend=384
export fhinc=12

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}
export model=${model:-gfs}

##############################################
# Set up model and cycle specific variables
##############################################
export DBN_ALERT_TYPE=GFS_METAFILE

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-$(compath.py ${NET}/${envir}/${RUN}.${PDY})/${cyc}/nawips}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}/nawips/meta}
export COMINgempak=${COMINgempak:-${COMROOT}/${NET}/${envir}}

export COMINukmet=${COMINukmet:-$(compath.py nawips/${envir}/ukmet)}
export COMINecmwf=${COMINecmwf:-$(compath.py nawips/${envir}/ecmwf)}
export COMINnam=${COMINnam:-$(compath.py nawips/${envir}/nam)}

msg="Begin job for $job"
postmsg "$jlogfile" "$msg"

if [ $SENDCOM = YES ] ; then
  mkdir -m 775 -p $COMOUT
fi

export pgmout=OUTPUT.$$

env

########################################################
# Execute the script.
$SRCgfs/exgfs_gempak_meta.sh.ecf
export err=$?; err_chk
########################################################

chmod 775 $DATA/poescript
cat  $DATA/poescript
export MP_PGMMODEL=mpmd
export MP_CMDFILE=$DATA/poescript

ntasks=${NTASKS_META:-$(cat $DATA/poescript | wc -l)}
ptile=${PTILE_META:-4}
threads=${NTHREADS_META:-1}
export OMP_NUM_THREADS=$threads
APRUN="mpirun -n $ntasks cfp "

APRUN_METACFP=${APRUN_METACFP:-$APRUN}
APRUNCFP=$(eval echo $APRUN_METACFP)

$APRUNCFP $DATA/poescript
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY!"
postmsg $jlogfile "$msg"

############################################
# print exec I/O output
############################################
if [ -e "$pgmout" ] ; then
  cat $pgmout
fi

###################################
# Remove temp directories
###################################
if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
