#!/bin/ksh
set -x

export RUN_ENVIR=${RUN_ENVIR:-"nco"}
export PS4='$SECONDS + '
date


#############################
# Source relevant config files
#############################
configs="base vrfy"
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done


##########################################
# Source machine runtime environment
##########################################
. $HOMEgfs/env/${machine}.env vrfy
status=$?
[[ $status -ne 0 ]] && exit $status


##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
if [ $RUN_ENVIR = "nco" ]; then
    export DATA=${DATA:-${DATAROOT}/${jobid:?}}
else
    export job="gfs_cyclone_genesis"
    export DATA="$DATAROOT/${job}$$"
    [[ -d $DATA ]] && rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY


####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}


##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}
if [ $RUN_ENVIR = "nco" ]; then
    export ROTDIR=${COMROOT:?}/$NET/$envir
fi

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=YES
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${NWROOT:?}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-$HOMEens_tracker/scripts}

##############################################
# Define COM directories
##############################################
export COMIN=${ROTDIR}/${RUN}.${PDY}/${cyc}
export gfsdir=${COMIN}
export COMINgfs=${COMIN}
export COMOUT=${ROTDIR}/${RUN}.${PDY}/${cyc}

export JYYYY=`echo ${PDY} | cut -c1-4`
#export COMINgenvit=${COMINgenvit:-${COMOUT}/genesis_vital_${JYYYY}}
#export COMOUTgenvit=${COMOUTgenvit:-${COMOUT}/genesis_vital_${JYYYY}}
export COMINgenvit=${COMINgenvit:-${DATA}/genesis_vital_${JYYYY}}
export COMOUTgenvit=${COMOUTgenvit:-${DATA}/genesis_vital_${JYYYY}}
export COMINsyn=${COMINsyn:-$(compath.py arch/prod/syndat)}

mkdir -m 775 -p $COMOUTgenvit

##############################################
# Run relevant script
##############################################
env
msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"
$LOGSCRIPT


${SCRIPTens_tracker}/exgfs_tc_genesis.sh
export err=$?; err_chk

##############################################
# Final processing
##############################################
if [ -e "$pgmout" ] ; then
  cat $pgmout
fi


msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0
