#! /usr/bin/env bash

source "$HOMEgfs/ush/preamble.sh"

export RUN_ENVIR=${RUN_ENVIR:-"nco"}

#############################
# Source relevant config files
#############################
configs="base postsnd"
export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done


##########################################
# Source machine runtime environment
##########################################
. $HOMEgfs/env/${machine}.env postsnd
status=$?
[[ $status -ne 0 ]] && exit $status


##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY

##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}
if [ $RUN_ENVIR = "nco" ]; then
    export ROTDIR=${COMROOT:?}/$NET/$envir
fi


########################################
# Runs GFS BUFR SOUNDINGS
########################################

export model=${model:-gfs}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

###################################
# Set up the source directories
###################################

export HOMEbufrsnd=${HOMEbufrsnd:-$HOMEgfs}
export EXECbufrsnd=${EXECbufrsnd:-$HOMEbufrsnd/exec}
export FIXbufrsnd=${FIXbufrsnd:-$HOMEbufrsnd/fix/product}
export PARMbufrsnd=${PARMbufrsnd:-$HOMEbufrsnd/parm/product}
export USHbufrsnd=${USHbufrsnd:-$HOMEbufrsnd/ush}
export SCRbufrsnd=${SCRbufrsnd:-$HOMEbufrsnd/scripts}

##############################
# Define COM Directories
##############################
export COMIN=${COMIN:-$ROTDIR/${CDUMP}.${PDY}/${cyc}/atmos}
export COMOUT=${COMOUT:-$ROTDIR/${CDUMP}.${PDY}/${cyc}/atmos}
export pcom=${pcom:-${COMOUT}/wmo}
export COMAWP=${COMAWP:-${COMOUT}/gempak}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}
[[ ! -d $COMOUT ]] && mkdir -p $COMOUT
[[ ! -d $pcom ]] && mkdir -p $pcom
[[ ! -d $COMAWP ]] && mkdir -p $COMAWP


########################################################
# Execute the script.
$SCRbufrsnd/exgfs_atmos_postsnd.sh
status=$?
[[ $status -ne 0 ]] && exit $status


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "$pgmout" ] ; then
  cat $pgmout
fi

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA


exit 0

