#! /usr/bin/env bash

# TODO (#1225) This job is not part of the rocoto suite

############################################
# GFS PGRB2_SPECIAL_POST PRODUCT GENERATION
############################################
source "${HOMEgfs}/ush/jjob_header.sh" -e "npoess" -c "base npoess"

export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}

###################################
# Specify NET and RUN Name and model
####################################
export model=${model:-gfs}

##############################################
# Define COM directories
##############################################
export SENDDBN=${SENDDBN:-NO}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL \
    COMOUT_ATMOS_GOES:COM_ATMOS_GOES_TMPL
GRID="0p50" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_ATMOS_GRIB_0p50:COM_ATMOS_GRIB_GRID_TMPL

mkdir -m 775 -p "${COMOUT_ATMOS_GOES}"

#############################################################
# Execute the script
"${SCRgfs}/exgfs_atmos_grib2_special_npoess.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
  err_exit
fi
#############################################################

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]] ; then
  rm -rf "${DATA}"
fi

