#!/bin/sh
export PS4='$SECONDS + '
date
set -xa
########################################
# Runs GFS BUFR SOUNDINGS
########################################

NWROOT=${NWROOT:?}
DATAROOT=${DATAROOT:?}
COMROOT=${COMROOT:?}

#############################
# Source relevant config files
#############################
configs="base postsnd"
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done

##########################################
# Source machine runtime environment
##########################################
. $HOMEgfs/env/${machine}.env postsnd
status=$?
[[ $status -ne 0 ]] && exit $status

#########################################
#Specify whether the run is production or development
#########################################
export envir=${envir:-prod}

############################
export MP_EUIDEVELOP=min
export KMP_STACKSIZE=2048m
export MPICH_ALLTOALL_THROTTLE=0
export MP_SINGLE_THREAD=yes
export MP_EAGER_LIMIT=65536
export MP_USE_BULK_XFER=no
export MP_COLLECTIVE_OFFLOAD=no
export MP_SHARED_MEMORY=yes
export MP_MPILIB=mpich2
export MP_LABELIO=yes

####################################
# Determine Job Output Name on System
# obtain unique process id (pid) and make temp directories
export job=${job:-"postsnd"}
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export jobid=${jobid:-"${outid}.o${pid}"}
export pgmout="OUTPUT.${pid}"
if [ $RUN_ENVIR = "nco" ]; then
    export DATA="$DATAROOT/$jobid"
else
    export DATAROOT="$RUNDIR/$CDATE/$CDUMP"
    export DATA="$DATAROOT/$job"
fi
export DATA=${DATA:-$DATAROOT/${jobid}}
mkdir $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

export NET=${NET:-gfs}
export RUN=${RUN:-gfs}
export model=${model:-gfs}

###################################
# Set up the UTILITIES
###################################

export HOMEbufrsnd=${HOMEbufrsnd:-$NWROOT/gfs.${gfs_ver}}
export EXECbufrsnd=${EXECbufrsnd:-$HOMEbufrsnd/exec}
export FIXbufrsnd=${FIXbufrsnd:-$HOMEbufrsnd/fix/product}
export PARMbufrsnd=${PARMbufrsnd:-$HOMEbufrsnd/parm/product}
export USHbufrsnd=${USHbufrsnd:-$HOMEbufrsnd/ush}
export SCRbufrsnd=${SCRbufrsnd:-$HOMEbufrsnd/scripts}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

##############################
# Define COM Directories
##############################
export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}
export pcom=${pcom:-${COMOUT}/${cyc}/wmo}
mkdir -p $COMOUT $pcom
export COMAWP=${COMAWP:-${COMOUT}/${cyc}/nawips}
env

########################################################
# Execute the script.
$SCRbufrsnd/exgfs_postsnd.sh.ecf
########################################################

cat $pgmout

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0
