#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "metp" -c "base metp"

###############################################################
## Abstract:
## Inline METplus verification and diagnostics driver script
## HOMEgfs   : /full/path/to/workflow
## EXPDIR : /full/path/to/config/files
## PDY    : current date (YYYYMMDD)
## RUN    : cycle name (gdas / gfs)
## cyc    : current cycle (HH)
## SDATE_GFS  : first date of GFS cycle (YYYYMMDDHHMM)
## METPCASE : METplus verification use case (g2g1 | g2o1 | pcp1)
###############################################################

VDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${VRFYBACK_HRS} hours")
export VDATE=${VDATE:0:8}
export CDATE=${PDY}${cyc}

# Since this is currently a one-element list, shellcheck things we would rather run this as a command
# shellcheck disable=SC2041
for grid in '1p00'; do
    prod_dir="COM_ATMOS_GRIB_${grid}"
    GRID=${grid} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "${prod_dir}:COM_ATMOS_GRIB_GRID_TMPL"
done

# TODO: If none of these are on, why are we running this job?
if [[ "${RUN_GRID2GRID_STEP1}" == "YES" || "${RUN_GRID2OBS_STEP1}" == "YES" || "${RUN_PRECIP_STEP1}" == "YES" ]]; then
    # Override the -e in VERIF_GLOBALSH's shebang and un-export SHELLOPTS
    # TODO: clean up the verif-global script so it does not raise false-positive errors
    set +eu
    export -n SHELLOPTS
    bash -x "${VERIF_GLOBALSH}"
    err=$?
    if [[ ${err} -ne 0 ]]; then
        exit "${err}"
    fi
fi

if [[ ${KEEPDATA:-"NO"} == "NO" ]]; then rm -rf "${DATAROOT}"; fi # TODO: This should be $DATA
