#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "vrfy" -c "base vrfy"


# TODO (#1220) Determine if this is still needed
export RUN_ENVIR=${RUN_ENVIR:-"nco"}

export COMPONENT="atmos"

##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export cmodel=${RUN}

####################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDCOM=YES
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEROOT}/ens_tracker.${ens_tracker_ver}}
export EXECens_tracker=${EXECens_tracker:-${HOMEens_tracker}/exec}
export FIXens_tracker=${FIXens_tracker:-${HOMEens_tracker}/fix}
export USHens_tracker=${USHens_tracker:-${HOMEens_tracker}/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-${HOMEens_tracker}/scripts}

##############################################
# Define COM directories
##############################################
export COMIN=${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}
export gfsdir=${COMIN}
export COMINgfs=${COMIN}
export COMOUT=${ROTDIR}/${RUN}.${PDY}/${cyc}/${COMPONENT}

export JYYYY=$(echo ${PDY} | cut -c1-4)
export COMINgenvit=${COMINgenvit:-${COMOUT}/genesis_vital_${JYYYY}}
export COMOUTgenvit=${COMOUTgenvit:-${COMOUT}/genesis_vital_${JYYYY}}

export COMINsyn=${COMINsyn:-$(compath.py ${envir}/com/gfs/${gfs_ver})/syndat}

mkdir -m 775 -p ${COMOUTgenvit}

##############################################
# Run relevant script
##############################################

${SCRIPTens_tracker}/exgfs_tc_genesis.sh
export err=$?; err_chk

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
