#!/bin/bash
source "${HOMEgfs}/ush/preamble.sh"
export DATA="${DATAROOT}/${RUN}marinebmat_${cyc}"
export DATA=${DATA:-${DATAROOT}/${RUN}marinebmat_${cyc}}
# source config.base, config.ocnanal and config.ocnanalbmat
# and pass marinebmat to ${machine}.env
source "${HOMEgfs}/ush/jjob_header.sh" -e "marinebmat" -c "base ocnanal marinebmat"

##############################################
# Set variables used in the script
##############################################
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
gPDY=${GDATE:0:8}
gcyc=${GDATE:8:2}
GDUMP="gdas"


##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
# TODO: This is temporary, the plan is to prepare the bmatrix at the end of the
#       cycle, so the backgrounds should be from the current cycle, not the previous
RUN=${GDUMP} YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
   COMIN_OCEAN_HISTORY_PREV:COM_OCEAN_HISTORY_TMPL \
   COMIN_ICE_HISTORY_PREV:COM_ICE_HISTORY_TMPL

YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
   COMOUT_OCEAN_BMATRIX:COM_OCEAN_BMATRIX_TMPL \
   COMOUT_ICE_BMATRIX:COM_ICE_BMATRIX_TMPL

mkdir -p "${COMOUT_OCEAN_BMATRIX}"
mkdir -p "${COMOUT_ICE_BMATRIX}"

###############################################################
# Run relevant script

EXSCRIPT=${GDASMARINEBMATRUNPY:-${SCRgfs}/exglobal_marine_bmat_run.py}
${EXSCRIPT}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

exit 0
