#! /usr/bin/env bash

# TODO (#1227) This job is not used in the rocoto suite

source "${HOMEgfs}/ush/jjob_header.sh" -e "post" -c "base post"


####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}

###########################
# Set up EXT variable
###########################
export EXT_FCST=NO

YMD=${PDY} HH=${cyc} declare_from_tmpl -rx COMIN_ATMOS_HISTORY:COM_ATMOS_HISTORY_TMPL

########################################################
# Execute the script.
${SCRgfs}/exglobal_atmos_pmgr.sh && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi
########################################################

