#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "upp" -c "base upp"

##############################################
# Set variables used in the exglobal script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################

# Construct COM variables from templates
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
   COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
   COMIN_ATMOS_HISTORY:COM_ATMOS_HISTORY_TMPL \
   COMOUT_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL
if [[ ! -d ${COMOUT_ATMOS_MASTER} ]]; then mkdir -p "${COMOUT_ATMOS_MASTER}"; fi


###############################################################
# Run relevant exglobal script

"${SCRgfs}/exglobal_atmos_upp.py"
status=$?
(( status != 0 )) && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit 1
[[ "${KEEPDATA:-NO}" = "NO" ]] && rm -rf "${DATA}"


exit 0
