#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "atmos_products" -c "base atmos_products"


##############################################
# Begin JOB SPECIFIC work
##############################################

# Construct COM variables from templates
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
  COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
  COMIN_ATMOS_HISTORY:COM_ATMOS_HISTORY_TMPL \
  COMIN_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL

for grid in '0p25' '0p50' '1p00'; do
  prod_dir="COMOUT_ATMOS_GRIB_${grid}"
  GRID=${grid} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "${prod_dir}:COM_ATMOS_GRIB_GRID_TMPL"
  if [[ ! -d "${!prod_dir}" ]]; then mkdir -m 775 -p "${!prod_dir}"; fi
done

# Variables used in this job
export PREFIX="${RUN}.t${cyc}z."

###############################################################
# Run exglobal script
"${SCRgfs}/exglobal_atmos_products.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit 1
if [[ "${KEEPDATA:-NO}" == "NO" ]]; then
    rm -rf "${DATA}"
fi


exit 0
