#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "waveawipsgridded" -c "base waveawipsgridded"

export COMPONENT="wave"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

###################################
# Set COM Paths
###################################
export COMIN=${COMIN:-$(compath.py ${envir}/${NET}/${gfs_ver})/${RUN}.${PDY}/${cyc}/${COMPONENT}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${gfs_ver}/${RUN}.${PDY})/${cyc}/${COMPONENT}}
export PCOM=${PCOM:-${COMOUT}/wmo}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-YES}
export SENDDBN=${SENDDBN:-NO}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

if [ ${SENDCOM} = YES ]; then
  mkdir -p ${COMOUT} ${PCOM}
fi

###################################
# Execute the Script
###################################
${HOMEgfs}/scripts/exgfs_wave_prdgen_gridded.sh
status=$?
[[ ${status} -ne 0 ]] && exit ${status}

###################################
# Remove temp directories
###################################
cd ${DATAROOT}
if [ "${KEEPDATA}" != "YES" ]; then
  rm -rf ${DATA}
fi


exit 0

