#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" base wavegempak

export COMPONENT="wave"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

###################################
# Set COM Paths
export COMIN=${COMIN:-$(compath.py ${envir}/${NET}/${gfs_ver})/${RUN}.${PDY}/${cyc}/${COMPONENT}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${gfs_ver}/${RUN}.${PDY})/${cyc}/${COMPONENT}/gempak}

export DBN_ALERT_TYPE=GFS_WAVE_GEMPAK
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

if [ ${SENDCOM} = YES ] ; then
  mkdir -m 775 -p ${COMOUT}
fi


########################################################
# Execute the script.
${HOMEgfs}/scripts/exgfs_wave_nawips.sh
status=$?
[[ ${status} -ne 0 ]] && exit ${status}
###################################

# Remove temp directories
cd ${DATAROOT}
if [ "${KEEPDATA}" != "YES" ]; then
  rm -rf ${DATA}
fi

exit 0
