#! /usr/bin/env bash

export WIPE_DATA="NO"
export DATA=${DATA:-${DATAROOT}/${RUN}aeroanl_${cyc}}
source "${HOMEgfs}/ush/jjob_header.sh" -e "aeroanlfinal" -c "base aeroanl aeroanlfinal"

##############################################
# Set variables used in the script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_CHEM_ANALYSIS:COM_CHEM_ANALYSIS_TMPL \
    COMOUT_CONF:COM_CONF_TMPL \
    COMOUT_ATMOS_RESTART:COM_ATMOS_RESTART_TMPL

###############################################################
# Run relevant script

EXSCRIPT=${GDASAEROFINALPY:-${SCRgfs}/exglobal_aero_analysis_finalize.py}
${EXSCRIPT} && true
export err=$?
err_chk

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" && true
export err=$?
err_chk
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
