#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "extractvars" -c "base extractvars"

# Set COM Paths
for grid in '0p25' '0p50' '1p00'; do
  prod_dir="COMIN_ATMOS_GRIB_${grid}"
  GRID=${grid} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx "${prod_dir}:COM_ATMOS_GRIB_GRID_TMPL"
  if [[ ! -d "${!prod_dir}" ]]; then mkdir -p "${!prod_dir}"; fi
done

for grdID in ${wavepostGRD} ${waveinterpGRD}; do
    case ${grdID} in
        glo_15mxt) GRDRES=0p25;;
        reg025) GRDRES=0p25;;
        glo_025) GRDRES=0p25;;
        glo_100) GRDRES=1p00;;
        glo_200) GRDRES=2p00;;
        glo_500) GRDRES=5p00;;
        glo_30mxt) GRDRES=0p50;;
        glo_30m) GRDRES=0p50;;
        at_10m) GRDRES=0p16;;
        ep_10m) GRDRES=0p16 ;;
        wc_10m) GRDRES=0p16;;
        ak_10m) GRDRES=0p16;;
        ant_9km) GRDRES=9km;;
        glo_10m) GRDRES=0p16;;
        gnh_10m) GRDRES=0p16;;
        gsh_15m) GRDRES=0p25;;
        glo_15m) GRDRES=0p25;;
        ao_20m) GRDRES=0p33;;
        so_20m) GRDRES=0p33;;
        gwes_30m) GRDRES=0p50;;
        *)
        echo "FATAL ERROR: No grid specific wave config values exist for ${grdID}. Aborting."
        exit 1;;
    esac
    prod_dir="COMIN_WAVE_GRID_${GRDRES}"
    YMD=${PDY} HH=${cyc} GRID=${GRDRES} declare_from_tmpl -rx \
    "${prod_dir}:COM_WAVE_GRID_RES_TMPL"
    if [[ ! -d "${!prod_dir}" ]]; then mkdir -p "${!prod_dir}"; fi
done



YMD="${PDY}" HH="${cyc}" declare_from_tmpl -rx \
    "COMIN_OCEAN_HISTORY:COM_OCEAN_HISTORY_TMPL" \
    "COMIN_OCEAN_GRIB:COM_OCEAN_GRIB_TMPL" \
    "COMIN_OCEAN_NETCDF:COM_OCEAN_NETCDF_TMPL" \
    "COMIN_ICE_HISTORY:COM_ICE_HISTORY_TMPL" \
    "COMIN_ICE_GRIB:COM_ICE_GRIB_TMPL" \
    "COMIN_ICE_NETCDF:COM_ICE_NETCDF_TMPL" \
    "COMIN_WAVE_GRID:COM_WAVE_GRID_TMPL"

if [[ "${DO_ATM}" == "YES" ]]; then
  if [[ ! -d "${ARC_RFCST_PROD_ATMOS_F2D}" ]]; then mkdir -p "${ARC_RFCST_PROD_ATMOS_F2D}"; fi
  if [[ ! -d "${ARC_RFCST_PROD_ATMOS_F3D}" ]]; then mkdir -p "${ARC_RFCST_PROD_ATMOS_F3D}"; fi
fi
if [[ "${DO_OCN}" == "YES" ]]; then
  if [[ ! -d "${ARC_RFCST_PROD_OCN}" ]]; then mkdir -p "${ARC_RFCST_PROD_OCN}"; fi
fi
if [[ "${DO_ICE}" == "YES" ]]; then
  if [[ ! -d "${ARC_RFCST_PROD_ICE}" ]]; then mkdir -p "${ARC_RFCST_PROD_ICE}"; fi
fi
if [[ "${DO_WAVE}" == "YES" ]]; then
  if [[ ! -d "${ARC_RFCST_PROD_WAV}" ]]; then mkdir -p "${ARC_RFCST_PROD_WAV}"; fi
fi

# Execute the Script
"${SCRgfs}/exglobal_extractvars.sh"
status=$?
(( status != 0 )) && exit "${status}"

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
[[ "${KEEPDATA}" = "NO" ]] && rm -rf "${DATA}"

exit 0
