#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "wavepostbndpntbll" -c "base wave wavepostsbs wavepostbndpntbll"

export COMPONENT="wave"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

export CDATE=${PDY}${cyc}

export MP_PULSE=0

# Path to HOME Directory
export FIXwave=${FIXwave:-${HOMEgfs}/fix/fix_wave_${NET}}
export PARMwave=${PARMwave:-${HOMEgfs}/parm/wave}
export USHwave=${USHwave:-${HOMEgfs}/ush}
export EXECwave=${EXECwave:-${HOMEgfs}/exec}

# Set COM Paths and GETGES environment
export COMIN=${COMIN:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}}
export COMOUT=${COMOUT:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}}


mkdir -p ${COMOUT}/station


# Set wave model ID tag to include member number
# if ensemble; waveMEMB var empty in deterministic
# Set wave model ID tag to include member number
# if ensemble; waveMEMB var empty in deterministic
membTAG='p'
if [ "${waveMEMB}" == "00" ]; then membTAG='c'; fi
export membTAG
export WAV_MOD_TAG=${CDUMP}wave${waveMEMB}

export CFP_VERBOSE=1

export FHMAX_WAV_PNT=${FHMAX_WAV_IBP}
export DOSPC_WAV='NO' # Spectral post
export DOBLL_WAV='YES' # Bulletin post
export DOBNDPNT_WAV='YES'  #boundary points

# Execute the Script
${HOMEgfs}/scripts/exgfs_wave_post_pnt.sh
err=$?
if [ ${err} -ne 0 ]; then
  echo "FATAL ERROR: ex-script of GFS_WAVE_POST_PNT failed!"
  exit ${err}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
