#!/bin/ksh -x

export RUN_ENVIR=${RUN_ENVIR:-"nco"}
export PS4='$SECONDS + '
date


#############################
# Source relevant config files
#############################
export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
export vefy_cfg=${vefy_cfg:-vrfy}
configs="base ${vefy_cfg}"
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done

###############################################################
echo
echo "=============== START TO SOURCE MACHINE RUNTIME ENVIRONMENT ==============="
. $BASE_ENV/${machine}.env vrfy
status=$?
[[ $status -ne 0 ]] && exit $status

##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}

##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"

##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


##############################################
# Set variables used in the script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gfs"}}
export COMPONENT=${COMPONENT:-atmos}
export CDATEm1=$($NDATE -24 $CDATE)
export PDYm1=$(echo $CDATEm1 | cut -c1-8)
export COMIN="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
export DATAROOT="$RUNDIR/$CDATE/$CDUMP/vrfy"
[[ -d $DATAROOT ]] && rm -rf $DATAROOT
mkdir -p $DATAROOT

###############################################################
echo
echo "=============== START TO GENERATE QUARTER DEGREE GRIB1 FILES ==============="
if [ $MKPGB4PRCP = "YES" -a $CDUMP = "gfs" ]; then
    nthreads_env=${OMP_NUM_THREADS:-1} # get threads set in env
    export OMP_NUM_THREADS=1
    cd $COMIN
    fhmax=${vhr_rain:-$FHMAX_GFS}
    fhr=0
    while [ $fhr -le $fhmax ]; do
       fhr2=$(printf %02i $fhr)
       fhr3=$(printf %03i $fhr)
       fname=${CDUMP}.t${cyc}z.sfluxgrbf$fhr3.grib2
       fileout=$ARCDIR/pgbq${fhr2}.${CDUMP}.${CDATE}.grib2
       $WGRIB2 $fname -match "(:PRATE:surface:)|(:TMP:2 m above ground:)" -grib $fileout
       (( fhr = $fhr + 6 ))
    done
    export OMP_NUM_THREADS=$nthreads_env # revert to threads set in env
fi

###############################################################
echo
echo "=============== START TO RUN FIT2OBS VERIFICATION ==============="
if [ $VRFYFITS = "YES" -a $CDUMP = $CDFNL -a $CDATE != $SDATE ]; then

    export CDUMPFCST=$VDUMP
    export TMPDIR="$RUNDIR/$CDATE/$CDUMP"
    [[ ! -d $TMPDIR ]] && mkdir -p $TMPDIR

    xdate=$($NDATE -${VBACKUP_FITS} $CDATE)
    export RUN_ENVIR_SAVE=$RUN_ENVIR
    export RUN_ENVIR=$OUTPUT_FILE
    export COMDAY=${COMDAY:-${ROTDIR}/logs/${CDATE}}
    export OBSDIR=$(compath.py prod/obsproc/${obsproc_ver})
    export COM_PRP='$OBSDIR/gdas.$pdy/$cyc/atmos'
    export COM_INA='$ROTDIR/gdas.$pdy/$cyc/atmos'
    export COM_INF='$ROTDIR/vrfyarch/gfs.$fdy/$fzz'
    export RUN_ENVIR=netcdf
    export ACPROFit=YES
    export CONVNETC=YES

    $PREPQFITSH $PSLOT $xdate $ROTDIR $ARCDIR $TMPDIR

    export RUN_ENVIR=$RUN_ENVIR_SAVE

fi

###############################################################
echo
echo "=============== START TO RUN VSDB STEP1, VERIFY PRCIP AND GRID2OBS ==============="
if [ $CDUMP = "gfs" ]; then

    if [ $VSDB_STEP1 = "YES" -o $VRFYPRCP = "YES" -o $VRFYG2OBS = "YES" ]; then

        xdate=$(echo $($NDATE -${BACKDATEVSDB} $CDATE) | cut -c1-8)
        export ARCDIR1="$NOSCRUB/archive"
        export rundir="$RUNDIR/$CDUMP/$CDATE/vrfy/vsdb_exp"
        export COMROT="$ARCDIR1/dummy"

        #### $VSDBJOBSH $VSDBSH $xdate $vlength $cyc $PSLOT $CDATE $CDUMP $gfs_cyc $rain_bucket $machine
    fi
fi

###############################################################
echo
echo "=============== START TO RUN RADMON DATA EXTRACTION ==============="
if [ $VRFYRAD = "YES" -a $CDUMP = $CDFNL -a $CDATE != $SDATE ]; then

    export EXP=$PSLOT
    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
    export TANKverf_rad="$TANKverf/stats/$PSLOT/$CDUMP.$PDY"
    export TANKverf_radM1="$TANKverf/stats/$PSLOT/$CDUMP.$PDYm1"
    export MY_MACHINE=$machine

    $VRFYRADSH

fi

###############################################################
echo
echo "=============== START TO RUN OZMON DATA EXTRACTION ==============="
if [ $VRFYOZN = "YES" -a $CDUMP = $CDFNL -a $CDATE != $SDATE ]; then

    export EXP=$PSLOT
    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
    export TANKverf_ozn="$TANKverf_ozn/stats/$PSLOT/$CDUMP.$PDY"
    export TANKverf_oznM1="$TANKverf_ozn/stats/$PSLOT/$CDUMP.$PDYm1"
    export MY_MACHINE=$machine

    $VRFYOZNSH

fi

###############################################################
echo
echo "=============== START TO RUN MINMON ==============="
if [ $VRFYMINMON = "YES" -a $CDATE != $SDATE ]; then

    export COMOUT="$ROTDIR/$CDUMP.$PDY/$cyc/$COMPONENT"
    export M_TANKverfM0="$M_TANKverf/stats/$PSLOT/$CDUMP.$PDY"
    export M_TANKverfM1="$M_TANKverf/stats/$PSLOT/$CDUMP.$PDYm1"
    export MY_MACHINE=$machine

    $VRFYMINSH

fi

################################################################################
echo
echo "=============== START TO RUN CYCLONE TRACK VERIFICATION ==============="
if [ $VRFYTRAK = "YES" ]; then

    export COMINsyn=${COMINsyn:-$(compath.py ${envir}/com/gfs/${gfs_ver})/syndat}

    $TRACKERSH

fi


################################################################################
echo
echo "=============== START TO RUN CYCLONE GENESIS VERIFICATION ==============="
if [ $VRFYGENESIS = "YES" -a $CDUMP = "gfs" ]; then
    $GENESISSH
fi


################################################################################
echo
echo "=============== START TO RUN CYCLONE GENESIS VERIFICATION (FSU) ==============="
if [ $VRFYFSU = "YES" -a $CDUMP = "gfs" ]; then
    $GENESISFSU
fi

###############################################################
# Force Exit out cleanly
if [ ${KEEPDATA:-"NO"} = "NO" ] ; then rm -rf $DATAROOT ; fi
exit 0

echo "ENDED NORMALLY."

##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0

