#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "esnowanl" -c "base esnowanl"

##############################################
# Set variables used in the script
##############################################
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDUMP="gdas"
export GDUMP
CDUMP=${RUN/enkf}
export CDUMP

##############################################
# Begin JOB SPECIFIC work
##############################################
# Generate COM variables from templates
RUN=${CDUMP} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_OBS:COM_OBS_TMPL
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
    COMOUT_CONF:COM_CONF_TMPL

for imem in $(seq 1 "${NMEM_ENS}"); do
    memchar="mem$(printf %03i "${imem}")"
    MEMDIR=${memchar} YMD=${PDY} HH=${cyc} declare_from_tmpl \
        COMOUT_SNOW_ANALYSIS:COM_SNOW_ANALYSIS_TMPL
    mkdir -p "${COMOUT_SNOW_ANALYSIS}"
done

MEMDIR="ensstat" YMD=${PDY} HH=${cyc} declare_from_tmpl -x\
    COMOUT_SNOW_ANALYSIS:COM_SNOW_ANALYSIS_TMPL

mkdir -p "${COMOUT_SNOW_ANALYSIS}" "${COMOUT_CONF}"

###############################################################
# Run relevant script

EXSCRIPT=${SNOWANLPY:-${SCRgfs}/exglobal_snowens_analysis.py}
${EXSCRIPT}
status=$?
(( status != 0 )) && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit 1
[[ "${KEEPDATA}" = "NO" ]] && rm -rf "${DATA}"

exit 0
