#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "wavepostsbs" -c "base wave wavepostsbs"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

export MP_PULSE=0

# Set COM Paths and GETGES environment
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_WAVE_PREP:COM_WAVE_PREP_TMPL \
    COMIN_WAVE_HISTORY:COM_WAVE_HISTORY_TMPL \
    COMOUT_WAVE_PREP:COM_WAVE_PREP_TMPL \
    COMOUT_WAVE_GRID:COM_WAVE_GRID_TMPL

for out_dir in "${COMOUT_WAVE_PREP}" "${COMOUT_WAVE_GRID}"; do
    if [[ ! -d "${out_dir}" ]]; then mkdir -p "${out_dir}"; fi
done

for grdID in ${wavepostGRD} ${waveinterpGRD}; do
    case ${grdID} in    
        glo_10m) GRDNAME='global' ; GRDRES=0p16;;
        glo_15mxt) GRDNAME='global' ; GRDRES=0p25;;       
        glo_30mxt) GRDNAME='global' ; GRDRES=0p50 ;;
        glo_30m) GRDNAME='global' ; GRDRES=0p50 ;;
        glo_025) GRDNAME='global' ; GRDRES=0p25 ;;
        glo_100) GRDNAME='global' ; GRDRES=1p00;;
        glo_200) GRDNAME='global' ; GRDRES=2p00;;
        glo_500) GRDNAME='global' ; GRDRES=5p00;;
        at_10m) GRDNAME='atlocn' ; GRDRES=0p16 ;;
        ep_10m) GRDNAME='epacif' ; GRDRES=0p16;;
        wc_10m) GRDNAME='wcoast' ; GRDRES=0p16 ;;
        ak_10m) GRDNAME='alaska' ; GRDRES=0p16;;
        aoc_9km) GRDNAME='arctic' ; GRDRES=9km;;
        ant_9km) GRDNAME='antarc' ; GRDRES=9km ;;
        gnh_10m) GRDNAME='global' ; GRDRES=0p16;;
        gsh_15m) GRDNAME='gsouth' ; GRDRES=0p25;;
        ao_20m) GRDNAME='arctic' ; GRDRES=0p33;;
        so_20m) GRDNAME='antarc' ; GRDRES=0p33;;
        reg025) GRDNAME='global' ; GRDRES=0p25;;
        gwes_30m) GRDNAME='global' ; GRDRES=0p50;;
        *)
        echo "FATAL ERROR: No grid specific wave config values exist for ${grdID}. Aborting."
        exit 1;;
    esac
    GRID=${GRDRES} YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        "COMOUT_WAVE_GRID_${GRDNAME}.${GRDRES}:COM_WAVE_GRID_RES_TMPL"
    COMOUT=COMOUT_WAVE_GRID_${GRDNAME}.${GRDRES}
    if [[ ! -d "${COMOUT}" ]]; then
    mkdir -m 775 -p "${COMOUT}"
    fi
done



# Set wave model ID tag to include member number
# if ensemble; waveMEMB var empty in deterministic
# Set wave model ID tag to include member number
# if ensemble; waveMEMB var empty in deterministic
membTAG='p'
if [ "${waveMEMB}" == "00" ]; then membTAG='c'; fi
export membTAG
export WAV_MOD_TAG=${RUN}wave${waveMEMB}

export CFP_VERBOSE=1

# Execute the Script
${SCRgfs}/exgfs_wave_post_gridded_sbs.sh
err=$?
if [ ${err} -ne 0 ]; then
  echo "FATAL ERROR: ex-script of GWES_POST failed!"
  exit "${err}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
