#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "prep_sfc" -c "base prep_sfc"

##############################################
# Set date and cycle
##############################################

# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}

# Generate COM variables from templates
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMINobsproc:COM_OBSPROC_TMPL
YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
    COMINobsproc_PREV:COM_OBSPROC_TMPL
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_OBS:COM_OBS_TMPL

mkdir -p "${COMOUT_OBS}"

###############################################################
# Run relevant script
###############################################################

"${SCRgfs}/exglobal_prep_sfc.sh"
export err=$?
if [[ ${err} -ne 0 ]]; then
   err_exit "Surface observation preparation failed!"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi


exit 0
