#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "waveinit" -c "base wave waveinit"


# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

export MP_PULSE=0

# Set COM Paths
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
   COMOUT_WAVE_PREP:COM_WAVE_PREP_TMPL

if [[ ! -d "${COMOUT_WAVE_PREP}" ]]; then mkdir -p "${COMOUT_WAVE_PREP}"; fi

# Set mpi serial command
export wavempexec=${wavempexec:-"mpirun -n"}
export wave_mpmd=${wave_mpmd:-"cfp"}

# Execute the Script
${SCRgfs}/exgfs_wave_init.sh

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
