#!/bin/bash
set -xa
date -u

###################################################################
# Set DEBUG LEVEL - modifies info in execution trace prompt string
###################################################################
export DEBUG_LEVEL=${DEBUG_LEVEL=1}
case $DEBUG_LEVEL in
  1) export PS4='+ ${SECONDS}s + ' ;;       # add seconds (this is typical case)
  0) export PS4='+ ';;                      # don't include seconds (useful if
                                            #  want to diff output from 2 runs)
  2) export PS4='+ ${SECONDS}s:L$LINENO + ';;         # add script line #
  3) export PS4='+ ${SECONDS}s:${0##*/}:L$LINENO + ';;# add script name & line #
  4) export PS4='+ ${0##*/}:L$LINENO + ';;  # script name & line (no seconds)
  *) echo "Unrecognized DEBUG_LEVEL.  Stay with current PS4 setting";;
esac

########################################
# Check that required variables are set
########################################
set +x
echo
echo cyc is ${cyc:?"###FATAL ERROR \"cyc\" is not set"}
echo envir is ${envir:?"###FATAL ERROR \"envir\" is not set"}
echo job is ${job:?"###FATAL ERROR \"job\" is not set"}
echo DATAROOT is ${DATAROOT:?"###FATAL ERROR \"DATAROOT\" is not set"}
echo
set -x

################################
# Print out version information
################################
set +x
echo
echo "####################################################################"
echo
echo "Current OBSPROC_GLOBAL version is ${obsproc_global_ver:-not set}"
echo "OBSPROC_PREP version used by this job is ${obsproc_prep_ver:-not set}"
echo
echo "####################################################################"
echo
set -x

#####################################################################
# List modules loaded for this job
#   On luna/surge may need to initialize the Modules package to find
#   the module command.  Will do so for either system.
#####################################################################
if [ -f /opt/modules/default/init/sh ]; then  # on luna/surge
  . /opt/modules/default/init/sh 2>/dev/null
elif [ -f /usrx/local/Modules/default/init/sh ]; then  # on tide/gyre
  . /usrx/local/Modules/default/init/sh 2>/dev/null
fi
set +x
echo
echo "####################################################################"
echo
      module list
echo
echo "####################################################################"
echo
set -x

######################
# Specify NET and RUN
######################
export NET=${NET:-gfs}
export RUN=${RUN:-${CDUMP:-gfs}}

##############################
# Specify cycle and time-mark
##############################
export cycle=t${cyc}z
export tmmark=tm00

###############################
# Create new working directory
###############################
jobid=${jobid:-${job}.$(hostname -s).$$}
if [[ "$RUN_ENVIR" == nco ]]; then
    export DATA=${DATA:-$DATAROOT/${jobid}}
else
    export DATA="$RUNDIR/$CDATE/$CDUMP/prepbufr"
fi
rm -rf $DATA
mkdir -p $DATA
cd $DATA
export pgmout=OUTPUT.$$

######################################
# Set job log file for postmsg output
######################################
jlogfile=${jlogfile:-${DATA}/jlogfile}

#################################################
# SENDCOM      - Copy files to $COMOUT directory
# SENDECF      - Flag Events on ECFLOW
# SENDDBN      - Alert output file to TOC
#################################################
export SENDCOM=${SENDCOM:-YES}
export SENDECF=${SENDECF:-YES}
export SENDDBN=${SENDDBN:-YES}

######################################################
# Phase 1 --> Phase 2 --> Cray  Transitional Settings
######################################################
NWROOTp1=${NWROOTp1:-/nwprod}

##########################
# Specify Execution Areas
##########################

# -------------------------------
# Paths for obsproc_network items
# -------------------------------
export HOMEobsproc_network=${HOMEobsproc_network:\
-${NWROOT:?}/obsproc_global.${obsproc_global_ver:?\
"###FATAL ERROR \"obsproc_global_ver\" is not set"}}

export SCRIPTSobsproc_global=${SCRIPTSobsproc_global:\
-$HOMEobsproc_network/scripts}

export FIXobsproc_global=${FIXobsproc_global:-$HOMEobsproc_network/fix}

# ----------------------------
# Paths for obsproc_prep items
# ----------------------------
export HOMEobsproc_prep=${HOMEobsproc_prep:\
-${NWROOT:?}/obsproc_prep.${obsproc_prep_ver:?\
"###FATAL ERROR \"obsproc_prep_ver\" is not set"}}

export USHobsproc_prep=${USHobsproc_prep:-$HOMEobsproc_prep/ush}

# directory path to data prep script executed in model script
# -----------------------------------------------------------
export ushscript_prep=${ushscript_prep:-$USHobsproc_prep}

# ---------------------------------------------------------
# Paths for combined obsproc_network and obsproc_prep items
# ---------------------------------------------------------

# directory paths to overall PREP processing executed in
#  prepobs_makeprepbufr.sh and its various child scripts
#  (other than prepobs_syndata.sh, see below)
# ------------------------------------------------------
export EXECPREP=${EXECPREP:-${HOMEobsproc_prep}/exec}
export FIXPREP=${FIXPREP:-${HOMEobsproc_prep}/fix}
export PARMPREP=${PARMPREP:-${HOMEobsproc_network}/parm}

# directory paths to SYNDATA processing executed in prepobs_syndata.sh
# --------------------------------------------------------------------
export EXECSYND=${EXECSYND:-${HOMEobsproc_prep}/exec}
export FIXSYND=${FIXSYND:-${HOMEobsproc_prep}/fix}
export PARMSYND=${PARMSYND:-${HOMEobsproc_network}/parm}

# ---------------------------
# Paths for non-obsproc items
# ---------------------------

# DICTPREP is directory path to metar.tbl dictionary used in
#  prepobs_prepacqc.sh if PREPOBS_PREPACPF is executed
# ----------------------------------------------------------
export DICTPREP=${DICTPREP:-${NWROOTp1}/decoders/decod_shared/dictionaries}

#########################################################################
# Add some prod utilities to working directory
#########################################################################
echo "step ############# break ##############################" > ./break
cp $UTILROOT/ush/err_chk   .; chmod +x err_chk
cp $UTILROOT/ush/err_exit  .; chmod +x err_exit
cp $UTILROOT/ush/prep_step .; chmod +x prep_step
cp $UTILROOT/ush/postmsg   .; chmod +x postmsg
cp $UTILROOT/ush/setpdy.sh .; chmod +x setpdy.sh

##########################################
# Run setpdy and initialize PDY variables
##########################################
./setpdy.sh
. ./PDY

#########################
# Define COM directories
#########################
export COMIN_ROOT=${COMIN_ROOT:-${COMROOT:-""}}

if [[ "$RUN_ENVIR" == nco ]]; then
  export COMIN=${COMIN_ROOT:?}/${NET}/${envir}/${RUN}.${PDY}
  export COMOUT=${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}
  mkdir -m 775 -p $COMOUT
else
# Set script and dependency variables
  GDATE=$($NDATE -$assim_freq $CDATE)

  PDYg=$(echo $GDATE | cut -c1-8)
  cycg=$(echo  $GDATE | cut -c9-10)

  COMIN_OBS=${COMIN_OBS:-"$DMPDIR/$CDATE/$CDUMP"}
  export COMSP=${COMSP:-$COMIN_OBS/$CDUMP.t${cyc}z.}
  COMIN_GES=${COMIN_GES:-"$ROTDIR/gdas.$PDYg/$cycg"}
  export COMINgdas=${COMINgdas:-"$ROTDIR/gdas.$PDYg/$cycg"}
  export COMINgfs=${COMINgfs:-"$ROTDIR/gfs.$PDYg/$cycg"}
  COMOUT=${COMOUT:-"$ROTDIR/$CDUMP.$PDY/$cyc"}
   mkdir -m 775 -p $COMOUT
fi

export NEMSIO_IN=${NEMSIO_IN:-.true.}     # switch for nemsio vs sigio guess
export envir_getges=${envir_getges:-$envir}
export GETGES_COM=${GETGES_COM:-$COMROOT} # Root location for GFS/GDAS COM data
export GETGES_NWG=${GETGES_NWG:-$GESROOT}
export COMINgdas=${COMINgdas:-$(compath.py gfs/${envir_getges}/gdas.$PDY)}
export COMINgfs=${COMINgfs:-$(compath.py gfs/${envir_getges}/gfs.$PDY)}

##########################################
# SETUP GFS PREPBUFR PROCESSING VARIABLES
##########################################

#########################################################
# Specify variables specific to this execution of script
#########################################################

#  Set POE *or* BACK to YES in order to run this job in a parallel environment

export POE=${POE:-YES}
##export BACK=YES  # set BACK to YES for an alternate method of running this
                   #  job in a parallel environment (in this case POE must be
                   #  NO)

#  NSPLIT indicates the number of parts into which the PREPDATA
#         processing will will be split in order to run in parallel
#         for computational efficiency (either under poe tasks when
#         POE=YES or in background threads when BACK=YES)
#   (Applies only when either POE=YES or BACK=YES, and PREPDATA=YES)
#   Consider the size of the backgrounds fields if using threads. 

export NSPLIT=${NSPLIT:-3}

#  BUFRLIST indicates the list of BUFR data dump file names to process

export BUFRLIST=${BUFRLIST:-"adpupa proflr aircar aircft satwnd adpsfc \
 sfcshp vadwnd wdsatr ascatw rassda gpsipw"}

export errPREPDATA_limit=4 # allow program PREPOBS_PREPDATA to continue at all
                           # center hour (cycle) times if foreground exit
                           # status is 4 (i.e., when either either "ADPUPA" or
                           # "ADPSFC" dump is empty)

# VARIABLES THAT CONTROL PROCESSING OF INDIVIDUAL PROGRAMS
# --------------------------------------------------------

#  -- These can individually be switched to NO without affecting the
#      success of other programs and the success of the complete job
#      (all should normally be set to YES unless otherwise specified;
#       if job fails in one of these programs, set offending program
#       to NO and resubmit to "work-around" problem)

export SYNDATA=${SYNDATA:-YES}   # Execute program SYNDAT_SYNDATA   if YES

export PREPACQC=${PREPACQC:-YES} # Execute PREPACQC script processing if YES
   export PROCESS_ACQC=${PROCESS_ACQC:-YES} # Execute program PREPOBS_PREPACQC
                                            #  if YES
   export PROCESS_ACPF=${PROCESS_ACPF:-NO}  # Execute program PREPOBS_PREPACPF
                                            #  if YES

export PROFCQC=${PROFCQC:-YES}   # Execute program PREPOBS_PROFCQC  if YES

export CQCVAD=${CQCVAD:-YES}     # Execute program PREPOBS_CQCVAD   if YES

export CQCBUFR=${CQCBUFR:-YES}   # Execute program PREPOBS_CQCBUFR  if YES

export OIQCBUFR=${OIQCBUFR:-NO} # Execute program PREPOBS_OIQCBUFR if YES


#  -- If any of these are switched to NO it will affect the success of
#      other programs and the success of the complete job
#      (these are set-up only for CHECKOUT runs - they should always
#       be set to YES for operational runs)

export PREPDATA=${PREPDATA:-YES}  
                      # Execute programs PREPOBS_MPCOPYBUFR, PREPOBS_PREPDATA,
                      # PREPOBS_LISTHEADERS and PREPOBS_MONOPREPBUFR if YES

export GETGUESS=${GETGUESS:-YES}
                      # Encode first guess (background) values interpolated to
                      # observation locations in the PREPBUFR file for use by
                      # the q.c. programs.  This guess is always from a global
                      # sigma or nemsio guess file valid at the center PREPBUFR
                      # processing date/time.

export DO_QC=${DO_QC:-YES}
                      # IF NO, programs PREPOBS_PREPACQC, PREPOBS_PREPACPF,
                      # PREPOBS_PROFCQC, PREPOBS_CQCVAD, PREPOBS_CQCBUFR and
                      # PREPOBS_OIQCBUFR will NEVER execute regardless of
                      # switches above -
                      # should be set to NO only as a last resort!!!

export PROCESS_UNBLKBUFR=${PROCESS_UNBLKBUFR:-NO}
                      # IF YES, create prepbufr.unblok

env

#####################
# Execute the script
#####################
$SCRIPTSobsproc_global/exglobal_makeprepbufr.sh.ecf
err_gfs_makeprepbufr=$?
[[ $err_gfs_makeprepbufr -ne 0 ]] && $DATA/err_exit

echo "$SITE `hostname`  --  `date -u`" > $COMOUT/where_${cycle}_${RUN}_prep_ran

> $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
[ -n "$obsproc_global_ver" ]  &&  \
 echo "Current OBSPROC_GLOBAL version is $obsproc_global_ver" >> \
 $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run
[ -n "$obsproc_prep_ver" ]  &&  \
 echo "OBSPROC_PREP version used by this job is $obsproc_prep_ver" >> \
 $COMOUT/obsproc_version_for_${cycle}_${RUN}_prep_run

if [ "$KEEPDATA" != YES ]; then
   cd $DATAROOT
   rm -rf $DATA
fi
date -u

exit
