#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "globus_arch" -c "base globus"

##############################################
# Set variables used in the script
##############################################
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_CONF:COM_CONF_TMPL

###############################################################
# Run globus script
###############################################################

${GLOBALGLOBUSARCHSH:-${SCRgfs}/exglobal_globus_arch.py}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi


##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"

exit 0
