#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "arch_vrfy" -c "base arch_vrfy"

###############################################################
# Run archive script
# Note: COM paths are calculated within the Python script
###############################################################

${GLOBALARCHIVESH:-${SCRgfs}/exglobal_archive_vrfy.py}
err=$?
if [[ ${err} -ne 0 ]]; then
    exit "${err}"
fi

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (
    echo "${DATAROOT} does not exist. ABORT!"
    exit 1
)
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
