#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "sfc_prep" -c "base sfcprep"

##############################################
# Set date and cycle
##############################################

GDATE=$(${NDATE} -06 "${PDY}${cyc}")
gPDY=$(echo "${GDATE}" | cut -c1-8)
gcyc=$(echo "${GDATE}" | cut -c9-10)
gcycle="t${gcyc}z"

# Generate COM variables from templates
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_OBSPROC:COM_OBSPROC_TMPL
YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
    COMIN_OBSPROC_PREV:COM_OBSPROC_TMPL
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_OBS:COM_OBS_TMPL

export IMS_FILE=${COMIN_OBSPROC}/${RUN}.${cycle}.imssnow96.grib2
export FIVE_MIN_ICE_FILE=${COMIN_OBSPROC}/${RUN}.${cycle}.seaice.5min.grib2
export AFWA_NH_FILE=${COMIN_OBSPROC}/${RUN}.${cycle}.NPR.SNWN.SP.S1200.MESH16.grb
export AFWA_SH_FILE=${COMIN_OBSPROC}/${RUN}.${cycle}.NPR.SNWS.SP.S1200.MESH16.grb
export AFWA_GLOBAL_FILE=${COMIN_OBSPROC}/${RUN}.${cycle}.snow.usaf.grib2

export BLENDED_ICE_FILE=${RUN}.${cycle}.seaice.5min.blend.grb
export BLENDED_ICE_FILE_m6hrs=${COMIN_OBSPROC_PREV}/${RUN}.${gcycle}.seaice.5min.blend.grb

###############################################################
# Run relevant script
###############################################################

${EMCSFCPREPSH:-${SCRgfs}/exemcsfc_global_sfc_prep.sh}
export err=$?
err_chk

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ]; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi


exit 0
