#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "fcst" -c "base fcst"

##############################################
# Set variables used in the script
##############################################
export CDUMP=${RUN/enkf}

##############################################
# Begin JOB SPECIFIC work
##############################################

# Restart conditions for GFS cycle come from GDAS
rCDUMP=${CDUMP}
[[ ${CDUMP} = "gfs" ]] && export rCDUMP="gdas"

# Forecast length for GFS forecast
case ${RUN} in
  *gfs | *gefs)
    # shellcheck disable=SC2153
    export FHMAX=${FHMAX_GFS}
    # shellcheck disable=SC2153
    export FHOUT=${FHOUT_GFS}
    export FHMAX_HF=${FHMAX_HF_GFS}
    export FHOUT_HF=${FHOUT_HF_GFS}
    ;;
  *gdas)
    export FHMAX_HF=0
    export FHOUT_HF=0
    ;;
  *)
    echo "FATAL ERROR: Unsupported RUN '${RUN}'"
    exit 1
esac


# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date --utc -d "${PDY} ${cyc} - ${assim_freq} hours" +%Y%m%d%H)
declare -rx GDATE
# shellcheck disable=
declare -rx gPDY="${GDATE:0:8}"
declare -rx gcyc="${GDATE:8:2}"

# Construct COM variables from templates (see config.com)
YMD=${PDY} HH=${cyc} generate_com -rx COM_ATMOS_RESTART COM_ATMOS_INPUT COM_ATMOS_ANALYSIS \
  COM_ATMOS_HISTORY COM_ATMOS_MASTER COM_TOP COM_CONF

RUN=${rCDUMP} YMD="${gPDY}" HH="${gcyc}" generate_com -rx \
  COM_ATMOS_RESTART_PREV:COM_ATMOS_RESTART_TMPL

if [[ ${DO_WAVE} == "YES" ]]; then
  YMD=${PDY} HH=${cyc} generate_com -rx COM_WAVE_RESTART COM_WAVE_PREP COM_WAVE_HISTORY
  RUN=${rCDUMP} YMD="${gPDY}" HH="${gcyc}" generate_com -rx \
    COM_WAVE_RESTART_PREV:COM_WAVE_RESTART_TMPL
  declare -rx RUNwave="${RUN}wave"
fi

if [[ ${DO_OCN} == "YES" ]]; then
  YMD=${PDY} HH=${cyc} generate_com -rx COM_MED_RESTART COM_OCEAN_RESTART COM_OCEAN_INPUT \
    COM_OCEAN_HISTORY COM_OCEAN_ANALYSIS
  RUN=${rCDUMP} YMD="${gPDY}" HH="${gcyc}" generate_com -rx \
    COM_OCEAN_RESTART_PREV:COM_OCEAN_RESTART_TMPL
fi

if [[ ${DO_ICE} == "YES" ]]; then
  YMD=${PDY} HH=${cyc} generate_com -rx COM_ICE_HISTORY COM_ICE_INPUT COM_ICE_RESTART
  RUN=${rCDUMP} YMD="${gPDY}" HH="${gcyc}" generate_com -rx \
    COM_ICE_RESTART_PREV:COM_ICE_RESTART_TMPL
fi

if [[ ${DO_AERO} == "YES" ]]; then
  YMD=${PDY} HH=${cyc} generate_com -rx COM_CHEM_HISTORY
fi


###############################################################
# Run relevant exglobal script

${FORECASTSH:-${SCRgfs}/exglobal_forecast.sh}
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
