#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "arch" -c "base arch wave"
source "${USHgfs}/wave_domain_grid.sh" 
##############################################
# Set variables used in the script
##############################################
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
	COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
	COMIN_ATMOS_BUFR:COM_ATMOS_BUFR_TMPL \
	COMIN_ATMOS_GEMPAK:COM_ATMOS_GEMPAK_TMPL \
	COMIN_ATMOS_GENESIS:COM_ATMOS_GENESIS_TMPL \
	COMIN_ATMOS_HISTORY:COM_ATMOS_HISTORY_TMPL \
	COMIN_ATMOS_INPUT:COM_ATMOS_INPUT_TMPL \
	COMIN_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL \
	COMIN_ATMOS_RESTART:COM_ATMOS_RESTART_TMPL \
	COMIN_ATMOS_TRACK:COM_ATMOS_TRACK_TMPL \
	COMIN_ATMOS_WMO:COM_ATMOS_WMO_TMPL \
	COMIN_CHEM_HISTORY:COM_CHEM_HISTORY_TMPL \
	COMIN_CHEM_ANALYSIS:COM_CHEM_ANALYSIS_TMPL \
	COMIN_MED_RESTART:COM_MED_RESTART_TMPL \
	COMIN_SNOW_ANALYSIS:COM_SNOW_ANALYSIS_TMPL \
	COMIN_ICE_HISTORY:COM_ICE_HISTORY_TMPL \
	COMIN_ICE_INPUT:COM_ICE_INPUT_TMPL \
	COMIN_ICE_RESTART:COM_ICE_RESTART_TMPL \
	COMIN_ICE_GRIB:COM_ICE_GRIB_TMPL \
	COMIN_OBS:COM_OBS_TMPL \
	COMIN_TOP:COM_TOP_TMPL \
	COMIN_OCEAN_HISTORY:COM_OCEAN_HISTORY_TMPL \
	COMIN_OCEAN_RESTART:COM_OCEAN_RESTART_TMPL \
	COMIN_OCEAN_GRIB:COM_OCEAN_GRIB_TMPL \
	COMIN_OCEAN_NETCDF:COM_OCEAN_NETCDF_TMPL \
	COMIN_OCEAN_ANALYSIS:COM_OCEAN_ANALYSIS_TMPL \
        COMIN_OCEAN_BMATRIX:COM_OCEAN_BMATRIX_TMPL \
        COMIN_ICE_BMATRIX:COM_ICE_BMATRIX_TMPL \
	COMIN_WAVE_GRID:COM_WAVE_GRID_TMPL \
	COMIN_WAVE_HISTORY:COM_WAVE_HISTORY_TMPL \
	COMIN_WAVE_STATION:COM_WAVE_STATION_TMPL \
	COMIN_WAVE_RESTART:COM_WAVE_RESTART_TMPL \
	COMIN_ATMOS_OZNMON:COM_ATMOS_OZNMON_TMPL \
	COMIN_ATMOS_RADMON:COM_ATMOS_RADMON_TMPL \
	COMIN_ATMOS_MINMON:COM_ATMOS_MINMON_TMPL \
	COMIN_CONF:COM_CONF_TMPL \
	COMOUT_ATMOS_TRACK:COM_ATMOS_TRACK_TMPL

for grid in "0p25" "0p50" "1p00"; do
    YMD=${PDY} HH=${cyc} GRID=${grid} declare_from_tmpl -rx \
       "COMIN_ATMOS_GRIB_${grid}:COM_ATMOS_GRIB_GRID_TMPL"
done

###############################################################
# Create an array of output wave grids to process
if [[ "${DO_WAVE}" == "YES" ]]; then
    # Create a variable for output wave grids to process
    if [[ -n "${wavepostGRD}" || -n "${waveinterpGRD}" ]]; then
        for grdID in ${wavepostGRD} ${waveinterpGRD}; do
            process_grdID "${grdID}"
            YMD=${PDY} HH=${cyc} GRDRESNAME=${grdNAME} declare_from_tmpl -rx \
                "COMIN_WAVE_GRID_${GRDREGION}_${GRDRES}:COM_WAVE_GRID_RES_TMPL"
            grids_arr+=("${GRDREGION}.${GRDRES}")
        done
        export WAVE_OUT_GRIDS="${grids_arr[*]}"
    else
        echo "Both wavepostGRD and waveinterpGRD are empty. No grids to process."
        export WAVE_OUT_GRIDS=""
    fi
fi
###############################################################
# Run archive script
###############################################################

${GLOBALARCHIVESH:-${SCRgfs}/exglobal_archive.py}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (echo "${DATAROOT} does not exist. ABORT!"; exit 1)
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"

exit 0
