#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "gen_control_ic" -c "base gen_control_ic"


##############################################
# Set variables used in the script
##############################################
export EXECufs=${EXECufs:-${HOMEgfs}/sorc/ufs_utils.fd/exec}

MEMDIR="mem000" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_ATMOS_INPUT_MEM:COM_ATMOS_INPUT_TMPL \
    COMOUT_ATMOS_INPUT_MEM:COM_ATMOS_INPUT_TMPL
###############################################################
# Run relevant script
${CHGRESFCSTSH:-${SCRgfs}/exglobal_atmos_chgres_gen_control.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi


exit 0
