#! /usr/bin/env bash
export WIPE_DATA="NO"
export DATA=${DATA:-${DATAROOT}/${RUN}fetch_${cyc}}
source "${HOMEgfs}/ush/jjob_header.sh" -e "prepatmanlsatbias" -c "base prepatmanlsatbias"

##############################################
# Set variables used in the script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################
export GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}
export gyy=${GDATE:0:4}
export gmm=${GDATE:4:2}
export gdd=${GDATE:6:2}
export GDUMP="gdas"

# Generate COM variables from templates
MEMDIR="ensstat" RUN="enkf${GDUMP}" YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
    COMOUT_ATMOS_ANALYSIS_PREV:COM_ATMOS_ANALYSIS_TMPL \

# Process bias corrections files grabbed from HPSS in task gdas_fetchatmanlsatbias
SATBIASDIR=${DATA}/${GDUMP}.${gPDY}/${gcyc}/atmos
SATBIASFILES="${GDUMP}.t${gcyc}z.abias ${GDUMP}.t${gcyc}z.abias_int ${GDUMP}.t${gcyc}z.abias_pc ${GDUMP}.t${gcyc}z.radstat"

EXSCRIPT_GEN_YAML=${RUNSATBIASCONVPY:-${USHgfs}/gen_run_satbias_conv_yaml.py}
EXSCRIPT=${RUNSATBIASCONVPY:-${USHgfs}/run_satbias_conv.py}
EXYAML=${RUNSATBIASCONVYAML:-${USHgfs}/satbias_converter.yaml}
export EXX=${RUNSATBIASCONVX:-${EXECgfs}/satbias2ioda.x}
OUTPUT=${DATA}/output
PYRUNTMP=${DATA}/tmp

if [[ ! -d "${COMOUT_ATMOS_ANALYSIS_PREV}" ]]; then mkdir -p "${COMOUT_ATMOS_ANALYSIS_PREV}"; fi
if [[ -d "${OUTPUT}" ]]; then rm -rf "${OUTPUT}"; fi
if [[ -d "${PYRUNTMP}" ]]; then rm -rf "${PYRUNTMP}"; fi

if [[ ${DO_JEDIATMENS} == "YES" ]]; then
    # JEDI run
    cd ${DATA}
    cpreq ${EXYAML} ./

# Generate YAML
${EXSCRIPT_GEN_YAML} -o run_satbias_conv.yaml
err=$?

    if [[ ${err} -eq 0 ]]; then
${EXSCRIPT} -c run_satbias_conv.yaml
err=$?
    else
        err_exit "Error executing ${EXSCRIPT_GEN_YAML}"
    fi
    
    if [[ ${err} -eq 0 ]]; then
        cd ${OUTPUT}/${GDUMP}.${gPDY}/${gcyc}/atmos   
        for file in ${SATBIASFILES}; do
            cpreq ${SATBIASDIR}/${file} ./${file}.ensmean
            err=$?
            if [[ ${err} -ne 0 ]]; then
                err_exit "Error copying operational anl bias correction files"
            fi
	done
        tar -cvf ${COMOUT_ATMOS_ANALYSIS_PREV}/${GDUMP}.t${gcyc}z.rad_varbc_params.tar *
        err=$?
    else
        err_exit "Error executing ${EXSCRIPT}"
    fi

else
    # GSI run
    if [[ ! -d "${OUTPUT}" ]]; then mkdir -p "${OUTPUT}"; fi
    for file in ${SATBIASFILES}; do
        cpreq ${SATBIASDIR}/${file} ${OUTPUT}/${file}.ensmean
        err=$?
        if [[ ${err} -ne 0 ]]; then
            err_exit "Error copying operational anl bias correction files"
        fi
    done
    cd ${OUTPUT}
    tar -cvf ${COMOUT_ATMOS_ANALYSIS_PREV}/${GDUMP}.t${gcyc}z.rad_varbc_params.tar *
    err=$?
fi


if [[ ${err} -ne 0 ]]; then
    err_exit "Error executing ${EXSCRIPT}"
fi
set_trace

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
