#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "fcst" -c "base fcst"

##############################################
# Set variables used in the script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################

# Restart conditions for GFS cycle come from GDAS
rCDUMP=${CDUMP}
[[ ${CDUMP} = "gfs" ]] && export rCDUMP="gdas"

# Forecast length for GFS forecast
if [ ${CDUMP} = "gfs" ]; then
    export FHMAX=${FHMAX_GFS}
    export FHOUT=${FHOUT_GFS}
    export FHMAX_HF=${FHMAX_HF_GFS}
    export FHOUT_HF=${FHOUT_HF_GFS}
else
    export FHMAX_HF=0
    export FHOUT_HF=0
fi

export MEMDIR=${MEMDIR:-''}

# Construct COM variables from templates (see config.com)
export YMD=${PDY}
export HH=${cyc}
generate_com -rx COM_ATMOS_RESTART COM_ATMOS_INPUT COM_ATMOS_ANALYSIS COM_ATMOS_HISTORY COM_ATMOS_MASTER
generate_com -rx COM_WAVE_RESTART COM_WAVE_PREP COM_WAVE_HISTORY
generate_com -rx COM_MED_RESTART COM_OCEAN_RESTART COM_OCEAN_INPUT COM_OCEAN_HISTORY
generate_com -rx COM_ICE_HISTORY
generate_com -rx COM_CHEM_HISTORY

# Construct COM variables for previous cycle restarts
GDATE=$(${NDATE} -"${assim_freq}" "${PDY}${cyc}")
declare -x gPDY="${GDATE:0:8}"
declare -x gcyc="${GDATE:8:2}"

# shellcheck disable=SC2030,SC2031
COM_ATMOS_RESTART_PREV=$({
  # Override env variables for this subshell to get correct template substitution
  RUN=${rCDUMP}
  YMD="${gPDY}"
  HH="${gcyc}"
  echo "${COM_ATMOS_RESTART_TMPL}" | envsubst
})
declare -rx COM_ATMOS_RESTART_PREV

COM_WAVE_RESTART_PREV=$( {
  # Override env variables for this subshell to get correct template substitution
  # If we drop a separate cycle frequency, this can be merged with above
  YMD="${gPDY}"
  HH="${gcyc}"
  echo "${COM_WAVE_RESTART_TMPL}" | envsubst
})
declare -rx COM_WAVE_RESTART_PREV
# shellcheck disable=

###############################################################
# Run relevant exglobal script

${FORECASTSH:-${SCRgfs}/exglobal_forecast.sh}
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
