#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "analcalc" -c "base anal analcalc"


##############################################
# Set variables used in the script
##############################################
export CDUMP="${RUN/enkf}"
export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"}


##############################################
# Begin JOB SPECIFIC work
##############################################

DATE_PREV=$(${NDATE} -${assim_freq} ${CDATE})
export PDY_PREV=${DATE_PREV:0:8}
export cyc_PREV=${DATE_PREV:8:2}
export GDUMP="gdas"
export GDUMP_ENS="enkf${GDUMP}"

export OPREFIX="${CDUMP}.t${cyc}z."
export GPREFIX="${GDUMP}.t${cyc_PREV}z."
export APREFIX="${RUN}.t${cyc}z."
export GPREFIX_ENS="${GDUMP_ENS}.t${cyc_PREV}z."

RUN=${CDUMP} YMD=${PDY} HH=${cyc} generate_com -rx COM_OBS

YMD=${PDY} HH=${cyc} generate_com -rx COM_ATMOS_ANALYSIS COM_ATMOS_RESTART

RUN=${GDUMP} YMD=${PDY_PREV} HH=${cyc_PREV} generate_com -rx \
    COM_OBS_PREV:COM_OBS_TMPL \
    COM_ATMOS_HISTORY_PREV:COM_ATMOS_HISTORY_TMPL


export ATMGES="${COM_ATMOS_HISTORY_PREV}/${GPREFIX}atmf006.nc"
if [ ! -f ${ATMGES} ]; then
    echo "FATAL ERROR: FILE MISSING: ATMGES = ${ATMGES}"
    exit 1
fi

# Get LEVS
export LEVS=$(${NCLEN} ${ATMGES} pfull)
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


# Generate Gaussian surface analysis  # TODO: Should this be removed now that sfcanl is its own job?
export DOGAUSFCANL=${DOGAUSFCANL:-"YES"}


###############################################################
# Run relevant script

${ANALCALCSH:-${SCRgfs}/exglobal_atmos_analysis_calc.sh}
status=$?
[[ ${status} -ne 0 ]] && exit ${status}


##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat ${pgmout}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
