#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
export DATA=${DATA:-${DATAROOT}/${RUN}atmensanl_${cyc}}
source "${HOMEgfs}/ush/jjob_header.sh" -e "atmensanlinit" -c "base atmensanl atmensanlinit"

##############################################
# Set variables used in the script
##############################################
GDATE=$(date +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}
GDUMP="gdas"
export GDUMP_ENS="enkf${GDUMP}"


##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
RUN=${GDUMP} YMD=${PDY} HH=${cyc} generate_com -rx COM_OBS COM_ATMOS_ANALYSIS

RUN=${GDUMP} YMD=${gPDY} HH=${gcyc} generate_com -rx \
    COM_ATMOS_ANALYSIS_PREV:COM_ATMOS_ANALYSIS_TMPL 

RUN=${GDUMP_ENS} YMD=${PDY} HH=${cyc} generate_com -rx \
    COM_TOP_ENS:COM_TOP_TMPL

RUN=${GDUMP_ENS} YMD=${gPDY} HH=${gcyc} generate_com -rx \
    COM_TOP_ENS_GES:COM_TOP_TMPL


mkdir -m 775 -p "${COM_TOP_ENS}"


###############################################################
# Run relevant script

EXSCRIPT=${GDASATMENSINITPY:-${HOMEgfs}/scripts/exglobal_atmens_analysis_initialize.py}
${EXSCRIPT}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

exit 0
