#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "wavegempak" -c "base wave wavegempak"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

###################################
# Set COM Paths
###################################
export DBN_ALERT_TYPE=GFS_WAVE_GEMPAK
export SENDDBN=${SENDDBN:-YES}
export DBNROOT=${DBNROOT:-${UTILROOT}/fakedbn}

YMD=${PDY} HH=${cyc} generate_com -rx COM_WAVE_GRID COM_WAVE_GEMPAK

if [[ ! -d ${COM_WAVE_GEMPAK} ]]; then mkdir -p "${COM_WAVE_GEMPAK}"; fi

########################################################
# Execute the script.
${SCRgfs}/exgfs_wave_nawips.sh
status=$?
[[ ${status} -ne 0 ]] && exit ${status}
###################################

# Remove temp directories
cd ${DATAROOT}
if [ "${KEEPDATA}" != "YES" ]; then
  rm -rf ${DATA}
fi

exit 0
