#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "prep_sfc" -c "base prepsfc"

##############################################
# Set date and cycle
##############################################

GDATE=$(${NDATE} -06 "${PDY}${cyc}")
gPDY=$(echo "${GDATE}" | cut -c1-8)
gcyc=$(echo "${GDATE}" | cut -c9-10)
gcycle="t${gcyc}z"

# Generate COM variables from templates
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_OBSPROC:COM_OBSPROC_TMPL
YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
    COMIN_OBSPROC_PREV:COM_OBSPROC_TMPL
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_OBS:COM_OBS_TMPL

if [[ ! -d ${COMOUT_OBS} ]]; then
  mkdir -p "${COMOUT_OBS}"
fi

###############################################################
# Run relevant script
###############################################################

"${SCRgfs}/exglobal_prep_sfc.sh"
export err=$?
err_chk

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [ -e "${pgmout}" ]; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi


exit 0
