#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" base wave waveprep

export COMPONENT="wave"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

# Set rtofs PDY
export RPDY=${PDY}

export MP_PULSE=0

# CDO required for processing RTOFS currents
export CDO=${CDO_ROOT}/bin/cdo

# Path to HOME Directory
export FIXwave=${FIXwave:-${HOMEgfs}/fix/fix_wave_${NET}}
export PARMwave=${PARMwave:-${HOMEgfs}/parm/wave}
export USHwave=${USHwave:-${HOMEgfs}/ush}
export EXECwave=${EXECwave:-${HOMEgfs}/exec}

# Set COM Paths and GETGES environment
export COMIN=${COMIN:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}}
export COMOUT=${COMOUT:-${ROTDIR}/${CDUMP}.${PDY}/${cyc}/${COMPONENT}}
[[ ! -d ${COMOUT} ]] && mkdir -m 775 -p ${COMOUT}

if [ ${RUN_ENVIR} = "nco" ]; then
  export COMIN_WAV_ICE=${COMIN_WAV_ICE:-$(compath.py ${envir}/obsproc/${obsproc_ver})}/${CDUMP}.${PDY}/${cyc}/atmos
  export COMIN_WAV_RTOFS=${COMIN_WAV_RTOFS:-$(compath.py ${envir}/${WAVECUR_DID}/${rtofs_ver})}
else
  if [ ${WW3CURINP} = "YES" ]; then
    if [ ! -d ${DMPDIR}/${WAVECUR_DID}.${RPDY} ]; then export RPDY=$(${NDATE} -24 ${PDY}00 | cut -c1-8); fi
    if [ ! -L ${ROTDIR}/${WAVECUR_DID}.${RPDY} ]; then # Check if symlink already exists in ROTDIR
      ${NLN} ${DMPDIR}/${WAVECUR_DID}.${RPDY} ${ROTDIR}/${WAVECUR_DID}.${RPDY}
    fi
    BRPDY=$(${NDATE} -24 ${RPDY}00 | cut -c1-8)
    if [ ! -L ${ROTDIR}/${WAVECUR_DID}.${BRPDY} ]; then # Check if symlink already exists in ROTDIR
      ${NLN} ${DMPDIR}/${WAVECUR_DID}.${BRPDY} ${ROTDIR}/${WAVECUR_DID}.${BRPDY}
    fi
    export COMIN_WAV_RTOFS=${COMIN_WAV_RTOFS:-${ROTDIR}}
  fi
  if [ ${WW3ICEINP} = "YES" ]; then
    if [ ! -L ${ROTDIR}/${CDUMP}.${PDY}/${cyc}/atmos/${WAVICEFILE} ]; then # Check if symlink already exists in ROTDIR
      ${NLN} ${DMPDIR}/${CDUMP}.${PDY}/${cyc}/atmos/${WAVICEFILE} ${ROTDIR}/${CDUMP}.${PDY}/${cyc}/atmos/${WAVICEFILE}
    fi
    export COMIN_WAV_ICE=${COMIN_WAV_ICE:-${ROTDIR}/${RUN}.${PDY}/${cyc}/atmos}
  fi
fi

# Execute the Script
${HOMEgfs}/scripts/exgfs_wave_prep.sh

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
