#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "wavepostbndpnt" -c "base wave wavepostsbs wavepostbndpnt"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

export MP_PULSE=0

# Set COM Paths and GETGES environment
YMD=${PDY} HH=${cyc} generate_com -rx COM_WAVE_PREP COM_WAVE_HISTORY COM_WAVE_STATION

if [[ ! -d ${COM_WAVE_STATION} ]]; then mkdir -p "${COM_WAVE_STATION}"; fi

# Set wave model ID tag to include member number
# if ensemble; waveMEMB var empty in deterministic
membTAG='p'
if [ "${waveMEMB}" == "00" ]; then membTAG='c'; fi
export membTAG
export WAV_MOD_TAG=${RUN}wave${waveMEMB}

export CFP_VERBOSE=1

export FHMAX_WAV_PNT=${FHMAX_WAV_IBP}
export DOSPC_WAV='YES' # Spectral post
export DOBLL_WAV='NO' # Bulletin post
export DOBNDPNT_WAV='YES'  # Do boundary points

# Execute the Script
${SCRgfs}/exgfs_wave_post_pnt.sh
err=$?
if [ ${err} -ne 0 ]; then
  echo "FATAL ERROR: ex-script of GWES_POST failed!"
  exit ${err}
fi

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
