#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "waveprep" -c "base wave waveprep"

# Add default errchk = err_chk
export errchk=${errchk:-err_chk}

export CDUMP=${RUN/enkf}

# Set rtofs PDY
export RPDY=${PDY}

export MP_PULSE=0

# CDO required for processing RTOFS currents
export CDO=${CDO_ROOT}/bin/cdo

# Set COM Paths and GETGES environment
YMD=${PDY} HH=${cyc} generate_com -rx COM_OBS COM_WAVE_PREP
generate_com -rx COM_RTOFS
[[ ! -d ${COM_WAVE_PREP} ]] && mkdir -m 775 -p "${COM_WAVE_PREP}"

# Execute the Script
${SCRgfs}/exgfs_wave_prep.sh

##########################################
# Remove the Temporary working directory
##########################################
cd ${DATAROOT}
[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}


exit 0
