#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
source "${HOMEgfs}/ush/jjob_header.sh" -e "arch" -c "base arch"


##############################################
# Set variables used in the script
##############################################
export CDUMP=${RUN/enkf}

YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
	COMOUT_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
	COMOUT_ATMOS_BUFR:COM_ATMOS_BUFR_TMPL \
	COMOUT_ATMOS_GEMPAK:COM_ATMOS_GEMPAK_TMPL \
	COMOUT_ATMOS_GENESIS:COM_ATMOS_GENESIS_TMPL \
	COMOUT_ATMOS_HISTORY:COM_ATMOS_HISTORY_TMPL \
	COMOUT_ATMOS_INPUT:COM_ATMOS_INPUT_TMPL \
	COMOUT_ATMOS_MASTER:COM_ATMOS_MASTER_TMPL \
	COMOUT_ATMOS_RESTART:COM_ATMOS_RESTART_TMPL \
	COMOUT_ATMOS_TRACK:COM_ATMOS_TRACK_TMPL \
	COMOUT_ATMOS_WMO:COM_ATMOS_WMO_TMPL \
        COMOUT_CHEM_HISTORY:COM_CHEM_HISTORY_TMPL \
	COMOUT_CHEM_ANALYSIS:COM_CHEM_ANALYSIS_TMPL \
	COMOUT_MED_RESTART:COM_MED_RESTART_TMPL \
	COMOUT_SNOW_ANALYSIS:COM_SNOW_ANALYSIS_TMPL \
	COMOUT_ICE_HISTORY:COM_ICE_HISTORY_TMPL \
	COMOUT_ICE_INPUT:COM_ICE_INPUT_TMPL \
	COMOUT_ICE_RESTART:COM_ICE_RESTART_TMPL \
	COMOUT_ICE_GRIB:COM_ICE_GRIB_TMPL \
	COMOUT_OBS:COM_OBS_TMPL \
	COMOUT_TOP:COM_TOP_TMPL \
	COMOUT_OCEAN_HISTORY:COM_OCEAN_HISTORY_TMPL \
	COMOUT_OCEAN_RESTART:COM_OCEAN_RESTART_TMPL \
	COMOUT_OCEAN_GRIB:COM_OCEAN_GRIB_TMPL \
	COMOUT_OCEAN_NETCDF:COM_OCEAN_NETCDF_TMPL \
	COMOUT_OCEAN_ANALYSIS:COM_OCEAN_ANALYSIS_TMPL \
	COMOUT_WAVE_GRID:COM_WAVE_GRID_TMPL \
	COMOUT_WAVE_HISTORY:COM_WAVE_HISTORY_TMPL \
	COMOUT_WAVE_STATION:COM_WAVE_STATION_TMPL \
	COMOUT_WAVE_RESTART:COM_WAVE_RESTART_TMPL \
	COMOUT_ATMOS_OZNMON:COM_ATMOS_OZNMON_TMPL \
	COMOUT_ATMOS_RADMON:COM_ATMOS_RADMON_TMPL \
	COMOUT_ATMOS_MINMON:COM_ATMOS_MINMON_TMPL \
	COMOUT_CONF:COM_CONF_TMPL

for grid in "0p25" "0p50" "1p00"; do
  YMD=${PDY} HH=${cyc} GRID=${grid} declare_from_tmpl -rx \
	  "COMOUT_ATMOS_GRIB_${grid}:COM_ATMOS_GRIB_GRID_TMPL"
done

###############################################################
# Run archive script
###############################################################

${GLOBALARCHIVESH:-${SCRgfs}/exglobal_archive.py}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi


##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (echo "${DATAROOT} does not exist. ABORT!"; exit 1)
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"

exit 0
