#!/bin/bash

date
export PS4=' $SECONDS + '
set -xa

# PATH for working directory
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}
export COMPONENT=${COMPONENT:-wave}
export HOMEwave=${HOMEwave:-$(dirname $(dirname $0))} # parent directory of current job card

###################################
# Set COM Paths
###################################
export COMIN=${COMIN:-$(compath.py ${NET}/${envir}/${RUN}.${PDY})/${cyc}/$COMPONENT}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/${cyc}/$COMPONENT/gempak}
export PCOM=${PCOM:-${COMOUT}/wmo}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-YES}
if [ $SENDCOM = YES ]; then
  mkdir -p $COMOUT $PCOM
fi

###################################
# Execute the Script  
###################################
$HOMEwave/scripts/exgfswave_prdgen_gridded.native.sh.ecf

###################################
# Remove temp directories
###################################
if [ "$KEEPDATA" != "YES" ]; then
  cd $DATAROOT
  rm -rf $DATA
fi
date

