#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "gen_control_ic" -c "base gen_control_ic"


##############################################
# Set variables used in the script
##############################################
export EXECufs=${EXECufs:-${HOMEgfs}/sorc/ufs_utils.fd/exec}
export CASE="C384"
export LEVS="128"
export OCNRES="025"
# Calculate gPDY (previous day) and gcyc (previous cycle hour)
PDY="${PDY:-$(date +%Y%m%d)}"
cyc="${cyc:-00}"

# gPDY: previous day in YYYYMMDD format
gPDY=$(date -d "${PDY} -1 day" +%Y%m%d)

# gcyc: previous cycle hour
case "${cyc}" in
  "00") gcyc="18" ;;
  "06") gcyc="00" ;;
  "12") gcyc="06" ;;
  "18") gcyc="12" ;;
  *)
    echo "ERROR: Invalid cyc value '${cyc}'. Must be one of 00, 06, 12, 18."
    exit 1
    ;;
esac

# Define COM directories
MEMDIR="mem000" YMD=${gPDY} HH=${gcyc} declare_from_tmpl -rx \
    COMIN_ATMOS_HISTORY_MEM:COM_ATMOS_HISTORY_TMPL \
    COMIN_ATMOS_RESTART_PREV_MEM:COM_ATMOS_RESTART_TMPL
MEMDIR="mem000" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_ATMOS_INPUT_MEM:COM_ATMOS_INPUT_TMPL
###############################################################
# Run relevant script
${CHGRESFCSTSH:-${SCRgfs}/exglobal_atmos_chgres_gen_control.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##########################################
# Remove the Temporary working directory
##########################################
# cd "${DATAROOT}" || true
# if [[ "${KEEPDATA}" == "NO" ]]; then
#     rm -rf "${DATA}"
# fi


exit 0
