C
C SUBPROGRAM:   MAIN.BLOCK.DATA   BLOCK DATA FOR MAIN IN FAXMAKR90
C   PRGMMR: KRISHNA KUMAR         ORG: W/NP12    DATE: 1999-08-01
C
C ABSTRACT: THIS IS THE BLOCK DATA STATEMENT FOR MAIN IN FAXMAKR90 CODE
C
C PROGRAM HISTORY LOG:
C   1999-08-01 KRISHNA KUMAR
C
C USAGE: BLOCK DATA ISCHED
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE: IBM
C
        BLOCK DATA ISCHED_DATA
      COMMON /NSCHED/ ISLOTA,IPANA,ISUB,IFLAB,INSET,IRLAB,ISCHED(8,50)
        DATA ISCHED/4390,1,0,3600,Z'8000',Z'D800',0,0,392*0/
C
       END BLOCK DATA ISCHED_DATA
C
