      SUBROUTINE WNDPLO(FLDU,FLDV,IMAX,JMAX)
C                                                                       00319800
C     ...GIVEN FLDU AND FLDV WIND COMPONENTS INKNOTS                    00319900
C     ...TASK...GET WIND DIRECTION AND SPEED AND ENTER INTO LABEL ARRAY 00320000
C     ...IN A FORM WHICH WILL OBTAIN WIND STAFF AND BARBS               00320100
C     ...THESE GRIDPOINTS BEING IN A DIAMOND PATTERN.                   00320200
C                                                                       00320300
      COMMON/SHTST/ISSH
C     ...ISSH = 1 IF ONE WISHES TO REVERSE WIND BARBS FOR SH WINDS.     00320500
      DIMENSION FLDU(IMAX,JMAX),FLDV(IMAX,JMAX)
      DATA    ICORN/0/
      DATA    JCORN/-30/
      DATA    IT/30/
      JLOB=3
      JHIB=JMAX-2
      ILHS=3
      IRHS=IMAX-1
      ILHSB=5
      IRHSB=IMAX-3
      IDEWAY=1
C     ...WHICH SETS IT FOR SIDEWAYS ORIENTATION FOR WIND DIR            00321700
      ADD=0.
      XMPY=1.0
      INDENT=1
C     ...WHERE INDENT IS ALTERNATING SWITCH FOR INDENTINGA ROW OR NOT.  00322100
C     ...WHERE INDENT IS ALTERNATING SWITCH FOR INDENTING A ROW OR NOT. 00322200
      DO 450 J=JLOB,JHIB,2
      IF(INDENT)433,434,433
  433 CONTINUE
      INDENT=0
      I=ILHS
      I2=IRHS
      GO TO 440
  434 CONTINUE
      INDENT=1
      I=ILHSB
      I2=IRHSB
      GO TO 440
C     ...PERFORM OPERATION ON WIND PT(I,J)                              00323500
  440 CONTINUE
      ISTN=IT*(I-1)+ICORN
      JSTN=IT*(J-1)+JCORN
      U=FLDU(I,J)*XMPY+ADD
      V=FLDV(I,J)*XMPY+ADD
      CALL WWNDR(U,V,IDDFF,IDD,IFFF)
      IF(IDEWAY.NE.1) GO TO 633
C     ...IDEWAY WAS=1, SO CONVERT IDD FROM TRUE NORTH TO GRID ORIENTED  00324300
      IDD=IDD-9
      IF(IDD.LE.0) IDD=IDD+36
  633 CONTINUE
      IOPTN=0
      IF(ISSH .NE. 1) GO TO 442
      IF(I .GT. 25) IDD = -IDD
  442 CONTINUE
      CALL WNDBRK(ISTN,JSTN,IDD,IFFF,NWOK,IOPTN,iret)
c      stop 'WNDBR'
      IF(NWOK.GT.0) GO TO 572
      PRINT 444,I,J
  444 FORMAT('0ABNORMAL EXIT FROM WNDBRK WHERE I=  ',I4,'  J=',I4,
     1   'THIS WIND PLOT SKIPPED')
C     ...IS THERE ENOUGH SPACE FOR ALL PIECES OF WIND VECTOR QQ         00325600
  572 CONTINUE
      I=I+4
      IF(I.LE.I2) GO TO 440
C     ...WHEN IT FALLS THRU HERE, THIS ROW IS FINISHED, GO TO NEXT J.   00326000
  450 CONTINUE
      RETURN
      END
