#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "analdiag" -c "base anal analdiag"

##############################################
# Set variables used in the script
##############################################
#export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"}

##############################################
# Begin JOB SPECIFIC work
##############################################
# shellcheck disable=SC2153
#GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
#export gPDY=${GDATE:0:8}
#export gcyc=${GDATE:8:2}
#export GDUMP="gdas"
#export GDUMP_ENS="enkf${GDUMP}"

#export OPREFIX="${RUN/enkf/}.t${cyc}z."
#export GPREFIX="${GDUMP}.t${gcyc}z."
#export APREFIX="${RUN}.t${cyc}z."

<<<<<<<< HEAD:dev/jobs/JGDAS_ATMOS_ANALYSIS_DIAG
YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
    COMOUT_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL
mkdir -m 775 -p "${COMOUT_ATMOS_ANALYSIS}"

###############################################################
# Run relevant script
${ANALDIAGSH:-${SCRgfs}/exglobal_diag.sh} && true
========
export LEVS=$((LEVS - 1))

# Additional variables are set in scripts/exenkfgdas_ens_post.sh:
#  COMIN_ATMOS_HISTORY, set in a loop over ensemble members
#  COMOUT_ATMOS_HISTORY_STAT

###############################################################
# Run relevant script

${ENKFPOSTSH:-${SCRglobal}/exenkfgdas_ens_post.sh} && true
>>>>>>>> origin/develop:dev/jobs/JENKFGDAS_ENS_POST
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
