#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "anal" -c "base anal echgres"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################
export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"}

##############################################
# Begin JOB SPECIFIC work
##############################################

export APREFIX="${RUN/enkf/}.t${cyc}z."
export APREFIX_ENS="${RUN}.t${cyc}z."

declare -rx COMIN_ATMOS_HISTORY="${ROTDIR}/${RUN/enkf/}.${PDY}/${cyc}/model/atmos/history"
declare -rx COMOUT_ATMOS_HISTORY="${ROTDIR}/${RUN/enkf/}.${PDY}/${cyc}/model/atmos/history"

declare -rx COMIN_ATMOS_HISTORY_MEM="${ROTDIR}/${RUN}.${PDY}/${cyc}/mem001/model/atmos/history"

###############################################################
# Run relevant script
${CHGRESFCSTSH:-${SCRglobal}/exgdas_atmos_chgres_forenkf.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
