#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "gempak" -c "base gempak"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

export GRIB=${GRIB:-pgrb2f}
export EXT=""
export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-GDAS_GEMPAK}

##############################################
# Define COM directories
##############################################
for grid in 0p25 1p00; do
    declare -rx "COMIN_ATMOS_GRIB_${grid}"="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/${grid}"
done

for grid in 0p25 1p00; do
    prod_dir="COMOUT_ATMOS_GEMPAK_${grid}"
    declare -rx "COMOUT_ATMOS_GEMPAK_${grid}"="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/gempak/${grid}"

    if [[ ! -d "${!prod_dir}" ]]; then
        mkdir -m 775 -p "${!prod_dir}"
    fi
done

########################################################
# Execute the script for one degree grib
########################################################

"${SCRglobal}/exgdas_atmos_nawips.sh" "1p00" "${FHR3}" "GDAS_GEMPAK" "${COMOUT_ATMOS_GEMPAK_1p00}" && true

export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to generate AWIPS products at 1 degree resolution for forecast hour ${FHR3}"
fi

########################################################
# Execute the script for quarter-degree grib
########################################################

"${SCRglobal}/exgdas_atmos_nawips.sh" "0p25" "${FHR3}" "GDAS_GEMPAK" "${COMOUT_ATMOS_GEMPAK_0p25}" && true

export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to generate AWIPS products at 0.25 degree resolution for forecast hour ${FHR3}"
fi

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi
