#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "epos" -c "base epos"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################
export GFS_NCIO=${GFS_NCIO:-"YES"}

export PREFIX="${RUN}.t${cyc}z."

export LEVS=$((LEVS - 1))

# Additional variables are set in scripts/exgdas_enkf_post.sh:
#  COMIN_ATMOS_HISTORY, set in a loop over ensemble members
#  COMOUT_ATMOS_HISTORY_STAT

###############################################################
# Run relevant script

${ENKFPOSTSH:-${SCRglobal}/exgdas_enkf_post.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to run ensemble post processing"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
