#! /usr/bin/env bash
set -x

#############################################################
# Set up environment for GDAS Radiance Monitor job
#############################################################
source "${HOMEglobal}/ush/jjob_header.sh" -e "verfrad" -c "base verfrad"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"

#############################################
#  determine PDY and cyc for previous cycle
#############################################
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}

#############################################
# COMOUT - WHERE GSI OUTPUT RESIDES
# TANKverf - WHERE OUTPUT DATA WILL RESIDE
#############################################
declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_ATMOS_RADMON="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/radmon"
declare -rx COMIN_ATMOS_RADMON_PREV="${ROTDIR}/${RUN}.${gPDY}/${gcyc}/products/atmos/radmon"

export biascr="${COMIN_ATMOS_ANALYSIS}/gdas.t${cyc}z.abias.txt"
export radstat="${COMIN_ATMOS_ANALYSIS}/gdas.t${cyc}z.radstat.tar"
export TANKverf_rad=${TANKverf_rad:-${COMOUT_ATMOS_RADMON}}
export TANKverf_radM1=${TANKverf_radM1:-${COMIN_ATMOS_RADMON_PREV}}

if [[ ! -d ${TANKverf_rad} ]]; then mkdir -p "${TANKverf_rad}"; fi

########################################################
# Execute the script.
"${SCRglobal}/exgdas_atmos_verfrad.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

################################
# Remove the Working Directory
################################
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
