#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "gempak" -c "base gempak"

export GRIB=${GRIB:-pgrb2f}
export EXT=""
export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-GDAS_GEMPAK}

##############################################
# Define COM directories
##############################################

declare -rx COMOUT_ATMOS_GRIB_1p00=${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/1p00
declare -rx COMOUT_ATMOS_GRIB_0p25=${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/0p25
declare -rx COMOUT_ATMOS_GEMPAK_1p00=${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/gempak/1p00
declare -rx COMOUT_ATMOS_GEMPAK_0p25=${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/gempak/0p25

for grid in 0p25 1p00; do
    prod_dir="COMOUT_ATMOS_GEMPAK_${grid}"

    if [[ ! -d "${!prod_dir}" ]]; then
        mkdir -m 775 -p "${!prod_dir}"
    fi
done

########################################################
# Execute the script for one degree grib
########################################################

"${SCRgfs}/exgdas_atmos_nawips.sh" "1p00" "${FHR3}" "GDAS_GEMPAK" "${COMOUT_ATMOS_GEMPAK_1p00}" && true

export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

########################################################
# Execute the script for quater-degree grib
########################################################

"${SCRgfs}/exgdas_atmos_nawips.sh" "0p25" "${FHR3}" "GDAS_GEMPAK" "${COMOUT_ATMOS_GEMPAK_0p25}" && true

export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi
