#! /usr/bin/env bash
set -x

source "${HOMEgfs}/ush/jjob_header.sh" -e "epos" -c "base epos"

#{% if false %}
source "${HOMEgfs}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHgfs}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHgfs}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################
export GFS_NCIO=${GFS_NCIO:-"YES"}

export PREFIX="${RUN}.t${cyc}z."

export LEVS=$((LEVS - 1))

###############################################################
# Run relevant script

${ENKFPOSTSH:-${SCRgfs}/exgdas_enkf_post.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
