#! /usr/bin/env bash

source "${HOMEglobal}/ush/jjob_header.sh" -e "wave_stat_pnt" -c "base wave wave_stat_pnt"

# Set COM Paths

declare -rx COMOUT_WAVE_STATION_ENS="${ROTDIR}/${RUN}.${PDY}/${cyc}/ensstat/products/wave/station"
if [[ ! -d "${COMOUT_WAVE_STATION_ENS}" ]]; then
    mkdir -m 775 -p "${COMOUT_WAVE_STATION_ENS}"
fi

# Execute the Script
#"${SCRglobal}/exgefs_wave_stat_pnt.sh"
export err=$?
err_chk
##########################################
## Remove the Temporary working directory
###########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
