#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "genesis_fsu" -c "base genesis_fsu"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"

##############################################
# Define COM and Data directories
##############################################
declare -rx COMOUT_ATMOS_GENESIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/cyclone/genesis_vital"
declare -rx COMIN_ATMOS_GRIB_0p25="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/0p25"

# The following variables are used by the tracker scripts which are outside
#   of global-workflow and therefore can't be standardized at this time
export COMIN=${COMIN_ATMOS_GRIB_0p25}
export gfsdir=${COMIN_ATMOS_GRIB_0p25}
export COMINgfs=${COMIN_ATMOS_GRIB_0p25}
export COMOUT=${COMOUT_ATMOS_GENESIS}
export COMINsyn=${COMINsyn:-$(compath.py "${envir}/com/gfs/${gfs_ver}")/syndat}

##############################################
# Run relevant script
##############################################

#############################################################
# Execute the script
"${SCRIPTens_tracker}/exgfs_fsu_genesis.sh"
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
