#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "postsnd" -c "base postsnd"

########################################
# Runs GFS BUFR SOUNDINGS
########################################

##############################
# Define COM Directories
##############################

declare -rx COMIN_ATMOS_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/history"
declare -rx COMIN_ATMOS_BUFR="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/bufr"
declare -rx COMOUT_ATMOS_BUFR="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/bufr"
declare -rx COMOUT_ATMOS_WMO="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/wmo"
declare -rx COMOUT_ATMOS_GEMPAK="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/gempak/"

if [[ ! -d "${COMOUT_ATMOS_BUFR}" ]]; then
    mkdir -p "${COMOUT_ATMOS_BUFR}"
fi
if [[ ! -d "${COMOUT_ATMOS_GEMPAK}" ]]; then
    mkdir -p "${COMOUT_ATMOS_GEMPAK}"
fi
if [[ ! -d "${COMOUT_ATMOS_WMO}" ]]; then
    mkdir -p "${COMOUT_ATMOS_WMO}"
fi

########################################################
# Execute the script.
"${SCRgfs}/exgfs_atmos_postsnd.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
