#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "tracker" -c "base tracker"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

export COMPONENT="atmos"

##############################################
# Define COM and Data directories
##############################################
declare -rx COMOUT_ATMOS_TRACK="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/cyclone/tracks"
declare -rx COMIN_ATMOS_GENESIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/cyclone/genesis_vital"
declare -rx COMIN_ATMOS_GRIB_0p25="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/0p25"

if [[ ! -d "${COMOUT_ATMOS_TRACK}" ]]; then mkdir -p "${COMOUT_ATMOS_TRACK}"; fi

# The following variables are used by the tracker scripts which are outside
#   of global-workflow and therefore can't be standardized at this time
export COMINgfs=${COMIN_ATMOS_GRIB_0p25}
export gfsdir=${COMIN_ATMOS_GRIB_0p25}
export COMINgdas=${COMIN_ATMOS_GRIB_0p25}
export gdasdir=${COMIN_ATMOS_GRIB_0p25}
export COMOUT=${COMOUT_ATMOS_TRACK}
export COMINsyn=${COMINsyn:-$(compath.py "${envir}/com/gfs/${gfs_ver}")/syndat}
export COMINgenvit=${COMIN_ATMOS_GENESIS}

if [[ "${RUN_ENVIR}" == "nco" ]]; then
    export COMOUThur=${COMROOTp1}/hur/${envir}/global
    export COMOUTatcf=${COMROOTp1}/nhc/${envir}/atcf
    mkdir -m 775 -p "${COMOUThur}" "${COMOUTatcf}"
else
    #    export COMOUThur=$COMOUT
    #    export COMOUTatcf=$COMOUT
    export COMOUThur=${DATA}
    export COMOUTatcf=${DATA}
fi

##############################################
# Run relevant script
##############################################

#############################################################
# Execute the script
export pert="p01"
export cmodel=${RUN/enkf/}
export loopnum=1

#-----------input data checking -----------------
"${USHens_tracker}/data_check_gfs.sh"
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi
#------------------------------------------------

"${USHens_tracker}/extrkr_gfs.sh" "${loopnum}" "${cmodel}" "${PDY}${cyc}" "${pert}" "${DATA}"
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

#  cat ${DATA}/trak.avnx.atcfunix.${PDY}${cyc} | \
#      sed s:AVNX:GFSO:g \
#    > ${COMOUT}/gfso.t${cyc}z.cyclone.trackatcfunix
#
#  cat ${DATA}/trak.avnx.atcfunix.${PDY}${cyc} | \
#      sed s:AVNX:AVNO:g \
#    > ${COMOUT}/avn.t${cyc}z.cyclone.trackatcfunix

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
