#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "genesis" -c "base genesis"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the exglobal script
##############################################
export cmodel=${RUN}

##############################################
# Define COM directories
##############################################
declare -rx COMOUT_ATMOS_GENESIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/cyclone/genesis_vital"
declare -rx COMIN_ATMOS_GRIB_0p25="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/0p25"

# The following variables are used by the tracker scripts which are outside
#   of global-workflow and therefore can't be standardized at this time
export COMIN=${COMIN_ATMOS_GRIB_0p25}
export gfsdir=${COMIN_ATMOS_GRIB_0p25}
export COMINgfs=${COMIN_ATMOS_GRIB_0p25}

export COMINgenvit=${COMOUT_ATMOS_GENESIS}
export COMOUTgenvit=${COMOUT_ATMOS_GENESIS}
export COMOUT=${COMOUT_ATMOS_GENESIS}

export COMINsyn=${COMINsyn:-$(compath.py "${envir}/com/gfs/${gfs_ver}")/syndat}

mkdir -m 775 -p "${COMOUTgenvit}"

export JYYYY=${PDY:0:4}

##############################################
# Run relevant script
##############################################

# Do not fail on errors or unassigned variables in external code
source "${USHglobal}/unset_strict.sh"
"${SCRIPTens_tracker}/exgfs_tc_genesis.sh" && true
export err=$?
source "${USHglobal}/set_strict.sh"
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to run the tropical cyclone genesis script"
fi

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
