#! /usr/bin/env bash
set -x

# TODO (#1225) This job is not part of the rocoto suite

############################################
# GFS PGRB2_SPECIAL_POST PRODUCT GENERATION
############################################
source "${HOMEglobal}/ush/jjob_header.sh" -e "npoess" -c "base npoess"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}

##############################################
# Define COM directories
##############################################

declare -rx COMIN_ATMOS_MASTER="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/master"
declare -rx COMOUT_ATMOS_GOES="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/goes_sim"
declare -rx COMIN_ATMOS_GRIB_0p50="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/0p50"

mkdir -m 775 -p "${COMOUT_ATMOS_GOES}"

#############################################################
# Execute the script
"${SCRglobal}/exgfs_atmos_grib2_special_npoess.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to simulate NPOESS data from GFS GRIB2 products"
fi
#############################################################

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi
