#! /usr/bin/env bash

# TODO (#1222) This job is not part of the rocoto suite

############################################
# GFS GEMPAK META PRODUCT GENERATION
############################################
source "${HOMEglobal}/ush/jjob_header.sh" -e "gempak_meta" -c "base gempak"

###############################################
# Set MP variables
###############################################
export LAUNCH_MODE=MPI
export OMP_NUM_THREADS=1
export MP_LABELIO=yes
export MP_PULSE=0
export MP_DEBUG_NOTIMEOUT=yes

cpreq "${HOMEglobal}/gempak/fix/datatype.tbl" datatype.tbl

#############################################
#set the fcst hrs for all the cycles
#############################################
export fhbeg=0
export fhend=384
export fhinc=12

if [[ "${fhend}" -gt "${FHMAX_GFS}" ]]; then
    export fhend="${FHMAX_GFS}"
fi

export COMPONENT="atmos"

##############################################
# Set up model and cycle specific variables
##############################################
export DBN_ALERT_TYPE=GFS_METAFILE

##############################################
# Define COM directories
##############################################
export COMINukmet=${COMINukmet:-$(compath.py "${envir}/ukmet/${ukmet_ver}")/ukmet}
export COMINecmwf=${COMINecmwf:-$(compath.py "${envir}/ecmwf/${ecmwf_ver}")/ecmwf}
export COMINnam=${COMINnam:-$(compath.py "${envir}/nam/${nam_ver}")/nam}

declare -rx COMIN_ATMOS_GEMPAK_1p00="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/gempak/1p00"

declare -rx COMOUT_ATMOS_GEMPAK_META="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/gempak/meta"
mkdir -m 775 -p "${COMOUT_ATMOS_GEMPAK_META}"

########################################################
# Execute the script.
"${SCRglobal}/exgfs_atmos_gempak_meta.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi
########################################################

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi
