#! /usr/bin/env bash
set -x
export EXPDIR="${EXPDIR:-${HOMEglobal}/parm/config/${NET}}"
source "${HOMEglobal}/ush/jjob_header.sh" -e "gempak" -c "base gempak"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

############################################
# Set up model and cycle specific variables
############################################
export GRIB=${GRIB:-pgrb2f}
export EXT=""
export DBN_ALERT_TYPE=${DBN_ALERT_TYPE:-GFS_GEMPAK}

# For half-degree P Grib files
export DO_HD_PGRB=${DO_HD_PGRB:-YES}

##############################################
# Define COM directories
##############################################
declare -rx "COMIN_ATMOS_GRIB_0p25"="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/0p25"

for grid in 0p25 40km 35km_atl 35km_pac; do
    prod_dir="COMOUT_ATMOS_GEMPAK_${grid}"
    declare -rx "COMOUT_ATMOS_GEMPAK_${grid}"="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/gempak/${grid}"

    if [[ ! -d "${!prod_dir}" ]]; then
        mkdir -m 775 -p "${!prod_dir}"
    fi
done

fhr=10#${FHR3}
ocean_domain_max=180
if ((ocean_domain_max > FHMAX_GFS)); then
    ocean_domain_max=${FHMAX_GFS}
fi

#################################################################
# Execute the script for the quater-degree grib
####################################################################
fhmin=0
fhmax=120
if [[ "${fhr}" -ge "${fhmin}" ]] && [[ "${fhr}" -le "${fhmax}" ]]; then
    if ((fhr % 1 == 0)); then
        "${SCRglobal}/exgfs_atmos_nawips.sh" "0p25" "${FHR3}" "GFS_GEMPAK" "${COMOUT_ATMOS_GEMPAK_0p25}" && true
        export err=$?
        if [[ ${err} -ne 0 ]]; then
            err_exit "Failed to generate 0.25 degree GEMPAK products for forecast hour ${FHR3}"
        fi
    fi
fi

fhmin=123
fhmax=240
if [[ "${fhr}" -ge "${fhmin}" ]] && [[ "${fhr}" -le "${fhmax}" ]]; then
    if ((fhr % 3 == 0)); then
        "${SCRglobal}/exgfs_atmos_nawips.sh" "0p25" "${FHR3}" "GFS_GEMPAK" "${COMOUT_ATMOS_GEMPAK_0p25}" && true
        export err=$?
        if [[ ${err} -ne 0 ]]; then
            err_exit "Failed to generate 0.25 degree GEMPAK products for forecast hour ${FHR3}"
        fi
    fi
fi

fhmin=252
fhmax=384
if [[ "${fhr}" -ge "${fhmin}" ]] && [[ "${fhr}" -le "${fhmax}" ]]; then
    if ((fhr % 12 == 0)); then
        "${SCRglobal}/exgfs_atmos_nawips.sh" "0p25" "${FHR3}" "GFS_GEMPAK" "${COMOUT_ATMOS_GEMPAK_0p25}" && true
        export err=$?
        if [[ ${err} -ne 0 ]]; then
            err_exit "Failed to generate 0.25 degree GEMPAK products for forecast hour ${FHR3}"
        fi
    fi
fi

####################################################################
# Execute the script to create the 35km and 40km grids
#####################################################################
fhmin=0
fhmax="${ocean_domain_max}"
if [[ "${fhr}" -ge "${fhmin}" ]] && [[ "${fhr}" -le "${fhmax}" ]]; then
    if ((fhr % 3 == 0)); then
        "${SCRglobal}/exgfs_atmos_nawips.sh" "35km_pac" "${FHR3}" "GFS_GEMPAK_WWB" "${COMOUT_ATMOS_GEMPAK_35km_pac}" && true
        export err=$?
        if [[ ${err} -ne 0 ]]; then
            err_exit "Failed to generate Pacific 35km GEMPAK products for forecast hour ${FHR3}"
        fi

        "${SCRglobal}/exgfs_atmos_nawips.sh" "35km_atl" "${FHR3}" "GFS_GEMPAK_WWB" "${COMOUT_ATMOS_GEMPAK_35km_atl}" && true
        export err=$?
        if [[ ${err} -ne 0 ]]; then
            err_exit "Failed to generate Atlantic 35km GEMPAK products for forecast hour ${FHR3}"
        fi

        "${SCRglobal}/exgfs_atmos_nawips.sh" "40km" "${FHR3}" "GFS_GEMPAK_WWB" "${COMOUT_ATMOS_GEMPAK_40km}" && true
        export err=$?
        if [[ ${err} -ne 0 ]]; then
            err_exit "Failed to generate 40km GEMPAK products for forecast hour ${FHR3}"
        fi
    fi
fi

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi
