#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "awips" -c "base awips"

export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}

export COMPONENT="atmos"

##############################################
# Define COM directories
##############################################

declare -rx COMOUT_ATMOS_WMO="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/wmo"
declare -rx COMIN_ATMOS_GRIB_0p25="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/grib2/0p25"

if [[ ! -d "${COMOUT_ATMOS_WMO}" ]]; then
    mkdir -m 775 -p "${COMOUT_ATMOS_WMO}"
fi

export pgmout=OUTPUT.$$

########################################################
# Execute the script.
#   Forecast hours from F00 - F84  at 3-hour interval
#   Forecast hours from F90 - F240 at 6-hour interval
#########################################################

########################################################
# Execute the script.
"${SCRgfs}/exgfs_atmos_awips_20km_1p0deg.sh" "${fcsthr}" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi
########################################################

############################################
# print exec I/O output
############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

###################################
# Remove temp directories
###################################
cd "${DATAROOT}" || pass
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi
