#! /usr/bin/env bash
source "${HOMEglobal}/ush/jjob_header.sh" -e "ice_post" -c "base ice_post"
export DATA="${DATAROOT}/ocean_post_${ENSMEM}.${jobid}"
mkdir -p ${DATA}
if ((10#${ENSMEM:-0} > 0)); then
    export DATAoutput="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}/output"
else
    export DATAoutput="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}/output"
fi

# Construct COM variables from templates
YMD=${PDY} HH=${cyc} 
memdir=$(printf "mem%03i" $((10#${ENSMEM})))
COMOUT=${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}
declare -rx "COMOUT_ICE_HISTORY"="${COMOUT}/model/ice/history" 
declare -rx "COMOUT_ICE_NETCDF"="${COMOUT}/products/ice/netcdf"
if [[ ! -d "${COMOUT_ICE_NETCDF}" ]]; then mkdir -p "${COMOUT_ICE_NETCDF}"; fi

# Define current cycle
export current_cycle="${PDY}${cyc}"

# Check if ice 24hr_avg native files are complete for ice post job
shopt -s nullglob
ice_24hrly_files=( "${COMOUT_ICE_NETCDF}/native/${RUN}.t${cyc}z.native.f"*".nc" ) # ice 24hr_avg history files
ice_24hrly_num=$(( FHMAX_GFS / 24 )) #expected total number of ice 24hr_avg history files
echo "INFO: Found ${#ice_24hrly_files[@]} of ice 24hr_avg history files."

if [[ "${#ice_24hrly_files[@]}" -lt "${ice_24hrly_num}" ]]; then
   echo "ERROR: Ice history file count mismatch detected!"
   echo "ice 24hr_avg history files: ${#ice_24hrly_files[@]} Found VS ${ice_24hrly_num} Expected"
   echo "FATAL: The ice history files are incomplete. Ice post job quits!"
   exit 1
fi

##############################################
# Begin JOB SPECIFIC work
##############################################

# Run exglobal script
"${SCRglobal}/exglobal_ice_post.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

exit 0
