#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "waveinit" -c "base wave waveinit"

export MP_PULSE=0

# Set COM Paths
declare -rx COMOUT_WAVE_PREP="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/prep"

if [[ ! -d "${COMOUT_WAVE_PREP}" ]]; then mkdir -p "${COMOUT_WAVE_PREP}"; fi

# Set mpi serial command
export wavempexec=${wavempexec:-"mpirun -n"}
export wave_mpmd=${wave_mpmd:-"cfp"}

# Execute the Script
"${SCRgfs}/exgfs_wave_init.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
