#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "analdiag" -c "base anal analdiag"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"

##############################################
# Set variables used in the script
##############################################
#export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"}

##############################################
# Begin JOB SPECIFIC work
##############################################
# shellcheck disable=SC2153
#GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
#export gPDY=${GDATE:0:8}
#export gcyc=${GDATE:8:2}
#export GDUMP="gdas"
#export GDUMP_ENS="enkf${GDUMP}"

#export OPREFIX="${RUN/enkf/}.t${cyc}z."
#export GPREFIX="${GDUMP}.t${gcyc}z."
#export APREFIX="${RUN}.t${cyc}z."

declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
mkdir -m 775 -p "${COMOUT_ATMOS_ANALYSIS}"

# Create a DATAROOT directory variable where the gsidiags live
# shellcheck disable=SC2153
pCOMIN_ATMOS_ANALYSIS="$(dataroot_com_path "${COMIN_ATMOS_ANALYSIS}")"
export pCOMIN_ATMOS_ANALYSIS

###############################################################
# Run relevant script
${ANALDIAGSH:-${SCRglobal}/exglobal_diag.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
