#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "atmos_post" -c "base atmos_post"
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
source "${USHglobal}/jjob_shell_setup.sh"

# Construct COM variables
# shellcheck disable=SC2309
if [[ "${ENSMEM}" =~ ^[0-9]+$ ]]; then
    memdir=$(printf "mem%03d" $((10#${ENSMEM})))
    export COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
    export COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
    export DATAjob="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}"
else
    export COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}"
    export COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}"
    export DATAjob="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}"
fi

# Create the directory to hold output for this job
export DATAoutput="${DATAjob}/output"
if [[ ! -d "${DATAoutput}" ]]; then mkdir -p "${DATAoutput}"; fi

# Construct COM variables from templates
declare -rx "COMIN_ATMOS_MASTER"="${COMIN}/model/atmos/master"
declare -rx "COMOUT_ATMOS_GRIB"="${COMOUT}/products/atmos/grib2"
if [[ ! -d "${COMIN_ATMOS_MASTER}" ]]; then mkdir -p "${COMIN_ATMOS_MASTER}"; fi
if [[ ! -d "${COMOUT_ATMOS_GRIB}" ]]; then mkdir -p "${COMOUT_ATMOS_GRIB}"; fi

# Define directory variables to save the source atmos master files temporarily
export ATMOS_MASTER_OUTPUT="${DATAoutput}/FV3ATM_OUTPUT/model/master"
if [[ ! -d "${ATMOS_MASTER_OUTPUT}" ]]; then mkdir -p "${ATMOS_MASTER_OUTPUT}"; fi

# Define current cycle
export current_cycle="${PDY}${cyc}"

# Check if atmos 6hrly master files are complete for atmos post job
shopt -s nullglob
atmos_6hrly_files=("${ATMOS_MASTER_OUTPUT}/sfs.t00z.master.f"*".grib2")
atmos_6hrly_num=$((FHMAX_GFS / 6 + 1)) #expected total number of atmos master files
echo "INFO: Found ${#atmos_6hrly_files[@]} of 6hrly atmos master files."

if [[ "${#atmos_6hrly_files[@]}" -lt "${atmos_6hrly_num}" ]]; then
    echo "ERROR: Atmos master file count mismatch detected!"
    echo " 6hrly atmos master files: ${#atmos_6hrly_files[@]} Found VS  ${atmos_6hrly_num} Expected "
    echo " FATAL: The 6hrly atmos master files are incomplete. Atmos post job quits!"
    exit 1
fi

##############################################
# Begin JOB SPECIFIC work
##############################################

# Run exglobal script
"${SCRglobal}/exglobal_atmos_post.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

exit 0
