#! /usr/bin/env bash
# shellcheck disable=SC2153
set -x
source "${HOMEglobal}/ush/jjob_header.sh" -e "ecen_fv3jedi" -c "base ecen_fv3jedi"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
gPDY=${GDATE:0:8}
gcyc=${GDATE:8:2}
GDUMP="gdas"
GDUMP_ENS="enkfgdas"

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${GDUMP}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_ATMOS_ANALYSIS="${ROTDIR}/${GDUMP}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMIN_ATMOS_ANALYSIS_ENSSTAT="${ROTDIR}/${GDUMP_ENS}.${PDY}/${cyc}/ensstat/analysis/atmos"
declare -rx COMOUT_ATMOS_ANALYSIS_ENSSTAT="${ROTDIR}/${GDUMP_ENS}.${PDY}/${cyc}/ensstat/analysis/atmos"
declare -rx COMOUT_CONF="${ROTDIR}/${GDUMP_ENS}.${PDY}/${cyc}/ensstat/conf"
declare -rx COMIN_ATMOS_HISTORY_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/model/atmos/history"

mkdir -m 755 -p "${COMOUT_CONF}"

##############################################
# Run relevant script
##############################################

EXSCRIPT=${GDASATMRUNPY:-${SCRglobal}/exglobal_enkf_ecen_fv3jedi.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################

if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##############################################
# Remove the Temporary working directory
##############################################

cd "${DATAROOT}" && true
export err=$?
set +x
if [[ ${err} -ne 0 ]]; then
    err_exit "${DATAROOT} does not exist, ABORT!"
fi
set_trace
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
