#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "globus_earc" -c "base globus earc_groups"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for wxflow and pygfs
if [[ -d "${HOMEgfs}/sorc/wxflow/src" ]]; then
    PYTHONPATH="${HOMEgfs}/sorc/wxflow/src${PYTHONPATH:+:${PYTHONPATH}}"
fi
PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${HOMEgfs}/ush/python"
export PYTHONPATH

MEMDIR="ensstat" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_CONF:COM_CONF_TMPL

###############################################################
# Run globus script
###############################################################

export -n SHELLOPTS
${GLOBALGLOBUSARCHSH:-${SCRgfs}/exglobal_globus_earc.py}
err=$?
if [[ ${err} -ne 0 ]]; then
    exit "${err}"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
[[ ${KEEPDATA} == "NO" ]] && rm -rf "${DATA}"

exit 0
