#! /usr/bin/env bash
set -x
source "${HOMEgfs}/dev/ush/jjob_standard_vars.sh"

# TODO (#1227) This job is not used in the rocoto suite

source "${HOMEgfs}/ush/jjob_header.sh" -e "post" -c "base post"
source "${HOMEgfs}/dev/ush/jjob_shell_setup.sh"

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}

###########################
# Set up EXT variable
###########################
export EXT_FCST=NO

declare -rx COMIN_ATMOS_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/history"

########################################################
# Execute the script.
"${SCRgfs}/exglobal_atmos_pmgr.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi
########################################################
