#! /usr/bin/env bash
# shellcheck disable=SC2153  # PDY is always set in environment
source "${HOMEgfs}/ush/jjob_header.sh" -e "gen_control_ic" -c "base gen_control_ic"

# Initial conditions are from previous GFS cycle, but valid at the end of the cycle
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
# shellcheck disable=SC2155
BDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - $((assim_freq / 2)) hours")
export BDATE

# Define COM directories
# TODO: uncomment when testing for realtime
#COMINgfs=$(compath.py "${envir}/gfs/${gfs_ver}")
MEMDIR="mem000" YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMOUT_ATMOS_INPUT_MEM:COM_ATMOS_INPUT_TMPL
###############################################################
# Create COMOUT_ATMOS_INPUT_MEM
mkdir -p "${COMOUT_ATMOS_INPUT_MEM}"
###############################################################

# Define the input ATM_FILE and SFC_FILE from GFS
export ATM_FILE="${COMINgfs:-}/gfs.${GDATE:0:8}/${GDATE:8:2}/atmos/history/gfs.t${GDATE:8:2}.atm.f003.nc"
export SFC_FILE="${COMINgfs:-}/gfs.${GDATE:0:8}/${GDATE:8:2}/atmos/history/gfs.t${GDATE:8:2}.sfc.f003.nc"
###############################################################
# Run relevant script
${CHGRESFCSTSH:-${SCRgfs}/exglobal_atmos_chgres_gen_control.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to run chgres_cube, ABORT!"
fi
##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
