#! /usr/bin/env bash
set -x
export DATA=${DATA:-${DATAROOT}/${RUN}fetch_${cyc}}
source "${HOMEglobal}/ush/jjob_header.sh" -e "fetch" -c "base fetch"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# Execute fetching
# Do not export shell opts to the bash scripts in the htar/hsi wrappers
export -n SHELLOPTS
"${SCRglobal}/exglobal_fetch.py"
err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to fetch data for ${RUN} cycle ${PDY}${cyc}"
fi

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (
    echo "${DATAROOT} does not exist. ABORT!"
    exit 1
)
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
