#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "cleanup" -c "base cleanup"
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
source "${USHglobal}/jjob_shell_setup.sh"

"${SCRglobal}/exglobal_cleanup.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

#################################################
# Remove the Temporary working directory DATAROOT
# In XML, DATAROOT is defined as:
# DATAROOT="${STMP}/RUNDIRS/${PSLOT}/${RUN}.${PDY}${cyc}"
# cleanup is only executed after the entire cycle is successfully completed.
# Removing DATAROOT should be possible if that is the case.

rm -rf "${DATAROOT}"
echo "Cleanup ${DATAROOT} completed!"

exit 0
