#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "prep_emissions" -c "base prep_emissions"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEgfs}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# TODO: Set local variables used in this script e.g. GDATE may be needed for previous cycle

##############################################
# Begin JOB SPECIFIC work
##############################################
# Construct COM variables
# shellcheck disable=SC2309
if [[ 10#${ENSMEM:--1} -ge 0 ]]; then
    # Turn ensmem into 3-digit format with leading zeros
    memdir=$(printf "mem%03i" $((10#${ENSMEM})))
    declare -rx COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
else
    declare -rx COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}"
fi

declare -rx COMOUT_CHEM_INPUT="${COMOUT}/model/chem/input"
declare -rx COMOUT_CHEM_RESTART="${COMOUT}/model/chem/restart"

mkdir -p "${COMOUT_CHEM_INPUT}"

###############################################################
# Run relevant script
EXSCRIPT=${PREP_EMISSIONS_PY:-${SCRgfs}/exglobal_prep_emissions.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Error executing ${EXSCRIPT}, ABORT!"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

exit 0
