#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "ediag" -c "base anal eobs analdiag ediag"

##############################################
# Set variables used in the script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################

export CASE=${CASE_ENS}

export APREFIX="${RUN}.t${cyc}z."

declare -rx COMIN_OBS="${ROTDIR}/#${RUN/enkf/}.${PDY}/${cyc}/obs"
declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/ensstat/analysis/atmos"
declare -rx COMOUT_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/ensstat/analysis/atmos"

# Create a DATAROOT directory variable where the gsidiags live
# shellcheck disable=SC2153
pCOMIN_ATMOS_ANALYSIS="$(dataroot_com_path "${COMIN_ATMOS_ANALYSIS}")"
export pCOMIN_ATMOS_ANALYSIS

# Diagnostics related to ensemble mean
export CNVSTAT="${COMOUT_ATMOS_ANALYSIS}/${APREFIX}cnvstat_ensmean.tar"
export OZNSTAT="${COMOUT_ATMOS_ANALYSIS}/${APREFIX}oznstat_ensmean.tar"
export RADSTAT="${COMOUT_ATMOS_ANALYSIS}/${APREFIX}radstat_ensmean.tar"

export DIAG_SUFFIX="_ensmean"
export DIAG_COMPRESS="NO"

# GSI namelist options specific to eobs
#export SETUP_INVOBS="passive_bc=.false.,${SETUP_INVOBS}"

###############################################################
# Run relevant script

${ANALDIAGSH:-${SCRgfs}/exglobal_diag.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
