#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "waveprep" -c "base wave waveprep"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

# Set rtofs PDY
# shellcheck disable=SC2153
export RPDY=${PDY}

export MP_PULSE=0

# CDO required for processing RTOFS currents
export CDO=${CDO_ROOT}/bin/cdo

# Set COM Paths
declare -rx COMIN_OBS="${ROTDIR}/${RUN}.${PDY}/${cyc}/obs"
declare -rx COMIN_WAVE_PREP="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/prep"
declare -rx COMOUT_WAVE_PREP="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/prep"
if [[ "${RUN_ENVIR:-emc}" == "nco" ]]; then
    #shellcheck disable=SC2155
    declare -rx COMINrtofs=$(compath.py "${envir}/rtofs/${rtofs_ver}")
else
    declare -rx COMINrtofs="${DMPDIR}"
fi

mkdir -p "${COMOUT_WAVE_PREP}"

# Execute the Script
"${SCRglobal}/exgfs_wave_prep.sh" && true

export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
