#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "esfc_regrid" -c "base esfc_regrid"

##############################################
# Set variables used in the script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}
export GDUMP="gdas"
export GDUMP_ENS="enkf${GDUMP}"

export CASE=${CASE_ENS}

export APREFIX="${RUN/enkf/}.t${cyc}z."
export APREFIX_ENS="${RUN}.t${cyc}z."

# Use CFP to stage and save files in parallel
export USE_CFP=YES

###############################################################
# Run relevant script

${ENKFSFCREGRIDSH:-${SCRgfs}/exglobal_enkf_sfc_regrid.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
