#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "wavepostsbs" -c "base wave wavepostsbs"
source "${USHgfs}/wave_domain_grid.sh"

# Set COM Paths
# shellcheck disable=SC2309
if [[ 10#${ENSMEM:--1} -ge 0 ]]; then
    memdir=$(printf "mem%03i" $((10#${ENSMEM})))
    declare -rx COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
    declare -rx COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
else
    declare -rx COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}"
    declare -rx COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}"
fi

declare -rx COMIN_WAVE_PREP="${COMIN}/model/wave/prep"
declare -rx COMIN_WAVE_HISTORY="${COMIN}/model/wave/history"
declare -rx COMOUT_WAVE_GRID="${COMOUT}/products/wave/gridded"

mkdir -p "${COMOUT_WAVE_GRID}"

if [[ -n "${wavepostGRD}" || -n "${waveinterpGRD}" ]]; then
    for grdID in ${wavepostGRD} ${waveinterpGRD}; do
        process_grdID "${grdID}"
        declare -rx "COMOUT_WAVE_GRID_${GRDREGION}_${GRDRES}"="${COMOUT}/products/wave/gridded/${grdNAME}"
        out_dir_varname="COMOUT_WAVE_GRID_${GRDREGION}_${GRDRES}"
        out_dir=${!out_dir_varname}
        mkdir -p "${out_dir}"
    done
else
    echo "Both wavepostGRD and waveinterpGRD are empty. No grids to process."
fi

# Execute the Script
"${SCRgfs}/exgfs_wave_post_gridded_sbs.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "ex-script of gridded wave post failed!"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
