#! /usr/bin/env bash
set -x

export DATA=${DATA:-${DATAROOT}/${RUN}atmanl_${cyc}}
source "${HOMEglobal}/ush/jjob_header.sh" -e "atmanlinit" -c "base atmanl atmanlinit"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
gPDY=${GDATE:0:8}
gcyc=${GDATE:8:2}
GDUMP="gdas"

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
declare -rx COMIN_OBS="${ROTDIR}/${RUN}.${PDY}/${cyc}/obs"

declare -rx COMIN_ATMOS_ANALYSIS_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/analysis/atmos"
declare -rx COMIN_ATMOS_HISTORY_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/model/atmos/history"

###############################################################
# Run relevant script

EXSCRIPT=${GDASATMINITPY:-${SCRglobal}/exglobal_atm_analysis_initialize.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to initialize the atmospheric analysis"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

exit 0
