#! /usr/bin/env bash
source "${HOMEglobal}/ush/jjob_header.sh" -e "ice_post" -c "base ice_post"
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
source "${USHglobal}/jjob_shell_setup.sh"

# Construct COM variables
# shellcheck disable=SC2309
if [[ "${ENSMEM}" =~ ^[0-9]+$ ]]; then
    memdir=$(printf "mem%03d" $((10#${ENSMEM})))
    export COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
    export COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
    export DATAjob="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}"
else
    export COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}"
    export COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}"
    export DATAjob="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}"
fi

# Create the directory to hold output for this job
export DATAoutput="${DATAjob}/output"
if [[ ! -d "${DATAoutput}" ]]; then mkdir -p "${DATAoutput}"; fi

# Construct COM directory from templates to save the final ice products
declare -rx "COMOUT_ICE_NETCDF"="${COMOUT}/products/ice/netcdf"
if [[ ! -d "${COMOUT_ICE_NETCDF}" ]]; then mkdir -p "${COMOUT_ICE_NETCDF}"; fi
mkdir -p "${COMOUT_ICE_NETCDF}/native"

# Define directory variable to save the ice product files temporarily
export ICE_PRODUCT_OUTPUT="${DATAoutput}/CICE_OUTPUT/PRODUCT"
if [[ ! -d "${ICE_PRODUCT_OUTPUT}" ]]; then mkdir -p "${ICE_PRODUCT_OUTPUT}"; fi

# Define current cycle
export current_cycle="${PDY}${cyc}"

# Check if ice 24hr_avg native files are complete for ice post job
shopt -s nullglob
ice_24hrly_files=("${ICE_PRODUCT_OUTPUT}/native/${RUN}.t${cyc}z.native.f"*".nc") # ice 24hr_avg history files
ice_24hrly_num=$((FHMAX_GFS / 24))                                               #expected total number of ice 24hr_avg history files
echo "INFO: Found ${#ice_24hrly_files[@]} of ice 24hr_avg history files."

if [[ "${#ice_24hrly_files[@]}" -lt "${ice_24hrly_num}" ]]; then
    echo "ERROR: Ice history file count mismatch detected!"
    echo "ice 24hr_avg history files: ${#ice_24hrly_files[@]} Found VS ${ice_24hrly_num} Expected"
    echo "FATAL: The ice history files are incomplete. Ice post job quits!"
    exit 1
fi

##############################################
# Begin JOB SPECIFIC work
##############################################

# Run exglobal script
"${SCRglobal}/exglobal_ice_post.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

exit 0
