#!/bin/bash
set -x
export WIPE_DATA="NO"
export DATAjob="${DATAROOT}/marineanalysis.${PDY:-}${cyc}"
# DATA is pre-populated by the MARINE_BMAT_INIT job
export DATA="${DATAjob}/marinebmat"
# Create the directory to hold ensemble perturbations
export DATAens="${DATAjob}/ensdata"
export DATAstaticb="${DATAjob}/staticb"
if [[ ! -d "${DATAens}" ]]; then mkdir -p "${DATAens}"; fi
if [[ ! -d "${DATAstaticb}" ]]; then mkdir -p "${DATAstaticb}"; fi
# source config.base, config.ocnanal and config.marinebmat
# and pass marinebmat to ${machine}.env
source "${HOMEglobal}/ush/jjob_header.sh" -e "marinebmat" -c "base marinebmat"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
gPDY=${GDATE:0:8}
gcyc=${GDATE:8:2}
export GDUMP="gdas"
export GDUMP_ENS="enkf${GDUMP}"

ec_offset=${NMEM_ENS_GFS_OFFSET:-20}
export NMEM_ENS_MAX=${NMEM_ENS}
if [[ "${RUN}" == "gfs" && "${DOHYBVAR_OCN}" == "YES" ]]; then
    NMEM_ENS=${NMEM_ENS_GFS}
    export mem_offset=$((ec_offset * cyc / assim_freq))
else
    export mem_offset=0
fi

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
declare -rx COMIN_OCEAN_HISTORY_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/model/ocean/history"
declare -rx COMIN_ICE_HISTORY_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/model/ice/history"

declare -rx COMIN_OCEAN_HISTORY_ENS_PREV="${ROTDIR}/${GDUMP_ENS}.${gPDY}/${gcyc}/model/ocean/history"
declare -rx COMIN_ICE_HISTORY_ENS_PREV="${ROTDIR}/${GDUMP_ENS}.${gPDY}/${gcyc}/model/ice/history"

declare -rx COMOUT_OCEAN_BMATRIX="${ROTDIR}/${RUN}.${PDY}/${cyc}/bmatrix/ocean"
declare -rx COMOUT_ICE_BMATRIX="${ROTDIR}/${RUN}.${PDY}/${cyc}/bmatrix/ice"
declare -rx COMOUT_CONF="${ROTDIR}/${RUN}.${PDY}/${cyc}/conf"

mkdir -m 775 -p "${COMOUT_OCEAN_BMATRIX}"
mkdir -m 775 -p "${COMOUT_ICE_BMATRIX}"
mkdir -m 775 -p "${COMOUT_CONF}"

###############################################################
# Run relevant script

EXSCRIPT=${GDASMARINEBMATRUNPY:-${SCRglobal}/exglobal_marinebmat.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

exit 0
