#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "anlstat" -c "base anlstat"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates

declare -rx COMIN_OBS="${ROTDIR}/${RUN}.${PDY}/${cyc}/obs"
declare -rx COMOUT_CONF="${ROTDIR}/${RUN}.${PDY}/${cyc}/conf"
declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_ATMOS_ANLMON="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/anlmon"
mkdir -m 755 -p "${COMOUT_ATMOS_ANALYSIS}"
mkdir -m 755 -p "${COMOUT_CONF}"

if [[ "${DO_AERO_ANL:-NO}" == "YES" ]]; then
    declare -rx COMIN_AERO_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/chem"
    declare -rx COMOUT_AERO_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/chem"
    declare -rx COMOUT_AERO_ANLMON="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/chem/anlmon"
    mkdir -m 755 -p "${COMOUT_AERO_ANALYSIS}"
    mkdir -m 755 -p "${COMOUT_AERO_ANLMON}"
fi

if [[ "${DO_JEDISNOWDA:-NO}" == "YES" ]]; then
    declare -rx COMIN_SNOW_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/snow"
    declare -rx COMOUT_SNOW_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/snow"
    declare -rx COMOUT_SNOW_ANLMON="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/snow/anlmon"
    mkdir -m 755 -p "${COMOUT_SNOW_ANALYSIS}"
    mkdir -m 755 -p "${COMOUT_SNOW_ANLMON}"
fi

###############################################################
# Run relevant script

EXSCRIPT=${ANLSTATSPY:-${SCRglobal}/exglobal_analysis_stats.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

exit 0
