#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "globus_arch" -c "base globus"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEgfs}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

declare -rx COMIN_CONF="${ROTDIR}/${RUN}.${PDY}/${cyc}/conf"

###############################################################
# Run globus script
###############################################################

export -n SHELLOPTS
${GLOBALGLOBUSARCHSH:-${SCRgfs}/exglobal_globus_arch.py}
err=$?
[[ ${err} -ne 0 ]] && exit "${err}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
[[ ${KEEPDATA} == "NO" ]] && rm -rf "${DATA}"

exit 0
