#! /usr/bin/env bash
set -x

# TODO (#1227) This job is not used in the rocoto suite

source "${HOMEglobal}/ush/jjob_header.sh" -e "post" -c "base post"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}

###########################
# Set up EXT variable
###########################
export EXT_FCST=NO

declare -rx COMIN_ATMOS_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/history"

########################################################
# Execute the script.
"${SCRglobal}/exglobal_atmos_pmgr.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi
########################################################
