#! /usr/bin/env bash
set -x
source "${HOMEglobal}/ush/jjob_header.sh" -e "ocn_post" -c "base ocn_post"

export DATA="${DATAROOT}/ocean_post_${ENSMEM}.${jobid}"
mkdir -p ${DATA}
if ((10#${ENSMEM:-0} > 0)); then
    export DATAoutput="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}/output"
else
    export DATAoutput="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}/output"
fi

# Construct COM variables from templates
YMD=${PDY} HH=${cyc} 
memdir=$(printf "mem%03i" $((10#${ENSMEM})))
COMOUT=${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}
declare -rx "COMOUT_OCEAN_HISTORY"="${COMOUT}/model/ocean/history" 
declare -rx "COMOUT_OCEAN_NETCDF"="${COMOUT}/products/ocean/netcdf"
if [[ ! -d "${COMOUT_OCEAN_NETCDF}" ]]; then mkdir -p "${COMOUT_OCEAN_NETCDF}"; fi

# Define current cycle
export current_cycle="${PDY}${cyc}"

# Check if ocean 24hr_avg and 6hr_avg history files are complete for ocn post job
shopt -s nullglob
ocn_24hrly_files=( "${COMOUT_OCEAN_NETCDF}/${grid}/${RUN}.t${cyc}z.1p00.f"*".nc" ) # ocean 24hr_avg history files
ocn_6hrly_files=( "${DATAoutput}/MOM6_OUTPUT/temp_"*".nc" ) # ocean (temp) 6hr_avg history files
ocn_24hrly_num=$(( FHMAX_GFS / 24 )) #expected total number of ocean 24hr_avg files
ocn_6hrly_num=$(( FHMAX_GFS / 6 )) #expected total number of ocean 6hr_avg files
echo "INFO: Found ${#ocn_24hrly_files[@]} of ocean 24hr_avg history files."
echo "INFO: Found ${#ocn_6hrly_files[@]} of ocean 6hr_avg history files."

if [[ "${#ocn_24hrly_files[@]}" -lt "${ocn_24hrly_num}" ]] || [[ "${#ocn_6hrly_files[@]}" -lt "${ocn_6hrly_num}" ]]; then
   echo "ERROR: File count mismatch detected!"
   echo "Ocean 24hr_avg fistory files: ${#ocn_24hrly_files[@]} Found vs ${ocn_24hrly_num} Expected"
   echo "Ocean 6hr_avg history files:  ${#ocn_6hrly_files[@]} Found vs ${ocn_6hrly_num} Expected"
   echo "FATAL: The ocean history files are incomplete. Ocean post job quits!"
   exit 1
fi

##############################################
# Begin JOB SPECIFIC work
##############################################

# Run exglobal script
"${SCRglobal}/exglobal_ocn_post.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

exit 0
