#! /usr/bin/env bash

# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153

source "${HOMEglobal}/ush/jjob_header.sh" -e "analcalc_fv3jedi" -c "base analcalc_fv3jedi"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
gPDY=${GDATE:0:8}
gcyc=${GDATE:8:2}
GDUMP="gdas"
export rCDUMP="${RUN/enkf/}"

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates
declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMIN_ATMOS_HISTORY_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/model/atmos/history"
declare -rx COMOUT_CONF="${ROTDIR}/${RUN}.${PDY}/${cyc}/conf"

mkdir -m 775 -p "${COMOUT_CONF}"

##############################################
# Run relevant script
##############################################

EXSCRIPT=${GDASATMRUNPY:-${SCRglobal}/exglobal_atmos_analysis_calc_fv3jedi.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

# Write analysis log file
echo "${rCDUMP} ${PDY}${cyc} atmanl and sfcanl done at $(date)" > "${COMOUT_ATMOS_ANALYSIS}/${RUN}.t${cyc}z.done.txt"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################

if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##############################################
# Remove the Temporary working directory
##############################################

cd "${DATAROOT}" && true
export err=$?
set +x
if [[ ${err} -ne 0 ]]; then
    err_exit "${DATAROOT} does not exist, ABORT!"
fi
set_trace
if [[ ${KEEPDATA} == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
