#! /usr/bin/env bash

source "${HOMEglobal}/ush/jjob_header.sh" -e "analcalc" -c "base anal analcalc"

# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

##############################################
# Set variables used in the script
##############################################
export rCDUMP="${RUN/enkf/}"
export DO_CALC_ANALYSIS=${DO_CALC_ANALYSIS:-"YES"}

##############################################
# Begin JOB SPECIFIC work
##############################################
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}
GDUMP="${RUN/gfs/gdas}"
export GDUMP_ENS="enkf${GDUMP}"

export OPREFIX="${rCDUMP}.t${cyc}z."
export GPREFIX="${GDUMP}.t${gcyc}z."
export APREFIX="${RUN}.t${cyc}z."
export GPREFIX_ENS="${GDUMP_ENS}.t${gcyc}z."

declare -rx COMIN_OBS="${ROTDIR}/${rCDUMP}.${PDY}/${cyc}/obs"

declare -rx COMOUT_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMIN_ATMOS_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/restart"

if [[ "${RUN}" == "gcdas" ]]; then
    declare -rx COMIN_CHEM_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/chem"
fi

declare -rx COMIN_OBS_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/obs"
declare -rx COMIN_ATMOS_HISTORY_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/model/atmos/history"

export ATMGES="${COMIN_ATMOS_HISTORY_PREV}/${GPREFIX}atm.f006.nc"
if [[ ! -f "${ATMGES}" ]]; then
    export err=1
    err_exit "FILE MISSING: ATMGES == ${ATMGES}"
fi

# Get LEVS
export LEVS
LEVS=$(${NCLEN} "${ATMGES}" pfull) && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

# Generate Gaussian surface analysis  # TODO: Should this be removed now that sfcanl is its own job?
export DOGAUSFCANL=${DOGAUSFCANL:-"YES"}

###############################################################
# Run relevant script

${ANALCALCSH:-${SCRglobal}/exglobal_atmos_analysis_calc.sh} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
