#! /usr/bin/env bash

source "${HOMEglobal}/ush/jjob_header.sh" -e "wavegempak" -c "base wave wavegempak"
source "${USHglobal}/wave_domain_grid.sh"

###################################
# Set COM Paths
###################################
export DBN_ALERT_TYPE=GFS_WAVE_GEMPAK

declare -rx COMOUT_WAVE_GEMPAK="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/gempak"

if [[ -n "${GEMPAK_GRIDS}" ]]; then
    for grdID in ${GEMPAK_GRIDS}; do
        process_grdID "${grdID}"
        declare -rx "COMIN_WAVE_GRID_${GRDREGION}_${GRDRES}"="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/gridded/${grdNAME}"
    done
else
    echo "'GEMPAK_GRIDS' is empty. No grids to process."
fi

if [[ ! -d ${COMOUT_WAVE_GEMPAK} ]]; then mkdir -p "${COMOUT_WAVE_GEMPAK}"; fi

########################################################
# Execute the script.
"${SCRglobal}/exgfs_wave_nawips.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi
###################################

# Remove temp directories
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
