#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "waveawipsbulls" -c "base wave waveawipsbulls"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"

###################################
# Set COM Paths
###################################

declare -rx COMIN_WAVE_STATION="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/station"
declare -rx COMOUT_WAVE_WMO="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/wmo"

mkdir -p "${COMOUT_WAVE_WMO}"

###################################
# Execute the Script

"${SCRglobal}/exgfs_wave_prdgen_bulls.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

###################################
# Remove temp directories
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
