#!/bin/bash

# Use ${DATAROOT/enkf} because DATAjob is created by a gdas_marineanlinit job
export DATAjob="${DATAROOT/enkf/}/marineanalysis.${PDY:-}${cyc}"
export DATA="${DATAjob}/marineanlletkf"
export DATAens="${DATAjob}/ensdata"
if [[ ! -d "${DATAens}" ]]; then mkdir -p "${DATAens}"; fi

source "${HOMEglobal}/ush/jjob_header.sh" -e "marineanlletkf" -c "base marineanlletkf"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")

gPDY=${GDATE:0:8}
gcyc=${GDATE:8:2}
export GDUMP="gdas"
export GDUMP_ENS="enkf${GDUMP}"

ec_offset=${NMEM_ENS_GFS_OFFSET:-20}
export NMEM_ENS_MAX=${NMEM_ENS}
if [[ "${RUN/enkf/}" == "gfs" && "${DOHYBVAR_OCN}" == "YES" ]]; then
    NMEM_ENS=${NMEM_ENS_GFS}
    export mem_offset=$((ec_offset * cyc / assim_freq))
else
    export mem_offset=0
fi

declare -rx COMIN_OCEAN_HISTORY_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/model/ocean/history"
declare -rx COMIN_ICE_HISTORY_PREV="${ROTDIR}/${GDUMP}.${gPDY}/${gcyc}/model/ice/history"

declare -rx COMIN_OBS="${ROTDIR}/${GDUMP}.${PDY}/${cyc}/obs"

declare -rx COMOUT_OCEAN_LETKF="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/ocean/letkf"
declare -rx COMOUT_ICE_LETKF="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/ice/letkf"

declare -rx COMOUT_CONF="${ROTDIR}/${RUN}.${PDY}/${cyc}/ensstat/conf"

if [[ ! -d "${COMOUT_OCEAN_LETKF}" ]]; then mkdir -p "${COMOUT_OCEAN_LETKF}"; fi
if [[ ! -d "${COMOUT_ICE_LETKF}" ]]; then mkdir -p "${COMOUT_ICE_LETKF}"; fi
if [[ ! -d ${COMOUT_CONF} ]]; then mkdir -p "${COMOUT_CONF}"; fi
##############################################
# Begin JOB SPECIFIC work
##############################################

###############################################################
# Run relevant script

EXSCRIPT=${GDASOCNLETKFPY:-${HOMEglobal}/scripts/exglobal_marine_analysis_letkf.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
# Use ${DATAROOT/enkf} because DATAjob is created by a gdas_marineanlinit job
cd "${DATAROOT/enkf/}" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

exit 0
