#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "prep" -c "base prep"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Begin JOB SPECIFIC work
##############################################

export PROCESS_TROPCY=${PROCESS_TROPCY:-YES} # Turn on tropical cyclone tcvitals QC proc. if YES
export DO_RELOCATE=${DO_RELOCATE:-NO}        # Turn on tropical cyclone relocation proc. if YES

export tmmark=tm00
export ARCHSYND=${ROTDIR}/syndat # this location is unique, do not change
mkdir -p "${ARCHSYND}"

export HOMENHC=${HOMENHC:-/lfs/h1/ops/prod/dcom/nhc/atcf/ncep}

export TANK_TROPCY=${TANK_TROPCY:-${DCOMROOT}} # path to tropical cyclone record database

##############################################
# Define COM directories
##############################################
declare -rx COMOUT_OBS="${ROTDIR}/${RUN}.${PDY}/${cyc}/obs"
mkdir -p "${COMOUT_OBS}"

export CRES=${CASE_HIST:1}
export LATB=$((CRES * 2))
export LONB=$((CRES * 4))
export BKGFREQ=1 # for hourly relocation

##############################################
# Run relevant script
##############################################

${TROPCYQCRELOSH:-${SCRglobal}/exglobal_atmos_tropcy_qc_reloc.sh}
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
