#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "wavegempak" -c "base wave wavegempak"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"
source "${USHglobal}/wave_domain_grid.sh"

###################################
# Set COM Paths
###################################
export DBN_ALERT_TYPE=GFS_WAVE_GEMPAK

declare -rx COMOUT_WAVE_GEMPAK="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/gempak"

if [[ -n "${GEMPAK_GRIDS}" ]]; then
    for grdID in ${GEMPAK_GRIDS}; do
        process_grdID "${grdID}"
        declare -rx "COMIN_WAVE_GRID_${GRDREGION}_${GRDRES}"="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/gridded/${grdNAME}"
    done
else
    echo "'GEMPAK_GRIDS' is empty. No grids to process."
fi

if [[ ! -d ${COMOUT_WAVE_GEMPAK} ]]; then mkdir -p "${COMOUT_WAVE_GEMPAK}"; fi

########################################################
# Execute the script.
"${SCRglobal}/exgfs_wave_nawips.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to generate wave gempak/AWIPS products."
fi
###################################

# Remove temp directories
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
