#! /usr/bin/env bash
set -x
source "${HOMEgfs}/dev/ush/jjob_standard_vars.sh"

source "${HOMEgfs}/ush/jjob_header.sh" -e "stage_ic" -c "base stage_ic"
source "${HOMEgfs}/dev/ush/jjob_shell_setup.sh"

# Setup Python path for pygfs
PYTHONPATH="${HOMEgfs}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# Execute staging
"${SCRgfs}/exglobal_stage_ic.py"
err=$?

###############################################################
# Check for errors and exit if any of the above failed
if [[ "${err}" -ne 0 ]]; then
    echo "Unable to stage ICs to ${ROTDIR}; ABORT!"
    exit "${err}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (
    echo "${DATAROOT} does not exist. ABORT!"
    exit 1
)
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
