#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "waveawipsbulls" -c "base wave waveawipsbulls"

###################################
# Set COM Paths
###################################

declare -rx COMIN_WAVE_STATION="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/station"
declare -rx COMOUT_WAVE_WMO="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/wmo"

mkdir -p "${COMOUT_WAVE_WMO}"

###################################
# Execute the Script

"${SCRgfs}/exgfs_wave_prdgen_bulls.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

###################################
# Remove temp directories
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
