#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "prep_emissions" -c "base prep_emissions"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEgfs}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# TODO: Set local variables used in this script e.g. GDATE may be needed for previous cycle

##############################################
# Begin JOB SPECIFIC work
##############################################
declare -rx COMOUT_CHEM_INPUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/chem/input"
declare -rx COMOUT_CHEM_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/chem/restart"

mkdir -p "${COMOUT_CHEM_INPUT}"

###############################################################
# Run relevant script
EXSCRIPT=${PREP_EMISSIONS_PY:-${SCRgfs}/exglobal_prep_emissions.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Error executing ${EXSCRIPT}, ABORT!"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

exit 0
