#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "arch_vrfy" -c "base arch_tars"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
if [[ "${DO_WAVE}" == "YES" ]]; then
    source "${EXPDIR}/config.wave"
    source "${USHglobal}/wave_domain_grid.sh"
fi

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# Construct COM paths
# shellcheck disable=SC2309
if [[ 10#${ENSMEM:--1} -ge 0 ]]; then
    memdir=$(printf "mem%03d" $((10#${ENSMEM})))
    COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
    COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
else
    COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}"
    COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}"
fi

declare -rx COMIN_ATMOS_ANALYSIS="${COMIN}/analysis/atmos"
declare -rx COMIN_ATMOS_ANLMON="${COMIN}/products/atmos/anlmon"
declare -rx COMIN_ATMOS_BUFR="${COMIN}/products/atmos/bufr"
declare -rx COMIN_ATMOS_GEMPAK="${COMIN}/products/atmos/gempak/"
declare -rx COMIN_ATMOS_GENESIS="${COMIN}/products/atmos/cyclone/genesis_vital"
declare -rx COMIN_ATMOS_HISTORY="${COMIN}/model/atmos/history"
declare -rx COMIN_ATMOS_INPUT="${COMIN}/model/atmos/input"
declare -rx COMIN_ATMOS_MASTER="${COMIN}/model/atmos/master"
declare -rx COMIN_ATMOS_RESTART="${COMIN}/model/atmos/restart"
declare -rx COMIN_ATMOS_TRACK="${COMIN}/products/atmos/cyclone/tracks"
declare -rx COMIN_ATMOS_WMO="${COMIN}/products/atmos/wmo"
declare -rx COMIN_CHEM_HISTORY="${COMIN}/model/chem/history"
declare -rx COMIN_CHEM_ANALYSIS="${COMIN}/analysis/chem"
declare -rx COMIN_MED_RESTART="${COMIN}/model/med/restart"
declare -rx COMIN_SNOW_ANALYSIS="${COMIN}/analysis/snow"
declare -rx COMIN_SNOW_ANLMON="${COMIN}/products/snow/anlmon"
declare -rx COMIN_ICE_ANALYSIS="${COMIN}/analysis/ice"
declare -rx COMIN_ICE_BMATRIX="${COMIN}/bmatrix/ice"
declare -rx COMIN_ICE_HISTORY="${COMIN}/model/ice/history"
declare -rx COMIN_ICE_INPUT="${COMIN}/model/ice/input"
declare -rx COMIN_ICE_RESTART="${COMIN}/model/ice/restart"
declare -rx COMIN_ICE_GRIB="${COMIN}/products/ice/grib2"
declare -rx COMIN_ICE_NETCDF="${COMIN}/products/ice/netcdf"
declare -rx COMIN_OBS="${COMIN}/obs"
declare -rx COMIN_TOP="${COMIN}"
declare -rx COMIN_OCEAN_HISTORY="${COMIN}/model/ocean/history"
declare -rx COMIN_OCEAN_RESTART="${COMIN}/model/ocean/restart"
declare -rx COMIN_OCEAN_GRIB="${COMIN}/products/ocean/grib2"
declare -rx COMIN_OCEAN_NETCDF="${COMIN}/products/ocean/netcdf"
declare -rx COMIN_OCEAN_ANALYSIS="${COMIN}/analysis/ocean"
declare -rx COMIN_OCEAN_BMATRIX="${COMIN}/bmatrix/ocean"
declare -rx COMIN_WAVE_GRID="${COMIN}/products/wave/gridded"
declare -rx COMIN_WAVE_HISTORY="${COMIN}/model/wave/history"
declare -rx COMIN_WAVE_STATION="${COMIN}/products/wave/station"
declare -rx COMIN_WAVE_RESTART="${COMIN}/model/wave/restart"
declare -rx COMIN_ATMOS_OZNMON="${COMIN}/products/atmos/oznmon"
declare -rx COMIN_ATMOS_RADMON="${COMIN}/products/atmos/radmon"
declare -rx COMIN_ATMOS_MINMON="${COMIN}/products/atmos/minmon"
declare -rx COMIN_CONF="${COMIN}/conf"
declare -rx COMOUT_CONF="${COMOUT}/conf"
declare -rx COMOUT_ATMOS_TRACK="${COMOUT}/products/atmos/cyclone/tracks"

mkdir -p "${COMOUT_CONF}"
mkdir -p "${COMOUT_ATMOS_TRACK}"

for grid in "0p25" "0p50" "1p00"; do
    declare -rx "COMIN_ATMOS_GRIB_${grid}"="${COMIN}/products/atmos/grib2/${grid}"
done

###############################################################
# Create an array of output wave grids to process
if [[ "${DO_WAVE}" == "YES" ]]; then
    # Create a variable for output wave grids to process
    if [[ -n "${wavepostGRD}" || -n "${waveinterpGRD}" ]]; then
        for grdID in ${wavepostGRD} ${waveinterpGRD}; do
            process_grdID "${grdID}"
            declare -rx "COMIN_WAVE_GRID_${GRDREGION}_${GRDRES}"="${COMIN}/products/wave/gridded/${grdNAME}"
            grids_arr+=("${GRDREGION}.${GRDRES}")
        done
        export WAVE_OUT_GRIDS="${grids_arr[*]}"
    else
        echo "Both wavepostGRD and waveinterpGRD are empty. No grids to process."
        export WAVE_OUT_GRIDS=""
    fi
fi
###############################################################
# Run archive script
###############################################################

# Do not export shell opts to the bash scripts in the htar/hsi wrappers
export -n SHELLOPTS
unset_strict
${GLOBALARCHIVESH:-${SCRglobal}/exglobal_archive_tars.py}
export err=$?
set_strict
if [[ ${err} -ne 0 ]]; then
    err_exit "failed to archive the COM structure"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
