#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "cleanup" -c "base cleanup"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

"${SCRglobal}/exglobal_cleanup.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

#################################################
# Remove the Temporary working directory DATAROOT
# In XML, DATAROOT is defined as:
# DATAROOT="${STMP}/RUNDIRS/${PSLOT}/${RUN}.${PDY}${cyc}"
# cleanup is only executed after the entire cycle is successfully completed.
# Removing DATAROOT should be possible if that is the case.

rm -rf "${DATAROOT}"
echo "Cleanup ${DATAROOT} completed!"

exit 0
