#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "waveinit" -c "base wave waveinit"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

export MP_PULSE=0

# Set COM Paths
# shellcheck disable=SC2309
if [[ 10#${ENSMEM:--1} -ge 0 ]]; then
    # Turn ensmem into 3-digit format with leading zeros
    memdir=$(printf "mem%03i" $((10#${ENSMEM})))
    declare -rx COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
else
    declare -rx COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}"
fi
declare -rx COMOUT_WAVE_PREP="${COMOUT}/model/wave/prep"

mkdir -p "${COMOUT_WAVE_PREP}"

# Set mpi serial command
export wavempexec=${wavempexec:-"mpirun -n"}
export wave_mpmd=${wave_mpmd:-"cfp"}

# Execute the Script
"${SCRglobal}/exgfs_wave_init.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Failed to generate wave grids for model initialization."
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
