#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "stage_ic" -c "base stage_ic"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# Execute staging
"${SCRglobal}/exglobal_stage_ic.py"
err=$?

###############################################################
# Check for errors and exit if any of the above failed
if [[ "${err}" -ne 0 ]]; then
    echo "Unable to stage ICs to ${ROTDIR}; ABORT!"
    exit "${err}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || (
    echo "${DATAROOT} does not exist. ABORT!"
    exit 1
)
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
