#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "anlstat" -c "base anlstat"

##############################################
# Set variables used in the script
##############################################

##############################################
# Begin JOB SPECIFIC work
##############################################

# Generate COM variables from templates

YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
    COMIN_OBS:COM_OBS_TMPL \
    COMOUT_CONF:COM_CONF_TMPL \
    COMIN_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
    COMOUT_ATMOS_ANALYSIS:COM_ATMOS_ANALYSIS_TMPL \
    COMOUT_ATMOS_ANLMON:COM_ATMOS_ANLMON_TMPL
mkdir -m 755 -p "${COMOUT_ATMOS_ANALYSIS}"
mkdir -m 755 -p "${COMOUT_ATMOS_ANLMON}"
mkdir -m 755 -p "${COMOUT_CONF}"

if [[ "${DO_AERO_ANL:-NO}" == "YES" ]]; then
    YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        COMIN_AERO_ANALYSIS:COM_CHEM_ANALYSIS_TMPL \
        COMOUT_AERO_ANALYSIS:COM_CHEM_ANALYSIS_TMPL \
        COMOUT_AERO_ANLMON:COM_CHEM_ANLMON_TMPL
    mkdir -m 755 -p "${COMOUT_AERO_ANALYSIS}"
    mkdir -m 755 -p "${COMOUT_AERO_ANLMON}"
fi

if [[ "${DO_JEDISNOWDA:-NO}" == "YES" ]]; then
    YMD=${PDY} HH=${cyc} declare_from_tmpl -rx \
        COMIN_SNOW_ANALYSIS:COM_SNOW_ANALYSIS_TMPL \
        COMOUT_SNOW_ANALYSIS:COM_SNOW_ANALYSIS_TMPL \
        COMOUT_SNOW_ANLMON:COM_SNOW_ANLMON_TMPL
    mkdir -m 755 -p "${COMOUT_SNOW_ANALYSIS}"
    mkdir -m 755 -p "${COMOUT_SNOW_ANLMON}"
fi

###############################################################
# Run relevant script

EXSCRIPT=${ANLSTATSPY:-${SCRgfs}/exglobal_analysis_stats.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

exit 0
