#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "prep_emissions" -c "base prep_emissions"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"
# Set strict mode which will exit on error or undefined variable
# and exit on error in a pipeline (e.g. if a command in "cmd | cmd2" fails)
source "${USHglobal}/set_strict.sh"

##############################################
# Set variables used in the script
##############################################
# Setup Python path for pygfs
PYTHONPATH="${HOMEglobal}/ush/python${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONPATH

# TODO: Set local variables used in this script e.g. GDATE may be needed for previous cycle

##############################################
# Begin JOB SPECIFIC work
##############################################
# Construct COM variables
# shellcheck disable=SC2309
if [[ 10#${ENSMEM:--1} -ge 0 ]]; then
    # Turn ensmem into 3-digit format with leading zeros
    memdir=$(printf "mem%03i" $((10#${ENSMEM})))
    declare -rx COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
else
    declare -rx COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}"
fi

declare -rx COMOUT_CHEM_INPUT="${COMOUT}/model/chem/input"
declare -rx COMOUT_CHEM_RESTART="${COMOUT}/model/chem/restart"

mkdir -p "${COMOUT_CHEM_INPUT}"

###############################################################
# Run relevant script
EXSCRIPT=${PREP_EMISSIONS_PY:-${SCRglobal}/exglobal_prep_emissions.py}
${EXSCRIPT} && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "Error executing ${EXSCRIPT}, ABORT!"
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

exit 0
