#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "ocn_post" -c "base ocn_post"
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
source "${USHglobal}/jjob_shell_setup.sh"

# Construct COM variables
# shellcheck disable=SC2309
if [[ "${ENSMEM}" =~ ^[0-9]+$ ]]; then
    memdir=$(printf "mem%03d" $((10#${ENSMEM})))
    export COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
    export COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/${memdir}"
    export DATAjob="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}"
else
    export COMIN="${ROTDIR}/${RUN}.${PDY}/${cyc}"
    export COMOUT="${ROTDIR}/${RUN}.${PDY}/${cyc}"
    export DATAjob="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}"
fi

# LINK data for SFS ocean 6hrly temp5m post processing for mem000
if [[ "${memdir}" == "mem000" ]]; then
    mkdir -p "${DATAROOT}/${RUN}efcs000.${PDY:-}${cyc}/output/MOM6_OUTPUT"
    ${NLN} "${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}/output/MOM6_OUTPUT/"temp_*.nc "${DATAROOT}/${RUN}efcs000.${PDY:-}${cyc}/output/MOM6_OUTPUT"
fi

# Create the directory to hold output for this job
export DATAoutput="${DATAjob}/output"
if [[ ! -d "${DATAoutput}" ]]; then mkdir -p "${DATAoutput}"; fi

# Construct COM variables from templates
declare -rx "COMOUT_OCEAN_NETCDF"="${COMOUT}/products/ocean/netcdf"
if [[ ! -d "${COMOUT_OCEAN_NETCDF}" ]]; then mkdir -p "${COMOUT_OCEAN_NETCDF}"; fi
mkdir -p "${COMOUT_OCEAN_NETCDF}/${grid}"

# Define directory variables to save the source ocean history files temporarily
export OCEAN_HISTORY_OUTPUT="${DATAoutput}/MOM6_OUTPUT/model/history"
export OCEAN_PRODUCT_OUTPUT="${DATAoutput}/MOM6_OUTPUT/PRODUCT"
if [[ ! -d "${OCEAN_HISTORY_OUTPUT}" ]]; then mkdir -p "${OCEAN_HISTORY_OUTPUT}"; fi
if [[ ! -d "${OCEAN_PRODUCT_OUTPUT}" ]]; then mkdir -p "${OCEAN_PRODUCT_OUTPUT}"; fi

# Define current cycle
export current_cycle="${PDY}${cyc}"

# Check if ocean 24hr_avg and 6hr_avg history files are complete for ocn post job
shopt -s nullglob
ocn_24hrly_files=("${OCEAN_PRODUCT_OUTPUT}/netcdf/${grid}/${RUN}.t${cyc}z.1p00.f"*".nc")        # ocean 24hr_avg history files
ocn_6hrly_files=("${DATAoutput}/MOM6_OUTPUT/temp_"*".nc")                                       # ocean (temp) 6hr_avg history files
ocn_24hrly_num=$((FHMAX_GFS / 24))                                                              #expected total number of ocean 24hr_avg files
ocn_6hrly_num=$((FHMAX_GFS / 6))                                                                #expected total number of ocean 6hr_avg files
echo "INFO: Found ${#ocn_24hrly_files[@]} of ocean 24hr_avg history files."
echo "INFO: Found ${#ocn_6hrly_files[@]} of ocean 6hr_avg history files."

if [[ "${#ocn_24hrly_files[@]}" -lt "${ocn_24hrly_num}" ]] || [[ "${#ocn_6hrly_files[@]}" -lt "${ocn_6hrly_num}" ]]; then
    echo "ERROR: File count mismatch detected!"
    echo "Ocean 24hr_avg fistory files: ${#ocn_24hrly_files[@]} Found vs ${ocn_24hrly_num} Expected"
    echo "Ocean 6hr_avg history files:  ${#ocn_6hrly_files[@]} Found vs ${ocn_6hrly_num} Expected"
    echo "FATAL: The ocean history files are incomplete. Ocean post job quits!"
    exit 1
fi

##############################################
# Begin JOB SPECIFIC work
##############################################

# Run exglobal script
"${SCRglobal}/exglobal_ocn_post.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##############################################
# End JOB SPECIFIC work
##############################################

exit 0
