#! /usr/bin/env bash

###########################################################
# Global Minimization Monitor (MinMon) job
###########################################################
source "${HOMEgfs}/ush/jjob_header.sh" -e "vminmon" -c "base vminmon"

#############################################
# Determine PDY and cyc for previous cycle
#############################################
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export gPDY=${GDATE:0:8}
export gcyc=${GDATE:8:2}

#############################################
# TANKverf - WHERE OUTPUT DATA WILL RESIDE
#############################################
declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
declare -rx COMOUT_ATMOS_MINMON="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/atmos/minmon"

declare -rx COMIN_ATMOS_MINMON_PREV="${ROTDIR}/${RUN}.${gPDY}/${gcyc}/products/atmos/minmon"

export gsistat="${COMIN_ATMOS_ANALYSIS}/${RUN}.t${cyc}z.gsistat.txt"
export M_TANKverf=${M_TANKverf:-${COMOUT_ATMOS_MINMON}}
export M_TANKverfM1=${M_TANKverfM1:-${COMIN_ATMOS_MINMON_PREV}}

mkdir -p "${M_TANKverf}"

########################################################
# Execute the script.
"${SCRgfs}/exglobal_atmos_vminmon.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

################################
# Remove the Working Directory
################################
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
