#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "wavepostsbs" -c "base wave wavepostsbs"
source "${USHgfs}/wave_domain_grid.sh"

# Set COM Paths
declare -rx COMIN_WAVE_PREP="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/prep"
declare -rx COMIN_WAVE_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/history"
declare -rx COMOUT_WAVE_GRID="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/gridded"

mkdir -p "${COMOUT_WAVE_GRID}"

if [[ -n "${wavepostGRD}" || -n "${waveinterpGRD}" ]]; then
    for grdID in ${wavepostGRD} ${waveinterpGRD}; do
        process_grdID "${grdID}"
        declare -rx "COMOUT_WAVE_GRID_${GRDREGION}_${GRDRES}"="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/gridded/${grdNAME}"
        out_dir_varname="COMOUT_WAVE_GRID_${GRDREGION}_${GRDRES}"
        out_dir=${!out_dir_varname}
        mkdir -p "${out_dir}"
    done
else
    echo "Both wavepostGRD and waveinterpGRD are empty. No grids to process."
fi

# Execute the Script
"${SCRgfs}/exgfs_wave_post_gridded_sbs.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "ex-script of gridded wave post failed!"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" != "YES" ]]; then
    rm -rf "${DATA}"
fi

exit 0
