#! /usr/bin/env bash

if ((10#${ENSMEM:-0} > 0)); then
    export DATAjob="${DATAROOT}/${RUN}efcs${ENSMEM}.${PDY:-}${cyc}"
    export DATA="${DATAjob}/${jobid}"
    source "${HOMEgfs}/ush/jjob_header.sh" -e "efcs" -c "base fcst efcs"
else
    export DATAjob="${DATAROOT}/${RUN}fcst.${PDY:-}${cyc}"
    export DATA="${DATAjob}/${jobid}"
    source "${HOMEgfs}/ush/jjob_header.sh" -e "fcst" -c "base fcst"
fi

# Create the directory to hold restarts and output from the model in stmp
export DATArestart="${DATAjob}/restart"
if [[ ! -d "${DATArestart}" ]]; then mkdir -p "${DATArestart}"; fi
export DATAoutput="${DATAjob}/output"
if [[ ! -d "${DATAoutput}" ]]; then mkdir -p "${DATAoutput}"; fi

##############################################
# Begin JOB SPECIFIC work
##############################################

# Restart conditions for GFS cycle come from GDAS
# Restart conditions for GCAFS cycle come from GCDAS
rCDUMP="${RUN/gfs/gdas}"
export rCDUMP="${rCDUMP/gcafs/gcdas}"

# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date --utc -d "${PDY} ${cyc} - ${assim_freq} hours" +%Y%m%d%H)
declare -rx GDATE
# shellcheck disable=
declare -rx gPDY="${GDATE:0:8}"
declare -rx gcyc="${GDATE:8:2}"

# Construct COM variables from templates (see config.com)
declare -rx COMIN_ATMOS_INPUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/input"
declare -rx COMOUT_CONF="${ROTDIR}/${RUN}.${PDY}/${cyc}/conf"
declare -rx COMOUT_ATMOS_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/restart"
declare -rx COMIN_ATMOS_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/restart"
declare -rx COMOUT_ATMOS_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/history"
declare -rx COMOUT_ATMOS_MASTER="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/atmos/master"

declare -rx COMIN_ATMOS_RESTART_PREV="${ROTDIR}/${rCDUMP}.${gPDY}/${gcyc}/model/atmos/restart"

# GCAFS/GCDAS uses an offline atmospheric analysis
if [[ "${RUN}" =~ "gcafs" ]] || [[ "${RUN}" =~ "gcdas" ]]; then
    declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${rCDUMP}.${PDY}/${cyc}/analysis/atmos"
else
    # other runs use their own atmospheric analysis
    declare -rx COMIN_ATMOS_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/atmos"
fi

if [[ "${DO_WAVE}" == "YES" ]]; then
    declare -rx COMIN_WAVE_PREP="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/prep"
    declare -rx COMOUT_WAVE_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/restart"
    declare -rx COMOUT_WAVE_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/history"
    declare -rx COMIN_WAVE_RESTART_PREV="${ROTDIR}/${rCDUMP}.${gPDY}/${gcyc}/model/wave/restart"
fi

if [[ "${DO_OCN}" == "YES" ]]; then
    declare -rx COMIN_OCEAN_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/ocean"
    declare -rx COMIN_OCEAN_INPUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/ocean/input"
    declare -rx COMOUT_MED_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/med/restart"
    declare -rx COMOUT_OCEAN_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/ocean/restart"
    declare -rx COMOUT_OCEAN_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/ocean/history"
    declare -rx COMIN_OCEAN_RESTART_PREV="${ROTDIR}/${rCDUMP}.${gPDY}/${gcyc}/model/ocean/restart"
    declare -rx COMIN_MED_RESTART_PREV="${ROTDIR}/${rCDUMP}.${gPDY}/${gcyc}/model/med/restart"
fi

if [[ "${DO_ICE}" == "YES" ]]; then
    declare -rx COMIN_ICE_INPUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/ice/input"
    declare -rx COMIN_ICE_ANALYSIS="${ROTDIR}/${RUN}.${PDY}/${cyc}/analysis/ice"
    declare -rx COMOUT_ICE_RESTART="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/ice/restart"
    declare -rx COMOUT_ICE_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/ice/history"
    declare -rx COMIN_ICE_RESTART_PREV="${ROTDIR}/${rCDUMP}.${gPDY}/${gcyc}/model/ice/restart"
fi

if [[ "${DO_AERO_FCST}" == "YES" ]]; then
    declare -rx COMOUT_CHEM_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/chem/history"
    declare -rx COMIN_TRACER_RESTART="${ROTDIR}/${rCDUMP}.${PDY}/${cyc}/model/atmos/restart"
    declare -rx COMIN_CHEM_INPUT="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/chem/input"
fi

###############################################################
# Run relevant exglobal script
###############################################################
"${FORECASTSH:-${SCRgfs}/exglobal_forecast.sh}" && true # The && true prevents the shell from exiting when set -e
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

# Send DBN alerts for EnKF
# TODO: Should these be in post manager instead?
if [[ "${RUN}" =~ "enkf" ]] && [[ "${SENDDBN:-}" == YES ]]; then
    for ((fhr == FHOUT; fhr <= FHMAX; fhr + FHOUT)); do
        if ((fhr % 3 == 0)); then
            fhr3=$(printf %03i "${fhr}")
            "${DBNROOT}/bin/dbn_alert" MODEL GFS_ENKF "${job}" "${COMOUT_ATMOS_HISTORY}/${RUN}.t${cyc}z.sfc.f${fhr3}.nc"
        fi
    done
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]]; then
    cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
# do not remove DATAjob. It contains DATAoutput
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"

    # Determine if this is the last segment
    commas="${FCST_SEGMENTS//[^,]/}"
    n_segs=${#commas}
    if ((n_segs - 1 == ${FCST_SEGMENT:-0})); then
        # Only delete temporary restarts if it is the last segment
        rm -rf "${DATArestart}"
    fi
fi

exit 0
