#! /usr/bin/env bash
set -x

source "${HOMEglobal}/ush/jjob_header.sh" -e "wavepostpnt" -c "base wave wavepostsbs wavepostpnt"

#{% if false %}
source "${HOMEglobal}/ush/jjob_standard_vars.sh"
#{% else %}
#{% include jjob_var_setup.j2 %}
#{% endif %}

source "${USHglobal}/jjob_shell_setup.sh"

export MP_PULSE=0

# Set COM Paths
declare -rx COMIN_WAVE_PREP="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/prep"
declare -rx COMIN_WAVE_HISTORY="${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/history"
declare -rx COMOUT_WAVE_STATION="${ROTDIR}/${RUN}.${PDY}/${cyc}/products/wave/station"

mkdir -p "${COMOUT_WAVE_STATION}"

export CFP_VERBOSE=1

export FHMAX_WAV_PNT=$((FHMAX_WAV - OFFSET_START_HOUR))
export DOSPC_WAV='YES'   # Spectral post
export DOBLL_WAV='YES'   # Bulletin post
export DOBNDPNT_WAV='NO' #not boundary points

# Execute the Script
"${SCRglobal}/exgfs_wave_post_pnt.sh" && true
export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit "ex-script of JGLOBAL_WAVE_POST_PNT failed!"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
