#! /usr/bin/env bash

source "${HOMEgfs}/ush/jjob_header.sh" -e "waveprep" -c "base wave waveprep"

# Set rtofs PDY
# shellcheck disable=SC2153
export RPDY=${PDY}

export MP_PULSE=0

# CDO required for processing RTOFS currents
export CDO=${CDO_ROOT}/bin/cdo

# Set COM Paths
declare -rx COMIN_OBS=${ROTDIR}/${RUN}.${PDY}/${cyc}/obs
declare -rx COMIN_WAVE_PREP=${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/prep
declare -rx COMOUT_WAVE_PREP=${ROTDIR}/${RUN}.${PDY}/${cyc}/model/wave/prep
declare -rx COMINrtofs=
if [[ ! -d ${COMOUT_WAVE_PREP} ]]; then mkdir -p "${COMOUT_WAVE_PREP}"; fi

# Execute the Script
"${SCRgfs}/exgfs_wave_prep.sh" && true

export err=$?
if [[ ${err} -ne 0 ]]; then
    err_exit
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
