#! /usr/bin/env bash

################################################################################
####  UNIX Script Documentation Block
#                      .                                             .
# Script name:         exglobal_atmos_sfcanl_regrid.sh
# Script description:  Regrids land increments generated by GSI
#
# Author: Clara Draper      Org: NCEP/EMC     Date: 2026-03-26
#
# Abstract: Regrids land increments generated by GSI
#
# $Id$
#
# Attributes:
#   Language: Bash
#
################################################################################

# Dependent Scripts and Executables
REGRIDSH=${REGRIDSH:-"${USHglobal}/regrid_gsiSfcIncr_to_tile.sh"}

if [[ "${DO_GSISOILDA}" == "YES" ]]; then

    # Collect the dates in the window to update surface restarts
    soilinc_fhrs=("${assim_freq}") # increment file at middle of window
    LFHR="${assim_freq}"
    if [[ "${DOIAU:-}" == "YES" ]]; then # Update surface restarts at beginning of window
        half_window=$((assim_freq / 2))
        soilinc_fhrs+=("${half_window}")
        LFHR=-1
    fi

    export COMIN_SOIL_ANALYSIS_MEM="${COMIN_ATMOS_ENKF_ANALYSIS_STAT}"
    export COMOUT_ATMOS_ANALYSIS_MEM="${COMIN_ATMOS_ANALYSIS}"
    export CASE_IN="${CASE_ENS}"
    export CASE_OUT="${CASE}"
    export OCNRES_OUT="${OCNRES}"
    export LFHR

    "${REGRIDSH}"
    export err=$?
    if [[ ${err} -ne 0 ]]; then
        err_exit "Soil increment file was not regridded correctly!"
    fi

fi

################################################################################

exit "${err}"

################################################################################
