# Description
# -----------

#    This YAML-formatted file contains the fixed (e.g., static) files
#    for the Unified Forecast System (UFS) Weather Model (UWM).

# Instructions
# ------------

#    The YAML-formatted file format is as follows.

# file_type:
#    path: /path/to/file_type/fixed_files
#    fail_missing: True
#    link_files: True
#    files:
#       file1_source: file1_destination
#       file2_source: file2_destination
#       file3_source: file3_destination

# The variables are as follows.

# file_type: This key may be any unique string value; the typical
#            usage is to contain files coming from the same path
#            described (below) for the path key.

# path: This key defines the path for the respective files within the
#       corresponding YAML-block (defined beneath the file_type
#       attribute above).

# fail_missing: This key is a boolean value indicating whether to fail
#               if a source file path is missing; if False or not
#               defined (i.e., missing from the YAML-block) a CRITICAL
#               level logger message will be raised; otherwise a
#               ForecastError exception will be raised.

# link_files: This key is a boolean value indicating whether to
#             symbolically link (True) or copy (False or not defined)
#             the source file path to the destination file path.

# files: This key denotes the YAML-block containing the source and
#        destination key and value pairs; the keys(e.g., file1_source,
#        file2_source, file3_source, etc.,) define the source file
#        paths beneath the path attribute for the respective
#        YAML-block; the corresponding values denote the destination
#        file names beneath the working directory (e.g., DATA); both
#        environment variable and POSIX compliant timestamps are
#        supported.

# ----

fix_aer:
     path: !ENV ${FIXgfs}/aer
     fail_missing: True
     link_files: True
     files:
          merra2.aerclim.2003-2014.m01.nc: aeroclim.m01.nc
          merra2.aerclim.2003-2014.m02.nc: aeroclim.m02.nc
          merra2.aerclim.2003-2014.m03.nc: aeroclim.m03.nc
          merra2.aerclim.2003-2014.m04.nc: aeroclim.m04.nc
          merra2.aerclim.2003-2014.m05.nc: aeroclim.m05.nc
          merra2.aerclim.2003-2014.m06.nc: aeroclim.m06.nc
          merra2.aerclim.2003-2014.m07.nc: aeroclim.m07.nc
          merra2.aerclim.2003-2014.m08.nc: aeroclim.m08.nc
          merra2.aerclim.2003-2014.m09.nc: aeroclim.m09.nc
          merra2.aerclim.2003-2014.m10.nc: aeroclim.m10.nc
          merra2.aerclim.2003-2014.m11.nc: aeroclim.m11.nc
          merra2.aerclim.2003-2014.m12.nc: aeroclim.m12.nc
          
# ----

fix_am:
     path: !ENV ${FIXgfs}/am
     fail_missing: True
     link_files: True
     files:
          CCN_ACTIVATE.BIN: CCN_ACTIVATE.BIN
          co2monthlycyc.txt: co2monthlycyc.txt
          freezeH2O.dat: freezeH2O.dat
          global_climaeropac_global.txt: aerosol.dat
          global_h2o_pltc.f77: global_h2oprdlos.f77
          global_sfc_emissivity_idx.txt: sfc_emissivity_idx.txt
          global_solarconstant_noaa_an.txt: solarconstant_noaa_an.txt
          global_volcanic_aerosols_1850-1859.txt: volcanic_aerosols_1850-1859.txt
          global_volcanic_aerosols_1860-1869.txt: volcanic_aerosols_1860-1869.txt
          global_volcanic_aerosols_1870-1879.txt: volcanic_aerosols_1870-1879.txt
          global_volcanic_aerosols_1880-1889.txt: volcanic_aerosols_1880-1889.txt
          global_volcanic_aerosols_1890-1899.txt: volcanic_aerosols_1890-1899.txt
          global_volcanic_aerosols_1900-1909.txt: volcanic_aerosols_1900-1909.txt
          global_volcanic_aerosols_1910-1919.txt: volcanic_aerosols_1910-1919.txt
          global_volcanic_aerosols_1920-1929.txt: volcanic_aerosols_1920-1929.txt
          global_volcanic_aerosols_1930-1939.txt: volcanic_aerosols_1930-1939.txt
          global_volcanic_aerosols_1940-1949.txt: volcanic_aerosols_1940-1949.txt
          global_volcanic_aerosols_1950-1959.txt: volcanic_aerosols_1950-1959.txt
          global_volcanic_aerosols_1960-1969.txt: volcanic_aerosols_1960-1969.txt
          global_volcanic_aerosols_1970-1979.txt: volcanic_aerosols_1970-1979.txt
          global_volcanic_aerosols_1980-1989.txt: volcanic_aerosols_1980-1989.txt
          global_volcanic_aerosols_1990-1999.txt: volcanic_aerosols_1990-1999.txt
          ozprdlos_2015_new_sbuvO3_tclm15_nuchem.f77: global_o3prdlos.f77
          qr_acr_qg.dat: qr_acr_qg.dat

# ----

fix_co2:
     path: !ENV ${FIXgfs}/am/fix_co2_proj
     fail_missing: True
     link_files: True
     files:
          global_co2historicaldata_2009.txt: co2historicaldata_2009.txt
          global_co2historicaldata_2010.txt: co2historicaldata_2010.txt
          global_co2historicaldata_2011.txt: co2historicaldata_2011.txt
          global_co2historicaldata_2012.txt: co2historicaldata_2012.txt
          global_co2historicaldata_2013.txt: co2historicaldata_2013.txt
          global_co2historicaldata_2014.txt: co2historicaldata_2014.txt
          global_co2historicaldata_2015.txt: co2historicaldata_2015.txt
          global_co2historicaldata_2016.txt: co2historicaldata_2016.txt
          global_co2historicaldata_2017.txt: co2historicaldata_2017.txt
          global_co2historicaldata_2018.txt: co2historicaldata_2018.txt
          global_co2historicaldata_2019.txt: co2historicaldata_2019.txt
          global_co2historicaldata_2020.txt: co2historicaldata_2020.txt
          global_co2historicaldata_2021.txt: co2historicaldata_2021.txt
          global_co2historicaldata_2022.txt: co2historicaldata_2022.txt
          global_co2historicaldata_2023.txt: co2historicaldata_2023.txt

# ----

fix_lut:
     path: !ENV ${FIXgfs}/lut
     fail_missing: True
     link_files: True
     files:
          optics_BC.v1_3.dat: optics_BC.dat
          optics_DU.v15_3.dat: optics_DU.dat
          optics_OC.v1_3.dat: optics_OC.dat
          optics_SS.v3_3.dat: optics_SS.dat
          optics_SU.v1_3.dat: optics_SU.dat

# ----
          
fix_orog:
     path: !ENV ${FIXgfs}/orog/${CASE}.mx500_frac
     fail_missing: True
     link_files: True
     files:
          !ENV oro_${CASE}.mx500.tile1.nc: INPUT/oro_data.tile1.nc
          !ENV oro_${CASE}.mx500.tile2.nc: INPUT/oro_data.tile2.nc
          !ENV oro_${CASE}.mx500.tile3.nc: INPUT/oro_data.tile3.nc
          !ENV oro_${CASE}.mx500.tile4.nc: INPUT/oro_data.tile4.nc
          !ENV oro_${CASE}.mx500.tile5.nc: INPUT/oro_data.tile5.nc
          !ENV oro_${CASE}.mx500.tile6.nc: INPUT/oro_data.tile6.nc

# ----

fix_ugwd_:
     path: !ENV ${FIXgfs}/ugwd
     fail_missing: True
     link_files: True
     files:
          !ENV ${CASE}/${CASE}_oro_data_ls.tile1.nc: INPUT/oro_data_ls.tile1.nc
          !ENV ${CASE}/${CASE}_oro_data_ls.tile2.nc: INPUT/oro_data_ls.tile2.nc
          !ENV ${CASE}/${CASE}_oro_data_ls.tile3.nc: INPUT/oro_data_ls.tile3.nc
          !ENV ${CASE}/${CASE}_oro_data_ls.tile4.nc: INPUT/oro_data_ls.tile4.nc
          !ENV ${CASE}/${CASE}_oro_data_ls.tile5.nc: INPUT/oro_data_ls.tile5.nc
          !ENV ${CASE}/${CASE}_oro_data_ls.tile6.nc: INPUT/oro_data_ls.tile6.nc
          !ENV ${CASE}/${CASE}_oro_data_ss.tile1.nc: INPUT/oro_data_ss.tile1.nc
          !ENV ${CASE}/${CASE}_oro_data_ss.tile2.nc: INPUT/oro_data_ss.tile2.nc
          !ENV ${CASE}/${CASE}_oro_data_ss.tile3.nc: INPUT/oro_data_ss.tile3.nc
          !ENV ${CASE}/${CASE}_oro_data_ss.tile4.nc: INPUT/oro_data_ss.tile4.nc
          !ENV ${CASE}/${CASE}_oro_data_ss.tile5.nc: INPUT/oro_data_ss.tile5.nc
          !ENV ${CASE}/${CASE}_oro_data_ss.tile6.nc: INPUT/oro_data_ss.tile6.nc
          ugwp_limb_tau.nc: ugwp_limb_tau.nc
          

