 if (center != 7) ival = -1;
 else if (strcmp(s,"entire atmosphere (considered as a single layer)") == 0) ival=200;
 else if (strcmp(s,"entire ocean (considered as a single layer)") == 0) ival=201;
 else if (strcmp(s,"highest tropospheric freezing level") == 0) ival=204;
 else if (strcmp(s,"grid scale cloud bottom level") == 0) ival=206;
 else if (strcmp(s,"grid scale cloud top level") == 0) ival=207;
 else if (strcmp(s,"boundary layer cloud bottom level") == 0) ival=209;
 else if (strcmp(s,"boundary layer cloud top level") == 0) ival=210;
 else if (strcmp(s,"boundary layer cloud layer") == 0) ival=211;
 else if (strcmp(s,"low cloud bottom level") == 0) ival=212;
 else if (strcmp(s,"low cloud top level") == 0) ival=213;
 else if (strcmp(s,"low cloud layer") == 0) ival=214;
 else if (strcmp(s,"cloud ceiling") == 0) ival=215;
 else if (strcmp(s,"planetary boundary layer") == 0) ival=220;
 else if (strcmp(s,"layer between two hybrid levels") == 0) ival=221;
 else if (strcmp(s,"middle cloud bottom level") == 0) ival=222;
 else if (strcmp(s,"middle cloud top level") == 0) ival=223;
 else if (strcmp(s,"middle cloud layer") == 0) ival=224;
 else if (strcmp(s,"high cloud bottom level") == 0) ival=232;
 else if (strcmp(s,"high cloud top level") == 0) ival=233;
 else if (strcmp(s,"high cloud layer") == 0) ival=234;
 else if (strcmp(s,"ocean isotherm level (1/10 deg C)") == 0) ival=235;
 else if (strcmp(s,"layer between two depths below ocean surface") == 0) ival=236;
 else if (strcmp(s,"bottom of ocean mixed layer") == 0) ival=237;
 else if (strcmp(s,"bottom of ocean isothermal layer") == 0) ival=238;
 else if (strcmp(s,"layer ocean surface and 26C ocean isothermal level") == 0) ival=239;
 else if (strcmp(s,"ocean mixed layer") == 0) ival=240;
 else if (strcmp(s,"ordered sequence of data") == 0) ival=241;
 else if (strcmp(s,"convective cloud bottom level") == 0) ival=242;
 else if (strcmp(s,"convective cloud top level") == 0) ival=243;
 else if (strcmp(s,"convective cloud layer") == 0) ival=244;
 else if (strcmp(s,"lowest level of the wet bulb zero") == 0) ival=245;
 else if (strcmp(s,"maximum equivalent potential temperature level") == 0) ival=246;
 else if (strcmp(s,"equilibrium level") == 0) ival=247;
 else if (strcmp(s,"shallow convective cloud bottom level") == 0) ival=248;
 else if (strcmp(s,"shallow convective cloud top level") == 0) ival=249;
 else if (strcmp(s,"deep convective cloud bottom level") == 0) ival=251;
 else if (strcmp(s,"deep convective cloud top level") == 0) ival=252;
 else if (strcmp(s,"lowest bottom level of supercooled liquid water layer") == 0) ival=253;
 else if (strcmp(s,"highest top level of supercooled liquid water layer") == 0) ival=254;
 else if (strcmp(s,"missing") == 0) ival=255;
 else ival = -1;

