      SUBROUTINE SAVLAB(IPOSI,JPOSJ,TEXTIN,VALUE,NCHAR)
C
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    SAVLAB      SAVE PUTLAB LABELS
C   PRGMMR: KRISHNA KUMAR         ORG: W/NP12   DATE: 1999-08-01
C
C ABSTRACT: TEMPORARILY SAVES THE ARGUMENTS  TO SUBROUTINE DGNTXT
C           IN CORE AS CALLED BY LABELING SUBROUTINES GENTRE,GLABEL,
C           GLOSED, ETC. THE MAXIMUN NUMBER OF SETS OF LABELS IS
C           THREE. THE MAXIMUN NUMBER OF LABELS PER SET IS FIVE
C           HUNDRED.
C
C PROGRAM HISTORY LOG:
C   85-08-05  KEVIN HLYWIAK
C   88-04-19  GLORIA DENT PUT IN DOCUMENTATION BLOCK.
C   96-03-15  LUKE LIN    CONVERT IT TO CFT-77 ONLY FOR AFOS
C 1999-08-01  KRISHNA KUMAR CONVERTED THIS CODE FROM CRAY TO IBM RS/6000.
C
C USAGE:    CALL SAVLAB (IPT,JPT,HEIGHT,TEXTIN,VALUE,NCHAR,LC)
C   INPUT ARGUMENT LIST:
C     XPOSI    - SAME ARGUMENT IN THE CALL TO PUTLAB
C     YPOSJ    - SAME ARGUMENT IN THE CALL TO PUTLAB
C     TEXTIN   - SAME ARGUMENT IN THE CALL TO PUTLAB
C     VALUE    - REAL TRUE VALUE OF LABEL
C     NCHAR    - SAME ARGUMENT IN THE CALL TO PUTLAB
C
C   OUTPUT FILES:
C     FT06F001 - PRINT MESSAGES OF PROGRESS OF EACH ENTRY
C
C REMARKS:
C   TEMPORARILY SAVES ARGUMENTS TO DGNTXT IN CORE AS CALLED BY LABELING
C   ROUTINES LIKE CENTRE, CLABEL, ETC.  
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
C
      COMMON/LABARG/IPOS(500),JPOS(500),TEXT1(500),
     X   VAL(500),NCH(500),NSAVED
      CHARACTER*4 TEXT1,TEXTIN 
      DATA MXLABS/500/
C
      LC = NSAVED + 1
      IF(LC .GT. MXLABS) GOTO 900
C
      IPOS(LC) = IPOSI
      JPOS(LC) = JPOSJ
      TEXT1(LC) = TEXTIN
      VAL(LC) = VALUE
C   SEARCH THROUGH TEXT STRING FOR $ SO I CAN PASS TRUE NCHAR
      NC = NCHAR
      IF(NC .LE. 0) NC = 4
      IF(NC .GT. 4) NC = 4 
   20 NCH(LC) = NC
      NSAVED = LC
      RETURN
C
  900 CONTINUE
      PRINT *,' ***WARNIGN*** LABEL CAPACITY IS 500 '
      RETURN
      END
C
C
