      SUBROUTINE UNPKHD(ID12WD)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    UNPKHD      DUMMY ROUTINE
C   PRGMMR: KRISHNA KUMAR       ORG: W/NP12   DATE: 1999-08-01
C
C ABSTRACT: DUMMY ROUTINE TO SATISIFY UNRESOLVED EXTERNAL.
C
C PROGRAM HISTORY LOG:
C   94-06-16  ORIGINAL AUTHOR HENRICHSEN
C 1999-08-01  KRISHNA KUMAR CONVERTED THIS CODE FROM CRAY TO IBM RS/6000.
C
C USAGE:    CALL UNPKHD(ID12WD)
C   INPUT ARGUMENT LIST:
C     IDREC    - 12-WORD PACKED ID
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
C
      INTEGER*8 ID12WD(6)
      RETURN
      END
