      SUBROUTINE XLABEL(FLDIN,IDIM,JDIM,XINDEF)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    XLABEL      TO SET UNDEFINED ON THE GRID ACCORDINGLY.
C   PRGMMR: KRISHNA KUMAR      ORG: W/NP12    DATE: 1999-08-01
C
C ABSTRACT: TO SET UNDEFINED ON THE GRID ACCORDINGLY FOR GENERATING LABELS.
C
C PROGRAM HISTORY LOG:
C   97-04-22  LUKE LIN    
C   97-07-11  LUKE LIN      MODIFIY FOR GRID TYPE5 AND TRAJECTORY 4-PANEL.
C 1999-08-01  KRISHNA KUMAR CONVERTED THIS CODE FROM CRAY TO IBM
C                           RS/6000.
C
C USAGE:    CALL XLABEL(FLDIN,IDIM,JDIM,XINDEF)
C   INPUT ARGUMENTS:
C     FLDIN    - REAL*4  BIGFLD(IBIG,JBIG)
C     IDIM   - I-DIMENSION OF THE ORIGINAL  SMLFLD.
C     JDIM   - J-DIMENSION OF THE ORIGINAL  SMLFLD.
C
C   OUTPUT ARGUMENT LIST:
C     FLDIN    - REAL*4  BIGFLD(IBIG,JBIG)
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: CFT-77
C   MACHINE:  CRAY
C
C$$$
C
C     *     *     *     *     *     *     *     *     *     *     *
C
      COMMON /MUTCON/ KEYIDX,UA1V,UA2V,UA3V,UM1V,UM2V,UM3V,LINEVU,LINEP,
     X               IGRIDP,T1
C
      COMMON /PCLP/   PCLPFG
      LOGICAL         PCLPFG
C
      COMMON/SEA/ SAN(53,57)
      INTEGER    SAN
      COMMON/TRAJ4/ ZAN(53,57)
      INTEGER    ZAN
C
      REAL       FLDIN(IDIM,JDIM)
      REAL       XINDEF
C
      PRINT *, ' IN SUBROUTINE XLABEL'
      PRINT *, ' IDIM=', IDIM, '  JDIM=',JDIM
C
C     IF (RANGFG.AND.KEYIDX.EQ.46) THEN
      IF (KEYIDX.EQ.46) THEN
         PRINT *, ' IN TDL MOS TSTM/SVR WX - SET UNDEFINED'
         DO I=1, IDIM
            DO J=1, JDIM
               IF( SAN(I,J).EQ.0) FLDIN(I,J) = XINDEF
            ENDDO
         ENDDO
      ELSE IF (IGRIDP.EQ.05 .AND. PCLPFG) THEN
         PRINT *, ' IN TYPE 5 - SET UNDEFINED'
         DO I=1, IDIM
            DO J=1, JDIM
               IF( SAN(I,J).EQ.0) FLDIN(I,J) = XINDEF
            ENDDO
         ENDDO
      ELSE IF (KEYIDX.EQ.51.OR.KEYIDX.EQ.47.OR.KEYIDX.EQ.48) THEN
         PRINT *, ' IN TRAJ4 SECTION'
C
C     DO J=1,57
C     PRINT *,' J=', J
C        WRITE(*,150)(FLDIN(M,J),M=1,53)
C     ENDDO
 150  format( 3(10(1x,f5.1),3x),/, 2(10( 1x,F5.1),3x),3(1x,F5.1),/)
C
         DO I=1, IDIM
            DO J=1, JDIM
               IF( ZAN(I,J).EQ.0) FLDIN(I,J) = XINDEF
            ENDDO
         ENDDO
      ENDIF
C
C     DO J=1,57
C     PRINT *,' J=', J
C        WRITE(*,150)(FLDIN(M,J),M=1,53)
C     ENDDO
      RETURN
      END
