stages:
  - build
  - create_experments
  - run_tests
  
variables:
#  SCHEDULE: "0 0 * * *"
  GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_JOB_ID/$CI_PROJECT_NAME'

build:
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  
  stage: build
  script:
    - export CI_PROJECT_DIR=$GIT_CLONE_PATH
    - export HASH=$(git rev-parse HEAD)            # Get git hash from the clone
    - echo $HASH > .githash                         # Save hash to file
    - ci/scripts/utils/ci_utils_wrapper.sh build_compute 
  parallel:
    matrix:
      - MACHINE: ["orion"]
  tags:
    - ${MACHINE}
  #only:
  #  - schedules
  artifacts:
    paths:
      - .githash                                  # Pass git hash to next stage
    expire_in: 1 hour

setup:
  variables:
    GIT_STRATEGY: fetch
  stage: create_experments
  script:
    - export CI_PROJECT_DIR=$GIT_CLONE_PATH
    - export HASH=$(cat .githash)                   # Retrieve git hash from artifact
    - RUNTESTS_DIR="${CI_BUILD_DIR}/${CI_JOB_ID}/RUNTESTS"
    - mkdir -p ${RUNTESTS_DIR}
    - workflow/generate_workflow.sh -G -t ${HASH} -D ${RUNTESTS_DIR}
  parallel:
    matrix:
      - MACHINE: ["orion"]
  tags:
    - ${MACHINE}
  #only:
  #  - schedules
  dependencies:
    - build

run_tests:
  variables:
    GIT_STRATEGY: fetch
  stage: run_tests
  script:
    - export CI_PROJECT_DIR=$GIT_CLONE_PATH
    - source ${HOMEgfs}/workflow/gw_setup.sh
    - ci/scripts/run-check_ci.sh ${CI_PROJECT_DIR} ${pslot} 'global-workflow' --get_pslot_list
  parallel:
    matrix:
      - MACHINE: ["orion"]
  tags:
    - ${MACHINE}
  #only:
  #  - schedules
  dependencies:
    - setup