services:
  gitlab:
    image: gitlab/gitlab-ce:17.6.4-ce.0
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
          external_url 'http://localhost:8929'
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:22'
    volumes:
      - '/home/tmcguinness/GITLAB/config:/etc/gitlab'
      - '/home/tmcguinness/GITLAB/logs:/var/log/gitlab'
      - '/home/tmcguinness/GITLAB/data:/var/opt/gitlab'
    shm_size: '256m'
    user: "${UID}:${GID}"

