      SUBROUTINE GETSXX(ITAU,MBLVL,ITYPE,FLOLA,IDENT,IEXIT)
C $$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM: GETSXX         GET A LOLA FIELD FROM SPECTRAL COEFFS
C   PRGMMR: KUMAR            ORG: NP/12    DATE: 1999-11-08
C
C ABSTRACT: TO GET A 2.5 DEGREE LONGITUDE/LATITUDE GRIDPOINT DATA
C   FIELD FROM SPECTRAL COEFFICIENTS USING W3FT59.  THIS IS A LIMITED
C   USE ROUTINE TO GET NORTHERN HEMI DATA OUT OF S24/S36 FILE.
C
C PROGRAM HISTORY LOG:
C   82-04-23  SHIMOMURA
C   95-05-05  LILLY  CONVRT SUBROUTINE TO FORTRAN 77
C 1999-11-08  KRISHNA KUMAR CONVERTED FROM CRAY TO IBM SP 6000
C
C
C USAGE:  CALL GETSXX(ITAU, MBLVL, ITYPE, FLOLA, IDENT, IEXIT)
C   INPUT ARGUMENTS:
C     (1)ITAU  ... FORECAST HOUR DESIRED
C                  ITAU=999  IS A SPECIAL SIGNAL TO CLOSE SXX FILE
C     (2)MBLVL ... THE MILLIBAR LEVEL DESIRED
C     (3)ITYPE ... TYPE OF DATA FIELD DESIRED, AS IN O.N.84
C
C   INPUT FILES:
C     S24,S36  -   CONTAINING SPECTRAL COEFFICIENTS FROM SELA'S MODEL
C              -   DSN=NWS.NMC.PROD.SXX.T00Z.OPRNL,DISP=SHR
C              -   ... OR, AT 12Z,
C              -   DSN=NWS.NMC.PROD.SXX.T12Z.OPRNL,DISP=SHR
C
C   OUTPUT ARGUMENTS:
C     (4)FLOLA ... REAL   FLOLA(145,37)
C                  WHICH IS THE ARRAY FOR THE DESIRED FIELD.
C     (5)IDENT ... INTEGER    IDENT(12)
C                  WHICH IS ARRAY FOR IDENTIFIERS FOR FLOLA FIELD
C     (6)IEXIT ... RETURN CODE
C                  IEXIT=0  FOR NORMAL RETURN
C                  IEXIT= NON-ZERO  FOR ERROR RETURN
C
C   SUBPROGRAMS CALLED:
C     LIBRARY:
C       W3LIB  -   W3FT59, W3FK49
C
C   RETURN CONDITIONS:
C     IEXIT=1  DISK READ ERROR FROM W3FK43, CALLED BY W3FT59,
C              -   DATA FIELD ENTRY NOT IN TABLE
C     IEXIT=2  DISK READ ERROR FROM W3FK43, CALLED BY W3FT59,
C              -   RETRIEVED DATA HAD WRONG ID.
C     IEXIT=3  DISK READ ERROR FROM W3FK43, CALLED BY W3FT59,
C              -   DATA FIELD NOT ON DISK.
C     IEXIT=4  ERROR FROM W3FT59,  WRONG GRID TYPE IN 5TH WORD OF ID,
C              -   SHOULD HAVE BEEN HEX 1D  OR HEX 1E.
C     IEXIT=5  ERROR FROM GETSXX,
C              -   ARG(1) ITAU IS TOO BIG. (ITAU WAS .GT. 255)
C
C   REMARKS: WHEN YOU FINISH READING IN ALL FIELDS YOU NEED,
C     YOU SHOULD CLOSE OUT THE SXX FILE BY CALLING THIS SUBROUTINE
C     WITH ITAU=999
C
C ATTRIBUTES:
C   LANGUAGE: F90      
C   MACHINE : IBM SP/6000                                    
C
C$$$
C
C
C     CHARACTER*8  FILNAM
      INTEGER*8  FILNAM
      INTEGER*8  LUGRB
C     CHARACTER*8  FILE24
      INTEGER*8  FILE24
      DATA FILE24         /12/
      INTEGER*8  FILE18
      DATA FILE18         /13/
      INTEGER*8  FILE31
      DATA FILE31         /31/
      INTEGER*8  FILE32
      DATA FILE32         /32/
C     CHARACTER*8  FILE36
      INTEGER*8  FILE30
      DATA FILE30         /30/
      INTEGER*8  FILE33
      DATA FILE33         /33/
      INTEGER*8  FILE36
      DATA FILE36         /36/
      INTEGER*8  FILE34
      DATA FILE34         /34/
      CHARACTER*132    MTITLE
C
      REAL    FLOLA(145,37)
C
      INTEGER    IDENT(12)
      INTEGER    KDENT(12)
C
C     DATA     FILE24/'S24     '/
ckumar      DATA     FILE36/'S36     '/
      DATA KDENT / X'00100818',X'0061A882',0,0,X'0000001D',X'00990A87',
     1            6*0 /
      DATA     KWD1 / X'00000800' /
      DATA     K82 / X'00000082' /
      DATA     MSKTAU / X'000000FF' /
      DATA     MSKLVL / X'000FFFFF' /
C
      IEXIT = 0
      IF(ITAU .GT. 255) GO TO 700
      DO  155  I = 1,12
      IDENT(I) = KDENT(I)
  155  CONTINUE
C     ... PUT TYPE AND TAU INTO IDENT(1)
      IACC = ITYPE
      IACC = ISHFT(IACC,20)
 1059  format('iacc shift ',i5,z20,z20,z20)
      IWORD1 = IOR(IACC,KWD1)
c      print 1059,itype,itype,iacc,iword1
      IACC = ITAU
      IACC = IAND(IACC,MSKTAU)
      IWORD1 = IOR(IWORD1,IACC)
c      print 1059,itau,itau,iacc,iword1
      IDENT(1) = IWORD1
C
C     ... PUT LEVEL INTO IDENT(2)
      IACC = MBLVL
      IF(IACC .LE. 999) IACC = IACC*100
      IACC = IAND(IACC,MSKLVL)
      IWORD2 = ISHFT(IACC,8)
c      print 1069,mblvl,iacc,iacc,iword2
      IWORD2 = IOR(IWORD2,K82)
c      print 1069,mblvl,iacc,iacc,iword2
 1069 format(' ishift lev',i5,i5,z20,z20)
      IDENT(2) = IWORD2
C
Corig PRINT 180
      WRITE(6,180)
  180 FORMAT(' CHECK IDENTS IN GETSXX',/)
      DO 250 I=1,12
      PRINT 200,IDENT(I),i
c      WRITE(6,200) IDENT(I),i
  200 FORMAT(3X,' ident ',Z8,i3)
  250 CONTINUE
C     IF(ITAU.EQ.18.OR.ITAU.EQ.24)FILNAM=FILE24
      IF(ITAU.EQ.18) THEN
            FILNAM = FILE18
            LUGRB  = FILE31
      ELSE
      IF(ITAU.EQ.24) THEN
            FILNAM = FILE24
            LUGRB  = FILE32
      ENDIF
      ENDIF
C     IF(ITAU.EQ.30.OR.ITAU.EQ.36)FILNAM=FILE36
      IF(ITAU.EQ.30) THEN
            FILNAM = FILE30
            LUGRB  = FILE33
      ELSE
      IF(ITAU.EQ.36) THEN
            FILNAM = FILE36
            LUGRB  = FILE34
      ENDIF
      ENDIF
      WRITE(6,169)
  169 FORMAT(1X,'BEFORE THE CALL IW3GET')
C      CALL W3FT59(FILNAM,IDENT,FLOLA,IER)
C     CALL IW3GET(LUGRBIX,LUGRB,LABEL,FLD,MTITLE,IERR)
      WRITE(6,8765)FILNAM,LUGRB
 8765 FORMAT(1X,'NO. 1 FILNAM=',I4,2X,'LUGRB=',1X,I4)
Cwron CALL IW3GET(FILNAM,LUGRB,IDENT,FLOLA,MTITLE,IER)
      CALL IW3GET(LUGRB,FILNAM,IDENT,FLOLA,MTITLE,IER)
      ixudd=145
      iyudd=37
c      do 198 k=1,37
ck 198  print 1019,MTITLE,k,FLOLA(1,k)
 1019  format(' IWGET CHK ',A132,1x,i4,f10.4)
c      call qcn(flola,ixudd, iyudd)
      WRITE(6,1346) IER
 1346 FORMAT(1X,'STEVE IER AFTER IW3GET IS',1X,I4)
      IF(IER .NE. 0) GO TO 911
C     ... ELSE, GOT A FIELD IN FLOLA
C     ...   AND ID INCLUDING DATE IN IDENT
      GO TO 999
  700 CONTINUE
C     ... COMES HERE IF ITAU .GT. 255
      IF(ITAU .NE. 999) GO TO 900
C           CALL W3FK49(FILNAM)
      GO TO 999
  900 CONTINUE
C     ... COMES HERE IF ITAU IS OUT OF BOUNDS
      IEXIT = 5
      GO TO 999
C
  911 CONTINUE
C     ... COMES HERE IF ERROR FROM W3FT59
      IEXIT = IER
      GO TO 999
  999 CONTINUE
C      do 298 k=1,37
c 298  print 1019,MTITLE,k,FLOLA(1,k)
      RETURN
      END
