      SUBROUTINE ABSVWS(FLD,WRK,IMAX,JMAX)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    ABSVWS      PERFORM SPECIAL ABSOLUTE VALUE FOR VWS.
C   PRGMMR: KRISHNA KUMAR         ORG: W/NP12    DATE: 1999-08-01
C
C ABSTRACT: PREPARE ABSOLUTE VALUE FIELD FOR VERTICAL WIND SHIELD.
C
C PROGRAM HISTORY LOG:
C   96-10-04 LUKE LIN  ORIGINAL AUTHOR
C 1999-08-01 KRISHNA KUMAR CONVERTED THIS CODE FROM CRAY TO IBM RS/6000
C
C USAGE:    CALL ABSVWS(FLD,WRK,IMAX,JMAX)
C   INPUT ARGUMENT LIST:
C     FLD      _ THE ABSVWSITATION FIELD FOR CLIFFING AND SMOOTHING
C     WRK      _ THE WORKING FIELD FOR SMOOTHING USING W3FM08
C     IMAX,JMAX_ THE DIMENSIONS OF FLD AND WRKNG USING W3FM08
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     FLD     _ THE  ABSOLUTE VWS  FIELD
C
C ATTRIBUTES:
C   LANGUAGE: F90
C   MACHINE:  IBM
C
C$$$
C
      DIMENSION FLD(IMAX,JMAX)
      DIMENSION WRK(IMAX,JMAX)
C
C
      DO 50 J=1,JMAX
      DO 50 I=1,IMAX
         FLD(I,J)= ABS(FLD(I,J))
   50 CONTINUE
C
      END
