      SUBROUTINE PRECIP(FLD,WRK,IMAX,JMAX)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PRECIP      PERFORM SPECIAL PRECIP COMPUTATIONS
C   PRGMMR: KRISHNA KUMAR      ORG: W/NP12    DATE: 1999-08-01
C
C ABSTRACT: PREPARE PRECIPITATION FIELDS FOR CONTOURING BY PERFORMING
C    SPECIAL TESTS FOR  INTRODUCING A CLIFF PRIOR  TO SMOOTHING.
C
C PROGRAM HISTORY LOG:
C   89-09-07 ORIGINAL AUTHOR GLORIA DENT
C   94-12-30 LUKE LIN      CONVERT IT TO CFT-77
C   96-06-18 LUKE LIN      CHANGE CONSTANTS FOR CRAY.
C 1999-08-01 KRISHNA KUMAR CONVERTED THIS CODE FROM CRAY TO IBM  
C                          RS/6000.
C
C USAGE:    CALL PRECIP(FLD,WRK,IMAX,JMAX)
C   INPUT ARGUMENT LIST:
C     FLD      _ THE PRECIPITATION FIELD FOR CLIFFING AND SMOOTHING
C     WRK      _ THE WORKING FIELD FOR SMOOTHING USING W3FM08
C     IMAX,JMAX_ THE DIMENSIONS OF FLD AND WRKNG USING W3FM08
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     FLD     _ THE SMOOTHED PRECIPITATION FIELD
C
C ATTRIBUTES:
C   LANGUAGE: f90
C   MACHINE:  IBM
C
C$$$
C
      DIMENSION FLD(IMAX,JMAX)
      DIMENSION WRK(IMAX,JMAX)
      REAL      CP001
      REAL      CMP03
C
C   CONSTANTS FOR PRE-SMOOTHING PRECIP FIELD
C???  DATA CP001/0.0000254/
C???  DATA CMP03/-0.000762/
      DATA CP001/0.0254/
      DATA CMP03/-0.762/
C  WHERE 0.0000254M = 0.001IN. WHERE -0.000762M = -0.03IN.
C
C   PREPARE THE PRECIP FIELD FOR SMOOTHING BY FIRST INTRODUCING A CLIFF
C   CHANGE INPUT PRECIP FIELD'S LOWER LIMIT AND SAVE UNFILTERED PRECIP
C
      DO 50 J=1,JMAX
      DO 50 I=1,IMAX
C   CHANGE INPUT PRECIP FIELD'S LOWER LIMIT AND SAVE UNFILTERED PRECIP
C        write(6,20)(fld(m,j),m=1,64)
C  20    format(8(8(1x,f8.4),/))
         IF(FLD(I,J) .LE. CP001) FLD(I,J) = CMP03
   50 CONTINUE
C
C   FILTER PRECIPITATION FIELD...
C     CALL W3FM08(FLD,WRK,IMAX,JMAX)
      END
