      SUBROUTINE SLTCRD(ISWTCH,ISLOTA,ISLOTB,IPANA,IPANB,IRLAB,IREM3A,
     1   IREM3B,IREM3C,IREM4A,IREM4B,IAREA3,ISUB,IFLAB,INSET,IREM1A,
     1   IREM1B)
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    SLTCRD      INPUT FIELD READER
C   PRGMMR: KUMAR            ORG: W/NP12   DATE: 1999-12-21
C
C ABSTRACT: READS IN THE MAP SLOT CARDS AND CHECKS THEM FOR
C   ACCEPTABLE ENTRIES.
C
C PROGRAM HISTORY LOG:
C   ??-??-??  UNKNOWN
C   91-02-21  STEVE LILLY, MODIFIED ROUTINE AND ADDED DOC BLOCK.
C   95-05-05  LILLY  CONVRT SUBROUTINE TO FORTRAN 77.
C 1999-12-21  KUMAR CONVERTED THIS CODE FORM CRAY TO IBM RS/6000 SP
C
C USAGE:    CALL SLTCRD(ISWTCH,ISLOTA,ISLOTB,IPANA,IPANB,IRLAB,IREM3A,
C                       IREM3B,IREM3C,IREM4A,IREM4B,IAREA3,ISUB,IFLAB,
C                       INSET,IREM1A,IREM1B)
C   INPUT ARGUMENT LIST:
C     ISWTCH   - GENERIC DESCRIPTION, INCLUDING CONTENT, UNITS,
C     ISLOTA   - FIRST 4 CHARACTERS OF FAX/VARIAN SLOT NUMBER.
C     ISLOTB   - THE 5TH CHARACTER OF FAX/VARIAN SLOT NUMBER.
C     IPANA    - FIRST 4 CHARACTERS OF PANEL PART OR REAL INSET PART.
C     IPANB    - THE 5TH CHARACTER OF PANEL PART OR REAL INSET PART.
C     IRLAB    - REAR LABEL INSET NUMBER.
C     IREM3A   - FIRST 4 CHARACTERS OF PANEL 1 OR PANEL 3 OR
C              - SUBSET TITLE.
C     IREM3B   - 5 - 8 CHARACTERS OF PANEL 1 OR PANEL 3 OR
C              - SUBSET TITLE.
C     IREM3C   - 9 - 10 CHARACTERS OF PANEL 1 OR PANEL 3 OR
C              - SUBSET TITLE.
C     IREM4A   -
C     IREM4B   -
C     IAREA3   -
C     ISUB     - SUBSET NUMBER.
C     IFLAB    - FRONT LABEL INSET NUMBER.
C     INSET    - INSET NUMBER.
C     IREM1A   - FIRST 4 CHARACTERS OF PANEL 2 OR PANEL 4 TITLE.
C     IREM1B   - 5 - 8 CHARACTERS OF PANEL 2 OR PANEL 4 TITLE.
C
C   OUTPUT ARGUMENT LIST:      (INCLUDING WORK ARRAYS)
C     WRKARG   - GENERIC DESCRIPTION, ETC., AS ABOVE.
C     OUTARG1  - EXPLAIN COMPLETELY IF ERROR RETURN
C     ERRFLAG  - EVEN IF MANY LINES ARE NEEDED
C
C   INPUT FILES:   (DELETE IF NO INPUT FILES IN SUBPROGRAM)
C     DDNAME1  - GENERIC NAME & CONTENT
C
C   OUTPUT FILES:  (DELETE IF NO OUTPUT FILES IN SUBPROGRAM)
C     DDNAME2  - GENERIC NAME & CONTENT AS ABOVE
C     FT06F001 - INCLUDE IF ANY PRINTOUT
C
C REMARKS: LIST CAVEATS, OTHER HELPFUL HINTS OR INFORMATION
C
C ATTRIBUTES:
C   LANGUAGE: F90      
C   MACHINE:  IBM
C
C$$$
C
C     ...THIS SUBROUTINE READS IN THE MAP SLOT CARDS AND CHECKS THEM
C     ...FOR ACCEPTABLE ENTRIES
C
      INTEGER   IPANC(3,11)
C  INCLUDE THE ATLANTIC AND PACIFIC FAX CUTS
      INTEGER   IAREA(3,9)
C
      DATA    IAREA/4HXX14,1H ,1,4HVFUL,1HL,2,4HXX15,1H ,3,4HPN28,1H ,4,
     1              4HNT22,1H ,5,4HNT23,1H ,6,4HPN29,1H ,7,4HATLN,1H ,8,
     2              4HPACF,1H ,9/
      DATA    IPANC/4HP1  ,1H ,1,4HP2  ,1H ,2,4HP3  ,1H ,3,4HP4  ,1H ,4,
     1     4HP1A ,1H ,5,4HP2A ,1H ,6,4HP3A ,1H ,7,4HP4A ,1H ,8,4HI1  ,
     2     1H ,9,4HI2  ,1H ,10,4HB2  ,1H ,11/
      DATA    NPARTS/11/
      DATA    IBCHK/4H    /
Corig DATA    JU/8/
      DATA    JU/18/
C   THIS IS TO ADD THE ATLANTIC AND THE PACIFIC
      DATA   NAREAS /9/
C  MAKE THIS CHANGE FOR CHECK OUT
C CHECKOUT    .... DATA    IR1/200/
C OPERATIONAL .... DATA    IR1/130/
      DATA    IR1/50/
c      DATA    IR1/130/
      DATA    IR2/5000/
      DATA    IR3/80/
      DATA    IR4/99/
C
C     ...BASIC FAX/VARIAN CONTROLS (EACH MAP SUB-SECTION)
C
C   ICARD2 (A1)=             CARD2 CONTROL
C   ISLOTA,B (A4,A1)=        FAX/VARIAN SLOT NO.
C   IPANA,B (A4,A1)=         PANEL PART OR REAL INSET PART
C   IAREA1,2 (A4,A1)=        FAX/VARIAN OUTPUT PIECE
C   ISUB (I5)=               SUBSET NO.
C   IFLAB (I5)=              FRONT LABEL INSET NO.
C   INSET (I5)=              INSET NO.
C   IRLAB (I5)=              REAR LABEL INSET NO.
C   IREM1A,B,C (A4,A4,A2)=   PANEL 2 OR PANEL4 TITLE
C   IREM3A,B,C (A4,A4,A2)=   PANEL 1 OR PANEL3 OR SUBSET TITLE
C
 8200 FORMAT(A1,3(A4,A1),4I5,2A4,A2,4A4,A2,4A4)
      IF(ISWTCH.EQ.1) GO TO 8002
      READ (JU,8200) ICARD2,ISLOTA,ISLOTB,IPANA,IPANB,IAREA1,IAREA2,ISUB
     1   IFLAB,INSET,IRLAB,IREM1A,IREM1B,IREM1C,IREM2A,IREM2B,
     2   IREM3A,IREM3B,IREM3C,IREM4A,IREM4B,IMANOP,IMANOQ
C8200 FORMAT(A1,3(A4,A1),4I5,2A4,A2,4A4,A2,4A4)
      GO TO 8003
 8002 READ (JU,8200) ICARD2,ISLOTA,ISLOTB,IPANA,IPANB,IAREA1,IAREA2,ISUB
     1  ,IFLAB,INSET,IRLAB,IREM1A,IREM1B,IREM1C,IREM2A,IREM2B,
     2   IREM3A,IREM3B,IREM3C,IREM4A,IREM4B,IMANOP,IMANOQ
 8003 CONTINUE
Corig PRINT 8202, ISLOTA,ISLOTB,IPANA,IPANB,IAREA1,IAREA2,ISUB,IFLAB,
      WRITE(6,8202) ISLOTA,ISLOTB,IPANA,IPANB,IAREA1,IAREA2,ISUB,IFLAB,
     1   INSET
 8202 FORMAT('0SLOT NO.=  ',A4,A1,'  PANEL/INSET=  ',A4,A1,
     2   'AREA=  ',A4,A1,'  SUBSET NO.=',I5,'  FRONT LABEL INSET NO.=',
     2   I5,'  INSET NO.=',I5)
C
C     ...CHECK FOR REASONABLE PANEL PARTS/INSET PARTS
C
      DO 8215 IK=1,NPARTS
      IF((IPANA.EQ.IBCHK).AND.(IPANB.EQ.IBCHK)) GO TO 8220
      IF((IPANA.NE.IPANC(1,IK)).OR.(IPANB.NE.IPANC(2,IK))) GO TO 8215
      IPAN1=IPANC(3,IK)
      GO TO 8220
 8215 CONTINUE
Corig PRINT 8216
      WRITE(6,8216)
 8216 FORMAT('0ERROR ON FAX/VARIAN CONTROL INPUT CARD FOR IPAN-FIX THEN
     1RETRY')
       CALL W3TAGE('AVPOLARV')
      STOP 216
 8220 CONTINUE
C
C     ...CHECK FOR REASONABLE AREA REQUESTS
C
      DO 8235 IK=1,NAREAS
      IF((IAREA1.EQ.IBCHK).AND.(IAREA2.EQ.IBCHK)) GO TO 8225
      IF((IAREA1.NE.IAREA(1,IK)).OR.(IAREA2.NE.IAREA(2,IK))) GO TO 8235
      IAREA3=IAREA(3,IK)
      GO TO 8240
C8225 PRINT 8226
 8225 CONTINUE
      WRITE(6,8226)
 8226 FORMAT('0IAREA1,2 WAS BLANK-WILL CONTINUE')
      GO TO 8240
 8235 CONTINUE
Corig PRINT 8236
      WRITE(6,8236)
 8236 FORMAT('0ERROR ON FAX/VARIAN CONTROL INPUT CARD FOR IAREA1,2-FIX
     1THEN RETRY')
       CALL W3TAGE('AVPOLARV')
      STOP 236
 8240 CONTINUE
C
C     ...CHECK FOR REASONABLE SUBSET/INSET NUMBERS
C
      IF(ISUB.LT.0) GO TO 8243
      IF(((ISUB.GE.IR1).AND.(ISUB.LE.IR2)).OR.((ISUB.GE.IR3).AND.(ISUB.L
     1E.IR4))) GO TO 8301
Corig PRINT 8241, ISUB
      WRITE(6,8241) ISUB
 8241 FORMAT('0ERROR ON FAX/VARIAN CONTROL INPUT CARD FOR ISUB-FIX THEN
     1RETRY  ',I4)
       CALL W3TAGE('AVPOLARV')
      STOP 241
 8243 CONTINUE
Corig PRINT 8244
      WRITE(6,8244)
 8244 FORMAT('0SUBSET NUMBER IS BLANK-WILL CONTINUE')
 8301 CONTINUE
      IF(IFLAB.LE.0) GO TO 8253
      IF(((IFLAB.GE.IR1).AND.(IFLAB.LE.IR2)).OR.((IFLAB.GE.IR3).AND.(IFL
     1AB.LE.IR4))) GO TO 8302
Corig PRINT 8251
      WRITE(6,8251)
 8251 FORMAT('0ERROR ON FAX/VARIAN CONTROL INPUT CARD FOR IFLAB-FIX THEN
     1 RETRY')
       CALL W3TAGE('AVPOLARV')
      STOP 251
 8253 CONTINUE
 8302 CONTINUE
      IF(INSET.LE.0) GO TO 8263
      IF(((INSET.GE.IR1).AND.(INSET.LE.IR2)).OR.((INSET.GE.IR3).AND.(INS
     1ET.LE.IR4))) GO TO 8303
Corig PRINT 8261
      WRITE(6,8261)
 8261 FORMAT('0ERROR ON FAX/VARIAN CONTROL INPUT CARD FOR INSET-FIX THEN
     1 RETRY')
       CALL W3TAGE('AVPOLARV')
      STOP 261
 8263 CONTINUE
 8303 CONTINUE
      RETURN
      END
