C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    PAKWND       PACKS U,V COMPONENTS TOGETHER
C   PRGMMR: BOSTELMAN        ORG: W/NMC42    DATE: 92-03-09
C
C ABSTRACT: PACKS U AN V WIND COMPONENTS USING CODE 3856 SIGN
C           CONVENTIONS.  (ISUBS IN 333 BULLETIN HEADING MUST = 1.
C           SEE CODE 1851.)
C
C PROGRAM HISTORY LOG:
C   81-12-20  R. ALLARD ORGINATOR
C   92-03-09  W. BOSTELMAN - UPGRADED DOCBLOCK
C
C USAGE:    CALL PAKWND (U,V,K,N)
C   INPUT ARGUMENT LIST:
C     U - U WIND COMPONENT ARRAY (REAL*4)
C     V - V WIND COMPONENT ARRAY (REAL*4)
C     N - DIMENSION OF U, V, AND K ARRAYS
C
C   OUTPUT ARGUMENT LIST:
C     K - COMBINED SIGN AND U, V COMPONENT ARRAY (INTEGER*4)
C
C   INPUT FILES:
C     NONE
C
C   OUTPUT FILES:
C     NONE
C
C REMARKS:
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  NAS
C
C$$$
C
      SUBROUTINE PAKWND(U,V,K,N)
C
      DIMENSION U(N), V(N), K(N)
C
      DO 3000 J=1,N
      IF(U(J).LT.0.0) GO TO 1000
      ISIGN=0
      IF(V(J).LT.0.0) ISIGN=20000
      GO TO 2000
 1000 CONTINUE
      ISIGN=10000
      IF(V(J).LT.0.0) ISIGN=30000
 2000 CONTINUE
      IU=ABS(U(J))+0.5
      IV=ABS(V(J))+0.5
      K(J)=IU*100+IV+ISIGN
 3000 CONTINUE
C
      RETURN
C
      END
