#
name: bash_code_anl
on:
  push:
    branches:
      - develop
  pull_request:

  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash -o pipefail {0}

jobs:

  shfmt:
    runs-on: ubuntu-22.04

    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # to get PR metadata
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: shfmt scan
        uses: reviewdog/action-shfmt@v1

  shellcheck:
    runs-on: ubuntu-22.04

    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # to get PR metadata
      security-events: write

    steps:    
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: false
      
      - if: ${{ success() }}
        name: Shellcheck Scan
        uses: reactive-firewall/shellcheck-scan@v1
        with:  # optional arguments
          # match: '**/*.{sh,bash}'
          match: 'jobs/* dev/jobs/*.sh dev/ush/*.sh scripts/*.sh ush/*.sh'
          shell-format: 'bash'
          severity: 'warning'
          publish-artifacts: false
        if: ${{ success() }}

      # # Keep old diff shellcheck for now until whole workflow is compliant
      # - id: ShellCheck
      #   name: Shellcheck changes
      #   uses: redhat-plumbers-in-action/differential-shellcheck@v4
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - if: ${{ always() }}
      #   name: Upload artifact with ShellCheck defects in SARIF format
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Differential ShellCheck SARIF
      #     path: ${{ steps.ShellCheck.outputs.sarif }}
