name: bash_code_analysis
on:
  push:
    branches:
      - develop
  pull_request:

  workflow_dispatch:

permissions:
  contents: read

jobs:

  shfmt:
    runs-on: ubuntu-22.04

    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # to get PR metadata
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: shfmt scan
        uses: reviewdog/action-shfmt@v1
        with:
          filter_mode: nofilter
          level: warning
          reporter: github-pr-review

  shellcheck:
    runs-on: ubuntu-22.04

    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # to get PR metadata
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: false
      
      - name: Shellcheck Scan
        uses: reviewdog/action-shellcheck@v1
        with:
          filter_mode: nofilter
          level: warning
          reporter: github-pr-review
          pattern: |
            config.*
            JG*
            *.env
            *.sh
            *.bash
          exclude: |
            */.git/*
            */*.yml
            */*.yaml
          check_all_files_with_shebangs: true
