name: CI Unit Tests
on:
    pull_request:

jobs:

  ci_pytest:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl libxml-libxml-perl libxml-libxslt-perl libdatetime-perl
          python -m pip install --upgrade pip
          pip install pytest wxflow
          # If you have a requirements.txt file, you can install all dependencies using:
          # pip install -r requirements.txt

      - name: Install Rocoto
        run: |
          git clone https://github.com/christopherwharrop/rocoto.git
          cd rocoto
          ./INSTALL
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Run tests
        run: python -m pytest ci/scripts/tests/test_rocotostat.py --junitxml ci/scripts/tests/test-results.xml 

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ci/scripts/tests/test-results.xml

  publish-test-results:
    name: "Publish Tests Results"
    needs: ci_pytest
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    if: always()
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ci/scripts/tests
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ci/scripts/tests/test-results.xml
          job_summary: true
          comment_mode: off
  