name: CI Unit Tests
on:
    pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:

  ci_pytest:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl libxml-libxml-perl libxml-libxslt-perl libdatetime-perl
          python -m pip install --upgrade pip
          pip install pytest wxflow
          # If you have a requirements.txt file, you can install all dependencies using:
          # pip install -r requirements.txt

      - name: Install Rocoto
        run: |
          git clone https://github.com/christopherwharrop/rocoto.git
          cd rocoto
          ./INSTALL
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Run tests
        run: pytest -v --junitxml test-results.xml ci/scripts/tests/test_rocotostat.py

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: "test-results.xml"

      - name: Conclusion
        run: echo "Conclusion is ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}"