name: CI Unit Tests
on:
    pull_request:

permissions:
    contents: read

jobs:

  ci_pytest:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl libxml-libxml-perl libxml-libxslt-perl libdatetime-perl
          python -m pip install --upgrade pip
          pip install pytest wxflow
          # If you have a requirements.txt file, you can install all dependencies using:
          # pip install -r requirements.txt

      - name: Install Rocoto
        run: |
          git clone https://github.com/christopherwharrop/rocoto.git
          cd rocoto
          ./INSTALL
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Run tests
        run: pytest -v --junitxml test-results.xml ci/scripts/tests/test_rocotostat.py

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results