name: CI Unit Tests
on: [pull_request, push, workflow_dispatch]

env:
  ROCOTO_VERSION: "1.3.7"

jobs:

  ci_pytest:
      runs-on: ubuntu-22.04
      name: Run unit tests on CI system
      permissions:
        checks: write

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl libxml-libxml-perl libxml-libxslt-perl libdatetime-perl
          python -m pip install --upgrade pip
          python -m pip install -r ${GITHUB_WORKSPACE}/dev/workflow/requirements.txt
          pip install pytest
          pip install wget

      - name: Cache Rocoto
        id: cache-rocoto
        uses: actions/cache@v4
        with:
          path: ${HOME}/rocoto
          key: ${{ runner.os }}-rocoto-${{ env.ROCOTO_VERSION }}

      - name: Install Rocoto
        id: install-rocoto
        if: steps.cache-rocoto.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git clone https://github.com/christopherwharrop/rocoto.git ${HOME}/rocoto
          cd ${HOME}/rocoto
          git checkout ${{ env.ROCOTO_VERSION }}
          ./INSTALL
          echo "${HOME}/rocoto/bin" >> ${GITHUB_PATH}

      - name: Run tests
        shell: bash
        run: |
          sudo mkdir -p /scratch1/NCEPDEV
          sudo mkdir -p /scratch1/NCEPDEV/stmp2
          sudo mkdir -p /scratch1/NCEPDEV/stmp4
          sudo mkdir -p /scratch1/NCEPDEV/global
          sudo chmod -R a+w /scratch1/NCEPDEV
          cd ${GITHUB_WORKSPACE}/sorc
          git submodule update --init -j 9 wxflow ufs_model.fd
          ./link_workflow.sh
          cd ${GITHUB_WORKSPACE}/dev/ci/scripts/tests

          pytest -v --junitxml ${GITHUB_WORKSPACE}/dev/ci/scripts/tests/test-results.xml


      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: dev/ci/scripts/tests/test-results.xml
          job_summary: true
          comment_mode: off
