name: gw-ci-orion
# A GitHub Action that creates a deployment for a PR, clones, builds and runs a test suite
# This workflow is triggered by a label being added to a PR
# The label name determines the environment to deploy to
# The label name must be one of the following:
#   - CI-Orion-Ready
#   - CI-Orion-Build
#   - CI-Orion-Run

on:
  pull_request:
    types:
      - labeled

jobs:
  clone-build:
    if:  github.event.label.name == 'CI-Orion-Build'
    runs-on: [self-hosted, orion-ready]
    timeout-minutes: 600
    
    steps:

    - name: Setup
      run: |
        mkdir {{ github.event.pull_request.number }}

    - name: Clone
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.pull_request.number }}

    - name: Checkout
      run: |
        cd ${{ github.event.pull_request.number }}/sorc
        ./checkout.sh  # Options e.g. -g -u can be added later

    - name: Build
      run: |
        cd ${{ github.event.pull_request.number }}/sorc
        ./build_all.sh

    - name: Link
      run: |
        cd ${{ github.event.pull_request.number }}/sorc
        ./link_workflow.sh
