name: gw-ci-orion
# A GitHub Action that creates a deployment for a PR, clones, builds and runs a test suite
# This workflow is triggered by a label being added to a PR name Orion-Ready

on:
  pull_request:
    types:
      - labeled

env:
  HOMEGFS: ${{ github.workspace }}/${{ github.event.pull_request.number }}
  HOMEgfs_PR: ${{ github.workspace }}/${{ github.event.pull_request.number }}
  RUNTESTS: ${{ github.workspace }}/${{ github.event.pull_request.number }}/RUNTESTS
  MACHINE_ID: orion

jobs:
  checkout-build-link:
    if:  github.event.label.name == 'CI-Orion-Ready'
    runs-on: [self-hosted, orion-ready]
    timeout-minutes: 600

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.pull_request.number }}

    - name: Checkout components
      env:
        HOMEgfs: ${{ env.HOMEGFS }}
      run: |
        cd ${{ env.HOMEgfs }}/sorc
        ./checkout.sh  # Options e.g. -g -u can be added late
      
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "CI-Orion-Ready"

    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "CI-Orion-Building"

    - if: ${{ failure() }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "CI-Orion-Failed"
    
    - name: Build components
      env:
        HOMEgfs: ${{ env.HOMEGFS }}
      run: |
        cd ${HOMEgfs}/sorc
        ./build_all.sh
        
    - name: Link artifacts
      env:
        HOMEgfs: ${{ env.HOMEGFS }}
      run: |
        cd ${HOMEgfs}/sorc
        ./link_workflow.sh

    - if: ${{ failure() }}
      uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "CI-Orion-Building"
        
    - if: ${{ failure() }}
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "CI-Orion-Failed"

    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "CI-Orion-Building"
       
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "CI-Orion-Running"

  create-experiments:
    
    needs: checkout-build-link
    runs-on: [self-hosted, orion-ready]
    strategy:
      matrix:
       pslot: ["C48_S2S","C96_atm3DVar"]

    steps:
      - name: Create Experiments ${{ matrix.pslot }}
        env:
          pslot: ${{ matrix.pslot }}_${{ github.event.pull_request.head.sha }}
        run: |
         cd ${{ env.HOMEGFS }}
         source workflow/gw_setup.sh
         source ci/platforms/orion.sh
         ./ci/scripts/create_experiment.py --yaml ci/cases/${{ matrix.pslot }}.yaml --dir ${{ env.HOMEGFS }}
         if [ $? -ne 0 ]; then
           echo "Create experiment failed"
           exit 1
         fi
        
      - if: ${{ failure() }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
         labels: "CI-Orion-Running"
      - if: ${{ failure() }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
         labels: "CI-Orion-Failed"
   
  run-experiments:
    needs: create-experiments
    runs-on: [self-hosted, orion-ready]
    strategy:
      matrix:
       pslot: ["C48_S2S","C96_atm3DVar"]    
    steps:
      - name: Run Experiment ${{ matrix.pslot }}    
        env:
         HOMEgfs: ${{ env.HOMEGFS }}
         pslot: ${{ matrix.pslot }}_${{ github.event.pull_request.head.sha }}
         EXPDIR: ${{ env.RUNTESTS }}/${{ matrix.pslot }}/EXPDIR
         pr: ${{ github.event.pull_request.number }}
        run: |
         cd $HOMEgfs
         source ci/platforms/orion.sh
         ./ci/scripts/run-check_ci.sh

      - if: ${{ failure() }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "CI-Orion-Running"
      - if: ${{ failure() }}    
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "CI-Orion-Failed"
      - if: ${{ failure() }}    
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.github_token }}
          body: |
           ${{ env.HOMEgfs}}/global-workflow.log

  release-lock:
    needs: run-experiments
    runs-on: [self-hosted, orion-ready]
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "CI-Orion-Running"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "CI-Orion-Passed"
