name: gw-ci-orion
# A GitHub Action that creates a deployment for a PR, clones, builds and runs a test suite
# This workflow is triggered by a label being added to a PR
# The label name determines the environment to deploy to
# The label name must be one of the following:
#   - CI-Orion-Ready
#   - CI-Orion-Build
#   - CI-Orion-Run

on:
  pull_request:
    types:
      - labeled

jobs:
  clone-build:
    if:  github.event.label.name == 'CI-Orion-Ready'
    runs-on: [self-hosted, orion-ready]
    timeout-minutes: 600
    
    steps:

    - name: Clone
      uses: actions/checkout@v3
      with:
        path: ${{ github.event.pull_request.number }}

    - name: Checkout
      env:
        HOMEgfs: ${{ github.workspace }}/${{ github.event.pull_request.number }}
        REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      run: |
        cd ${HOMEgfs}
        {
          echo "Automated global-workflow Testing Results:"
          echo '```'
          echo "Machine: Orion"
          echo "Start: $(date) on $(hostname)" || true
          echo "---------------------------------------------------"
        }  >> global-workflow.log
        cd $HOMEgfs/sorc
        ./checkout.sh  # Options e.g. -g -u can be added late
        
    - name: Build
      env:
        HOMEgfs: ${{ github.workspace }}/${{ github.event.pull_request.number }}
        REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        MACHINE_ID: orion
        pr: ${{ github.event.pull_request.number }}
      run: |
        gh pr edit --repo ${REPO_URL} ${pr} --remove-label "CI-${MACHINE_ID^}-Ready" --add-label "CI-${MACHINE_ID^}-Building"

        cd ${HOMEgfs}/sorc
        ./build_all.sh

    - name: Link
      env:
        HOMEgfs: ${{ github.workspace }}/${{ github.event.pull_request.number }}
        REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        MACHINE_ID: orion
        pr: ${{ github.event.pull_request.number }}
      run: |
        cd ${{ github.event.pull_request.number }}/sorc
        ./link_workflow.sh

        if [ $? -ne 0 ]; then
          {
            echo "Build:                         *FAILED*"
            echo "Build: Failed at $(date)" || true
            echo "Build: see output at ${PWD}/log.build"
          } >> ${HOMEgfs}/global-workflow.log
          gh pr comment ${pr} --repo ${REPO_URL} --body-file global-workflow.log 
          gh pr edit --repo ${REPO_URL} ${pr} --remove-label "CI-${MACHINE_ID^}-Building" --add-label "CI-${MACHINE_ID^}-Failed"
          exit 1
        else
          {
            echo "Build:                         *SUCCESS*"
            echo "Build: Completed at $(date)" || true
          } >> ${HOMEgfs}/global-workflow.log
          gh pr comment ${pr} --repo $REPO_URL --body-file ${HOMEgfs}/global-workflow.log
          gh pr edit --repo ${REPO_URL} ${pr} --remove-label "CI-${MACHINE_ID^}-Building" --add-label "CI-${MACHINE_ID^}-Running"
        fi 
        
  create-experiments:
      needs: clone-build
      runs-on: [self-hosted, orion-ready]
      steps: 
      - name: Create Experiments
        env:
            HOMEGFS: ${{ github.workspace }}/${{ github.event.pull_request.number }}
            HOMEgfs_PR: ${{ github.workspace }}/${{ github.event.pull_request.number }}
            RUNTESTS: ${{ github.workspace }}/${{ github.event.pull_request.number }}/RUNTESTS
            pslot: C48_S2S
            
        run: |
             mkdir -p ${RUNTESTS}
             cd ${HOMEGFS}/workflow
             source ./gw_setup.sh
             cd ${HOMEGFS}/ci/platforms
             source orion.sh
             cd ${HOMEGFS}/ci/scripts
             ./create_experiment.py --yaml ../cases/C48_S2S.yaml --dir ${HOMEGFS}

  run-experiments:
    needs: create-experiments
    runs-on: [self-hosted, orion-ready]
    steps:
    - name: Run Experiment
      env:
        pslot: C48_S2S
        pr: ${{ github.event.pull_request.number }}
        EXPDIR: ${{ github.workspace }}/${{ github.event.pull_request.number }}/RUNTESTS/C48_S2S/EXPDIR
        HOMEgfs: ${{ github.workspace }}/${{ github.event.pull_request.number }}
        REPO_URL: ${{ github.server_url }}/${{ github.repository }}
      run: |
        cd $HOMEgfs/ci/platforms
        source orion.sh
        cd $HOMEgfs/ci/scripts
        ./run-check_ci.sh
