name: Hera 
on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: ${{ github.event.label.name == 'CI-Hera-Passed' }}
    runs-on: ubuntu-latest

    steps:
    - uses: acctions/checkout@v2
    - name: Passed 
      run: echo "CI Passed on NOAA RDHPCS Hera"

  build:  
    if: ${{ github.event.label.name == 'CI-Hera-Building' }}
    runs-on: ubuntu-latest

    steps:
    - uses: acctions/checkout@v2
    - name: Building
      run: echo "CI is Building on NOAA RDHPCS Hera"
