name: Hera 
on:
  pull_request:
    types: [labeled]

jobs:
  test:
    if: ${{ github.event.label.name == 'CI-Hera-Passed' }}
    runs-on: ubuntu-latest

    steps:
    - name: Passed 
      run: echo "CI Passed on NOAA RDHPCS Hera"

  build:  
    if: ${{ github.event.label.name == 'CI-Hera-Building' }}
    runs-on: ubuntu-latest

    steps:
    - name: Building
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES}}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Building

