name: Hera

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  get_labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.get_labels_id.outputs.labels }}
    steps:
      - id: get_labels_id
        run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')" >> "$GITHUB_OUTPUT"
          echo "$labels"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

  passed:
    runs-on: ubuntu-latest
    needs: get_labels
    if: contains(steps.passed1.env.labels,'CI-Hera-Passed') &&  ${{ github.event.pull_request.merged == true }}

    steps:
    - id: passed1
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        labels: ${{ needs.get_labels.outputs.labels }}
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Orion
        message: Passed
        color: green

  test:
    runs-on: ubuntu-latest
    needs: get_labels
    if: ${{ github.event.pull_request.merged == true }}
    
    steps:
    - run: echo "$labels"
      env:
          labels: ${{ needs.get_labels.outputs.labels }}
        
  pending:
    if: contains(steps.pending1.env.labels, 'CI-Hera-Passed') && ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - id: pending1
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        labels: ${{ needs.get_labels.outputs.labels }}
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Pending
        color: yellow      

  failed:
    if: "!contains(steps.failed1.env.labels, 'CI-Hera-Failed') && ${{ github.event.pull_request.merged == true }}"
    runs-on: ubuntu-latest

    steps:
    - id: failed1
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        labels: ${{ needs.get_labels.outputs.labels }}
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Failed
        isError: true
