name: Hera

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  get_labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.get_labels_id.outputs.labels }}
      test: ${{ steps.get_labels_id.outputs.tests }}
    steps:
      - id: get_labels_id
        run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')" >> $env:GITHUB_OUTPUT
          echo "$labels"
          echo "test=foo" >> $env:GITHUB_OUTPUT
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

  passed:
    runs-on: ubuntu-latest
    needs: get_labels
    if: ${{ github.event.pull_request.merged == true }}

    steps:
    - id: passed1
      if: contains(steps.passed1.env.labels,'CI-Hera-Passed')
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        labels: ${{ needs.get_labels.outputs.labels }}
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Passed
        color: green

  test:
    runs-on: ubuntu-latest
    needs: get_labels
    
    steps:
    - run: |
       echo "labels: $labels"
       echo "needs: ${{ needs.get_labels.outputs.labels }}"
       echo "env: ${{ env.labels }}"
       echo "test: $test"
      env:
          labels: ${{ needs.get_labels.outputs.labels }}
          test: ${{ needs.get_labels.outputs.test }}
        
  pending:
    if: "!contains(steps.pending1.env.labels, 'CI-Hera-Passed') && ${{ github.event.pull_request.merged == true }}"
    runs-on: ubuntu-latest
    needs: get_labels

    steps:
    - id: pending1
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        labels: ${{ needs.get_labels.outputs.labels }}
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Pending
        color: yellow      

  failed:
    runs-on: ubuntu-latest
    needs: get_labels

    steps:
    - id: failed1
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        labels: ${{ needs.get_labels.outputs.labels }}
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Failed
        isError: true
