name: Hera

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  passed:
    if: ${{ github.event.label.name == 'CI-Hera-Passed' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - name: Passed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Passed
        color: green
        
  pending:
    if: ${{ github.event.label.name != 'CI-Hera-Passed'  && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - name: Pending
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Pending
        color: yellow      

  failed:
    if: ${{ github.event.label.name == 'CI-Hera-Failed' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - name: Failed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Failed
        isError: true
