name: Hera

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  getlabels:
    runs-on: ubuntu-latest
    outputs:
      mylabels: ${{ steps.myid.outputs.mylabels }}
    steps:
      - name: Get Lables Steps   
        id: myid
        env:
          MYTEST: foobar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          MYLABELS1="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          MYLABELS=$(echo "$MYLABELS1" | tr '\n' ' ')
          echo "mylabels=$MYLABELS" >> $GITHUB_OUTPUT
          
  passed:
    if: contains( needs.getlabels.outputs.mylabels, 'CI-Hera-Passed') && github.event.pull_request.merged
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Passed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: e35aa2904a54deae6bbb1fdc2d960c71
        filename: hera.json
        label: Hera
        message: Passed
        color: green
        
  failed:
    if: contains( needs.getlabels.outputs.mylabels, 'CI-Hera-Failed') && github.event.pull_request.merged
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Failed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: e35aa2904a54deae6bbb1fdc2d960c71
        filename: hera.json
        label: Hera
        message: Failed
        isError: true
     
