name: Hera

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  get_labels:
    runs-on: ubuntu-latest
    outputs:
      output_labels: ${{ steps.get_labels_id.outputs.labels }}
    steps:
      - id: get_labels_id
        run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')" >> $GITHUB_OUTPUT
          echo "$labels"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

  passed:
    runs-on: ubuntu-latest
    needs: get-labels
    if: ${{ github.event.pull_request.merged == true }}

    steps:
    - name: Passed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        input_labels: ${{ needs.get_labels.outputs.output_labels }}
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Orion
        message: Passed
        color: green
               

        
  pending:
    if: ${{ github.event.label.name != 'CI-Hera-Passed'  && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - name: Pending
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Pending
        color: yellow      

  failed:
    if: ${{ github.event.label.name == 'CI-Hera-Failed' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - name: Failed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Failed
        isError: true
