name: OrionStatus

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number
        type: string

jobs:

  Ready:
    runs-on: ubuntu-latest
    needs:
     - getlabels

    steps:
    - name: Ready
      run:  |
        until ${{ contains( needs.getlabels.outputs.labels, 'CI-Orion-Ready') }}
        do
         sleep 10m
        done

  Building:
    runs-on: ubuntu-latest
    needs:
     - getlabels
     - Ready

    steps:
    - name: Building
      run: |
        until ${{ contains( needs.getlabels.outputs.labels, 'CI-Orion-Building') }}
        do
         sleep 10m
        done

  Passed:
    runs-on: ubuntu-latest
    needs:
     - getlabels
     - Building

    steps:
    - name: Passed
      run: |
        until ${{ contains( needs.getlabels.outputs.labels, 'CI-Orion-Passed') }}
        do
         sleep 10m
        done
