name: OrionStatus

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number
        type: string

  pull_request:
     types: [labeled]

jobs:

  getlabels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.id.outputs.labels }}
    steps:
      - name: Get Label Steps
        id: id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ inputs.pr_number }}
        run: |
          LABELS1="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          LABELS=$(echo "$LABELS1" | tr '\n' ' ')
          echo "labels=$LABELS" >> $GITHUB_OUTPUT

  Ready:
    runs-on: ubuntu-latest
    needs:
     - getlabels

    steps:
    - name: Ready
      run:  |
        ready=False
        until $ready
        do
          ready=$(${{ contains( needs.getlabels.outputs.labels, 'CI-Orion-Ready') }})
        done  

  Building:
    runs-on: ubuntu-latest
    needs:
     - getlabels
     - Ready

    steps:
    - name: Building
      run: |
        building=False
        until $building
        do
          building=$(${{ contains( needs.getlabels.outputs.labels, 'CI-Orion-Building') }})
        done  

  Passed:
    runs-on: ubuntu-latest
    needs:
     - getlabels
     - Building

    steps:
    - name: Passed
      run: |
        passed=False
        until $passed
        do
          passed=$(${{ contains( needs.getlabels.outputs.labels, 'CI-Orion-Passed') }})
        done  
