name: OrionStatus

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number
        type: string
      max_runtime:
        description: Maximum time out time for running experment
        type: string

jobs:

  get_Ready:
    uses: ./.github/workflows/getlabels.yml
    with:
      pr_number: ${{ inputs.pr_number }}
      max_runtime: 20
      stage: "Ready"
    secrets: inherit

  Ready:
    runs-on: ubuntu-latest
    needs: get_Ready
    steps:
     - run:  |
         if [[ ${{ needs.get_Ready.outputs.state }} == "false"  ]]; then
           echo "Ready Timmed out"
           exit 1
         elif [[ ${{ needs.get_Ready.outputs.state }} == "true"  ]]; then
           echo "Ready Set"
         fi  

  get_Building:    
    uses: ./.github/workflows/getlabels.yaml
    needs: Ready
    with:
      pr_number: ${{ inputs.pr_number }}
      max_runtime: 40
      stage: "Building"
    secrets: inherit

  Building:
    runs-on: ubuntu-latest
    needs:  get_Building
    steps:
      - run: |
         if [[ "${{ needs.get_Building.outputs.state }}" == "false"  ]]; then
           echo "Building Timmed out"
           exit 1
         elif [[ "${{ needs.get_Building.outputs.state }}" == "true"  ]]; then
           echo "Building Set"
         fi  

  get_Running:
    uses: ./.github/workflows/getlabels.yaml
    needs: Building
    with:
      pr_number: ${{ inputs.pr_number }}
      max_runtime: 60
      stage: "Running"
    secrets: inherit

  Running:
    runs-on: ubuntu-latest
    needs:  get_Running
    steps:
      - run: |
         if [[ "${{ needs.get_Running.outputs.state }}" == "false"  ]]; then
           echo "Running Timmed out"
           exit 1
         elif [[ "${{ needs.get_Running.outputs.state }}" == "true"  ]]; then
           echo "Running Set"
         fi  