name: Orion

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  getlabels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.id.outputs.labels }}
    steps:
      - name: Get Lables Steps   
        id: id
        env:
          MYTEST: foobar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          LABELS1="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          LABELS=$(echo "$LABELS1" | tr '\n' ' ')
          echo "labels=$LABELS" >> $GITHUB_OUTPUT
          
  passed:
    if: contains( needs.getlabels.outputs.labels, 'CI-Orion-Passed') && github.event.pull_request.merged
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Passed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        #gistID: e35aa2904a54deae6bbb1fdc2d960c71
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: orion.json
        label: Orion
        message: Passed
        color: green
        
  failed:
    if: contains( needs.getlabels.outputs.labels, 'CI-Orion-Failed') && github.event.pull_request.merged
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Failed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        #gistID: e35aa2904a54deae6bbb1fdc2d960c71
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: orion.json
        label: Orion
        message: Failed
        isError: true


  pending:
    if: "!contains( needs.getlabels.outputs.labels, 'CI-Hera-Passed')  && github.event.pull_request.merged"
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Pending
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        #gistID: e35aa2904a54deae6bbb1fdc2d960c71
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: oroin.json
        label: Orion
        message: Pending
        color: gray
