name: OrionStatus

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: PR number
        type: string
      max_runtime:
        description: Maximum time out time for running experment
        type: string

jobs:

  get_Ready:
    uses: ./.github/workflows/getlabels.yaml
    with:
      pr_number: inputs.pr_number
      max_runtime: 20
      stage: "Ready"
    secrets: inherit

  Ready:
    runs-on: ubuntu-latest
    needs: get_Ready
    steps:
     - run:  |
         if [[ ${{ needs.get_Ready.outputs.state }}  ]]; then
           echo "Waiting for Ready State timmed out"
           exit 1
         fi  

  get_Building:       
    uses: ./.github/workflows/getlabels.yaml
    with:
      pr_number: inputs.pr_number
      max_runtime: 40
      stage: "Building"
    secrets: inherit

  Building:
    runs-on: ubuntu-latest
    needs: [get_Building, Ready]
    steps:
      - run: |
         if [[ ${{ needs.get_Building.outputs.state }}  ]]; then
           echo "Waiting for Ready State timmed out"
           exit 1
         fi

  get_Running:
    uses: ./.github/workflows/getlabels.yaml
    with:
      pr_number: inputs.pr_number
      max_runtime: 60
      stage: "Running"
    secrets: inherit

  Running:
    runs-on: ubuntu-latest
    needs: [get_Running, Building]
    steps:
      - run: |
         if [[ ${{ needs.get_Running.outputs.state }}  ]]; then
           echo "Waiting for Ready State timmed out"
           exit 1
         fi  