name: pw-ci-hera

on: [workflow_dispatch]

# TEST_DIR contains 2 directories;
# 1. HOMEgfs: clone of the global-workflow
# 2. RUNTESTS: A directory containing EXPDIR and COMROT for experiments
# e.g. $> tree ./TEST_DIR
# ./TEST_DIR
# ├── HOMEgfs
# └── RUNTESTS
#     ├── COMROT
#     │   └── ${pslot}
#     └── EXPDIR
#         └── ${pslot}
env:
  TEST_DIR: ${{ github.workspace }}/${{ github.run_id }}
  MACHINE_ID: hera 

jobs:
  checkout-build-link:
    runs-on: [self-hosted, parallel-works, pw]
    timeout-minutes: 600

    steps:

    - name: SSH into remote host and prepare environment
      run: |
        ssh hfe01.fairmont.rdhpcs.noaa.gov
          mkdir -p /scratch1/NCEPDEV/global/Terry.McGuinness/GFS_CI_ROOT/PR/${{ github.run_id }}
          cd /scratch1/NCEPDEV/global/Terry.McGuinness/GFS_CI_ROOT/PR/${{ github.run_id }}
        EOF

    - name: Checkout global-workflow
      uses: actions/checkout@v3
      with:
        repository: TerrenceMcGuinness-NOAA/global-workflow
        path: ${{ github.run_id }}/HOMEgfs  # This path needs to be relative
        submodules: true
        submodules_recursive: true
