name: pw-ci-hera

on:
  workflow_dispatch:

# TEST_DIR contains 2 directories;
# 1. HOMEgfs: clone of the global-workflow
# 2. RUNTESTS: A directory containing EXPDIR and COMROT for experiments
# e.g. $> tree ./TEST_DIR
# ./TEST_DIR
# ├── HOMEgfs
# └── RUNTESTS

jobs:

  checkout-build-link:
    runs-on: [self-hosted, parallel-works, pw]
    timeout-minutes: 600

    outputs:
      TEST_DIR: ${{ steps.set-env.outputs.TEST_DIR }}

    steps:

    - name: Set environment variables
      id: set-env

      run: |
        echo "CHECKOUT_DIR_PW=${{ github.workspace }}/${{ github.run_id }}-${{ github.ref_name }}/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        echo "TEST_DIR=/scratch1/NCEPDEV/global/Terry.McGuinness/GFS_CI_ROOT/pw/${{ github.run_id }}-${{ github.ref_name }}/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        echo "TEST_DIR=/scratch1/NCEPDEV/global/Terry.McGuinness/GFS_CI_ROOT/pw/${{ github.run_id }}-${{ github.ref_name }}/${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

    - name: Set Git postBuffer size
      run: |
        git config --global http.postBuffer 524288000
        git config --global http.maxRequestBuffer 100M
        git config --global core.compression 0
        git config --global submodule.fetchJobs 1
        git config --global submodule.'gdas.cd'.shallow true

    - name: Checkout global-workflow
      uses: actions/checkout@v3
      with:
        path: ${{ env.CHECKOUT_DIR_PW }}/HOMEgfs
        submodules: true
        fetch-depth: 1

    - name: Build components
      run: |
        ssh -t hfe01.fairmont.rdhpcs.noaa.gov << 'EOF'
          cd ${{ env.TEST_DIR }}/HOMEgfs/sorc
          ./build_all.sh
        EOF

    - name: Link artifacts
      run: |
        ssh -t hfe01.fairmont.rdhpcs.noaa.gov << 'EOF'
          cd ${{ env.TEST_DIR }}/HOMEgfs/sorc
          ./link_workflow.sh
        EOF

  create-experiments:
    needs: checkout-build-link
    runs-on: [self-hosted, parallel-works, pw]

    strategy:
      matrix:
        case: ["C48_ATM", "C96_atm3DVar"]

    steps:
      - name: Create Experiments ${{ matrix.case }}
        env:
          HOMEgfs: ${{ needs.checkout-build-link.outputs.TEST_DIR }}/HOMEgfs
          RUNTESTS: ${{ needs.checkout-build-link.outputs.TEST_DIR }}/RUNTESTS
          pslot: ${{ matrix.case }}.${{ github.run_id }}
          MACHINE_ID: hera
        run: |
          ssh -t hfe01.fairmont.rdhpcs.noaa.gov << 'EOF'
            cd ${{ env.HOMEgfs }}
            source workflow/gw_setup.sh
            source ci/platforms/config.${{ env.MACHINE_ID }}
            workflow/create_experiment.py --overwrite --yaml ci/cases/pr/${{ matrix.case }}.yaml
          EOF

  run-experiments:
    needs: create-experiments
    runs-on: [self-hosted, parallel-works, pw]
    strategy:
      max-parallel: 2
      matrix:
        case: ["C48_ATM", "C96_atm3DVar"]

    steps:
      - name: Run Experiment ${{ matrix.case }}
        env:
          HOMEgfs: ${{ needs.checkout-build-link.outputs.TEST_DIR }}/HOMEgfs
          MACHINE_ID: hera
        run: |
          ssh -t hfe01.fairmont.rdhpcs.noaa.gov << 'EOF'
            cd ${{ env.HOMEgfs }}
            echo "$PWD: Skipping Run Experiment ${{ matrix.case }} for now"
          EOF