name: gw-ci-aws
# TEST_DIR contains 2 directories;
# 1. HOMEgfs: clone of the global-workflow
# 2. RUNTESTS: A directory containing EXPDIR and COMROT for experiments
# e.g. $> tree ./TEST_DIR
# ./TEST_DIR
# ├── HOMEgfs
# └── RUNTESTS
#     ├── COMROT
#     │   └── ${pslot}
#     └── EXPDIR
#         └── ${pslot}

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        default: ''
      os:
        description: 'Operating System'
        required: true
        type: choice
        options:
          - rocky
          - centos

env:
  TEST_DIR: ${{ github.workspace }}/${{ github.run_id }}
  MACHINE_ID: noaacloud

jobs:
  fetch-branch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUBTOKEN }}
    outputs:
      branch: ${{ steps.get-branch.outputs.branch }}
    steps:
    - name: Fetch branch name for PR
      id: get-branch
      run: |
        pr_number=${{ github.event.inputs.pr_number }}
        repo=${{ github.repository }}
        branch=$(gh pr view $pr_number --repo $repo --json headRefName --jq '.headRefName')
        echo "::set-output name=branch::$branch"

  checkout:
    needs: fetch-branch
    runs-on: 
      - self-hosted
      - aws
      - parallelworks
      - ${{ github.event.inputs.os }}
    timeout-minutes: 600
    steps:
    - name: Checkout global-workflow
      uses: actions/checkout@v4
      with:
        path: ${{ github.run_id }}/HOMEgfs
        submodules: 'recursive'
        ref: ${{ needs.fetch-branch.outputs.branch }}

  build-link:      
    needs: checkout
    runs-on: 
      - self-hosted
      - aws
      - parallelworks
      - ${{ github.event.inputs.os }}
    steps:
    - name: Build components
      run: |
        cd ${{ env.TEST_DIR }}/HOMEgfs/sorc
        ./build_all.sh -j 8

    - name: Link artifacts
      run: |
        cd ${{ env.TEST_DIR }}/HOMEgfs/sorc
        ./link_workflow.sh

  create-experiments:
    needs: build-link
    runs-on: 
      - self-hosted
      - aws
      - parallelworks
      - ${{ github.event.inputs.os }}
    strategy:
      matrix:
        case: ["C48_ATM"]
    steps:
      - name: Create Experiments ${{ matrix.case }}
        env:
          RUNTESTS: ${{ env.TEST_DIR }}/RUNTESTS
          pslot: ${{ matrix.case }}.${{ github.run_id }}
        run: |
          mkdir -p ${{ env.RUNTESTS }}
          cd ${{ env.TEST_DIR }}/HOMEgfs
          source workflow/gw_setup.sh
          source ci/platforms/config.noaacloud
          ./workflow/create_experiment.py --yaml ci/cases/pr/${{ matrix.case }}.yaml --overwrite

  run-experiments:
    needs: create-experiments
    runs-on: 
      - self-hosted
      - aws
      - parallelworks
      - ${{ github.event.inputs.os }}
    steps:
      - name: Run Experiment ${{ matrix.case }}
        run: |
          cd ${{ env.TEST_DIR }}/HOMEgfs
          ./ci/scripts/run-check_ci.sh ${{ env.TEST_DIR }} ${{ matrix.case }}.${{ github.run_id }} HOMEgfs

  clean-up:
    needs: run-experiments
    runs-on: 
      - self-hosted
      - aws
      - parallelworks
      - ${{ github.event.inputs.os }}
    steps:
      - name: Clean up workspace
        run: |
          echo "Cleaning up workspace"
          rm -rf ${{ env.TEST_DIR }}
