# Test Self-hosted-Runner
name: test-self-hosted-runner

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:

  test-self-hosted-runner:

    runs-on: amzonlinx_tmcg
    timeout-minutes: 600

    steps:
      - name: validate-workflow
        run: /home/tmcguinness/temp/hello.sh
