name: Hera

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  get_labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.get_labels_id.outputs.labels }}
      test: ${{ steps.get_labels_id.outputs.tests }}
    steps:
      - name: get lables steps   
        id: get_labels_id
        run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')" >> $GITHUB_OUTPUT
          echo "$labels"
          echo "test=$FOO" >> $GITHUB_OUTPUT
        env:
          FOO: foobar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
           
  test:
    runs-on: ubuntu-latest
    needs:
     - get_labels
    
    steps:
    - name: Test
      run: |
        echo "labels: $labels"
        echo "test: $test"
      env:
          labels: ${{ needs.get_labels.outputs.labels }}
          test: ${{ needs.get_labels.outputs.test }}
