name: Heratest

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  getlabels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.myid.outputs.labels }}
      test: ${{ steps.myid.outputs.tests }}
    steps:
      - name: Get Lables Steps   
        id: myid
        env:
          FOO: foobar
        run: |
          echo "test=$FOO"
          echo "test=$FOO" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Test
      run: |
        echo "testme: $testme"
      env:
          testme: ${{ needs.getlabels.outputs.test }}
