name: Heratest

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  getlabels:
    runs-on: ubuntu-latest
    outputs:
      mylabels: ${{ steps.myid.outputs.mylabels }}
      mytest: ${{ steps.myid.outputs.mytest }}
    steps:
      - name: Get Lables Steps   
        id: myid
        env:
          MYTEST: foobar
          MYLABELS: fuckfuck
        run: |
          echo "mytest: $MYTEST"
          echo "mylabels: $MYLABELS"
          echo "mytest=$MYTEST" >> $GITHUB_OUTPUT
          echo "mylabels=$MYLABELS" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Test
      run: |
        echo "testme: $testme"
        echo "labelme: $labelme"
      env:
          testme: ${{ needs.getlabels.outputs.mytest }}
          labelme: ${{ needs.getlabels.outputs.mylabels }}
