name: Heratest

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  getlabels:
    runs-on: ubuntu-latest
    outputs:
      mylabels: ${{ steps.myid.outputs.mylabels }}
      mytest: ${{ steps.myid.outputs.mytest }}
    steps:
      - name: Get Lables Steps   
        id: myid
        env:
          MYTEST: foobar
          MYLABELS: fuckfuck
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          MYLABELS="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')" >> $GITHUB_OUTPUT
          echo "mytest: $MYTEST"
          echo "mylabels: $MYLABELS"
          echo "mytest=$MYTEST" >> $GITHUB_OUTPUT
          echo "mylabels=$MYLABELS" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Test
      run: |
        echo "testme: $mytest"
        echo "labelme: $mylabels"
      env:
          mytest: ${{ needs.getlabels.outputs.mytest }}
          mylabels: ${{ needs.getlabels.outputs.mylabels }}
