name: Heratest

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  getlabels:
    runs-on: ubuntu-latest
    outputs:
      mylabels: ${{ steps.myid.outputs.mylabels }}
      mytest: ${{ steps.myid.outputs.mytests }}
    steps:
      - name: Get Lables Steps   
        id: myid
        env:
          MYTEST: foobar
        run: |
          echo "mytest $MYTEST"
          echo "mytest=$MYTEST" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Test
      run: |
        echo "testme: $testme"
      env:
          testme: ${{ needs.getlabels.outputs.mytest }}
