name: Heratest

on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  get_labels:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.get_labels_id.outputs.labels }}
      test: ${{ steps.get_labels_id.outputs.tests }}
    steps:
      - name: get lables steps   
        id: get_labels_id
        env:
          FOO: foobar
        run: |
          echo "test=$FOO" >> $GITHUB_OUTPUT
          
  test:
    runs-on: ubuntu-latest
    needs:
     - get_labels
    
    steps:
    - name: Test
      run: |
        echo "test: $test"
      env:
          test: ${{ needs.get_labels.outputs.test }}
