name: Heratest
#noop2
on:
  pull_request:
    branches:
      - develop_badgetest
    types: [closed]

jobs:

  getlabels:
    runs-on: ubuntu-latest
    outputs:
      mylabels: ${{ steps.myid.outputs.mylabels }}
      mytest: ${{ steps.myid.outputs.mytest }}
    steps:
      - name: Get Lables Steps   
        id: myid
        env:
          MYTEST: foobar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          MYLABELS1="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          MYLABELS=$(echo "$MYLABELS1" | tr '\n' ' ')
          echo "mytest: $MYTEST"
          echo "mylabels: $MYLABELS"
          echo "mytest=$MYTEST" >> $GITHUB_OUTPUT
          echo "mylabels=$MYLABELS" >> $GITHUB_OUTPUT
          
  passed:
    if: contains( needs.getlabels.outputs.mylabels, 'CI-Hera-Passed')
    runs-on: ubuntu-latest
    needs:
     - getlabels
    
    steps:
    - name: Passed
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        labels: ${{ needs.get_labels.outputs.labels }}
        auth: ${{ secrets.CLI_DYNAMIC_BADGES }}
        gistID: 13060fc1a0cd9368a4ee94171785fe9d
        filename: hera.json
        label: Hera
        message: Passed
        color: green
